### ISSUE TITLE
e2e tests for ArgoCD & Flux

### ISSUE THREAD

**Issue by moolen** [external-secrets/external-secrets#1029]
ArgoCD and Flux are first class citizens of the project.

Context: with 0.5.0 we had a couple of issues that could've been caught earlier when we would have had e2e tests.

AC:
* create a dedicated gitops testsuite with a small set of tests
  * the testsuite should be focused around the integration with $GITOPS tool
  * we should be able to deploy ESO via helm
  * we should be able to use `ExternalSecrets`. fake provider is fine for this use-case.
  * ensure/document behavior and implications around `creationPolicy=Merge` and `deletionPolicy`
* deploy ArgoCD and run the test suite
* deploy flux v2 and run the test suite

**Comment by gusfcarvalho** [comment]
I am keen to do one of those, as ways to get more involved with Argo / Flux and gitops (warning alert I would be slow :smile:)

Should we test flux v1 as well? I think it is the majority of our flux issues.

**Comment by moolen** [comment]
I'd focus on flux v2 and argocd; flux v1 is deprecated already. I started taking a look on that already, but sure go ahead!

I imagine that as a result we would have two e2e suites:
1. the provider suite (the "current" one)
2. a gitops integration suite

We need two suites because we install ESO globally [here](https://github.com/external-secrets/external-secrets/blob/main/e2e/e2e_test.go#L34). 

And we would want to install ESO through $GITOPS tool instead using the manifests from the local file tree. This will likely be the tricky part.

**Comment by gusfcarvalho** [comment]
After a second thought, I think my time will be somewhat more limited now from the work side. I don't think I'll have the time to take this issue, specially because I would still need to learn some basics around flux and argo... sorry for that :sweat_smile:
