### ISSUE TITLE
Unable to login to k8s container external-secrets-webhook

### ISSUE THREAD

**Issue by AnuragEkkati** [external-secrets/external-secrets#1030]
kubectl exec -it external-secret-sync-external-secrets-webhook-649d4f45f6-895hj -n external-secret -- <command>

command i tried, sh, /bin/sh, /bin/bash, /bin/zsh, ls, cat

none of the commands works and I get below error. 

error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "d973e58adda942db6605c4d164c8bce866f8d5dd6115f2d91d4bda53f33aa9a9": OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "cd": executable file not found in $PATH: unknown

**Comment by gusfcarvalho** [comment]
This not an issue and it is expected. The base image we use is `distroless` one, as you can check in here: https://github.com/external-secrets/external-secrets/blob/main/Dockerfile#L1

In order for us to help you out, what are you actually trying to achieve that requires a shell to be available?

**Comment by AnuragEkkati** [comment]
I am trying to create SecretStore on my k8s cluster and I get this error. 

Error from server (InternalError): error when creating "Secret-Store.yaml": Internal error occurred: failed calling webhook "validate.secretstore.external-secrets.io": Post "https://vault-sync-external-secrets-webhook.vault-sync.svc:443/validate-external-secrets-io-v1beta1-secretstore?timeout=5s": dial tcp 10.192.5.17:9443: i/o timeout

10.192.5.17 is the cluster ip of XXXXX-webhook-5cc46b7b5d-lprms pod

Below is my Secret-Store.yaml. This same config works on another cluster but not sure what is going on here. 

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: xxxxxxxxx
  namespace: secrets-manager
spec:
  provider:
    vault:
      server: "https://vault.xxxxxx"
      path: "/secret"
      version: "v2"
      auth:
        appRole:
          path: "approle"
          roleId: "XXXXX"
          secretRef:
            name: "cert-manager-vault-approle"
            key: "secret-id"

I am not sure what is the reason for this.

I want to check if it is related to cert which the webhooks pod is reading from /tmp/certs.

**Comment by lfraga** [comment]
Hey @AnuragEkkati , is your cluster GKE?

If so, there is a note in v0.5.0 regarding TCP port 9433 and firewall rules

https://github.com/external-secrets/external-secrets/releases/tag/v0.5.0

`Note: If you are deploying external-secrets into a GKE cluster, you might need to add a firewall rule allowing traffic to port 9443 (see https://cloud.google.com/kubernetes-engine/docs/how-to/private-clusters#add_firewall_rules)`

If you are not using GKE it would also be interesting to validate if there are any network level restrictions for this port (TCP 9443), this is probably an issue unrelated to external-secrets

---

@gusfcarvalho I've been looking in the documentation on this note and haven't found anything, is this a permanent requirement in future releases? if so, it would be interesting to add the project documentation, I can take care of that in this case =)

**Comment by lfraga** [comment]
#965 maybe relevant

**Comment by AnuragEkkati** [comment]
Yes mine is a GKE cluster. and I am using external-secrets.io v0.5.1. 

I am able to create the SecretStore resource after following the steps and enabling the port 9443 on the controlplane network of the cluster. 

Thanks for your help.
