### ISSUE TITLE
Feature - Add support for multiple scopedNamespaces

### ISSUE THREAD

**Issue by jmmclean** [external-secrets/external-secrets#1050]
**Describe the solution you'd like**
Have multiple namespaces scoped rather than a single namespace via `scopedNamespace` in helm chart 

**What is the added value?**
In a situation where a single k8s cluster is managing multiple environments (ie an ops cluster), we have to manage our resources in a "namespaced" mode. This means we may need to managed `n` number of external secrets that are scoped to secretstores (in each namepsace) using `controllerClass`. If I run services such as Argo CD AND Argo Workflows which are scoped for a specific environment, then I can only reconcile secrets for one of those services, unless i deploy both to the same namespace.

**Give us examples of the outcome**
If I have ArgoCD and Argo Workflows deployed to namespaces `argo-cd-dev` and `argo-workflows-dev` and create secretstores in each namespace having `controller: dev`, I would like to be able to specific multiple scoped Namespaces to reconcile secrets within. 

> Note: ArgoCD is also running in `namespaced` mode, meaning it cannot manager Cluster resources (ie ClusterRole, ClusterRoleBinding)

**Comment by gusfcarvalho** [comment]
Hi @jmmclean ! Your use case is still a bit shady for me. I believe #163  wouldn't apply here, for your use case, am I correct?

Your intention is to have a namespaced ESO deployment to sync in multiple namespaces using the same controller Class?
effectively deploying a scoped ESO would allow the operator to only handle resources for that namespace. Is your usecase having multiple ESO deployments per namespace?

**Comment by jmmclean** [comment]
Hey @gusfcarvalho I want an ESO to be deployed per namespace where secrets being managed, but have them deployed to a single namespace (eg `external-secrets-dev`). I don't know how to do Go development, otherwise i would likely have added a flag for `--namespaces` rather than `--namespace` and managed it by code. I do not have the ability to use a ClusterSecretStore bc my CM (ie argo cd) is deployed in a way that it will not manage cluster resources (for control reasons)
