### ISSUE TITLE
Vault Provider: Support (Cluster)SecretStore paths prefixes with slashes included

### ISSUE THREAD

**Issue by lotyrin** [external-secrets/external-secrets#1052]
I'd like to be able to have a single Vault kv backend with paths that differ by environment/namespace/etc. by providing different (Cluster)SecretStores that have different path prefixes that include slashes to prefix the underlying ExternalSecrets by.

Currently it is assumed in the [path builder](https://github.com/external-secrets/external-secrets/blob/64057e9736709db07dfa85ed426b525c9b590447/pkg/provider/vault/vault.go#L600-L625) that the path prefix in the (Cluster)SecretStore does not contain slashes, such that when the path is generated to Vault (adding /data/ to the <backend>/data/<subpath> paths) the URLs are wrong and this results in a 404 from Vault.

**Comment by gusfcarvalho** [comment]
Hi @lotyrin ! Can you provide your manifests? It is not clear what is happening to cause the erratic behavior in your use case.

**Comment by lotyrin** [comment]
Oh, I see now. It's possible to create a kv engine that has slashes in its name. Given that, the current behavior of the vault provider is correct. Otherwise you wouldn't be able to use kv engines with a path containing slashes.
