### ISSUE TITLE
conversion webhook for external-secrets.io/v1alpha1 the server could not find the requested resource

### ISSUE THREAD

**Issue by jprecuch** [external-secrets/external-secrets#1055]
**Describe the solution you'd like**
We deleted all namespaces/charts from our environment to be able to cleanly deploy 0.5.1 external-secrets.
However all namespaces which had (probably) external-secret are stuck in
```
                "lastTransitionTime": "2022-04-25T14:11:12Z",
                "message": "Failed to delete all resource types, 1 remaining: conversion webhook for external-secrets.io/v1alpha1, Kind=ExternalSecret failed: the server could not find the requested resource",
                "reason": "ContentDeletionFailed",
                "status": "True",
                "type": "NamespaceDeletionContentFailure"
```
To overcome this I need to edit crds and remove finalizers:
```
kubectl edit crds clustersecretstores.external-secrets.io
kubectl edit crds externalsecrets.external-secrets.io

  finalizers:
  - customresourcecleanup.apiextensions.k8s.io
 ```
Tthis will get the namespace finally deleted. Problem comes when I want to install external-secrets again

The install will always fail because of:
```
Helm install failed: failed post-install: conversion webhook for [external-secrets.io/v1alpha1](http://external-secrets.io/v1alpha1), Kind=ClusterSecretStore failed: the server could not find the requested resource
```
I'm deploying external-secrets with values adjusted (because with them those pods does not start anyway)
```
    certController:
      create: false
    webhook:
      create: false
```
Any ideas how to move further? Shouldn't external-secrets with webhook and certController disabled not try to convert anything and check for webhook? Currently I'm not able to deploy chart anyhow.

**What is the added value?**

**Give us examples of the outcome**

**Observations (Constraints, Context, etc):**

**Comment by gusfcarvalho** [comment]
Hi @jprecuch ! If you want to deploy with no conversion Webhook, you need to update your ExternalSecrets and SecretStore versions to v1beta1. It is not possible to keep using v1alpha1 without the conversion webhook.

this seemed to me like a race condition (the webhook deployment getting deleted before any resources you have in your cluster. To fix this you can try to first remove the ExternalSecrets/SecretStores and then to remove the webhook. This issue is only going to happen while you are using v1alpha1.

If you already have some resources installed with v1alpha1 and you don’t want to remove them to update to v1beta1, the webhook is mandatory.

**Comment by jprecuch** [comment]
Thanks @gusfcarvalho. The issue here is that I have v1beta1 already for everything set, problem seems to be that even after I nuked all the namespaces, deleted helm deployments, external-secret chart thinks there is something with 1alpha1 existing when I have webhook and certController in false.

After I've enabled webhooks/controller it will deploy fine. But it seems there is some issue if there was 1alpha1 secret existing prior deletion and redeploy of external-secret in new version with webhooks disabled.
We can close this issue if there is no way how to check what external-secret chart found in v1aplha1 even all was nuked.

**Comment by jprecuch** [comment]
I'm closing this because we fixed it by enabling webhook +  certController at the end

**Comment by joncotton** [comment]
Same story here. What was supposed to be a smooth upgrade from v0.4.4 (because I'm not using `dataFrom`) absolutely wasn't. Nuking everything still didn't help.

On upgrade, I was surprised to find two new Pods running.
cert controller failed with
```
{"level":"error","ts":1651510124.6512027,"msg":"Failed to get API Group-Resources","error":"Get \"https://172.20.0.1:443/api?timeout=32s\": net/http: TLS handshake timeout","stacktrace":"sigs.k8s.io/controller-runtime/pkg/cluster.New\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/cluster/cluster.go:160\nsigs.k8s.io/controller-runtime/pkg/manager.New\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/manager/manager.go:313\ngithub.com/external-secrets/external-secrets/cmd.glob..func1\n\t/home/runner/work/external-secrets/external-secrets/cmd/certcontroller.go:49\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902\ngithub.com/external-secrets/external-secrets/cmd.Execute\n\t/home/runner/work/external-secrets/external-secrets/cmd/root.go:172\nmain.main\n\t/home/runner/work/external-secrets/external-secrets/main.go:21\nruntime.main\n\t/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/proc.go:255"}

{"level":"error","ts":1651510124.6513805,"logger":"setup","msg":"unable to start manager","error":"Get \"https://172.20.0.1:443/api?timeout=32s\": net/http: TLS handshake timeout","stacktrace":"github.com/external-secrets/external-secrets/cmd.glob..func1\n\t/home/runner/work/external-secrets/external-secrets/cmd/certcontroller.go:67\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902\ngithub.com/external-secrets/external-secrets/cmd.Execute\n\t/home/runner/work/external-secrets/external-secrets/cmd/root.go:172\nmain.main\n\t/home/runner/work/external-secrets/external-secrets/main.go:21\nruntime.main\n\t/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/proc.go:255"}
```

webhook pod failed with
```
{"level":"error","ts":1651510622.3331673,"logger":"setup","msg":"invalid certs. retrying...","error":"stat /tmp/certs/tls.crt: no such file or directory","stacktrace":"github.com/external-secrets/external-secrets/cmd.waitForCerts\n\t/home/runner/work/external-secrets/external-secrets/cmd/webhook.go:161\ngithub.com/external-secrets/external-secrets/cmd.glob..func3\n\t/home/runner/work/external-secrets/external-secrets/cmd/webhook.go:69\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902\ngithub.com/external-secrets/external-secrets/cmd.Execute\n\t/home/runner/work/external-secrets/external-secrets/cmd/root.go:172\nmain.main\n\t/home/runner/work/external-secrets/external-secrets/main.go:21\nruntime.main\n\t/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/proc.go:255"}
{"level":"info","ts":1651510632.3339875,"logger":"setup","msg":"validating certs"}
```
and the secrets pod failed with
```
W0502 16:58:02.437901       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: failed to list *v1beta1.ExternalSecret: conversion webhook for external-secrets.io/v1alpha1, Kind=ExternalSecret failed: Post "https://external-secrets-webhook.jh.svc:443/convert?timeout=30s": no endpoints available for service "external-secrets-webhook"

E0502 16:58:02.437955       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: Failed to watch *v1beta1.ExternalSecret: failed to list *v1beta1.ExternalSecret: conversion webhook for external-secrets.io/v1alpha1, Kind=ExternalSecret failed: Post "https://external-secrets-webhook.jh.svc:443/convert?timeout=30s": no endpoints available for service "external-secrets-webhook"
```

My thinking was the same. First I disabled the certController and webhook components with `create:false`. Then I nuked everything. Thank you, @jprecuch, for the tip about removing the `finalizers`. I'm pretty sure everything is gone. Then a fresh deploy/install with my single `SecretStore` and single `ExternalSecret` updated to `external-secrets.io/v1beta1` still fails.
```
W0502 17:26:07.019700       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: failed to list *v1beta1.SecretStore: conversion webhook for external-secrets.io/v1alpha1, Kind=SecretStore failed: Post "https://external-secrets-webhook.jh.svc:443/convert?timeout=30s": service "external-secrets-webhook" not found

E0502 17:26:07.019725       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:167: Failed to watch *v1beta1.SecretStore: failed to list *v1beta1.SecretStore: conversion webhook for external-secrets.io/v1alpha1, Kind=SecretStore failed: Post "https://external-secrets-webhook.jh.svc:443/convert?timeout=30s": service "external-secrets-webhook" not found
```

It sounds like I'll come to the same conclusion: running the cert and webhook components. From #1063:
> The webhook pod is not meant to be optional, though. It contains the ValidatingWebhooks for ExternalSecrets and for SecretStores, effectively blocking some misconfiguration that could be potentially dangerous to operations. The recommendation is to have one webhook deployment per cluster.

**Comment by joncotton** [comment]
Thank you for the prompt response! I saw the new components in the release notes but didn't understand their significance. I was also confused by their seeming optionality in the values.yaml (create: false), though I understand that you need to toggle a way to provide different cert management.

NetworkPolicy was the issue. Makes sense that _now_ it needs to talk to the Kube API to write back the conversion.
<details><summary>previous NetPol spec and the errors</summary>
<p>

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: external-secrets
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 443
      protocol: TCP
```

Causing this in cert-controller:
```
"msg":"Failed to get API Group-Resources","error":"Get \"https://172.20.0.1:443/api?timeout=32s\": net/http: TLS handshake timeout"
"logger":"setup","msg":"unable to start manager"
```
(and this in my istio-proxy sidecar)
```
2022-05-02T17:42:40.169991Z	info	Envoy proxy is ready
2022-05-02T17:43:37.322168Z	error	Request to probe app failed: Get "http://10.242.80.118:8081/readyz": dial tcp 127.0.0.6:0->10.242.80.118:8081: connect: connection refused, original URL path = /app-health/cert-controller/readyz
app URL path = /readyz
```

</p>
</details>

To extra clarify: is the webhook necessary if using v1beta1 resources from scratch (with nothing to convert)?

Second question, I'm already using Istio and could that simplify cert management?

**Comment by gusfcarvalho** [comment]
> To extra clarify: is the webhook necessary if using v1beta1 resources from scratch (with nothing to convert)?

We tried in releases 0.5.0 and 0.5.1 to make the CRDs transparent to the existence of the webhook pod (making it optional), but that caused several errors when using argocd or flux to deploy the CRDs. in release 0.5.2 we introduced a configuration to the CRDs that make at least one webhook deployment to be available. I think we can come up with some extra templating to make it optional again, although I'm concerned about the implications we might still have...

> Second question, I'm already using Istio and could that simplify cert management?

I don't remember istio supporting configuration of certificates out of the box. IIRC, it only supports for self configuration. If you are using cert-manager, you can configure it relatively easy by adding some annotations to the CRDs and ValidatingWebhookConfigurations.
