### ISSUE TITLE
Support AWS authentication using credentials file

### ISSUE THREAD

**Issue by evanrosebrook** [external-secrets/external-secrets#1060]
**Describe the solution you'd like**
ExternalSecret can currently authenticate with AWS using an access-key and secret-access-key pair. It would be good to also allow authentication using a credentials file(typically stored in ~/.aws/credentials). 

**What is the added value?**
By adding support for a credentials file, users who manage their access via credential file will be supported. This also has the happy benefit of supporting credentials that use a session token in addition to the access key and secret access key as in the case of an assumed role.

**Give us examples of the outcome**

ExternalSecrets will be able to pull secrets from SSM using a credentials file mounted to the external-secrets controller.

**Comment by moolen** [comment]
Context: `SharedConfigState` was set to Disabled explicitly here: https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/aws/auth/auth.go#L103

I don't mind enabling it.

**Comment by evanrosebrook** [comment]
that would be great.
