### ISSUE TITLE
Docu page does not reflect latest docu state

### ISSUE THREAD

**Issue by haf-tech** [external-secrets/external-secrets#1077]
e.g.
https://external-secrets.io/provider-ibm-secrets-manager/
the changes to `kv` etc are not available.
https://github.com/external-secrets/external-secrets/blob/main/docs/provider-ibm-secrets-manager.md

It seems, it is still an old version of the page

**Comment by gusfcarvalho** [comment]
Hi @haf-tech ! Documentation is now versioned. You should check it on https://external-secrets.io/latest/provider-ibm-secrets-manager

Did you find this link somewhere in our docs?

**Comment by haf-tech** [comment]
thanks @gusfcarvalho for the info
to be honest, I can not remember how I reached this page...I was on the blog section. In case, I find the source I will post it here

**Comment by gusfcarvalho** [comment]
Cool! Meanwhile, I'll close this issue. If you happen to find it, please reopen it!
