### ISSUE TITLE
[2] PushSecret: Platform Engineer can check the SecretSink sync status via `kubectl get`

### ISSUE THREAD

**Issue by ladeoshodi** [external-secrets/external-secrets#1095]
Epic: https://github.com/external-secrets/external-secrets/issues/976

### Acceptance Criteria
**Scenario**: A platform engineer can check the SecretSink sync status via` kubectl get`
**Given** a platform engineer is syncing secrets to an external secret provider
**When** the platform engineer runs the command `kubectl get` on the SecretSink custom resource definition
**Then** the platform engineer is able to see the status of the SecretSink sync as part of the output of `kubectl get`

#### Notes

1. SecretSink status:

 - Synced
 - NotSynced
 - Errored
 - NotImplemented

2. ps: the CRD should be modified as part of this story

**Comment by gusfcarvalho** [comment]
@dominicmeddick  and @William-Young-97 some helpers for this issue:

We have to define a reconciler code somewhere for the SecretSink. The reconciler should be an `struct` implementing the following methods:

```

SetupWithManager(mgr ctrl.Manager, opts controller.Options) error
Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error)
```

After the code is created, it must be called in the `cmd/root.go`, as a way to teach external-secrets-operator to start looking for this resource.

Imports you might need:
```
        ctrl "sigs.k8s.io/controller-runtime"
        "sigs.k8s.io/controller-runtime/pkg/client"
        "sigs.k8s.io/controller-runtime/pkg/controller"
```

**Comment by ladeoshodi** [comment]
ps: SecretSink status will be implemented in https://github.com/external-secrets/external-secrets/issues/1091
