### ISSUE TITLE
[3] PushSecret: Platform Engineers can view the status of a PushSecret sync via `kubectl describe`

### ISSUE THREAD

**Issue by ladeoshodi** [external-secrets/external-secrets#1096]
Epic: https://github.com/external-secrets/external-secrets/issues/976

### Acceptance Criteria
**Scenario**: A platform engineer can check the SecretSink sync status via` kubectl describe`
**Given** a platform engineer is syncing secrets to an external secret provider
**When** the platform engineer runs the command `kubectl describe` on the SecretSink custom resource definition
**Then** the platform engineer is able to see the status of the SecretSink sync as part of the output of `kubectl describe`

#### Notes
SecretSink status
* Synced
* NotSynced
* Errored

**Comment by ladeoshodi** [comment]
Not working on the latest version, something is broken, please fix :)  (see image)

![Image](https://user-images.githubusercontent.com/13224175/173865903-f22695c8-3cbf-464b-b69e-1b06410ab16f.png)

cc @AmrFawzymoh @dominicmeddick @radiosilence

**Comment by gusfcarvalho** [comment]
Pipeline fixed - moving back to acceptance


![Image](https://user-images.githubusercontent.com/17139678/175034754-51aedffb-9118-46c9-bc55-a1e983217e31.png)

**Comment by ladeoshodi** [comment]
Works now


![Image](https://user-images.githubusercontent.com/13224175/175514589-7740f200-eae8-46bd-b062-49b533c454d6.png)
