### ISSUE TITLE
[2] PushSecret: Platform Engineers can update secrets in a Secret Provider (AWS Secrets Manager)

### ISSUE THREAD

**Issue by ladeoshodi** [external-secrets/external-secrets#1103]
Epic: https://github.com/external-secrets/external-secrets/issues/976

### Acceptance Criteria
**Scenario**: A platform engineer can update secrets in AWS Secrets Manager
**Given** a platform engineer is syncing secrets from AWS Secrets Manager
**When** a secret is updated in the k8s cluster 
**And**  the Update method to sync secrets to AWS Secrets Manager is enabled
**Then** the platform engineer is able to update secrets in AWS Secrets Manager

#### Notes
- ps: SecretSink should only be able to override a secret in a Secret Provider if
  - the secret did not exist before (IfNotExists) or
  - the secret was created by the k8s cluster via ESO SecretSink

**Comment by Piojo12** [comment]
`[docker pull  

> @ghcr.io/external-secrets/external-secrets:sha256-1bacc54a2170928023868100f5bae0e33ae4e4d5d1f61415bed3ce32bec458a6.sig](https )  ##`
