### ISSUE TITLE
Add support for IBMCloud SM Private Certificate

### ISSUE THREAD

**Issue by nitzann** [external-secrets/external-secrets#1159]
Describe the solution you'd like
external-secrets should be able to extract and store a public cert type of IBM cloud secret

What is the added value?
Users that need to store private certificates data in a Kubernetes secret will be able to do so

Give us examples of the outcome

Should work just like any other IBMCloud supported secret, specifically it will be similar to imported_cert type. Available properties are certificate, intermediate, private_key

Observations (Constraints, Context, etc):

N/A

**Comment by IdanAdar** [comment]
Looks like this ticket can be closed now...
