### ISSUE TITLE
FailedScheduling when installing on fargate

### ISSUE THREAD

**Issue by ultratin** [external-secrets/external-secrets#1164]
**Describe the solution you'd like**
external secrets should be able to install on was fargate or at least better documentation regarding integration using fargate vs ecs

**What is the added value?**
Better documentation for the long run.

**Give us examples of the outcome**
When installing external-secrets through helm, the install goes perfectly but when I check the events for the `external-secrets` namespace, I'm presented with the error below. Looks like a fargate specific taint but I haven't been able to find any information about it. 
```
❯ k get events -n external-secrets
LAST SEEN   TYPE      REASON              OBJECT                                                   MESSAGE
31s         Warning   FailedScheduling    pod/external-secrets-6bbdcfc778-d5bjt                    0/5 nodes are available: 5 node(s) had taint {eks.amazonaws.com/compute-type: fargate}, that the pod didn't tolerate.
3m13s       Warning   FailedScheduling    pod/external-secrets-6bbdcfc778-zsmbz                    0/5 nodes are available: 5 node(s) had taint {eks.amazonaws.com/compute-type: fargate}, that the pod didn't tolerate.
31s         Normal    SuccessfulCreate    replicaset/external-secrets-6bbdcfc778                   Created pod: external-secrets-6bbdcfc778-d5bjt
```

**Observations (Constraints, Context, etc):**
Cluster is on k8s version 1.22 and running on AWS Fargate
Installed with the following commands
``` shell
helm repo add external-secrets https://charts.external-secrets.io
helm install external-secrets external-secrets/external-secrets -n external-secrets --set installCRDs=true
```

**Comment by gusfcarvalho** [comment]
Hi @ultratin ! Have you set any fargate profiles for your installation? I believe they are needed if you intend to run pods on it (see more at https://docs.aws.amazon.com/eks/latest/userguide/fargate-profile.html)

**Comment by ultratin** [comment]
I see, that makes much more sense as a lot of people have mention this repo as the best way to mount secrets to fargate. I'll take a look into it, would this be a good candidate for docs update?

**Comment by gusfcarvalho** [comment]
we always welcome PR to docs! I think you can put it into the examples session :)

**Comment by gusfcarvalho** [comment]
Some guides for it: You need to add your `.md` files to docs/ folder, then add a reference to it in `hack/api-docs/mkdocs.yml`
