### ISSUE TITLE
tls_skip_verify option in SecretStore for Hashicorp Vault server 

### ISSUE THREAD

**Issue by AnuragEkkati** [external-secrets/external-secrets#1191]
Hi, 

I am trying to authenticate with Hashicorp Vault Server from SecretStore. I provided the ca certificate as below mentioned in the externalsecrets documentation of SecretStore.

caProvider:
        # Can be Secret or ConfigMap
        type: "Secret"
        name: "my-cert-secret"
        key: "cert-key"

I am getting below error once i deploy the secretstore 

...
...
Status:
  Conditions:
    Last Transition Time:  2022-05-25T22:03:24Z
    Message:               unable to validate store
    Reason:                ValidationFailed
    Status:                False
    Type:                  Ready
Events:
  Type     Reason            Age                  From          Message
  ----     ------            ----                 ----          -------
  Warning  ValidationFailed  35s (x7 over 6m35s)  secret-store  invalid vault credentials: context deadline exceeded

**Logs of the container:**

{"level":"error","ts":1653516204.6760063,"logger":"controller.secretstore","msg":"Reconciler error","reconciler group":"external-secrets.io","reconciler kind":"SecretStore","name":"be-vault-secretstore","namespace":"be","error":"could not validate provider: invalid vault credentials: context deadline exceeded","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}

**Need Input/Help on**

1. Confirming if I am providing the right information. I am providing the caCert to the secretstore so that it can trust the Vault Server I provided. 
2. Is there any way to set the flag tls_skip_verify
3. How do we provide the client_cert and client_key for mTLS mode of authentication with VaultServer

Ref: 

### ExternalSecrets: https://external-secrets.io/v0.5.3/api-secretstore/

**Comment by gusfcarvalho** [comment]
Hi @AnuragEkkati ! 

regarding point 1 - The `context deadline exceeded` error is more likely due to external-secrets-operator not being able to reach vault server (even wrong address, firewall rules, or wrong port). If you are using a `SecretStore`, I believe your configuration is right and should work once the communication is happening. One way to investigate this is to spin up a pod and try to `telnet` or `nc` your vault server.

regarding point 2 - we do not have an option to set it - PRs are welcome, even though I think this is the type of configuration that we only want when debugging.

regarding your point 3 - we do not support client_cert and client_key for mTLS right now (see https://github.com/external-secrets/external-secrets/issues/1139).

**Comment by AnuragEkkati** [comment]
Thanks for the quick reply @gusfcarvalho. Let me check and respond back.

regarding your response to point 3, wanted to confirm 

* That you do have support for vault cert auth. 
* Providing client_cert and client_key for vault cert auth enables mTLS communication between client and vault 

cert:
   clientCert:
   secretRef:

**Comment by moolen** [comment]
Thats true, you can provide certs for authenticating with vault, what we can't do is use certs _just_ for mTLS and add a different auth method on top of it (e.g. static token): #1139

**Comment by AnuragEkkati** [comment]
Can i create a PR adding option to tls_skip_verify for testing purpose

**Comment by moolen** [comment]
Hey @AnuragEkkati sure, go ahead! I'll assign this issue to you then :heart:.

Do you want to add it to the store config? Or did you have something different in mind?
```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://my.vault.server:8200"
      # auth, version, path, caProvider, caBundle...
      verifyTLS: true # or false
```

**Comment by rnrsr** [comment]
you can pass the external-secret pod extraEnv:

```
extraEnv:
  - name: VAULT_SKIP_VERIFY
    value: "true"
```

this is how the old KES used to do it
