### ISSUE TITLE
Verify base image & generate SBOM

### ISSUE THREAD

**Issue by moolen** [external-secrets/external-secrets#1192]
We can use syft/grype to scan the base image we use to detect tampering. In  addition we should create an SBOM, store it as container attestation and sign it aswell with cosign.
That ensures that our users can trust our supply chain.
We should check in our CI pipeline that the complete chain is valid.

**Comment by IdanAdar** [comment]
Would it also be possible to supply multiple Dockerfiles? eg not only distro-less but also another variant based on RH UBI?

**Comment by moolen** [comment]
I second that! I don't mind adding UBI in a release image :+1:

**Comment by IdanAdar** [comment]
Sorry to hijack the ticket again, but what would be the process here? 

This is the base image to use:
```
FROM registry.access.redhat.com/ubi8/ubi-minimal
```

instead of 
```
FROM gcr.io/distroless/static
ARG TARGETOS
ARG TARGETARCH
```

How does this then translate to another Dockerfile in the repo and/or another image available/offered, that users can then replace, I assume, here: 

https://github.com/external-secrets/external-secrets-helm-operator/blob/main/config/manager/kustomization.yaml
```
images:
- name: controller
  newName: ghcr.io/external-secrets/external-secrets-helm-operator
  newTag: v0.5.9
```

**Comment by moolen** [comment]
yeah, we need another Dockerfile and change the build process so that we push multiple images; 
Users can choose which image to use by specifying it in the helm values:
* helm chart https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/values.yaml#L4
* olm https://github.com/external-secrets/external-secrets-helm-operator/blob/main/config/samples/operator_v1alpha1_operatorconfig.yaml#L11

The config in `config/manager/kustomization.yaml` you mentioned above is for the olm helm operator ([see dockerfile](https://github.com/external-secrets/external-secrets-helm-operator/blob/main/Dockerfile#L2)). Would you need support for OLM as well?

**Comment by IdanAdar** [comment]
Nope, you're right, it'd be those two entries you've mentioned.

**Comment by IdanAdar** [comment]
I've created a PR to add another Dockerfile, however I am not sure at all re image build process, publication of the image, etc. You may also want to move all Dockerfiles elsewhere, or re-name the original Dockerfile as well?
