### ISSUE TITLE
Implement main controller reconciliation

### ISSUE THREAD

**Issue by mcavoyk** [external-secrets/external-secrets#12]
**Describe the solution you'd like**
ExternalSecret controller should connect to the referenced SecretStore and fetch the secret material referenced by the ExternalSecrets resource. The controller should update the status of the ExternalSecret resource with the outcome of this reconciliation.

**Comment by knelasevero** [comment]
i am closing this one. Unless I am missing something, this is done. Feel free to reopen if you think otherwise.
