### ISSUE TITLE
Add a job to Helm chart to make sure API & validating webhook are running

### ISSUE THREAD

**Issue by aw1cks** [external-secrets/external-secrets#1221]
In `cert-manager`'s helm chart, a job is fired off to make sure the validating webhook's API server is healthy. This means that the chart install blocks until the validating webhook is able to accept incoming requests, enabling dependant charts to be installed unattended.

However with the `external-secrets` chart, if I want to e.g. install a SecretStore in another chart after installing the chart, I get a timeout since the validating webhook is still not able to validate my incoming manifest.

It would be really useful if the chart would block so that it could be installed unattended without a race condition.

**Comment by gusfcarvalho** [comment]
Hi @aw1cks ! Just wondering, are you using `--wait` option to install external-secrets chart?

**Comment by gusfcarvalho** [comment]
We have some Readiness probes to make sure helm only finishes when everything is ready (of course, considering `--wait` is used).

**Comment by aw1cks** [comment]
My apologies! It looks to not be an issue since upgrading to a newer version of Helm. I'll close this issue now
