### ISSUE TITLE
[Feature Request] - Propagate metadata to Service Account

### ISSUE THREAD

**Issue by vitorfhc** [external-secrets/external-secrets#1231]
**Describe the solution you'd like**
I am trying to create an `ExternalSecret` and a `SecretStore`, but I need both to have the annotation `argocd.argoproj.io/hook: PreSync`. The issue is that it's not possible to propagate this annotation to the `ServiceAccount` created by the store.

**What is the added value?**
We will be able to use Helm and ArgoCD hooks.

**Give us examples of the outcome**
We would get this template for the Service Account.

```apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::xxx:role/xxx"
  name: xxx
  namespace: xxx```

**Comment by gusfcarvalho** [comment]
Hi @vitorfhc ! You mean the serviceaccounta created by the helm chart?

**Comment by vitorfhc** [comment]
Yes @gusfcarvalho !

**Comment by vitorfhc** [comment]
Wait, am I wrong or I could do it with `.Values.serviceAccount.*`? I saw this [here](https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/templates/serviceaccount.yaml#L9-L12).

**Comment by gusfcarvalho** [comment]
Exactly. You can set it with the `Annotations` block for all the service accounts created by ESO

**Comment by vitorfhc** [comment]
I believe the link I sent you is about the controller's service account, and what I understood is that the annotations on it will be replicated to the store's service accounts by the controller.

Unfortunately, I think adding this annotation to the controller's service account is terrible, it could change my ArgoCD's workflow, and I don't want to do it.

I found a reference to the service account [in the CRD](https://github.com/external-secrets/external-secrets/blob/main/config/crds/bases/external-secrets.io_secretstores.yaml#L229). I wonder if we could change the CRD to inject these annotations in each store's service account, instead of using the same for all of them.

@gusfcarvalho

**Comment by vitorfhc** [comment]
I am sorry for the confusion. When associating a Service Account with a Store, we must create it. The controller doesn't create it for me. The option here is creating a Helm wrapper to make it easy.
