### ISSUE TITLE
Unable to Authenticate in EKS China Cluster with AWS provider

### ISSUE THREAD

**Issue by Primordium** [external-secrets/external-secrets#1251]
**Describe the solution you'd like**
Having authentication with regional endpoints for AWS provider in China

**What is the added value?**
Ability to use ESO in EKS china

I've tried and failed to have ESO working on AWS EKS China (Beijing region), my deploy consist in

Kubernetes version 1.22
IAM Role used in the same account of the EKS cluster.

Service Account
`Service Account
Name:                external-secrets-operator-cn-prod
Namespace:           secrets-importer-cn-prod
Labels:              app.kubernetes.io/instance=external-secrets-operator-cn-prod
                     app.kubernetes.io/managed-by=Helm
                     app.kubernetes.io/name=external-secrets
                     app.kubernetes.io/version=v0.5.6
                     helm.sh/chart: external-secrets-0.5.6
Annotations:         eks.amazonaws.com/audience: sts.amazonaws.com.cn
                     eks.amazonaws.com/role-arn: arn:aws-cn:iam::<ACCOUNT_NUMBER>:role/<ROLE>
                     meta.helm.sh/release-name: external-secrets-operator-cn-prod
                     meta.helm.sh/release-namespace: secrets-importer-cn-prod
Image pull secrets:  <none>
Mountable secrets:   kubernetes-external-secrets-cn-prod-token-4zg9z
Tokens:              kubernetes-external-secrets-cn-prod-token-4zg9z
Events:              <none>`

Cluster Store
`apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store-prod
spec:
  provider:
    aws:
      service: SecretsManager
      region: cn-north-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-operator-cn-prod
            namespace: secrets-importer-cn-prod`
            
Environment variables in "Main" pod (Not certController or webhook)
```
AWS_DEFAULT_REGION cn-north-1
AWS_REGION cn-north-1
AWS_ROLE_ARN arn:aws-cn:iam::<ACCOUNT_NUMBER>:role/<ROLE>
AWS_STS_REGIONAL_ENDPOITS=regional
AWS_WEB_INDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
```

At first I thought having AWS_STS_REGIONAL_ENDPOINTS would be picked up by aws provider to point to the correct sts endpoints, but since it was failing I've added the Env Variable: 
AWS_STS_ENDPOINT and tried with values https://sts.amazonaws.com.cn (which for wasn't reachable) and with
https://sts.cn-north-1.amazonaws.com.cn 

the latter which is the regional endpoint and AWS recommends to use when possible to decrease latency is reachable but ESO is unable to authenticate with it either. It outputs the following log

```
{"level":"info","ts":1654634933.0456045,"logger":"provider.aws","msg":"using aws session","region":"cn-north-1","credentials":{}}
{"level":"error","ts":1654634933.451265,"logger":"controllers.ClusterSecretStore","msg":"unable to validate store","clustersecretstore":"/cluster-secret-store-e2e","error":"could not validate provider: WebIdentityErr: failed to retrieve credentials\ncaused by: InvalidIdentityToken: Incorrect token audience\n\tstatus code: 400, request id: be90e6da-cdec-4f60-9c42-a046335695e5","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/secretstore.(*ClusterStoreReconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/clustersecretstore_controller.go:55\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
```

```
Setting the environment variable to china global sts endpoint gives:
{"level":"error","ts":1654640334.0753946,"logger":"controllers.ClusterSecretStore","msg":"unable to validate store","clustersecretstore":"/cluster-secret-store-e2e","error":"could not validate provider: WebIdentityErr: failed to retrieve credentials\ncaused by: RequestError: send request failed\ncaused by: Post \"http://sts.amazonaws.com.cn/\": dial tcp: lookup sts.amazonaws.com.cn on 10.100.0.10:53: no such host","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/secretstore.(*ClusterStoreReconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/clustersecretstore_controller.go:55\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227"}
```

I've used a few tools to check the connection on another pod in the same namespace to check the connections and the results are:

```
kubectl get service kube-dns -n kube-system
NAME       TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)         AGE
kube-dns   ClusterIP   10.100.0.10   <none>        53/UDP,53/TCP   72d


root@kvsst-5d7b56d74d-q5ts4:/# nslookup sts.amazonaws.com
Server:         10.100.0.10
Address:        10.100.0.10#53

** server can't find https://sts.amazonaws.com: NXDOMAIN


root@kvsst-5d7b56d74d-q5ts4:/# nslookup sts.cn-north-1.amazonaws.com.cn
Server:         10.100.0.10
Address:        10.100.0.10#53

Non-authoritative answer:
Name:   sts.cn-north-1.amazonaws.com.cn
Address: 54.222.22.180
```

I can ping google.com and other sites.
Am I missing something in the configuration? In other cluster located in Europe or North America it works perfectly fine.
           
I've even tried to use other Service Account that is being used with KES and I know it's working.

**Comment by marcincuber** [comment]
Hi,
I worked with China exactly the same region and it is never ending story :).

Back to your problem. I believe for some reason it is using sts endpoint which doesn't exist. As you are in Beijing region, it should be set to `sts.cn-north-1.amazonaws.com.cn`. Looking at the [docs](https://docs.amazonaws.cn/en_us/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html), https://sts.amazonaws.com.cn. is also available but Amazon recommends using Regional Amazon STS endpoints.

I am sure I had it working so I would suspect that there could be an issue with configuration of your service account and linked IAM Role. Do you mind providing your trusted policy for IAM Role? I bet this is something to do with your OIDC.

**Comment by Primordium** [comment]
Hi marcincuber,
I'm currently in holidays, so I don't have full access to the cluster right now, but to answer your question, I

> Back to your problem. I believe for some reason it is using sts endpoint which doesn't exist. As you are in Beijing region, it should be set to `sts.cn-north-1.amazonaws.com.cn`. Looking at the [docs](https://docs.amazonaws.cn/en_us/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html), `https://sts.amazonaws.com.cn.` is also available but Amazon recommends using Regional Amazon STS endpoints.

> I've tried both endpoints, the "global" one https://sts.amazonaws.com.cn didn't work the regional one, gave me the error I pasted on the first post.

> I am sure I had it working so I would suspect that there could be an issue with configuration of your service account and linked IAM Role. Do you mind providing your trusted relationship policy for IAM Role? I bet this is something to do with your OIDC. As in the error you can clearly see that it could obtain the credentials `failed to retrieve credentials`. Also share the yaml for `ClusterSecretStore` resource.

This is the IAM trust relationships that the role I'm trying to use has (I removed the account number and oidc prov). This role is used by KES and ESO.
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "1",
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws-cn:iam::<ACCOUNT_NUMBER>:oidc-provider/oidc.eks.cn-north-1.amazonaws.com.cn/id/########################"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringLike": {
                    "oidc.eks.cn-north-1.amazonaws.com.cn/id/################:sub": "system:serviceaccount:secrets-importer-cn-prod:*"
                }
            }
        }
    ]
}
```

This role is currently being used by the old Kubernetes External Secrets, and since I'm using the same namespace it should be ok. The role in environment variable AWS_ROLE_ARN points to this role.

I don't have access to the cluster store right now, but I have the template from where I deploy it, so I'm confident that the resource is something like:

`apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store-prod
spec:
  provider:
    aws:
      service: SecretsManager
      region: cn-north-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-operator-cn-prod
            namespace: secrets-importer-cn-prod`

I can verify this in one week, just to be 100% sure, I even tried to set the serviceAccountRef to the service account used by KES, which I know it's working

**Comment by marcincuber** [comment]
I think your trusted policy be of this structure:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws-cn:iam::${ACCOUNT_ID}:oidc-provider/${OIDC_PROVIDER}"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "${OIDC_PROVIDER}:aud": "sts.amazonaws.com",
          "${OIDC_PROVIDER}:sub": "system:serviceaccount:my-namespace:my-service-account"
        }
      }
    }
  ]
}
```

I can see you are using condition `StringEquals` for the entire namespace. However, you are still missing a condition ```${OIDC_PROVIDER}:aud": "sts.amazonaws.com```. See https://docs.amazonaws.cn/en_us/eks/latest/userguide/create-service-account-iam-policy-and-role.html

**Comment by moolen** [comment]
I wrote that on slack already, so just FTR: https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/aws/auth/token_fetcher.go#L28

This `sts.amazonaws.com` is hardcoded for this particular path. We need to make this configurable and then we should be good to go.

**Comment by marcincuber** [comment]
@moolen I have a feeling that the audience is the same across all regions. And based on the [docs](https://docs.amazonaws.cn/en_us/eks/latest/userguide/enable-iam-roles-for-service-accounts.html) it looks like the audience value is the same for China regions which is weird as all other endpoints are different.

**Comment by Primordium** [comment]
@moolen @marcincuber 
Sorry for the late response, I've tried the suggestions above to no avail. 
But lets start with the documentation on AWS China, I have some reservation with it is in English, although I'm not able to read them in Chinese you can clearly see there are differences when you switch the language (it seems they copied the global documentation, but didn't adjust to their use cases when in English), as you can see [here](https://docs.amazonaws.cn/en_us/eks/latest/userguide/enable-iam-roles-for-service-accounts.html) for example, the TRUST_RELATIONSHIP document in English shows 

English version
```
read -r -d '' TRUST_RELATIONSHIP <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws-cn:iam::${ACCOUNT_ID}:oidc-provider/${OIDC_PROVIDER}"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "${OIDC_PROVIDER}:aud": "sts.amazonaws.com",
          "${OIDC_PROVIDER}:sub": "system:serviceaccount:my-namespace:my-service-account"
        }
      }
    }
  ]
}
EOF
echo "${TRUST_RELATIONSHIP}" > trust.json
```

Chinese Version

```
read -r -d '' TRUST_RELATIONSHIP <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::${ACCOUNT_ID}:oidc-provider/${OIDC_PROVIDER}"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "${OIDC_PROVIDER}:sub": "system:serviceaccount:my-namespace:my-service-account"
        }
      }
    }
  ]
}
EOF
echo "${TRUST_RELATIONSHIP}" > trust.json
```

The endpoints for sts according to their [documentation](https://docs.amazonaws.cn/en_us/aws/latest/userguide/endpoints-Beijing.html) should end with `amazonaws.com.cn`

adding the aud entry to the Trust relationship policy, should not be needed for this use case, either way I tested with it, but it wield the same results.

My oidc provider in china points to and only to :` sts.amazonaws.com.cn`, this is a security requirement to avoid authenticating IAM roles outside china region, not sure, if in your use cases you have several oidc or with multiple endpoints, but in our case we have a setup like this, which I believe, is very common.

Since I was unable to make it work by changing the policy and editing the oidc provider is out of the question, I made a new ESO build changing the file
[https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/aws/auth/token_fetcher.go#L28](https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/aws/auth/token_fetcher.go#L28) 
and making the tokenAudience "sts.amazonaws.com.cn"
this change together with AWS_STS_ENDPOINT environment variable made it work right away.

After I remembered that in KES I had to use an annotation in the service account to make it work on china 
`eks.amazonaws.com/audience` 

With that in mind I further change token_fetcher to use annotation if available, (sorry for my go skills in advance)

```
	var tokenAudience = "sts.amazonaws.com"

	log.V(1).Info("fetching token", "ns", p.Namespace, "sa", p.ServiceAccount)
	testannot, _ := p.k8sClient.ServiceAccounts(p.Namespace).Get(ctx, p.ServiceAccount, metav1.GetOptions{})

	keys := testannot.GetAnnotations()
	if v, found := keys["eks.amazonaws.com/audience"]; found {
		tokenAudience = v
	}
```

with this change I have a working version in china eks as well in europe.

**Comment by moolen** [comment]
Good catch, this is very helpful! Thanks for writing it up in detail! I guess there are a couple of more annotations which aren't yet supported but really should. This seems like a quite easy fix :pray:

https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/pkg/annotations.go
