### ISSUE TITLE
ArgoCD: User cannot be authenticated with the token provided.

### ISSUE THREAD

**Issue by baileydoestech** [external-secrets/external-secrets#1287]
**Describe the solution you'd like**
We are trialing ESO using ArgoCD to deploy the standard ESO helm chart, however pods are failing due to an authorisation error to ghcr.io as shown below. We have no token in the cluster for GHCR but I would have thought access to the repository is public?

![image](https://user-images.githubusercontent.com/3185073/175027842-4a2ba7f4-b559-4b5d-8dc3-fe7eed114bfe.png)

**What is the added value?**
Installation should be as straightforward as possible, ideally without using a token to get images. 

**Give us examples of the outcome**
Ability to pull ESO images without the need to authenticate to GHCR.

**Comment by Marza** [comment]
@moolen it should be, but seems there is a problem or change with the registry recently that currently makes it not work.
I also have same problem since today.

```
% docker pull ghcr.io/external-secrets/external-secrets:v0.5.1
v0.5.1: Pulling from external-secrets/external-secrets
b0b160e41cf3: Pulling fs layer 
dc7fe2654f4e: Pulling fs layer 
error pulling image configuration: download failed after attempts=1: unauthorized: unauthenticated: User cannot be authenticated with the token provided.
```

**Comment by baileydoestech** [comment]
@moolen testing outside our cluster (which does have a transparent squid proxy) and still getting the same issue

![image](https://user-images.githubusercontent.com/3185073/175031887-af59bc56-5926-4e22-9af1-eb3815e44ae8.png)

**Comment by baileydoestech** [comment]
Yup that explains it thanks, images starting to come through now so hopefully they have resolved
