### ISSUE TITLE
[2] PushSecret: A platform Engineer can configure a PushSecret Synchronization Interval

### ISSUE THREAD

**Issue by gusfcarvalho** [external-secrets/external-secrets#1292]
Epic: https://github.com/external-secrets/external-secrets/issues/976

# Acceptance Criteria

Scenario: A platform engineer can configure a PushSecret Synchronization interval
Given a platform engineer has configured a PushSecret Sync. Interval
When a secret is updated in the k8s cluster
And it has passed Sync. Interval since the last PushSecret update,
Then the platform engineer is able to see the updated secrets information in the configured provider.

# Notes
* A PushSecret can be updated with no changes to the Custom Resource.

* The Platform engineer should be able to configure the Synchronization Interval in a human friendly manner ("1h", "10m", "10s")

* The Synchronization Interval should be available within the PushSecret spec as `refreshInterval`:
```
spec:
  refreshInterval: "1m"
```

**Comment by ladeoshodi** [comment]
Accepted: Secrets update automatically in GCP secret manager
