### ISSUE TITLE
Broken Link in the Documentation

### ISSUE THREAD

**Issue by eminalemdar** [external-secrets/external-secrets#1295]
**The Problem**
I don't know if this is a bug or not but I realized after merging this [PR](https://github.com/external-secrets/external-secrets/pull/1289) the [documentation](https://external-secrets.io/v0.5.7/#how-to-get-involved) is not updated. Also Edit this Page button on the documentation redirects to [this](https://github.com/external-secrets/external-secrets/edit/master/docs/index.md) broken URL. Maybe because of this the PR did not effect the documentation website.

It seems I've updated the wrong page. If you can guide me to the right page I can create another PR for this update to the documentation.

**Comment by moolen** [comment]
It's the right page you've edited, it's available here: https://external-secrets.io/main/
you must pick the correct release/branch (main) from the dropdown menu at the top of the page :)

**Comment by eminalemdar** [comment]
Ooh I see! Thanks a lot @moolen :) I am closing this issue.
