### ISSUE TITLE
external-secrets.io website does not redirect to HTTPS

### ISSUE THREAD

**Issue by tomerr-ma** [external-secrets/external-secrets#1305]
As a security project, It is expected that the project’s website will cover this basic standard if redirecting HTTP to HTTPS..

**Comment by gusfcarvalho** [comment]
Hi @tomerr-ma ! Thanks for bringing that into attention. I’ve updated gh-pages to force https, it should propaga-te anytime soon.

**Comment by gusfcarvalho** [comment]
Propagated! Closing this issue!
