### ISSUE TITLE
BUG: ExternalSecret controller is force normalizing `refreshInterval` to `XmYs`

### ISSUE THREAD

**Issue by nazarewk** [external-secrets/external-secrets#1312]
**Describe the solution you'd like**
The controller does not normalize the duration value.

**What is the added value?**
Helps interacting with GitOps tools like Argo CD

**Give us examples of the outcome**

--

**Observations (Constraints, Context, etc):**

ExternalSecret upgrade from 0.4.4 to 0.5.7 all our Argo CD applications are out of sync, because we specify `refreshInterval` as either `120s` or `2m`, while the ES controller started to normalize it to `2m0s` preventing Argo CD application to settle.

**Comment by gusfcarvalho** [comment]
hi @nazarewk ! This is a known issue when converting from `v1alpha1` to `v1beta1`. You have to update your resources to use v1beta1 within ArgoCD, or to specify the full duration syntax in your resources. you can check [here](https://github.com/external-secrets/external-secrets/issues/1031) for more information.

**Comment by nazarewk** [comment]
closing as a duplicate of #1031
