### ISSUE TITLE
Feature: Support to create configmaps when external secrets change

### ISSUE THREAD

**Issue by AnuragEkkati** [external-secrets/external-secrets#1316]
**Describe the solution you'd like**
As of now we create k8s secret when an external secret changes. But it will be really awesome if externalsecret CRD can create/manage/sync to configmap when external secrets update.

**What is the added value?**
Really great addition to the tool and the one stop solution for both secrets and configmap sync

**Comment by gusfcarvalho** [comment]
Hi @AnuragEkkati ! I need to let this open for a while, because part of our projects design was explicitly mentioning not to use configmaps. You can see it [here](https://github.com/external-secrets/external-secrets/blob/main/design/design-crd-spec.md)

**Comment by AnuragEkkati** [comment]
Thanks for the replly @gusfcarvalho
