### ISSUE TITLE
Client side throttling with many secrets and low refresh interval

### ISSUE THREAD

**Issue by bobbywatson3** [external-secrets/external-secrets#1336]
**Describe the solution you'd like**
On our cluster with ~1,800 external-secrets set at approximately 15s `refreshInterval`,  we frequently see secrets taking minutes to sync, and the following errors (in between successul syncs) in the logs:
```
I0707 17:40:58.294661       1 request.go:665] Waited for 49.945948656s due to client-side throttling, not priority and fairness, request: GET:https://172.20.0.1:443/api/v1/namespaces/foo/secrets/bar-secrets
```
Even with `concurrency` set to a high value like 1,000, we can't get around this throttling. Is it possible to configure the client side rate limiter? The kube go-client has the config [here](https://github.com/kubernetes/client-go/blob/506ef8944cd08d4de904e2a4a8b1039c31c63feb/rest/config.go#L115-L124). I think the external-secrets operator would need to be configured [here](https://github.com/external-secrets/external-secrets/blob/main/cmd/root.go#L93).  (Thanks @gusfcarvalho for help finding this)

This is with release v0.5.5.

**What is the added value?**
This would allow clusters with more sync traffic to maintain performant secret syncs.

**Observations (Constraints, Context, etc):**

Even with this traffic, resource utilization on the pods was very low at around 100mCPU and 220MiB of memory.

**Comment by gusfcarvalho** [comment]
Another option here would be to set a flag to allow caching Secrets and Configmaps, as this would effectively probably eliminate the ClientSided throttling.

**Comment by gusfcarvalho** [comment]
@moolen @knelasevero WDYT? maybe both options? (allow to configure RequestLimiter in the client Config and allow to configure enabling Secrets Caching)

**Comment by gusfcarvalho** [comment]
Hi @calebwoofenden ! The cache that I was mentioning was regarding the kubernetes secrets! Controller-runtime by default would cache anything to it as a way to not overload the APIserver (or the client apperently). For most cases this is not useful so we on purpose disabled the cache for secrets. Having this cache enabled would allow the client to be more efficient because it is eso the one creating the secrets in the first place.

**Comment by moolen** [comment]
I agree, both options would be beneficial, but having the ability to enable the cache will probably be enough. I guess the initial list/watch call is counted as a single request in regards to rate limiting.

Tho enabling cache will change the memory footprint significantly.

**Comment by florianmutter** [comment]
We are facing the same issue but I'm not sure if I can enable caching or not. Could someone tell me what the implications are of enabling caching? Is there something that could go wrong with caching enabled?

**Comment by moolen** [comment]
> not sure if I can enable caching or not

try it out :crossed_fingers: 

> Could someone tell me what the implications are of enabling caching?
> Is there something that could go wrong with caching enabled?

If you enable caching all Kubernetes `Kind=Secret` metadata is stored in-memory in the controller (memory usage will go up depending on the number+size of the secrets in your cluster). It will also change the access pattern of the operator towards the kube-apiserver - very likely less requests.


related: https://github.com/external-secrets/external-secrets/issues/1725

**Comment by florianmutter** [comment]
Thank you very much for the explanation. We will try it because it seems to have no impact on the operation of external secrets ecept different memory requirements.
