### ISSUE TITLE
AWS EKS: Internal error occurred: failed calling webhook "validate.externalsecret.external-secrets.io": Post "https://host:443/validate-external-secrets-io-v1beta1-externalsecret?timeout=5s": Address is not allowed

### ISSUE THREAD

**Issue by esteban1983cl** [external-secrets/external-secrets#1339]
**Describe the solution you'd like**
I need that external metrics works in AWS EKS with Custom CNI plugin like cilium, calico, etc.
Please, add to chart the ability to change the 8080 port for metrics.

**What is the added value?**
We'll get a fully supported solution for AWS EKS.

**Give us examples of the outcome**

N/A

**Observations (Constraints, Context, etc):**

Context: I have external-secrets installed into my EKS cluster. But when I deploy the ExternalSecret I get the message in the title of this issue. Investigating this issue, the probable fix is use hostNetwork flag that currently is supported by the chart, that is ok. In my case I get errors binding port error another pod running the 8080 with hostNetwork port is currently running.

EKS Version: 1.19
External Secrets Helm Chart Version: 0.5.3

Thanks for your support

**Comment by gusfcarvalho** [comment]
Hi @esteban1983cl ! You can already do it by setting the following in your `values.yaml` file:

```
extraArgs:
  metrics-addr: 8081
```

**Comment by gusfcarvalho** [comment]
@esteban1983cl can you confirm passing extraArgs fixed your issue?

**Comment by esteban1983cl** [comment]
Hi @gusfcarvalho I fixed my problem changing the conflicted pod of port and redeploy external secrets with "default" configuration. I'll try if I can do the change, thanks for your support.

**Comment by esteban1983cl** [comment]
Hi @gusfcarvalho should be a nice have add the same for healthzAddr in https://github.com/external-secrets/external-secrets/blob/main/cmd/root.go#L50

and

https://github.com/external-secrets/external-secrets/blob/main/cmd/root.go#L182

Thanks again for your support
