### ISSUE TITLE
Support additional custom labels on the serviceAccount in the helm chart ( for Azure workloadIdentity support)

### ISSUE THREAD

**Issue by alexku7** [external-secrets/external-secrets#1355]
Hello

In order to use the Azure Workload Identity authentication we need to add an additional label to the serviceAccount which is running the controller pod

The label is `azure.workload.identity/use: "true"`

Today the helm chart doesn't support to add additional custom labels to the serviceAccount, 
So we need to add this label manually after the helm install

**Comment by cebidhem** [comment]
Hello,

Even though I'm not using AKS, I think it makes sense to give users this possibility. I'm not a maintainer of the project, but I thought it could be an issue I could contribute on, being pure Helm.

Hope this gets merged !

**Comment by gusfcarvalho** [comment]
I think there are other ways to configure your setup without needing to add the label 🤔 but then again this feature would be useful by itself! }

Thanks for your contribution @cebidhem

**Comment by alexku7** [comment]
According the Microsoft docs the label is must to make the workload identity working

Thanks anyway
