### ISSUE TITLE
Use TokenRequest API to fetch service account tokens

### ISSUE THREAD

**Issue by javanthropus** [external-secrets/external-secrets#137]
**Describe the solution you'd like**
Use the [TokenRequest API](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#tokenrequest-v1-authentication-k8s-io) to fetch tokens used for authentication on demand.

**What is the added value?**
The TokenRequest API makes it possible to fetch tokens with a configurable TTL and audience so that they can be used for a specific purpose (such as authenticating with Vault with JWT auth or AWS via IRSA) and are only good for a short period of time before they expire.  Single purpose, short lived tokens are better for security.

The service account token that can currently be used may never expire and is intended for use with the Kubernetes API itself.  Using it with other services increases the chance that it may leak and be used against the cluster.

**Give us examples of the outcome**

This would extend the vault provider's kubernetes auth property in SecretStore and ClusterSecretStore and add a new property named `tokenRequestAPI`.  This object would include the [TokenRequestSpec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#tokenrequestspec-v1-authentication-k8s-io) object content.  It would also need to include a `serviceAccountName` property.  ClusterSecretStore would also need to include a `namespace` property.

The same new property would be added directly to the the aws provider's auth object.  This would enable the use of IRSA when authenticating with AWS since IRSA depends on using dedicated tokens.

**Observations (Constraints, Context, etc):**

The following YAML can be sent to the k8s API to receive a token:
```yaml
apiVersion: authentication.k8s.io/v1
kind: TokenRequest
spec:
  audiences:
    - bar
    - baz
  expirationSeconds: 630
```
This will request a token with a TTL of 10 minutes and 30 seconds with the audience list set to `bar` and `baz`.  A token created for the `demo` service account in the `default` namespace can be retrieved by sending that content to the API server at `api/v1/namespaces/default/serviceaccounts/foo/token`.  This can be demonstrated with curl as follows assuming you have already run `kubectl proxy` and that the YAML has bee saved to `token-request.yaml`:
```sh
curl -X POST localhost:8001/api/v1/namespaces/default/serviceaccounts/foo/token -H 'Content-Type: application/yaml; charset=utf-8' --data-binary @token-request.yaml
```

The only real limitation I have found so far is that the minimum TTL for tokens is 10 minutes.  The API enforces this, and I haven't found away to change that yet.

This requires the TokenRequest feature gate to be enabled (on by default since Kubernetes 1.12, and available since 1.10).  The following options for the kube-apiserver also need to be specified:
* `--service-account-signing-key-file`
* `--service-account-key-file`
* `--service-account-issuer`
* `--service-account-api-audiences`

These are apparently enabled by default in EKS.  ClusterAPI also enables them by default.

**Comment by moolen** [comment]
yes, we definitely want that!
I found good source for a reference implementation in the [secret-store-driver-aws](https://github.com/aws/secrets-store-csi-driver-provider-aws/blob/main/auth/auth.go) repo.

I think this is relevant for both `vault` and `aws` provider. That way the controller itself could run with 0 permissions while the service account provides the necessary auth for AWS.

**Comment by gabibeyer** [comment]
Would it be alright if I took this issue on?

**Comment by moolen** [comment]
sure, go ahead :)

**Comment by gabibeyer** [comment]
Hi @moolen and @javanthropus we are a bit unclear on the workflow for this authentication method. We decided to start with the AWS implementation (will probably ask vault questions later :stuck_out_tongue: ). In my understanding, the TokenRequestAPI is used to fetch a token using a serviceAccount from the kubernetes cluster. This would be performed at the SecretStore (authentication) level. Once that token is fetched, how would it be shared with AWS and OIDC to gain the granular access for containers to access the appropriate secrets using IRSA?

Would we need to continue to use the Secret Access Key and Secret ID to authenticate prior to fetching the token?

Can we assume an OIDC provider is available?

Thank you for the help, 
@knelasevero, @riccardomc, @gabibeyer

**Comment by javanthropus** [comment]
The mechanism used by AWS IAM and OIDC/JWT authentication in Vault will be different.  In the AWS case, you'll exchange the token with AWS IAM to get temporary AWS credentials, so there will be no need at all for standard AWS credentials to be used or provided.  This exchange mechanism is built into the AWS SDK in order to support [IRSA](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/).  I've only ever seen how to use that with projected service account tokens on the filesystem, but that's not going to work here, so hopefully there is a more direct way to use the SDK and feed it a token explicitly.  This may be a good place to start looking:

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/credentials@v1.2.1/stscreds

For Vault, the OIDC/JWT authentication method is used as documented here:

https://www.vaultproject.io/docs/auth/jwt#jwt-authentication

The token you get from k8s would be given directly as the `jwt` parameter.  A vault token is returned in exchange, which is then used for further interaction with vault.

**Comment by gabibeyer** [comment]
I **hate** to be that person, but I need to unassign myself from this issue. My workload is too high at the moment. I'm sorry for the inconvenience.

**Comment by knelasevero** [comment]
No worries Gabi :) Thanks for letting us know!

**Comment by moolen** [comment]
i un-assigned myself as i'm currently not working on the Vault provider for this use-case.
