### ISSUE TITLE
Empty secret value.

### ISSUE THREAD

**Issue by qspors** [external-secrets/external-secrets#1375]
Hello.

I'm working with specific deployment where I need to put set of params from AWS SSM.
But some params should be empty (null)
Make this tru ssm is not possible cuz AWS SSM is not suppirt emty values for params.
How I can specify empty param for my External secret ?
I have this manifest and I want to see my secret with empty values for second param.

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-gitlab-runner
  namespace: gitlab-gitlab-runner
spec:
  secretStoreRef:
    name: ssm-secret-store
    kind: ClusterSecretStore
  data:
  - secretKey: runner-registration-token
    remoteRef:
      key: /giltabstuff/runner_registration_token
  - secretKey: runner-token
    remoteRef:
      key: null or empty or ''

of course I can't specify 

  - secretKey: runner-token
    remoteRef:
      key: /giltabstuff/runner_token

cuz ssm can't be empty.

**Comment by gusfcarvalho** [comment]
Hi @qspors ! I think you can use templating to help you:

```
template:
  data:
    runner-registration-token: {{ .runnerRegistrationToken }}
    runner-token: ""
```

**Comment by gusfcarvalho** [comment]
Hi @qspors ! Did the templating helped you?

**Comment by gusfcarvalho** [comment]
hi @qspors ! I'm closing this issue as we didn't hear from you. Feel free to reopen it if that's still an issue
