### ISSUE TITLE
failed calling webhook connect: connection refused

### ISSUE THREAD

**Issue by RuBiCK** [external-secrets/external-secrets#1378]
**Describe the solution you'd like**

When installing a helm chart that contains secret-store and external-secrets , I get a webhook error

```
Error: Internal error occurred: failed calling webhook "validate.externalsecret.external-secrets.io": Post "https://pre-external-secrets-webhook.external-secrets.svc:443/validate-external-secrets-io-v1beta1-externalsecret?timeout=5s": dial tcp 10.80.0.178:9443: connect: connection refused
Give here all extra information that could be interesting. Such as Golang version and Kubernetes version if you are reporting a bug/problem. You can also foresee technical constrains like "this could only be implementing using this specific technology or approach, because of this and that".
```

external-secrets-webhook-pod:

```
2022-07-22T11:37:57+02:00 {"level":"info","ts":1658482677.3532994,"logger":"setup","msg":"certs are valid"}
2022-07-22T11:42:57+02:00 {"level":"info","ts":1658482977.3529713,"logger":"setup","msg":"validating certs"}
2022-07-22T11:42:57+02:00 {"level":"info","ts":1658482977.3536494,"logger":"setup","msg":"certs are valid"}

```

external-secrets-cert controller
```
{"level":"info","ts":1658483270.8927696,"logger":"controllers.webhook-certs-updater","msg":"injecting ca certificate and service names","cacrt":"---READTED---","name":"externalsecret-validate"}
{"level":"info","ts":1658483270.8992212,"logger":"controllers.webhook-certs-updater","msg":"updated webhook config","Webhookconfig":"/externalsecret-validate"}
{"level":"info","ts":1658483270.9027,"logger":"controllers.webhook-certs-updater","msg":"updating webhook config","Webhookconfig":"/secretstore-validate"}
{"level":"info","ts":1658483270.9071784,"logger":"controllers.webhook-certs-updater","msg":"injecting ca certificate and service names","cacrt":"---READTED---","name":"secretstore-validate"}
{"level":"info","ts":1658483270.9126368,"logger":"controllers.webhook-certs-updater","msg":"updated webhook config","Webhookconfig":"/secretstore-validate"}
```

I have opened any-any from EKS control plane to worker nodes for testing purposes without results
Checked [this similar issue](https://github.com/external-secrets/external-secrets/issues/956) 

**Context**
EKS 1.21
ESO v0.5.8 (upgraded from v0.5.1) deployed with ArgoCD 2.4 using helm template

I don't know how to keep troubleshooting this issue, any help is welcome

**Comment by moolen** [comment]
Did you checked both directions egress (control plane sg) and ingress (worker node sg) ?
Did you try to run it with port `10250` ? This seems to be open by default on EKS IIRC.

**Comment by gusfcarvalho** [comment]
Hey, @RuBiCK! 

> When installing a helm chart that contains secret-store and external-secrets , I get a webhook error
Do you mean you are trying to install the external-secrets pod and some `ExternalSecrets` resources and `SecretStore` resources?

**Comment by RuBiCK** [comment]
@gusfcarvalho external-secrets was previously installed without errors. This error happens when I try to deploy an application that creates `ExternalSecrets` and `SecretStore` (externalSecrets and SecretStore I define in custom helm chart)

**Comment by gusfcarvalho** [comment]
are you using any specific CNI @RuBiCK?

**Comment by RuBiCK** [comment]
Nothing custom or special, just the default installation that comes with EKS 1.21
CNI version: amazon-k8s-cni-init:v1.10.1-eksbuild.

Checked networking security groups and added any-any for troubleshooting:
* control plane
  *   Ingress allow all from worker nodes
  *   egress allow all to any
* worker nodes
  * ingress allow all from control plane
  * egress allow all to any
  
No results

**Comment by moolen** [comment]
IIRC: The vpc cni allocates an eni for the webhook container which also has a security group, that needs a tweak, too.

**Comment by moolen** [comment]
We have the webhook running in EKS in our e2e suite: 

https://github.com/external-secrets/external-secrets/blob/main/terraform/aws/modules/cluster/main.tf#L115

**Comment by RuBiCK** [comment]
I don't think it's bug, I think the issue it's on my side.

I have checked the ENI corresponding with secrets-webhook service and has the SG with any-any.

I would login into POD and check inside but is not possible (as read in other issues) and I can't use `kubectl debug` because it has been introduced in 1.23

To be honest, I'm not sure how to debug and troubleshoot the admission-webhook part

**Comment by RuBiCK** [comment]
I have tested port-forwarding secrets-webhook and an HTTP request always returns a connection refused. 
secrets-webhook metrics endpoint answer without problems.

**Comment by RuBiCK** [comment]
I have downgraded external-secrets from v0.5.8 to v.0.5.0 and now I can deploy without problems with webhook.

I upgraded the version of the container in Helm Chart but I think, something else between v0.5.0 and v0.5.8 in Helm Chart has changed in addition to container.
I have checked commits between those versions and  there were changes with CRD that I wasn't introducing

**Comment by diegopedroso** [comment]
@gusfcarvalho I face the same problem here:

**EKS 1.22 - private control plane
Calico 0.3.1**

When I try to create SecretStore and ExternalSecrets:

I tried to install external-secrets using helm, and my charts version is 5.8.0, my values:

```
webhook:
  create: true

certController:
  create: true

hostNetwork: true
```

Also, I tried setup webhook with differents ports, because the default (10250) conflicts with another K8s service, the output error:

`"error":"listen tcp :10250: bind: address already in use","stacktrace":`

With 10260 port I can deploy using helm, but when I apply the manifests:


```
Error from server (InternalError): error when creating "/tmp/teste.yaml": Internal error occurred: failed calling webhook "validate.secretstore.external-secrets.io": Post "https://external-secrets-webhook.external-secrets.svc:443/validate-external-secrets-io-v1beta1-secretstore?timeout=5s": context deadline exceeded
Error from server (InternalError): error when creating "/tmp/teste.yaml": Internal error occurred: failed calling webhook "validate.externalsecret.external-secrets.io": Post "https://external-secrets-webhook.external-secrets.svc:443/validate-external-secrets-io-v1beta1-externalsecret?timeout=5s": context deadline exceeded
```

I open my SG for all traffic and source 0.0.0.0/0 on the AWS console but face the error.


But if I remove both ValidatingWebhookConfiguration, like this:

```
 kubectl delete ValidatingWebhookConfiguration externalsecret-validate --ignore-not-found=true
 kubectl delete ValidatingWebhookConfiguration secretstore-validate --ignore-not-found=true
```

I can create both manifests (SecretStore and ExternalSecrets), but I can see the ES status:

```
❯ kubectl get es -A
NAMESPACE   NAME                             STORE           REFRESH INTERVAL   STATUS
app-1       application-1-external-secrets   vault-backend   5         
```
