### ISSUE TITLE
Externalsecret and secret creation and update takes around 5 min

### ISSUE THREAD

**Issue by igor-sidorov** [external-secrets/external-secrets#1393]
We are migrating to external-secrets.io. When we just apply charts it takes around 5 min to sync and create secret. 

Even we change refreshInterval secrets sync for around 5 min. I also try to use command from doc `kubectl annotate es my-es force-sync=$(date +%s) --overwrite` and it isn't help.

Could you please advice

**Comment by moolen** [comment]
What do you see in the logs of the controller?
Changing the annotation will cause a immediate reconciliation of the ExternalSecret.

**Comment by igor-sidorov** [comment]
Just many of 
{"level":"info","ts":1658929987.2561705,"logger":"provider.aws","msg":"using aws session","region":"us-east-1","credentials":null}

**Comment by gusfcarvalho** [comment]
Hi @igor-sidorov ! How many ExternalSecrets do you have, with which refreshInterval?

This may be a duplicate of #1336

**Comment by igor-sidorov** [comment]
For creation secrets we are using dataFrom.find. We have 27 External secrets. 

refreshInterval = 1m

Total ssm parameters around 200.

**Comment by moolen** [comment]
@igor-sidorov you can set the [loglevel](https://github.com/external-secrets/external-secrets/blob/main/cmd/root.go#L200) to `debug`? That will log a bit more context.

I don't have a wild guess to throw here, i think we need more information from :point_up_2: 

sidenote / enhancement idea:
It would be helpful to have metrics (maybe additionally a field in es.status) that shows the time taken for reconciliation of an ExternalSecret resource. Also, a (verbose) log event that logged when the reconciliation starts for a particular resource.

**Comment by igor-sidorov** [comment]
It is look like issue was because --concurrent=1.

I have increased that value --concurrent=10. And now secrets can't sync because of Throttling errors from AWS parameter store.

I changed image of deployment external-secrets (I think it is controller) to ghcr.io/external-secrets/external-secrets:main but still getting Throttling errors.

Is any option to solve Throttling errors on AWS parameter store?

**Comment by moolen** [comment]
I think you can throw money at AWS, they have increased limits with some non-standard parameters IIRC

I think we were about to add provider-level metrics in some issue. These would be helpful now. Let me see if i can implement them. That provides just visibility, that wont fix the issue tho.

**Comment by gusfcarvalho** [comment]
Hi @igor-sidorov ! I think its still worth to configure loglevel to debug. This way we can understand if there is any other bottleneck we can improve.

**Comment by igor-sidorov** [comment]
I have increased level but it won't provide any more useful data. I figured out that when you use dataFrom.find you communicate with AWS by GetParameterByPath api call. This method has limit 100 TPS what is very low. So I start use data which use method GetParameter and it not throw Throttling exception. I think it is worth to update manuals with that info.

**Comment by moolen** [comment]
:+1:  for adding docs around that


For cross-reference:
https://github.com/external-secrets/external-secrets/issues/1193
https://github.com/external-secrets/external-secrets/issues/1066

There is a proposal in https://github.com/external-secrets/external-secrets/issues/1193#issuecomment-1139970881 which could be more efficient in terms of API calls.
