### ISSUE TITLE
CNCF Onboarding Tasks

### ISSUE THREAD

**Issue by moolen** [external-secrets/external-secrets#1395]
relates to: https://github.com/cncf/toc/issues/882

This Issue tracks the state of the tasks needed for onboarding :point_up_2:

@knelasevero @gusfcarvalho feel free to @mention your name behind a TODO to claim it and start working on it, if needed create a separate issue.

Once completed check the box here. We can report to the TOC issue above regularly :point_up_2: 

---
From the project side, please ensure that you:

* [x]  all Understand the project proposal process and reqs: https://github.com/cncf/toc/blob/main/process/project_proposals.md#introduction
* [x]  all Understand the services available for your project at CNCF https://www.cncf.io/services-for-projects/
* [x]  all Ensure your project meets the CNCF IP Policy: https://github.com/cncf/foundation/blob/master/charter.md#11-ip-policy
  * [x] :warning: akeyless has no license file in their repo currently. i asked for clarification again, see: https://github.com/akeylesslabs/akeyless-go/issues/5 License was added :+1: 
  * [x] we have to wait for a new akeyless-go/v2 release: 2.17.0 was release :tada: 
  * [x] need to bump https://github.com/external-secrets/external-secrets/pull/1438 - Added code to bump it
  * [x] cleanup: #1446
* [x]  all Review the online programs guidelines: https://github.com/cncf/foundation/blob/master/online-programs-guidelines.md
* [x]  all Understand the trademark guidelines: https://www.linuxfoundation.org/en/trademark-usage/
* [x]  all Understand the license allowlist: https://github.com/cncf/foundation/blob/master/allowed-third-party-license-policy.md#approved-licenses-for-allowlist
* [x]  all Is your project working on written, open governance? see https://contribute.cncf.io/maintainers/governance/
  * [x] Basic governance is covered: Mission Statement, contributing guidelines, release guidelines, release planning
  * [x] I don't think we're supposed to have a rock-solid leadership with P&P fully fleshed out. This is something we'll figure out.
* [x] Slack: Are your slack channels migrated to the Kubernetes or CNCF Slack? (see https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another for more details). 
  * Ask about if we can add orbitLove to kubernetes slack channel.
* [x]  Is your project in its own separate neutral github organization?
* [x]  @moolen Submitted a Pull request to add your project as a sandbox project to https://landscape.cncf.io
  * [x] https://github.com/cncf/landscape/pull/2692
  * [ ] fixup devstats & new icon with text
* [x]  @knelasevero Create maintainer list + add to aggregated https://maintainers.cncf.io list by submitting a PR to it
* [x]  @knelasevero Have added your project to https://github.com/cncf/contribute
* [x]  @knelasevero Artwork: Submit a pull request to https://github.com/cncf/artwork with your artwork
   * done - https://github.com/cncf/artwork/pull/351
* [x]  @knelasevero Domain: transfer domain to the CNCF - https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63

Things that CNCF will need from the project:

* [x]  @knelasevero Provide emails for the maintainers added to https://maintainers.cncf.io in order to get access to the maintainers mailing list and ServiceDesk
   * We need to provide the email list on the issue?
* [x]  @bengurney1. Trademarks: transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements
* [x]  @gusfcarvalho GitHub: ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners, this helps us make sure we have continuity of GH ownership
* [x]  @gusfcarvalho GitHub: ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
  * [x] https://github.com/external-secrets/external-secrets/issues/994
* [x]  @moolen  GitHub: ensure that hat the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
* [x]  @moolen Website: ensure LF footer is there and [website guidelines](https://github.com/cncf/foundation/blob/master/website-guidelines.md) followed (if your project doesn't have a dedicated website, please adopt those guidelines to the README file of your project on GitHub).
* [x]  @bengurney1 Website: Analytics transferred to [projects@cncf.io](mailto:projects@cncf.io)
* [x]  @moolen CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en

Things that the CNCF will do or help the project to do:

* [x]  Devstats: add to devstats https://devstats.cncf.io/
* [x]  Marketing: update relevant intro + slide decks
* [x]  Events: update CFP + Registration + CFP Area forms
* [x]  ServiceDesk: confirm maintainers have read https://www.cncf.io/services-for-projects/
* [x]  CNCF Welcome Email Sent to confirm maintainer list access, welcome email has monthly project sync details
* [x]  Create space for meetings/events on https://community.cncf.io, e.g., https://community.cncf.io/pravega-community/ - (https://github.com/cncf/communitygroups/blob/main/README.md#cncf-projects)
* [x]  Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)

**Comment by gusfcarvalho** [comment]
I guess we are basically missing the legal part of the logo transfer and the domain transfer, is that right?

**Comment by moolen** [comment]
yeah, also i need to fixup the logo and devstats url on landscape.cncf.io, but that isn't a blocker.
Based on that list :point_up_2: it also the domain transfer

Thanks for the logos in the above linked PR, i can take them to landscape repo.
