### ISSUE TITLE
[Documentation] - Specify ESO limitations on consecutive assumeRoles with AWS provider

### ISSUE THREAD

**Issue by davidblum** [external-secrets/external-secrets#1400]
**Describe the solution you'd like**
Is it possible for `external-secrets` to assume role into another AWS account to access secrets manager?

We run AWS secrets manager in account A.

We run an EKS cluster with ESO installed in account B.

I would like to assume role from account B, and into the role in account A, and access the Secret Manager.

Is this supported?

**What is the added value?**
A team / company can have a central secrets manager in one account, and access it via ESO from multiple AWS accounts.

**Give us examples of the outcome**

Documentation exists demonstrating how to assume role into an alternative account.

Steps:
- external-secrets uses service account + oidc to assume role in "B" account
- external-secrets then assumes another role in our "A" account
- external-secrets then retrieves the secret from the "management" aws account

**Observations (Constraints, Context, etc):**

I'm not sure if this is supported or advised, but it seems to be a fairly common pattern in the AWS world.

**Comment by davidblum** [comment]
Ok, just got this working configuring OIDC trusts from both accounts.

I'm still curious on if ESO supports multiple role assumption as well.

I'll update the issue tomorrow with examples / steps for the cross OIDC thingy.

**Comment by moolen** [comment]
Hey! A simple assume role should be supported with all authenticatiom mechanisms.
But role jumping (chaining multiple assume-role calls) is not supported currently.

**Comment by davidblum** [comment]
Thanks @moolen ! I appreciate your response!

I think its inherent in the docs, but might be worth a specific callout.

**Comment by jeremygovi** [comment]
hi @davidblum
> Ok, just got this working configuring OIDC trusts from both accounts.

I'm facing the same issue, "classic" authentication (aws creds) is indeed a bad practice. 
Can you tell me how you achieved this? maybe some config to share about account A and B?
Thank you in advance

**Comment by MansurEsm** [comment]
I would be also interested!

What I have thought till now:
Account A is the account where the AWS secretmanager secrets are stored
Account B shall deliver a clustersecretstore which is connected to account A

Account A:
```data "aws_iam_policy_document" "cross_account_assume_role_policy" {
  statement {
    effect = "Allow"

    principals {
      type        = "AWS"
      identifiers = [data.account_b__sa_irsa_arn]
    }

    actions = ["sts:AssumeRole"]
  }
}

resource "aws_iam_role" "cross_account_assume_role" {
  name               = "account-b-sa-irsa-role"
  assume_role_policy = data.aws_iam_policy_document.cross_account_assume_role_policy.json
}```

So account B can assume role of account A ...

Then create in account B an irsa:
```module "secret_irsa" {

  source = "../modules/tf_module_aws_irsa"

  cluster_name         = module.eks.cluster_id
  service_name         = "myservicename"
  service_account_name = "account-b-sa"
  namespace            = "kube-system"
  oicd_issuer_url      = split("//", module.eks.cluster_oidc_issuer_url)[1]
  iam_policy_arns      = [aws_iam_policy.secret.arn]

  ...
}```

The aws_iam_policy has attached a policydocument which allows the appropirate action/ressource of the secretmanager...

Will this may work, or do I understand it wrong / have a gap?

**Comment by gusfcarvalho** [comment]
This would work. Generally speaking this restriction doesn’t exist anymore, as we now allow AWS provider to fetch additionalRoles. :)

**Comment by gusfcarvalho** [comment]
Just remember to give role A access to your secrets

**Comment by MansurEsm** [comment]
Sadly something is wrong...

In Account A:
I added an own KMS key (I read I have to) to the secret I want to access.
The KMS key assigns the principal role of Account B to allow access to the key (At the moment kms:*)

Like this:
```
{
    "Version": "2012-10-17",
    "Id": "key-consolepolicy-3",
    "Statement": [
        {
            "Sid": "Enable IAM User Permissions",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::ID-ACCOUNT-A:root"
            },
            "Action": "kms:*",
            "Resource": "*"
        },
        {
            "Sid": "Allow use of the key",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::ID_ACCOUNT-B:role/ACCOUNT-B-sa-irsaXYZ"
            },
            "Action": "kms:*",
            "Resource": "*"
        }
    ]
}
```

The ClusterExternalSecret gets created and the status is True/Ready
This ClusterExternalSecret should create an externalSecret connected to the ClusterSecretStore and should read the Secret (key) from Account-A

It does'nt.

The logs of the external-secrets pod  does neither record the secret of account-B (Or any issues like "could not find the secret, because looking in Account-A" or smth like this), nor any error.

How does the ClusterSecretStote "know" in which accounts to look for?
By the assigned role of the serviceAccount?
You say:
> as we now allow AWS provider to fetch additionalRoles. :)

This is the Role Policy of the irsa Role in Account-B:
```
{
    "Statement": [
        {
            "Action": [
                "secretsmanager:ListSecretVersionIds",
                "secretsmanager:GetSecretValue",
                "secretsmanager:GetResourcePolicy",
                "secretsmanager:DescribeSecret"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:secretsmanager:eu-central-1:ACCOUNT-A:secret:TheNameOfTheSecretIWant",
               [... some more ... ]
            ],
            "Sid": "secretstoreAccess"
        }
    ],
    "Version": "2012-10-17"
}
```

It would be also helpfull if the external-secret would log not found secrets somehow ... and not just (maybe) ignore them

**Comment by moolen** [comment]
Hey @MansurEsm, in order to help you we need all the information: how did you install eso, the (Cluster)SecretStore and ExternalSecret yaml, and the cloud side of things (IAM Roles + trust relationships).

Please open a new issue for this or swing by in our slack :)
