### ISSUE TITLE
getting started guide crd url

### ISSUE THREAD

**Issue by kfox1111** [external-secrets/external-secrets#1409]
The getting started guide mentions how to helm install the chart, and how to manage the crds with the chart, but lacks the kubectl apply command with url to install the crds yourself if you want to do that.

**Comment by gusfcarvalho** [comment]
Hi @kfox1111 ! Can you please describe a little bit more what is your use case?

**Comment by kfox1111** [comment]
Go to here:
https://external-secrets.io/v0.5.8/guides-getting-started/

Both option 1 and option 2 have the flag commented out:
```
# --set installCRDs=true
```

But doesn't say what to do if you don't have the helm flag set.
There should be some:
```
kubectl apply -f <url to the crds>
```

the end user should be able to do. The documentation is missing what to do.

**Comment by kfox1111** [comment]
Still broken. open back up please?

**Comment by kfox1111** [comment]
Still an issue. Please reopen.

**Comment by moolen** [comment]
Hey! I added `kind/feature`, that should prevent `stalebot` from closing the issue.
This a great good first issue for new contributors, i hope someone can pick this up :crossed_fingers:
