### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by dineeno** [external-secrets/external-secrets#1418]
**Describe the solution you'd like**
Please would it be possible to cut and release a new version (0.5.9) of external-secrets?

**What is the added value?**
I would like to verify the behaviour of the new support for [trusted profiles in the IBM provider](https://github.com/external-secrets/external-secrets/commit/fdf1f9ce6f6c3e224248a2285456da06b9046c6f) in a released image.

**Observations (Constraints, Context, etc):**
As mentioned in the project [Release Process page](https://external-secrets.io/v0.5.8/contributing-release/) I am raising this issue to request a release is cut.

**Comment by moolen** [comment]
Hey! Sure, happy to do that. We can probably make it tomorrow.

**Comment by moolen** [comment]
Actually we'd like to wait for #1381 before we release.

**Comment by moolen** [comment]
0.5.9 is out :tada:, closing this issue.
