### ISSUE TITLE
Documentation does not state that CreationPolicy=Owner setting ownerReference field

### ISSUE THREAD

**Issue by dowlingw** [external-secrets/external-secrets#1419]
**Describe the solution you'd like**
Update the creationPolicy=Merge (or create a new policy) that also sets the `ownerReference` on the managed secret.

**What is the added value?**
This would be useful for bootstrapping the `Secret` used by a `SecretStore`, and having external-secrets automatically syncronise changes to the secret after the initial secret creation.

This is possible with the Merge strategy already, however my GitOps tooling (argocd) is attempting to self-heal (converge on declared state) and clean up the secret as without the `ownerReference` metadata it does not understand the `Secret`s relationship to the `ExternalSecret` resource.

**Give us examples of the outcome**
I think this could be achieved by extending the check in the `mutationFunc` in `pkg/controllers/externalsecret/externalsecret_controller.go` to also set apply owner fields for the merge creationPolicy.

**Observations (Constraints, Context, etc):**
The initial secret is being created directly with `kubectl create secret generic ...`.

**Comment by gusfcarvalho** [comment]
Hi @dowlingw ! Have you tried using `cretionPolicy=Owner`? IIRC, it will take ownership of secrets with no `ownerReference` setup.

**Comment by dowlingw** [comment]
> Hi @dowlingw ! Have you tried using `cretionPolicy=Owner`? IIRC, it will take ownership of secrets with no `ownerReference` setup.

Oh! I hadn't actually tried that - the documentation suggests other behaviour:

> Owner (default)
>
> The External Secret Operator creates secret and sets the ownerReference field on the Secret. This secret is subject to [garbage collection](https://kubernetes.io/docs/concepts/architecture/garbage-collection/) if the initial ExternalSecret is absent. If a secret with the same name already exists that is not owned by the controller it will result in a conflict. The operator will just error out, not claiming the ownership.

Testing quickly and it appears that you're absolutely right. I'll PR a documentation fix shortly.

**Comment by gusfcarvalho** [comment]
I will change the issue name then so people can refer to it in a better way!
