### ISSUE TITLE
Authenticate with Roles instead of AWS Access_Key and Secret_Access_Key

### ISSUE THREAD

**Issue by MasterAKT** [external-secrets/external-secrets#1427]
**Describe the solution you'd like**

I would like configure secret store with AWS provider to authenticate without IAM User. Instead I would like to authenticate with role which has the right policy to SecretManager. I haven't seen anywhere in the your documentation that allows that other than providing AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY.

I will appreciate any suggestion, documentation or idea to point me to the right direction to achieve this

**Comment by moolen** [comment]
Hey, we have a couple of authentication methods, please take a look here: https://external-secrets.io/v0.5.8/provider-aws-secrets-manager/#aws-authentication.
Does that help?
