### ISSUE TITLE
Can modify verbosity logs, have a custom log level setting

### ISSUE THREAD

**Issue by EnriqueHormilla** [external-secrets/external-secrets#1449]
**Describe the solution you'd like**
Have log level setting for can use the most suitable in each envs.
**What is the added value?**
Log level setting is a basic setting in many of others apps

**Give us examples of the outcome**

I checked the documentations, but I can not see anything related to global configuration o log level config.

**Comment by EnriqueHormilla** [comment]
I saw here https://github.com/external-secrets/external-secrets/issues/462 Can i use `logLevel: "error"` in helm values ? it´s supported?
I try to find info in the documentation, but i don't see anything there.

**Comment by gusfcarvalho** [comment]
Hi @EnriqueHormilla ! you can set them using `extraArgs`:
```
extraArgs:
  log-level: debug
```
