### ISSUE TITLE
Synced secret gets deleted if deploying with argocd

### ISSUE THREAD

**Issue by martijnvdp** [external-secrets/external-secrets#1452]
Weird issue maybe i should post it in the argocd github, but maybe anyone else experienced the same.

If i deploy an external secret using argocd without specifying a target name , the sync works but the secret gets deleted.
If i create the same external secret manually it works fine and the secret doesnt get deleted and has the name of the external secret

**Comment by moolen** [comment]
Hey @martijnvdp!
I believe this is a uplicate of https://github.com/external-secrets/external-secrets/issues/1233. This has been fixed ~5d ago, the fix will be in the next release.

**Comment by martijnvdp** [comment]
> Hey @martijnvdp! I believe this is a uplicate of #1233. This has been fixed ~5d ago, the fix will be in the next release.

Cool thanks a lot
