### ISSUE TITLE
Question: SecretStore configuration with CRDs

### ISSUE THREAD

**Issue by hryamzik** [external-secrets/external-secrets#1458]
Looks like deprecated external-secrets helm chart had an ability to be fully configured with helm settings.

With this version I had to manually add `SecretStore` pointing to aws ssm. Is there any setting I miss to get it configured by CRDs or is this by design?

**Comment by gusfcarvalho** [comment]
Hi @hryamzik ! This is by design. This allows you to not give “god mode” permissions to external-secrets operator 🙂
