### ISSUE TITLE
errors with external-secrets operator

### ISSUE THREAD

**Issue by marcus1aleksand** [external-secrets/external-secrets#1475]
### Discussed in https://github.com/external-secrets/external-secrets/discussions/1474

<div type='discussions-op-text'>

<sup>Originally posted by **marcus1aleksand** August 17, 2022</sup>
I deployed the secrets-operator helm-chart to a new cluster and I am seeing the following error:

"Failed to get API Group-Resources"

Also I noticed that the webhook opaque secret is empty. Would anybody have an idea on what t could be causing that?</div>

**Comment by gusfcarvalho** [comment]
hi @marcus1aleksand ! We would need more information on how you're trying to install it. This message normally relates to CRDs not installed.

**Comment by marcus1aleksand** [comment]
Thanks for getting back to me, Gustavo. I checked for that, the CRDs are installed. I noticed that during the init process, there's an API call to the kubernetes service 10.0.0.1/api and that is failing. I wonder if there's something wrong with this new cluster.

**Comment by marcus1aleksand** [comment]
The issue may be closed. The problem was created because of missing firewall rules.
