### ISSUE TITLE
Support for AWS STS AssumeRole with External ID

### ISSUE THREAD

**Issue by piyat** [external-secrets/external-secrets#1478]
**Describe the solution you'd like**
The ClusterSecretStore API allows setting IAM role to be assumed by the external secrets controller when fetching secrets from AWS secrets manager.

When we configure cross-account secret retrieval, we do so by allowing any IAM identities in the local account (where ESO runs) to assume a role in the remote account (where the secrets are) by setting "trusted entities" on the IAM role and passing the account ID(s) where ESO will run. We also restrict access on the secret to the role (via a resource-based policy).

This leaves a gap, where other entities (not just ESO) can access the secrets if they're calling from a trusted AWS account. We can augment this security by configuring an ExternalID in the role's trust settings, and including it in the request made by ESO, but I do not see that this is supported at the moment. This may lead to a situation where, by default, credentials created for ESO to use can be used by other entities.

**What is the added value?**
Enhances security.

**Give us examples of the outcome**

`  provider:

    # (1): AWS Secrets Manager
    # aws configures this store to sync secrets using AWS Secret Manager provider
    aws:
      service: SecretsManager
      # Optional. If set, will be used when assuming IAM role
      externalID: verys3cure
      # Role is a Role ARN which the SecretManager provider will assume
      role: iam-role
      # AWS Region to be used for the provider
      region: eu-west-2
      # Auth defines the information necessary to authenticate against AWS
      auth:
...
`

If this proposal is accepted, we would be able to replicate the below call in the secret store

```aws sts assume-role --role-arn ROLE_ARN --role-session-name FOO --external-id verys3cure```

**Comment by moolen** [comment]
I don't mind adding an external-id to the CRD spec. 

> This leaves a gap, where other entities (not just ESO) can access the secrets if they're calling from a trusted AWS account.

I don't know anything about your set up, but using IRSA allows you to scope permissions to a single service account within a cluster. This is way safer than trusting a whole AWS account + using `external-id` to scope access (if i understand you correctly). There shouldn't be a need to scope access using `external-id`, as this is just an arbitrary string that an attacker needs to know.

**Comment by piyat** [comment]
Hi @moolen thanks for reviewing this.

You're right, but I (and I don't think this is unique to me) opted against IRSA, because it required me to setup an OIDC IDP. I don't think it's an unusual setup to do cross-account secrets with AWS ASM (resource based policies granting access to named IAM identities is a common pattern).

My setup is not unusual - I've just added an extra layer of segregation (linking secret stores to credentials with access to specific ASM secrets). So I have store-a with access to team-1 secrets and store-b with access to team-2 secrets.

AFAIK, the way to configure an IAM assume role to trust the caller assuming it is to either do as I've said (say identities in account 123 can assume me) or do that **and** give the caller an external id to pass in the call.

We can do without it, I just wanted to flag it if it might be of interest as it is a feature of IAM trust and we do use IAM roles with ESO.

**Comment by moolen** [comment]
Hey @piyat thanks for sharing context! 
External-secrets shouldn't prescribe how to do certain things like x-account access etc. because everyone uses features in a slightly different way. With that being said i'd be happy to get that into external secrets to support your use-case better!

**Comment by piyat** [comment]
Yeah absolutely - I think it would be neat to have the option (but for it to be totally optional of course!).

Thanks for your feedback!

**Comment by pevers** [comment]
Hi, we are trying to make the switch from https://github.com/external-secrets/kubernetes-external-secrets to this operator. We heavily rely on AWS STS for temporary access tokens and have used that with the deprecated external-secrets package as well to fetch secrets from SecretsManager. This doesn't seem to possible yet with the operator. 

Is there any progress on this issue? Perphaps we can pick it up as well.

**Comment by moolen** [comment]
@pevers do you rely on external-id as well? 
We didn't start with any work in this regard, feel free to take it :heart:. The above mentioned proposal sounds reasonable to me

**Comment by pevers** [comment]
> @pevers do you rely on external-id as well? We didn't start with any work in this regard, feel free to take it ❤️. The above mentioned proposal sounds reasonable to me

Hi @moolen , I see I misread the `AWSProvider` spec. It seems to be supported to let the controller assume a role. We are not using `sts:ExternalId` at the moment so it doesn't seem to affect us. 

Sorry for the confusion!

**Comment by yo-ga** [comment]
This issue may be closed, not staled
