### ISSUE TITLE
AWS Parameter Store JSON number results in "unable to unmarshal secret" when using dataFrom

### ISSUE THREAD

**Issue by Ghettoburger** [external-secrets/external-secrets#1479]
**Issue:**
Same problem as in [issue 510](https://github.com/external-secrets/external-secrets/issues/510), but with parameter store. So when JSON parameter has numerical value without double quotes, it will end up in ESO error.

**Example:**
parameter store secret:
```
{
  "DB_HOST": "myrds.eu-north-1.rds.amazonaws.com",
  "DB_PASSWORD": "verysecret",
  "DB_PORT": 5432,
  "DB_USERNAME": "seppo_hovi"
}
```

dataFrom is being used:
```
  dataFrom:
  - extract:
      key: /path/to/some/secret
```

Ends up in error:
`external-secrets-operator-79b8c57f87-m6s8b external-secrets {"level":"error","ts":1660907739.6617749,"logger":"controllers.ExternalSecret","msg":"could not get secret data from provider","ExternalSecret":"namespace/secret","SecretStore":"/cluster-param-store","error":"unable to unmarshal secret secret: json: cannot unmarshal number into Go value of type string 
--omitted--`

**Observations:**
On a quick glance it looks like `parameterstore.go` is handling this similarly as the `secretsmanager.go` pre [Fix 545](https://github.com/external-secrets/external-secrets/pull/545)

**Comment by Ghettoburger** [comment]
Ahh sorry, forgot to mention that! We are using `0.5.9`
```
    Image:         ghcr.io/external-secrets/external-secrets:v0.5.9
    Image ID:      ghcr.io/external-secrets/external-secrets@sha256:8aacccd4efd705565ad627bd2c300b70e2834b181a9b5b1952eb123419018e2d
```

**Comment by praveenperera** [comment]
Getting the same error in the same situation when using AWS Secrets Manager
