### ISSUE TITLE
Secret Store authentication vault token vulnerability

### ISSUE THREAD

**Issue by laxmansoma22** [external-secrets/external-secrets#1500]
**Describe the solution you'd like**
Describe the end goal of this proposal. What is this new functionality or the new behaviour (or what problem does it fix)? 

We are trying to use the external secret operator to retrieve the secrets from Vault , as part of we creating the secret store and trying to find out the security vulnerability which is the valid authentication model where we don't expose the secret the secret store.

**What is the added value?**
Explain the value that it adds. e.g. "Secret refreshing will make internal secrets up to date with external secrets".
we are looking for a solution to resolve this vulnerability issue

**Give us examples of the outcome**

Provide templates if you are proposing changes in the CRD. Provide example workflows or code snippets if they make sense to present.

**Observations (Constraints, Context, etc):**

Give here all extra information that could be interesting. Such as Golang version and Kubernetes version if you are reporting a bug/problem. You can also foresee technical constrains like "this could only be implementing using this specific technology or approach, because of this and that".

**Comment by laxmansoma22** [comment]
apiVersion: v2
appVersion: v0.5.8
description: External secret management for Kubernetes
home: https://github.com/external-secrets/external-secrets
icon: https://raw.githubusercontent.com/external-secrets/external-secrets/main/assets/eso-logo-large.png
keywords:
- kubernetes-external-secrets
- secrets
kubeVersion: '>= 1.19.0-0'
name: external-secrets
type: application
version: 0.5.8

**Comment by moolen** [comment]
I don't quite understand your request. Do i understand it correctly that you're trying to figure out an authentication method to retrieve secrets from vault? Further, you're concern is mostly around the issue to have a hardcoded secret that provides access to vault?
Did you find the vault provider docs around authentication [here](https://external-secrets.io/v0.5.9/provider-hashicorp-vault/#authentication)?
I'd recommend to take a look at the [Kubernetes native authentication with vault](https://external-secrets.io/v0.5.9/provider-hashicorp-vault/#kubernetes-authentication), that allows you to use service accounts to authenticate with vault and assign vault roles to individual service accounts, thus providing proper tenant isolation.

Please let me know if that answers your question.

**Comment by laxmansoma22** [comment]
``Thanks Moolen , we are trying to use vault token authentication model and our security team raised a concern to see if we can find a way to store that token in a secret repo to use that for authentication.

please find the yaml belo

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: inception-vault-secrets
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "https://vault-nonprod.cvshealth.com"
      path: "kv-v2/app/terraform/digital-dfp-dev/jedi"
      version: "v2"
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
data:
  token: xxxxxxxxxxxxxxxxxxxxx

**Comment by laxmansoma22** [comment]
`please find the yaml belo

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: inception-vault-secrets
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "https://vault-nonprod.cvshealth.com"
      path: "kv-v2/app/terraform/digital-dfp-dev/jedi"
      version: "v2"
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "vault-token"
          key: "token"
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
data:
  token: xxxxxxxxxxxxxxxxxxxxx
`

**Comment by moolen** [comment]
> [...] to see if we can find a way to store that token in a secret repo to use that for authentication.

There is no way of "hiding" that token from Kubernetes. I suggest using Kubernetes service-account based authentication, that way you get around that concern because you don't have a hard-coded long-lived credential that provides access to vault.
