### ISSUE TITLE
Refresh interval override

### ISSUE THREAD

**Issue by eTopchik** [external-secrets/external-secrets#1501]
**Describe the solution you'd like**
Overriding default of `refreshInterval` . Managing a lot of secrets and manually set refresh interval to them kinda takes time , would be good to have something in Values.yaml to override this value by default 

**What is the added value?**
Saves a lot of time 

Is there is a such option ? If not would be grateful if it will be added.

**Comment by afirth** [comment]
It seems that the one hour default is [part of the v1beta1 api](https://github.com/external-secrets/external-secrets/blob/2b5710d8d5f400fa385ee4d0239ff0970fe39568/apis/externalsecrets/v1beta1/externalsecret_types.go#L281)
Would be a great feature

**Comment by moolen** [comment]
My opinion: the problem i see is, that this contradicts the spec.refreshInterval defaults on the CRD level and leaves the user with galse expectations. Also, we would have to maintain this, although there is a solution to it:

I'd suggest users that want this feature to use a policy tool like kyverno to mutate the resources on the fly.

**Comment by SlevinWasAlreadyTaken** [comment]
Happy to check `kyverno`, it looks useful! Thanks for sharing.

Just to double-check:
Are you talking about the [spec.refreshInterval](https://external-secrets.io/v0.8.1/api/externalsecret/) from `ExternalSecret`?

If it is the case, I don't see anything about defaults in the doc so I was not expecting anything on my side, is there a default value for it?

**Comment by afirth** [comment]
https://github.com/external-secrets/external-secrets/blob/main/apis/externalsecrets/v1beta1/externalsecret_types.go#L327-L328 it's set here (kubebuilder is codegen) @SlevinWasAlreadyTaken
