### ISSUE TITLE
GitLab: Support Group-level CI/CD Variables

### ISSUE THREAD

**Issue by ron1** [external-secrets/external-secrets#1510]
**Describe the solution you'd like**
GitLab Provider support for GitLab Group-level CI/CD Variables. Currently, only GitLab Project-level CI/CD Variables are supported.

**What is the added value?**
The ESO GitLab Provider currently supports Project-level CI/CD Variables only. GitLab supports management of Group-level CI/CD Variables in addition to Project-level Variables. The GitLab REST API manages Group Variables and Project Variables independently. However, GitLab itself and GitLab CI allow Projects to "inherit" Group-level CI/CD Variables to enable variable reuse across Projects. Many existing GitLab CI deployments use Group-level Ci/CD Variables for this purpose.

An optimal GitLab Provider enhancement would behave like the GitLab UI and GitLab CI and expose both a project's Project Variables and its "inherited" Group Variables in a single Secret Store. A less ambitious GitLab Provider enhancement would simply introduce support for Group-level CI/CD Variables. In this case, a separate Group Variables Secret Store and a separate Project Variables Secret Store would be required to use both Project Variables and "inherited" Group Variables.

**Comment by SimonyanG** [comment]
Very useful feature

**Comment by domizei385** [comment]
I have addressed with https://github.com/external-secrets/external-secrets/pull/1692
