### ISSUE TITLE
Status inquiry on v0.5.10(?) release for key rewrite bug with Secrets Manager

### ISSUE THREAD

**Issue by grrttedwards** [external-secrets/external-secrets#1511]
https://github.com/external-secrets/external-secrets/issues/1488
https://github.com/external-secrets/external-secrets/issues/1447

It has been addressed and merged, is there any possible ETA on v0.5.10? I consume ESO via the helm chart.

It's blocking my work integrating some standard key rewrites in an internal helm chart of my own.

Thank you!

**Comment by moolen** [comment]
Hey! Sorry to hear that youre blocked :(
We want to do a release soon, tomorrow would be suboptimal due to a DNS migration. I believe Monday should work.

CC @gusfcarvalho

**Comment by moolen** [comment]
I want to get #1525 in before i do a release.
@gusfcarvalho is the DNS migration done?

**Comment by moolen** [comment]
DNS migration is still ongoing;

**Comment by grrttedwards** [comment]
What is the "DNS migration"? Out of curiosity. Thanks for the quick updates here.

**Comment by moolen** [comment]
Hey, we're moving our domain to the linux foundation, that's part of the CNCF Sandbox onboarding :)

**Comment by moolen** [comment]
DNS Migration is done :heavy_check_mark:, gonna do another round of reviews and prep a release :+1:
