### ISSUE TITLE
Bitwarden provider

### ISSUE THREAD

**Issue by sHaggYcaT** [external-secrets/external-secrets#1515]
Copy of [Bitwarden provider #1309](https://github.com/external-secrets/external-secrets/issues/1309) and [https://github.com/external-secrets/kubernetes-external-secrets/issues/675](https://github.com/external-secrets/kubernetes-external-secrets/issues/675)

It's an opensource and self-hosted security manager. Previous issue were closed because of incompatibility:

>Hi @jdomag ! We can only support providers that have HTTP APIs / GRPC, and it would be better if they had a go sdk as well. Is that the case for Bitwarden?
If not, I'd rather close this issue until it is compatible. We are not going to install a cli to handle communications with a given provider. This was the same approach for 1 password provider - we only started considering it when a go sdk became available.

Actually, bitwarden has HTTP API (a standard/swagger REST API): 
* [link to documentation](https://bitwarden.com/help/public-api/);
*  [link to cloud-based swagger UI](https://bitwarden.com/help/api/)

**Comment by gusfcarvalho** [comment]
hey @sHaggYcaT! Do you have any examples you can reference to which uses this API for getting the sensitive information? AFAIK (and from the documentation link you've just sent), there was no public method to return sensitive information.

**Comment by sHaggYcaT** [comment]
OK. Than, I think, it doesn't work this way

**Comment by FollieHiyuki** [comment]
https://bitwarden.com/help/vault-management-api has API endpoints to manage secret items. Note that they are exposed via [`bw serve` command](https://bitwarden.com/help/cli#serve) (not endpoints of the Bitwarden server) and doesn't have any authentication or encryption mechanism (already handled via `bw serve` middleman) so they shouldn't be served publicly.

This has quite a lot of limitations and security issues but I think it's worth looking into.

**Comment by WoozyMasta** [comment]
https://pkg.go.dev/github.com/cozy/cozy-stack/web/bitwarden

Package bitwarden exposes an API compatible with the Bitwarden Open-Soure apps.
