### ISSUE TITLE
Provide Dockerfile for UBI-based ESO image

### ISSUE THREAD

**Issue by IdanAdar** [external-secrets/external-secrets#1518]
As originally discussed with @moolen in https://github.com/external-secrets/external-secrets/issues/1192
I thought it's time to stop hijacking his Issue. :)

- [x] Provide Dockerfile
- [x] How to build the image?
- [x] How to publish the image?
- [ ] Documentation

**Comment by IdanAdar** [comment]
Initial PR to continue work on: https://github.com/external-secrets/external-secrets/issues/1518

**Comment by moolen** [comment]
Hey! I think we need to move both Dockerfiles to a `build` directory. If complexity in the makefile get's too high or it's too annoying it makes sense to move that out into a bash script.

- we need to build both images in a PR `make docker.build`
- [on master](https://github.com/external-secrets/external-secrets/blob/90027b559c5513cd047918136cbfe53b844cc1f0/.github/workflows/ci.yml#L252) and [on release](https://github.com/external-secrets/external-secrets/blob/main/.github/workflows/release.yml#L118) these are being promoted `make docker.promote` and `make docker.sign`
- note: the [`make docker.release`](https://github.com/external-secrets/external-secrets/blob/main/Makefile#L223-L231) uses a "fat manifest" to build multi-arch images
- the [e2e tests](https://github.com/external-secrets/external-secrets/blob/main/e2e/Makefile#L20) also call `make docker.build`

I think these are all the bits that need to be adapted.

**Comment by IdanAdar** [comment]
Hey @moolen

- I've created a  **build** directory with **distroless** and **ubi** folders, each containing the respective Dockerfiles
- I've then updated the ci.yaml to account for both, but here I'm pretty sure I've made a mess of it :) starting from this line: https://github.com/IdanAdar/external-secrets/blob/da1b3577534f16a04986ffffbead45f8e25ba4ad/.github/workflows/ci.yml#L244
   - Basically, I duplicated the steps and added the path for each of the folders, but honestly not sure at all what to do here.

I also think that the default should continue to be distroless as before, we just want another image built that we could use it to replace the default...

**Comment by moolen** [comment]
> I think that the default should continue to be distroless as before, we just want another image built that we could use it to replace the default...

Agreed!

> How do we give the built images different names

I think we can just use different tags for them. The current tags use distroless by default and the new ubi images can be tagged `{version}-ubi` for instance.

**Comment by IdanAdar** [comment]
Okay. Where should that tagging be done?
@cpanato can you provide review for my changes here?

**Comment by moolen** [comment]
> Where should that tagging be done?

I would first try to bake that into the `Makefile`, if that gets to complex/ugly i'd factor out a shell script that does the heavy lifiting.

**Comment by IdanAdar** [comment]
@moolen We've created a new PR addressing this request in another way. If you could please review. Thanks!

**Comment by IdanAdar** [comment]
Handled in another PR. Closing.
