### ISSUE TITLE
Support for immutable secrets

### ISSUE THREAD

**Issue by gabegorelick** [external-secrets/external-secrets#156]
**Describe the solution you'd like**
Recent versions of Kubernetes support the creation of [immutable secrets](https://kubernetes.io/docs/concepts/configuration/secret/#secret-immutable) via a boolean `immutable` attribute. It would be nice if ESO supported this.

The new-ish `Immutable` field on https://pkg.go.dev/k8s.io/api/core/v1#Secret:
```go
type Secret struct {
	metav1.TypeMeta `json:",inline"`
	// Standard object's metadata.
	// More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
	// +optional
	metav1.ObjectMeta `json:"metadata,omitempty" protobuf:"bytes,1,opt,name=metadata"`

	// Immutable, if set to true, ensures that data stored in the Secret cannot
	// be updated (only object metadata can be modified).
	// If not set to true, the field can be modified at any time.
	// Defaulted to nil.
	// +optional
	Immutable *bool `json:"immutable,omitempty" protobuf:"varint,5,opt,name=immutable"`

	// Data contains the secret data. Each key must consist of alphanumeric
	// characters, '-', '_' or '.'. The serialized form of the secret data is a
	// base64 encoded string, representing the arbitrary (possibly non-string)
	// data value here. Described in https://tools.ietf.org/html/rfc4648#section-4
	// +optional
	Data map[string][]byte `json:"data,omitempty" protobuf:"bytes,2,rep,name=data"`

	// stringData allows specifying non-binary secret data in string form.
	// It is provided as a write-only input field for convenience.
	// All keys and values are merged into the data field on write, overwriting any existing values.
	// The stringData field is never output when reading from the API.
	// +k8s:conversion-gen=false
	// +optional
	StringData map[string]string `json:"stringData,omitempty" protobuf:"bytes,4,rep,name=stringData"`

	// Used to facilitate programmatic handling of secret data.
	// +optional
	Type SecretType `json:"type,omitempty" protobuf:"bytes,3,opt,name=type,casttype=SecretType"`
}
```

It's not present on `ExternalSecretTemplate`, even though it seems like that type is designed to mirror `corev1.Secret`:
https://github.com/external-secrets/external-secrets/blob/5d7f2a5249bf08bd5e400047a69e4fa80a9f7ccc/apis/externalsecrets/v1alpha1/externalsecret_types.go#L56-L67

**What is the added value?**

From https://kubernetes.io/docs/concepts/configuration/secret/#secret-immutable:

- _protects you from accidental (or unwanted) updates that could cause applications outages_
- _improves performance of your cluster by significantly reducing load on kube-apiserver, by closing watches for secrets marked as immutable._

**Give us examples of the outcome**

Add `immutable` to `ExternalSecretTemplate`:

```yaml
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: example
spec:
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: secret-to-be-created
    creationPolicy: Owner
    template:
      immutable: true
  data:
  - secretKey: firstname
    remoteRef:
      key: my-json-secret
      property: name.first
```

I'm not sure how this should interact with refreshing. The simplest approach would be to attempt to refresh immutable secrets as normal according to their `refreshInterval` and then fail when K8s inevitably rejects the update (if there ever is one). You could also maybe reject the creation of any `ExternalSecret` with `immutable: true` and non-0 `refreshInterval`, but I think there may be a legitimate use case for refreshing to still run so that there's some indication that your K8s secret has diverged from what's in the upstream provider (you'll presumably see an ESO error and can then figure out what to do). Otherwise, you could instead change the default `refreshInterval` to be 0 if `immutable` is true.

**Observations (Constraints, Context, etc):**

I currently use KES and am looking at migrating to ESO. I haven't spun up ESO to actually test how it behaves when you specify `immutable: true`, but my reading of the code indicates it probably doesn't work.

KES currently supports this, although it's not documented AFAIK. It only works because KES more or less uses the specified template verbatim when constructing the Secret (one benefit of it being written in JS I suppose).

**Comment by mouhsen-ibrahim** [comment]
I would like to work on this issue, however, I cannot find docs for writing tests, where can I find the documentation for tests?

**Comment by ArthurPaivaT** [comment]
I have spoken to @knelasevero and we saw that this PR needs some changes, I can work on it.
