### ISSUE TITLE
enable-secrets-caching is not documented

### ISSUE THREAD

**Issue by bobbywatson3** [external-secrets/external-secrets#1588]
**Describe the solution you'd like**
`enable-secrets-caching` is a valid `extraArg`, but it's not documented. It would be great if it were. 

**What is the added value?**
I don't have to bother devs on slack to ask how to enable this.

**Give us examples of the outcome**
external-secrets devs get to enjoy their day without hearing slack noises.

**Comment by moolen** [comment]
I've restructured the docs in #1539 (to be merged) and added a section for CLI args here: https://github.com/external-secrets/external-secrets/pull/1539/files#diff-f7b862349bfea07473d1d9f4904410fc6f36309d1d26704fcaa59c347f250430

So it will be there soon :tm:
