### ISSUE TITLE
Setting metrics.service.enabled to 'true' doesn't expose metrics with 'externalsecret' prefix

### ISSUE THREAD

**Issue by Helinanu** [external-secrets/external-secrets#1653]
Hi,

I've tried with `v0.5.9` and `v0.6.0`  to set the `metrics.service.enabled` helm flag to true and it does create the `external-secrets-operator-metrics` service.

 I can scrape and curl the metrics inherited from Kubebuilder from there, but the custom metrics like `externalsecret_sync_calls_error`, `externalsecret_sync_calls_total`, `externalsecret_status_condition` are still missing?

**Comment by moolen** [comment]
did you create external secret resources, does the controller show log activity (i.e. reconciles the external secrets)? The controller needs to be running in order to create these metrics.

**Comment by Helinanu** [comment]
Ah it must have been lack of activity, I created a new secret store and secrets with much lower refresh interval and it works. Thanks and sorry!
