### ISSUE TITLE
Figure out our coverage enforcement

### ISSUE THREAD

**Issue by knelasevero** [external-secrets/external-secrets#168]
It is marking all our PRs as red... We have some options I think:

1- Remove codecov. We can still enforce and ask people to write tests with code review. Codecov also had data breach recently and this made some people jump off of it. Not sure though.

2- We find a way to configure Codecov to let coverage decrease if it is just a bit. I had a quick look and did not find a way, but did not look deep into it.

3- We change tools, and go for coveralls or any other one

**Comment by knelasevero** [comment]
Not sure why I closed this one. @serdarkalayci can you take care of this one?

**Comment by serdarkalayci** [comment]
Hello,
To enable code coverage data on SonarCloud, these steps must be taken:
On the SonarCloud:
Administration -> Analysis method
Disable the Automatic Analysis
![image](https://user-images.githubusercontent.com/14258482/134012761-536bea80-2132-4419-b87e-e29ab51e1f25.png)
Then by clicking Follow the tutorial under GitHub actions, the secret must be created on GitHub to give access to SonarCloud.
I also created a PR containing the sonar-project.properties file and made a change on ci.yaml to disable CodeCov and enable Sonar analysis. If everything goes as expected, we'll close this issue.
