### ISSUE TITLE
Updating, reverting and updating to 0.6 again renders external-secrets unusable

### ISSUE THREAD

**Issue by PauloGDPeixoto** [external-secrets/external-secrets#1694]
I'm doing some testing for upgrade scenarios in kubernetes clusters, and I need to go back and forth between 0.5.x and 0.6.1.
The first time I upgrade, everything works as expected. Afterwards, I revert to 0.5.x, and it still works as expected.
But once I go back to 0.6.1 once again, I get the following error when doing any operation related to external secrets:
```
Error from server: conversion webhook for external-secrets.io/v1alpha1, Kind=ClusterSecretStore failed: Post "https://external-secrets-webhook.external-secrets.svc:443/convert?timeout=30s": Address is not allowed
```
This example is for a `kubectl get ClusterSecretStore`, but an equivalent error appears when I do a `kubectl get externalsecrets`, for example.
Changing the port does not help.

In order to downgrade, I manually delete the CRDs, I'm using ArgoCD, I can see that after deleting these, everything syncs perfectly.

Any idea on what is happening and how can I revert this?

**Comment by gusfcarvalho** [comment]
What kubernetes cluster are you using? EKS with multiple CIDR? 😁

**Comment by PauloGDPeixoto** [comment]
EKS and AKS, both with one single CIDR.

**Comment by gusfcarvalho** [comment]
With EKS, there is one apodrecer setting related to what ip addresses range the api server is allowed to communicate with. My guess is that on each new deployment the webhook pod moves nodes until it gets on a node the api server cannot reach. You can check that by simply deleting the webhook pod and letting it recreate( here is a bit more about it https://kubernetes.slack.com/archives/C017BF84G2Y/p1666814278251399 for more info)

No idea what could be causing that on AKS

**Comment by PauloGDPeixoto** [comment]
I deleted the webhook pod in an EKS cluster and I still get the same error. This seems to be something that is not being correctly cleaned up.
When I revert to 0.5.x, I have to edit the CRDs `clustersecretstores.external-secrets.io` and `externalsecrets.external-secrets.io` and remove the finalizer, otherwise, they get stuck deleting, maybe it's something there that is not being deleted.

**Comment by PauloGDPeixoto** [comment]
I'm sorry, in fact this issue was EKS only. I was able to work around it by enabling the host network on the webhook deployment. I also had to change the port, which is not present in the values file, I figured it out by examining the webhook template.
Thanks for your help!
