### ISSUE TITLE
Skip parameter when is not available in aws ssm

### ISSUE THREAD

**Issue by MoonChel** [external-secrets/external-secrets#1698]
**Describe the solution you'd like**
I just want to confirm if this is expected behaviour: skip creating secret for keys that doesn't exists on secret provider

https://github.com/external-secrets/external-secrets/blob/36b3115787fa97521fc080c46d1219f34374f29c/pkg/controllers/externalsecret/externalsecret_controller_secret.go#L68

**What is the added value?**
If yes, we can update the docs

**Give us examples of the outcome**

Imagine templated external secret, where keys are template like: /apps/{service_name}/key1
It is really useful, that we can add secrets for non existing keys.

**Comment by gusfcarvalho** [comment]
Hi @MoonChel . This is only true if DeletionPolicy=Delete, which is not a default. The reason is if we are intending to delete the secret when it not exists, this operation is not an error.
