### ISSUE TITLE
Add support for Delinea Secret Server and DevOps Secrets Vault

### ISSUE THREAD

**Issue by martinborgman** [external-secrets/external-secrets#1709]
**Describe the solution you'd like**
I would like to see support for Delinea Secret Server and DevOps Secrets Vault

**What is the added value?**
Delinea is one of the top PAM solution providers in the market and since we use Delinea Secret Server I was missing support for it.

**Give us examples of the outcome**

That we can use Delinea Secret Server as a external secrets provider.

**Observations (Constraints, Context, etc):**

I'll point a Delinea developer to this issue to help add support for Delinea Secret Server and DevOps Secrets Vault.

**Comment by Fredouye** [comment]
Hi

I second that.

We're using Delinea Secret Server, which can be synchronized with Delinea DevOps Secrets Vault. It would be awesome if ESO could support it :)

I don't know about Delinea DevOps Secrets Vault, but Delinea Secret Server provides an API which allows to retrieve / write secrets.

**Comment by michaelsauter** [comment]
I'll take a stab at adding support for DevOps Secrets Vault.

I'm going to use https://github.com/DelineaXPM/dsv-sdk-go as it is the official SDK. It only supports a tiny subset of the API though, so only very basic read will work. Maybe Delinea can extend the SDK to cover more (e.g. reading a specific version).
