### ISSUE TITLE
externalsecret_sync_calls_error greater than externalsecret_sync_calls_total

### ISSUE THREAD

**Issue by pcperera** [external-secrets/external-secrets#1722]
**Issue**
In ESO metrics, we observe **externalsecret_sync_calls_error** > **externalsecret_sync_calls_total**. I expected total to represent the summation of both successful and error sync calls.

`externalsecret_sync_calls_total = externalsecret_sync_calls_error + successful syncs`

It however runs out that **externalsecret_sync_calls_error** is greater than the **externalsecret_sync_calls_total**.

![image](https://user-images.githubusercontent.com/15628990/202115144-05d29c7d-8aa9-4eff-bf9e-d6107e64171a.png)

**Observations**

![image](https://user-images.githubusercontent.com/15628990/202114772-3f2b9cd8-1122-4dcd-a6e3-0cde2e2b18bf.png)

**Questions**

- What exactly is represented by **externalsecret_sync_calls_total** ?

**Comment by moolen** [comment]
Hey, this is a bug the metrics don't get recorded correctly.
