### ISSUE TITLE
Webhook failing (in a new cluster) during kubectl apply

### ISSUE THREAD

**Issue by guisesterheim** [external-secrets/external-secrets#1739]
**Solution expected**
I have ExternalSecrets working nicely in our main cluster. It just won't work in the new cluster. Both have kubernetes 1.21 running. The solution I'd like is to understand what is happening on the data flow and get this new installation of external-secrets working in the new cluster as well.

**What is the added value?**
Get ExternalSecrets easier to install and work in different scenarios

**Additional information:**
I have ExternalSecrets working in one of the clusters we operate. When trying to use it in the second cluster, it just won't work. Both clusters don't have internet connection access.

The validating webhook is preventing me to apply my ClusterSecretStore and ExternalSecret (I'm attaching both of them).
![error aplying kube files](https://user-images.githubusercontent.com/7569966/203082974-1e9bd600-e3cd-478e-a815-615429337e33.png)

Here are the ClusterSecretStore and ExternalSecret:
<img width="359" alt="ClusterSecretStore and ExternalSecret" src="https://user-images.githubusercontent.com/7569966/203081553-03abb764-55c0-4166-8d13-dd40e51b6d4b.png">

I did try to spin up a new pod to try to curl the service from within the cluster. It wasn't much helpful since it says I'm getting a 503 (omitted proxy configs):
![curl](https://user-images.githubusercontent.com/7569966/203083811-0b9ba46e-f07c-4ee2-b753-24724ce5f56a.png)
![curl output](https://user-images.githubusercontent.com/7569966/203083815-171cce61-3deb-4770-810e-ad3969d02a65.png)

While trying to troubleshoot I did realize that the logs are showing something is wrong... but I don't have enough information to tell what that is. I don't see those errors on the original installation. They are present at the beginning of the logs, and then are gone. Still after that, I still can't apply my ClusterSecretStore and ExternalSecret.

**Webhook pod logs:**
![webhook pod logs](https://user-images.githubusercontent.com/7569966/203081074-38e3708d-7ee9-4739-a1af-b5aa7eeef9d4.png)

**Cert Controller logs**
![cert controller logs 1](https://user-images.githubusercontent.com/7569966/203081232-583501f8-ab9e-45e2-bbe2-8d76aac3e897.png)
![cert controller logs 2](https://user-images.githubusercontent.com/7569966/203081241-cb152d15-3245-4d77-bba4-f272e4e2b595.png)

**External Secrets pod logs**
![external secrets logs](https://user-images.githubusercontent.com/7569966/203081244-fec51fc2-6685-4935-9cd8-b13de768bbf1.png)

Your help is very much appreciated. Thanks in advance.

**Comment by vini-gorillas** [comment]
i ahve the same error as well. I was able to deploy it on the GKE cluster but not on EKS cluster, I am using the same helm chart on both clusters. kuberenetes version: `v1.21.14-eks-fb459a0` 

ESO version: `v0.6.1` 

I am getting the following error when trying to create the ClusterSecretStore

> Error: UPGRADE FAILED: failed to create resource: Internal error occurred: failed calling webhook "validate.clustersecretstore.external-secrets.io": Post "https://external-secretservice-webhook.external-secrets.svc:443/validate-external-secrets-io-v1beta1-clustersecretstore?timeout=5s": Address is not allowed

**Comment by guisesterheim** [comment]
Hi Gustavo! Thanks for reaching out.

ESO version is 0.5.9

Here are the rolebindings I have:
![Screenshot 2022-11-22 at 9 05 20 AM](https://user-images.githubusercontent.com/7569966/203336117-43ddd6ac-dca4-4508-a1a9-909101f10466.png)

About the installation: I run the helm installation with "dry-run", copied all the generated content and stored it into a file. Modified just the images address and installed on the cluster. I pulled the images and stored them on my local ECR.

Generated installation file is here:
[install.yaml.zip](https://github.com/external-secrets/external-secrets/files/10068175/install.yaml.zip)

Thank in for your support.

**Comment by gusfcarvalho** [comment]
Can you check with `kubectl get secrets -n external-secrets external-secrets-webhook` contains the data for the certificate generated by the cert-controller?

**Comment by guisesterheim** [comment]
Hi Gustavo! Thanks for reaching out to this. The project I'm involved with decided to step back on the solution and adopted another one. I won't be driving these tests anymore. Thanks for the support!
