### ISSUE TITLE
chart crds not ready and `--wait` does nothing because crds are deployed as regular resources

### ISSUE THREAD

**Issue by Morriz** [external-secrets/external-secrets#1759]
**Describe the solution you'd like**
Please make the chart follow helm v3 best practices and deploy resources in the `/crds/` folder (not `/templates/crds/`)? Then we can rely on `--wait` to validate wether the CRDs are ready. 

Without this we can't do a stateless deployment of crds and crs in one go, and have to make stateful logic/scripts that wait. Not nice. Or am I missing something?

**What is the added value?**

- Users can happily deploy the chart and belonging crs in one idempotent run.
- No more dynamic crds (imo those should be avoided), so we can validate templates accordingly during static analysis.

**Comment by gusfcarvalho** [comment]
Hi @Morriz. Unfortunately we cannot follow your suggestion, as we have decided to allow our components to be optional. Some of these components change the configuration of CRDs, meaning we need to template them.

**Comment by Morriz** [comment]
Ok.But it seems like a breach with k8s best practice tho, which theoretically could be solved by splitting up these dynamic crds into multiple static crds that cover the domain. I hope to learn as to why this approach was chosen. Do you know of a link to a doc/group/discussion?

**Comment by Morriz** [comment]
But to fix the problem introduced by this approach, you could add a helm post job that waits for the crds to become ready. Something like:
```bash
#!/usr/bin/env bash
set -e
while ! kubectl get crd | grep "externalsecrets"; do
  echo "Waiting until external-secrets CRDs are accessible"
  sleep 5
done
echo READY!
```
No?

**Comment by gusfcarvalho** [comment]
> But to fix the problem introduced by this approach, you could add a helm post job that waits for the crds to become ready. Something like:
> 
> ```shell
> #!/usr/bin/env bash
> set -e
> while ! kubectl get crd | grep "externalsecrets"; do
>   echo "Waiting until external-secrets CRDs are accessible"
>   sleep 5
> done
> echo READY!
> ```
> 
> (And make the logic conditional and precise of course.)
> 
> No?

This is not my domain of expertise, so if you can think of a contribution for it, I’d be happy to review it! 😁

generally speaking, the feature is that we allow multiple external secrets controllers with controllerClass, but in this scenario we can only have one webhook against multiple external secrets controllers

this extends to use cases where users simply cannot have a webhook installed, so we need to control when CRDs are installed and specific ConversionWebhook fields.

**Comment by moolen** [comment]
Cert-manager solved the problem with a "startupapi-check" that works as described:
 https://cert-manager.io/docs/release-notes/release-notes-1.5/#helm-chart

**Comment by Morriz** [comment]
It is actually not a problem if we split the charts in two, which is what we had to do for cert-manager as well. (They also think it is needed to have dynamic crds.)

Why can't crds be seen as a versioned api? So they can stay static? I still think it is a design flaw to go against this.

**Comment by gusfcarvalho** [comment]
because the feature that we introduced is exactly the conversion Webhook, meaning if we create versioned APIs that have conversion webhooks enabled/disabled, would completely defeat the purpose. This is simply how kubernetes works, and this design flaw goes back to the fact that conversion webhooks don't have a proper APIVersion/Kind, but are rather configured at CRD level.

**Comment by curtispd** [comment]
I do think this is a valid concern and would like to see a solution for it. Anyone who deploys the operator to a new cluster and then tries to use it right away in the script will encounter errors and have to work around this problem, as I have.

**Comment by gusfcarvalho** [comment]
Of course! Any PRs implementing something in the lines of https://github.com/external-secrets/external-secrets/issues/1759#issuecomment-1330240055 would be welcome! @curtispd would you like to take a shot, since it is affecting you?
