### ISSUE TITLE
Promote ESO as a certified operator on Red Hat Operator Hub

### ISSUE THREAD

**Issue by evolve75** [external-secrets/external-secrets#1762]
**Describe the solution you'd like**

ESO is already on the Red Hat community operator hub (<https://operatorhub.io>) since 2021, per #536. Can it be promoted to the [certified operator category](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.2/html/operators/olm-understanding-operatorhub)?

**What is the added value?**

Installation and acceptance of the operator will increase in enterprise deployment scenarios, with the certified tag.

**Observations (Constraints, Context, etc):**

`ESO` is a very useful operator to have for deployment into public cloud infrastructure for OpenShift and other k8s installations. Having the operator available in the "certified operator hub" provides an additional level of trust and acceptance for enterprise installations, who might otherwise be hesitant to deploy this from the community hub.

**Comment by gusfcarvalho** [comment]
I would personally love this as well 😄 no idea how can we achieve it.

**Comment by tabnul** [comment]
We are considering openshift / rosa and it could help us as well.

Secret management obviously is a topic which gets special attention within organizations.
The certified status surely will make discussions with the organization easier when adopting this product.

**Comment by moolen** [comment]
@knelasevero can you find out what prerequisites need to be met in order to be eligible for certification?

**Comment by knelasevero** [comment]
Will do, sorry, missed this one before

**Comment by evolve75** [comment]
@knelasevero , let me know if you need any assistance from the Red Hat side.

**Comment by knelasevero** [comment]
@evolve75 I also work at Red Hat! :)

I created the partner account, but couldn't find time to continue persuing this further.

In any case, would you please send me a internal slack message so we can push this forward?

**Comment by evolve75** [comment]
@knelasevero , will do.
