### ISSUE TITLE
You silently change refreshInterval "15h" to "15h0m0s" without an error message

### ISSUE THREAD

**Issue by tebaly** [external-secrets/external-secrets#1775]
**Describe the solution you'd like**
ArgoCD issue

**What is the added value?**
**refreshInterval**: "15h" incorrect -> always OutOfSync kind ExternalSecret 

**Give us examples of the outcome**
You silently change "15h" to "15h0m0s" without an error message

**Observations (Constraints, Context, etc):**

ArgoCD inherently keeps the resource unchanged and changes back "15h0m0s" to "15h". The process loops endlessly
* You must not change or correct anything - you must report an error in the value _refreshInterval_
* Or you should interpret "15h" as correct, and substitute "15h0m0s" it inside the processing behind the scenes

**Comment by gusfcarvalho** [comment]
Hi @tebaly ! This is because you are using `v1alpha1` APIVersion. To fix it, you can either upgrade to `v1beta1` or be verbose in your definition of refreshInterval.

**Comment by tebaly** [comment]
https://www.digitalocean.com/community/tutorials/how-to-access-vault-secrets-inside-of-kubernetes-using-external-secrets-operator-eso

```
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore

apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
```

Someone might go the same way :)
