### ISSUE TITLE
ExternalSecret TemplateFrom ConfigMap does not exist in CRD

### ISSUE THREAD

**Issue by atsai1220** [external-secrets/external-secrets#179]
**Describe the solution you'd like**
Using `templateFrom` would be a great use-case for alertmanager since we wouldn't need to fight against Go templating and delimiting in the secret string.

**What is the added value?**
We can manage receivers and routes with git by using ExternalSecrets for multiple clusters.

**Observations (Constraints, Context, etc):**
The CRD does not have information related to `templateFrom` as described in documentation.
https://github.com/external-secrets/external-secrets/blob/main/deploy/crds/external-secrets.io_externalsecrets.yaml

Here is the snippet in the documentation.
https://github.com/external-secrets/external-secrets/blob/6f69264240b398ce195428ae2ab24aa7289ec1af/docs/snippets/full-external-secret.yaml#L59-L63

**Comment by moolen** [comment]
> we wouldn't need to fight against Go templating

I feel you :sweat_smile: 

The `templateFrom` field is not yet implemented. The idea is to have a ConfigMap that stores the template instead of having to define the template in-line. Multiple ConfigMaps can be specified, the fields are merged in-order (last item may override first item).

**Comment by atsai1220** [comment]
> > we wouldn't need to fight against Go templating
> 
> I feel you 😅
> 
> The `templateFrom` field is not yet implemented. The idea is to have a ConfigMap that stores the template instead of having to define the template in-line. Multiple ConfigMaps can be specified, the fields are merged in-order (last item may override first item).

@moolen Thank you for making this PR (https://github.com/external-secrets/external-secrets/pull/222)! I tried installing v0.2.1 and v0.2.0 and the CRDs in the packages does not seem updated with the new fields. Manually applying the CRD from the main branch worked though. 

Is this something I can help package?

Package links from the Helm chart.
https://github.com/external-secrets/external-secrets/releases/download/helm-chart-0.2.1/external-secrets-0.2.1.tgz
https://github.com/external-secrets/external-secrets/releases/download/helm-chart-0.2.0/external-secrets-0.2.0.tgz

**Comment by atsai1220** [comment]
I build my own image and seems like the service account used needs additional privileges.

```
E0706 20:11:04.134044       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.2/tools/cache/reflector.go:167: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:vault-infra:external-secrets-kubernetes-external-secrets" cannot list resource "configmaps" in API group "" at the cluster scope
```

**Comment by moolen** [comment]
Hey @atsai1220 the `templateFrom` feature was not released yet, it will come into the next release - with your fix :wink:. Thanks for your PR :+1:
