### ISSUE TITLE
PushSecret - Option to set the Provider rotation settings

### ISSUE THREAD

**Issue by tabnul** [external-secrets/external-secrets#1822]
**Describe the solution you'd like**
We would like to be able to set the rotation settings of a Secret for the External Secrets Provider (AWS SEcrets Manager in our case).
It could also be valuable to be able to include the resource policy attached to the secret. This would make sharing the created secret with other services easier.

**What is the added value?**
This would enable us (and our auditors) to use a single point of thruth when checking for rotation settings of all secrets used AWS-wide. 
Also, this would reduce the overhead needed to actually cycle these secrets (logic in AWS used instead of the operator via the generators)

**Comment by tabnul** [comment]
might conflict with https://github.com/external-secrets/external-secrets/issues/1816

**Comment by gusfcarvalho** [comment]
Hi @tabnul ! I’m not sure that makes sense to our project! Every secret rotation is defined via the `refreshInterval`, meaning that the idea is a refresh with every reconcile loop, and not create one-off secrets and allow the provider to rotate it afterwards (as this would mean that any change to the kubernetes secret would stop to be reflected on your secret provider).

I’m starting to feel that your use case is not really about pushing secrets to AWS, but rather generating them there. Is that correct?

**Comment by tabnul** [comment]
> Hi @tabnul ! I’m not sure that makes sense to our project! Every secret rotation is defined via the `refreshInterval`, meaning that the idea is a refresh with every reconcile loop, and not create one-off secrets and allow the provider to rotate it afterwards (as this would mean that any change to the kubernetes secret would stop to be reflected on your secret provider).
> 
> I’m starting to feel that your use case is not really about pushing secrets to AWS, but rather generating them there. Is that correct?

Thanks for the quick reply.
I think that you are right with your last question. Outsourcing the rotation logic to AWS Secrets (or other providers) implicitly means that AWS will be in control of the Secret content and therefore the secret content shouldn't be pushed from K8S to begin with. 

I don't know if the API even supports this use case (it would require the option to force the autogeneration logic at least initially).
I also don't know if this fits in the philosophy of external-secrets-operator.


From auting perspective there are alternatives to check for the creationdate of secrets and therefore you could see when things were changed. But still, checking for a global policy would not be possible. This is a problem we with more AWS resources created from within Kubernetes.
