### ISSUE TITLE
Multiple operators per cluster

### ISSUE THREAD

**Issue by tabnul** [external-secrets/external-secrets#1833]
**Describe the solution you'd like**
We are testing a scenario where we use multiple operators in a single Kubernetes cluster.
We use the helm chart for deployment. The documentation states the project looks for testers, here i am ;)

**What is the added value?**
Multiple operators with seperate scoped namespaces helps reducing permissions in a multi-tenant situation to the absolute minimum.

**Give us examples of the outcome**
There are 2 conflicts;
- naming of CRDs is generic. 
We fixed this by just deploying the CRDS in one deployment, turning them off in the second. Next step would be seperating the CRD deployment from the operator deployment.
Ideally the name of the CRD's get the instance's name in it. This makes upgrading individual instances easier (no backwards compatibility needed, you can run 2 versions next to each other)

- the validation webhook names are generic.
We are unable to solve this. Both the helm templates should become dynamic (adding the instance's name as an example).
Given the webhooks are namespaced, i assume you need one per operator instance.

I am talking about; 
  - ValidatingWebhookConfiguration/externalsecret-validate 
  - ValidatingWebhookConfiguration/secretstore-validate

**Comment by gusfcarvalho** [comment]
Hi @tabnul ! Have you tried deploying your extra eso deployments with the flags `—installCRDs=false` and `webhook.create=false`?

the logic is that webhook configuration and CRDs should be installed once, while you have multiple eso operators deployed.

**Comment by tabnul** [comment]
> Hi @tabnul ! Have you tried deploying your extra eso deployments with the flags `—installCRDs=false` and `webhook.create=false`?
> 
> the logic is that webhook configuration and CRDs should be installed once, while you have multiple eso operators deployed.

Ok, thanks. I did deploy it using installCRDs=false in the second instance. 
I did not try it for the webhooks, because i was not sure whether this would even be possible, given the fact they are namespaced.

**Comment by gusfcarvalho** [comment]
Webhooks are not bound to the operator, but to a set of CRDs. It is not our intention with the multiple operator setup to spin up multiple CRDs, but rather to work with the existing CRDs in multiple setups.

So this is why the Webhooks are only one. They are not bound to an operator specifically.

**Comment by tabnul** [comment]
> Webhooks are not bound to the operator, but to a set of CRDs. It is not our intention with the multiple operator setup to spin up multiple CRDs, but rather to work with the existing CRDs in multiple setups.
> 
> So this is why the Webhooks are only one. They are not bound to an operator specifically.

Thanks. My intentions is to completely isolate workloads (in a multi tenant cluster)
It would make upgrades easier as well (being able to upgrade on a per-namespace/team basis instead of the entire cluster (i assume a situation where backwards compatibility is not in effect)

What is the philosophy/use-case behind supporting multiple operators in a cluster?

**Comment by gusfcarvalho** [comment]
> What is the philosophy/use-case behind supporting multiple operators in a cluster?

The philosophy/use-case is where you want to ensure that a given team/namespace has its own operator to handle their workloads, and increase the isolation level. This is really related to a security requirement rather than an operational one (i.e. this feature was developed taking into account that operators would be upgraded roughly at the same time, and not be running in different versions according to the tenants' wishes. If your concerns here are upgrades, this feature won't help you out (we do not make promises that our APIs will work smoothly without upgrading the CRDs, which may cause issues with the operators that you did not deploy.)

Having said that, if your concern is security-wise, this is the right feature for you, and  there are several ways that you can isolate multiple operator instances: you can set a `scopedNamespace`, you can configure a `controllerClass` (you can do both of them), and you can use namespace-bound ClusterSecretStores as well. Just remember that we recommend you to have all of your operators up to date with the CRD deployment (i.e. if CRD is version `0.7.1`, so should your operators)

**Comment by gusfcarvalho** [comment]
Also, it could be a nice feature to support the installation of multiple operators out of the box 😄 this would surely help out a lot of users struggling here. (PRs are welcome!)

**Comment by tabnul** [comment]
> Also, it could be a nice feature to support the installation of multiple operators out of the box 😄 this would surely help out a lot of users struggling here. (PRs are welcome!)

From the helm chart perspective, i think it already works by deploying the CRDS and Webhook only once. Lets call it the 'core' deployment. I will give it a shot next week and report back.
Ill do a PR on the docs if i succeed.

**Comment by tgjonestx** [comment]
Hi - is there any update on this (doc or procedure wise)?

I'm interested in much the same use-case. I'm willing to try it out in our test environment, but hoping to save myself some time if someone else has blazed a trail already.

In our case, cluster operators will manage the CRDs and keep multiple instances of the ES operator in-sync in terms of versions deployed, while at the same time allowing application owners (i.e. tenants) to have fine-grained access control over their secret store. In our case, that would be GCP Secrets Manager where each tenant has their own GCP SM in their own GCP Project. They could then grant other ES operator instances access to their GCP SM via the GCP IAM roles granted to the GCP Service Account that backs each tenant's Kubernetes Service Account via Workload Identity.

**Comment by moolen** [comment]
Most of it is described above, to sum it up:
1. you need a "core" eso deployment that installs the CRDs and serves validating / conversion webhooks
2. then you are able to deploy eso on a per-namespace basis with `--namespace`. It must not install the CRDs `--installCRDs=false`, webhook `webhook.create=false` or cert-controller `certController.create=false` components *


[*] Note: you should probably (1) disable ClusterSecretStore/ClusterExternalSecret if you don't need it (these resources are allowed to do cross-namespace references). There are helm values for it `crds.createClusterExternalSecret`. Also (2) strip down permissions of ESO: do not allow cluster-wide access to any resource. (including `ExternalSecret`, `SecretStore`, `Secret` and `serviceaccounts/token`).

I think that should be it :thinking:  :crossed_fingers: 
Please let us know if that works for you

**Comment by tgjonestx** [comment]
@moolen - That synopsis is really helpful. Thanks so much. I'll get back to you with my results

**Comment by tgjonestx** [comment]
@moolen That worked for me with the following additions to the per-namespace config you described in [2] - I also set `scopaedNamespace: NAMESPACE` and `scopedRBAC: true`.

**Comment by captonhotnes** [comment]
What the fuck are u doing
________________________________

**Comment by Veluu** [comment]
> > What is the philosophy/use-case behind supporting multiple operators in a cluster?
> 
> The philosophy/use-case is where you want to ensure that a given team/namespace has its own operator to handle their workloads, and increase the isolation level. This is really related to a security requirement rather than an operational one (i.e. this feature was developed taking into account that operators would be upgraded roughly at the same time, and not be running in different versions according to the tenants' wishes. If your concerns here are upgrades, this feature won't help you out (we do not make promises that our APIs will work smoothly without upgrading the CRDs, which may cause issues with the operators that you did not deploy.)
> 
> Having said that, if your concern is security-wise, this is the right feature for you, and there are several ways that you can isolate multiple operator instances: you can set a `scopedNamespace`, you can configure a `controllerClass` (you can do both of them), and you can use namespace-bound ClusterSecretStores as well. Just remember that we recommend you to have all of your operators up to date with the CRD deployment (i.e. if CRD is version `0.7.1`, so should your operators)

Hey,

I'm most likely missing something here. What's the benefit of multiple instances of the operators(I guess apart from potential security bugs in the operator itself) vs concealing tenants to their namespaces with coresponding SecretStores?

**Comment by omurilo** [comment]
Here I can get multiple controllers with this config: (I have other `helm_release` for a core and  installation of CRDs)

```tf
resource "helm_release" "external-secrets" {
  for_each    = toset(var.namespaces)

  name        = var.name
  repository  = "https://charts.external-secrets.io"
  chart       = "external-secrets"
  namespace   = each.key
  version     = var.helm_version

  set {
    name = "installCRDs"
    value = "false"
  }

  set {
    name = "rbac.servicebindings.create"
    value = "false"
  }

  set {
    name = "scopedNamespace"
    value = each.key
  }

  set {
    name = "scopedRBAC"
    value = "true"
  }

  set {
    name = "certController.create"
    value = "false"
  }

  set {
    name = "webhook.create"
    value = "false"
  }

  set {
    name  = "controllerClass"
    value = "external-secrets-${each.key}-controller"
  }

  values = [
    templatefile("${path.module}/values.yaml", {
      name     = var.name,
      version  = var.helm_version,
      severity = var.severity,
      squad    = var.squad
    })
  ]

  depends_on = [
    helm_release.external-secrets-crds
  ]
}
```
