### ISSUE TITLE
Skip secret extract if not exist

### ISSUE THREAD

**Issue by doryer** [external-secrets/external-secrets#1834]
**Describe the solution you'd like**
I would like to use multiple extract operations to override secrets in specific order, and not fails whole reconciliation if one of the secrets is not existed on the external secret provider

**What is the added value?**
Adding a flag to the extract method to skip if secret does not exist, and continue to the next secret on the extract chain, only output an error if no one of the secrets is exist.

**Give us examples of the outcome**

In the case of this example

```apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: core-exist-dev-core-not
spec:
  refreshInterval: 30s
  secretStoreRef:
    kind: ClusterSecretStore
    name: dev-cluster-secret-store
  dataFrom:
  - extract:
      key: core # exist
  - extract:
      key: dev/core # exist
  - extract:
      key: dev/dev-shared/core # not exist
```

In this case, take the secret values from `core` if exist, if not continue to the next one until you find a matching secret, if no one exists log an error log.
But, if `core` & `dev/core` exist and `dev/core` overrides `core` and `dev/dev-shared/core` is not exist, don't fail the whole reconciliation, just create the secret with the `dev/core` override to `core`.
Currently, he fails to reconcile with the error `could not get secret data from provider` and not creating the secret

**Provide templates if you are proposing changes in the CRD. Provide example workflows or code snippets if they make sense to present.**

`optionalSecret`: true/false ( default: false )

**Comment by gusfcarvalho** [comment]
You can already do that by specifying `DeletionPolicy=merge` - as long as your provider supports it (currently only a few of them support

**Comment by doryer** [comment]
> You can already do that by specifying `DeletionPolicy=merge` - as long as your provider supports it (currently only a few of them support

Oh, thanks tried it now, seems its working great with ASM. Thank you
