### ISSUE TITLE
Gitlab Provider: support multiple "environment" 

### ISSUE THREAD

**Issue by rfelgent** [external-secrets/external-secrets#1837]
**Describe the solution you'd like**
Gitlab Provider should collect project variables having specific environment_scope (like test, ref, prod) and add the default project variables having "environment_scope=all"

**What is the added value?**
a) Gitlab provider integration would have a better alignment with Gitlab project variables/concept/ideas. 
b) In this concrete use case the effort for managing project variables that are shared accross _all_ environemnts is reduced by using "environment_scope=all".

**Give us examples of the outcome**

I suggest to support multiple values for "environment" field like:

```
...
spec:
  provider:
    gitlab:
      ...
      projectID: "453"
      environment: [ "ref", "all" ]
...
```

Or a boolean flag for including "all" (default) variables; something like:

```
...
spec:
  provider:
    gitlab:
      ...
      projectID: "453"
      environment: "ref"
      includeAllEnvironmentScope: true  # default false for backward compatibility
...
```

**Observations (Constraints, Context, etc):**
not that I am aware of

@domizei385 and @moolen may I address this topic to you ?! ;-)
What do you think about this requirement/idea ?

**Comment by domizei385** [comment]
Following convention over configuration, I would not specifically set environments, By default gitlab itself would give out the specific environment variable followed by the wildcard. With the bugfix PR this behavior should now be resembled in the ESO provider.
