### ISSUE TITLE
Feature Flag Vault provide

### ISSUE THREAD

**Issue by 360build** [external-secrets/external-secrets#1844]
**Describe the solution you'd like**
I would like to see a feature flag that disables the logic to add /data in paths for HC vault provide

**What is the added value?**
or vault looks as follow 

brand/{env "testing|acceptance|production}/{service name}/

Per environment we configure a store and we would love to set the value:
brand/{env "testing|acceptance|production}/

So that de rest is the some per environment.  We can add the /data here by our-self so we can use these full paths 

**Give us examples of the outcome**
This could then be changed to:
`apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: io-devops-testing
spec:
  provider:
    vault:
      auth:
        tokenSecretRef:
          key: token
          name: vault-token
      path: io-devops
      server: https://vault
      version: "v2"`
      
   `apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: io-devops-testing
spec:
  provider:
    vault:
      auth:
        tokenSecretRef:
          key: token
          name: vault-token
      path: io-devops/data/testing
      manualPath: true
      server: https://vault
      version: "v2"`
      
  Then with this we would not have to define this part of the path in The ExternalSecret config
  Maybe the Feature flag has to be in the ExternalSecret or in both places. But it would solve the problem and backwards compatibility

**Comment by gusfcarvalho** [comment]
Hi @360build  you can already do this at the secretStore level (by configuring vault version: v1), or by specifying the full path directly in your `spec.data.remoteRef.key`.

e.g. at SecretStore level:
```
spec:
  provider:
    vault:
      kvVersion: "v1"
      path: "brand/data/testing"
```

e.g. at ExternalSecret level:

```
spec:
  data:
  -   remoteRef:
         key: "brand/data/testing/my-secret"
```

**Comment by 360build** [comment]
I see, yes that works perfectly!  

Thanks for this quick response. Fixing it just before Christmas. 

Would there be any needs to go to v2 in the future ?

**Comment by gusfcarvalho** [comment]
at the ExternalSecret level, you won't have any issues. If you're using at the SecretStore level, you won't be able to use `dataFrom.find`.

**Comment by 360build** [comment]
I will take this into account if I will ever have to use the dataFrom.find
