### ISSUE TITLE
Custom Metrics not getting to /metrics path

### ISSUE THREAD

**Issue by shapeofarchitect** [external-secrets/external-secrets#1845]
**Describe the solution you'd like**
Custom metric not being exposed on `/metrics` path, As per the implementation and doc it should.

**Give us examples of the outcome**
As per the description of `Custom Metrics` and per code it should be exposed for external secrets controller.
https://external-secrets.io/v0.5.2/guides-metrics/#external-secret-metrics

**Observations (Constraints, Context, etc):**
I have installed the operator in my kubernetes v1.23 and I couldn't get the operator giving me the custom metrics exported by external_secrets operator. I also tried to locally run this operator as well as in local kind/EKS cluster and experienced the same behavior.

Per code. 

- Metrics Registration was successful as no errors https://github.com/external-secrets/external-secrets/blob/main/pkg/controllers/externalsecret/metrics.go
- Controller is expected to expose the metric even if not exposing any values but it didn't ([
](https://github.com/external-secrets/external-secrets/blob/main/pkg/controllers/externalsecret/externalsecret_controller.go#L102))
<img width="1226" alt="Screen Shot 2022-12-25 at 20 10 28" src="https://user-images.githubusercontent.com/4916214/209480842-6b059a42-1dab-4249-834b-3b255754928b.png">

I think by default these custom metrics should be available , If I understand correctly the labels attached to these metrics would have value after install into Kubernetes cluster but that can't be the reason for these custom metrics not exposed ?

Appreciate the insight on this.

**Comment by gusfcarvalho** [comment]
sorry @shapeofarchitect. Do you have any `ExternalSecret` resource installed in your cluster? Your metrics look fine, but no active workers (meaning no tasks to actually generate the custom metrics you're looking for.

**Comment by shapeofarchitect** [comment]
@gusfcarvalho  thanks for replying to me. No at the moment I don't have any `ExternalSecret` installed in my local cluster. Is this mandatory to have that , I mean I should be able to see 0 for these custom metrics ? If I use `NewCounter` and `NewGuage` without dimensional metrics it works and it does give me 0 value of these metrics. Is that only applicable for dimensional metrics ?

**Comment by gusfcarvalho** [comment]
> @gusfcarvalho thanks for replying to me. No at the moment I don't have any `ExternalSecret` installed in my local cluster. Is this mandatory to have that , I mean I should be able to see 0 for these custom metrics ? If I use `NewCounter` and `NewGuage` without dimensional metrics it works and it does give me 0 value of these metrics. Is that only applicable for dimensional metrics ?

If there is no reconciliation calls happening (i.e. no ExternalSecret in the cluster), no `NewCounter` and `NewGauge` will be called, as they are registered during the reconciliation loop. 

As of today, you need to register an ExternalSecret to have those metrics available :)

**Comment by shapeofarchitect** [comment]
oh man , yea , sorry for the dumb thread. I quickly set up the vault and it worked like a charm. 

<img width="1094" alt="Screen Shot 2022-12-25 at 22 11 52" src="https://user-images.githubusercontent.com/4916214/209483177-970a3d84-fb76-4087-992a-acde82dcd84b.png">

**Comment by shapeofarchitect** [comment]
Thanks @gusfcarvalho  for help. All sorted.
