### ISSUE TITLE
404 not found link from external-secrets/README.md for stability-support

### ISSUE THREAD

**Issue by ca8IiN4oow** [external-secrets/external-secrets#1862]
**Describe the solution you'd like**
A non 404 link 

**What is the added value?**
Brand / image / helping people get to the stability-support document so they can review and adopt the project. 

**Give us examples of the outcome**

https://kubernetes.slack.com/archives/C017BF84G2Y/p1672862877406359

The page :  https://external-secrets.io/main/introduction/stability-support/ is suppose to be the correct one. 

**Observations (Constraints, Context, etc):**

**Comment by moolen** [comment]
Fixed with #1863

**Comment by moolen** [comment]
This will be on `main` docs, not the latest release 9.7.1.

Thanks for reporting this :heart:
