### ISSUE TITLE
ESO support for refreshing secrets in pods.

### ISSUE THREAD

**Issue by pcperera** [external-secrets/external-secrets#1865]
**Describe the solution you'd like**
Currently ESO doesn't seem (according to available documentation) to have the capability to refresh the deployments when the secrets are updated.

`
When the secret is updated, it should trigger restart of the deployment to fetch the new secrets. 
`

**What is the added value?**
It will not be necessary to use another external tool support restarting the pods when the secrets get updated. The secret deployment and orchestration will be fully handled by ESO.

https://github.com/external-secrets/kubernetes-external-secrets/issues/38

**Comment by knelasevero** [comment]
I agree, to me this is out of scope of the project, but I also think it is worth discussing and getting other perspectives

**Comment by jack-evans** [comment]
You should be able to use something like https://github.com/stakater/Reloader in conjunction with ESO to accomplish what you desire

**Comment by IdanAdar** [comment]
We use Reloader as well in order to reload pods that their secrets have changed. I do think that some cases of this could be in ESO in order to not add more tools into the mix, but, can live with ESO+Reloader...

**Comment by rounakdatta** [comment]
You can alsoo mount the Kubernetes Secret object into a volume mount i.e. Kubernetes mounts each credential as separate files. And in that case, you can have an application logic in code to read those files every X seconds (reasonable TTL). That'll not require the pod to be restarted, but I guess it's not scalable/deterministic.
