### ISSUE TITLE
Implement Metadata Policy across providers

### ISSUE THREAD

**Issue by gusfcarvalho** [external-secrets/external-secrets#1872]
`MetadataPolicy` allows providers to fetch metadata information from the secret objects, instead of the secret contents. Currently, only Azure Key Vault supports it. This needs to be implemented for the following providers:

- [x] #1873
- [x] #1874
- [x] #1875
- [x] #1876
- [x] #1877

**Comment by sebagomez** [comment]
this one can be closed! 🥳
