### ISSUE TITLE
Add MetadataPolicy=Fetch for GCP Secrets Manager

### ISSUE THREAD

**Issue by gusfcarvalho** [external-secrets/external-secrets#1874]
metadata Policy = Fetch is already available for Azure Key vault. We need to implement it for GCP provider by fetching `tags` information from the Secrets Manager

```
data:
- remoteRef:
    key: my-tag
```

**Comment by shuheiktgw** [comment]
May I try implementing this feature? 
/assign

**Comment by shuheiktgw** [comment]
@gusfcarvalho Hi, I have a question about this feature 👋 [Secret](https://pkg.go.dev/cloud.google.com/go/secretmanager@v1.10.0/apiv1/secretmanagerpb#Secret) actually has two metadata fields, `Labels` and `Annotations` just like [Kubernetes Secret](https://github.com/external-secrets/external-secrets/issues/1873) does. 

Should I support the Annotations filed as well? It seems currently the operator assumes [a tag equals a label](https://github.com/external-secrets/external-secrets/blob/769efdc391a1f9ca524f76199af190a6ef64317c/pkg/provider/gcp/secretmanager/client.go#L270), though.

**Comment by moolen** [comment]
After reading the `annotation` docs it seems that this shouldn't be used by the end-user, rather by tools like ESO etc. to store their state.
But there are always people who use it in a wrong way :dancers:. I like the  idea to prefix the property, i think it would be more in-line with other providers if we use a `/` to separate the type (label/annotation) from the key: `annotations/my-annotation` or `labels/my-annotation`. We have a similar problem with azure keyvault where we have different secret types `secret/{foo}`, `key/{foo}`, `certificate/{foo}`.

```
	// Annotations are distinct from various forms of labels.
	// Annotations exist to allow client tools to store their own state
	// information without requiring a database.
```

**Comment by shuheiktgw** [comment]
That makes sense. Thank you for the clarification! 🙂

**Comment by moolen** [comment]
I need to amend what i've said earlier: the approach with `labels/{foo}` and `annotations/{bar}` doesn't make sense:
Yes, we have the `secret/key/certificate` in Azure KeyVault, but this is for the `key`, not `property`.

The property is usually parsed as a gjson expression to allows users to extract nested data. With that being said: Let's go with your approach @shuheiktgw! `property: "annotations.my-annotation"`.

This has also been implemented in https://github.com/external-secrets/external-secrets/pull/2106 (where i noticed my error :man_facepalming:)
