### ISSUE TITLE
Add MetadataPolicy=Fetch for AWS Secret Manager

### ISSUE THREAD

**Issue by gusfcarvalho** [external-secrets/external-secrets#1875]
We need to implement MetadataPolicy=Fetch to AWS Secrets Manager. Details to be found out. Azure Keyvault provider has an implementation reference

**Comment by sebagomez** [comment]
Hey guys, I want to start working on this issue but I have a few questions I thought would be useful to get out into the issue itself.

According to AWS CLI [describe-secret documentation] (https://docs.aws.amazon.com/cli/latest/reference/secretsmanager/describe-secret.html), when I describe a secret I would the following info.

```json
{
    "ARN": "arn:aws:secretsmanager:us-west-2:123456789012:secret:MyTestSecret-Ca8JGt",
    "Name": "MyTestSecret",
    "Description": "My test secret",
    "KmsKeyId": "arn:aws:kms:us-west-2:123456789012:key/EXAMPLE1-90ab-cdef-fedc-ba987EXAMPLE",
    "RotationEnabled": true,
    "RotationLambdaARN": "arn:aws:lambda:us-west-2:123456789012:function:MyTestRotationLambda",
    "RotationRules": {
        "AutomaticallyAfterDays": 2,
        "Duration": "2h",
        "ScheduleExpression": "cron(0 16 1,15 * ? *)"
    },
    "LastRotatedDate": 1525747253.72,
    "LastChangedDate": 1523477145.729,
    "LastAccessedDate": 1524572133.25,
    "Tags": [
        {
            "Key": "SecondTag",
            "Value": "AnotherValue"
        },
        {
            "Key": "FirstTag",
            "Value": "SomeValue"
        }
    ],
    "VersionIdsToStages": {
        "a1b2c3d4-5678-90ab-cdef-EXAMPLE11111": [
            "AWSPREVIOUS"
        ],
        "a1b2c3d4-5678-90ab-cdef-EXAMPLE22222": [
            "AWSCURRENT"
        ],
        "a1b2c3d4-5678-90ab-cdef-EXAMPLE33333": [
            "AWSPENDING"
        ]
    },
    "CreatedDate": 1521534252.66,
    "PrimaryRegion": "us-west-2",
    "ReplicationStatus": [
        {
            "Region": "eu-west-3",
            "KmsKeyId": "alias/aws/secretsmanager",
            "Status": "InSync",
            "StatusMessage": "Replication succeeded"
        }
    ]
}
```

Do we want data in a Secret with this info? Would it be a single entry with all that json? What would the synced secret look like? 

Let me know if I'm in the right direction

**Comment by moolen** [comment]
I would restrict that to tags section only.

**Comment by sebagomez** [comment]
But don't we already have a feature for grabbing tags? I thought this was different, am I right?

**Comment by gusfcarvalho** [comment]
That’s the feature for getting tags for AWS :P

**Comment by sebagomez** [comment]
Aha! that makes sense! :D 

I've worked with that feature in Azure... I now realize that's the exact feature we want here 🤦‍♂️

Thank you both
