### ISSUE TITLE
Cannot create manifest files to be used with kustomize

### ISSUE THREAD

**Issue by aupadh12** [external-secrets/external-secrets#1900]
Hello Team,

I would like to use kustomize for managing the external secrets and so I wanted to have the manifest files.
I tried creating them using helm template but I am getting below error:
Error: chart requires kubeVersion: >= 1.19.0-0 which is incompatible with Kubernetes v1.16.0

What can I do to generate files?

**Comment by moolen** [comment]
What is your helm version? It is compiled against a specific version of kubernetes. Try using the latest helm version.
You can also try `helm template --validate` to pull the Kubernetes version from the kube-apiserver via kubeconfig.

Please Let me know if that helps.

**Comment by aupadh12** [comment]
Hi @moolen ,

upgrading helm version fixed this issue. Thank you.
