### ISSUE TITLE
ESO stopped working on OpenShift

### ISSUE THREAD

**Issue by open-sudo** [external-secrets/external-secrets#1906]
**Describe the solution you'd like**
When I deploy ESO on OpenShift 4.11.20, external secrets are not synched. Running "kubectl describe extenalsecret app-secret", I get: "could not get secret data from provider"

**Observations (Constraints, Context, etc):**

1) When I install ESO using Helm, I get these warnings:
Release "external-secrets" does not exist. Installing it now.
W0113 02:38:44.819046   58684 warnings.go:70] would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "external-secrets" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "external-secrets" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "external-secrets" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "external-secrets" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
W0113 02:38:44.839787   58684 warnings.go:70] would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "cert-controller" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "cert-controller" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "cert-controller" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "cert-controller" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
W0113 02:38:44.841567   58684 warnings.go:70] would violate PodSecurity "restricted:v1.24": allowPrivilegeEscalation != false (container "webhook" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "webhook" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "webhook" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "webhook" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")

2) After deployment, I get following error messages in PODS:

a) Pod: external-secrets-webhook-8fd54b58d-mlrpf. Message: http: TLS handshake error from 10.129.0.28:54530: remote error: tls: bad certificate

b) Pod: external-secrets-7584fd846f-68rnq. Message:
{"level":"info","ts":1673596125.4246821,"logger":"provider.aws.secretsmanager","msg":"fetching secret value","key":"app-secret","version":"AWSCURRENT"}
{"level":"error","ts":1673596125.7640798,"logger":"controllers.ExternalSecret","msg":"could not get secret data from provider","ExternalSecret":"app/app-secret","error":"RequestError: send request failed\ncaused by: Post \"https://secretsmanager.us-east-1.amazonaws.com/\": net/http: invalid header field value for \"Authorization\"","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:190\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235"}

**Comment by gusfcarvalho** [comment]
Hi @open-sudo ! This issue seems to be regarding some misconfiguration, most likely. Did you recently upgrade versions?  What version are you using?

**Comment by open-sudo** [comment]
I tried this many times on brand new clusters. The first thing I tried after initiating the cluster is set up ESO. I follow the procedure described here: https://ptuladhar3.medium.com/getting-started-with-external-secrets-operator-on-kubernetes-using-aws-secrets-manager-6dc403d9630c. So, I would like to think that it pulls the latest ESO.

**Comment by gusfcarvalho** [comment]
It might be worth to check for new lines in your AWS secret (if thats how you are authenticating). We've seen similar errors to yours that were because the authentication info (AccessKeyId and SecretAccessKey) contained "\n" in it.

**Comment by open-sudo** [comment]
You are right. Some invisible characters in the credentials. Not sure if I can ask this question here. My credential includes line break. If I put them AS in AWS Secret manager, ESO complains about it:

unable to unmarshal secret aws-credentials4: invalid character '\n' in string literal

On the other hand, if I base64 the credential before putting it in AWS Secret Manager, they are re-encoded when store in a Secret. I added:

   decodingStrategy: None
   encodingStrategy: None

But this doesn't help.

**Comment by gusfcarvalho** [comment]
You should set `decodingStrategy: Base64`. That will make eso automatically remove the double encoding for you (note that it is not eso that is double-encoding it, but rather kubernetes itself)

**Comment by open-sudo** [comment]
Awesome thanks. closing the ticket.
