### ISSUE TITLE
dockerfilejson templating empty, not rendered

### ISSUE THREAD

**Issue by makemesteaks** [external-secrets/external-secrets#1911]
Hello,

I am running ESO 0.7.1 and I have the following manifest:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: some-secret
  namespace: some-namespace
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws
  target:
    name: secret-name-inside-k8s
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths": {
            "{{ .url }}": {
              "username": "{{ .user }}",
              "password": "{{ .password }}",
              "email": "{{ .email }}",
              "auth": "{{ .auth }}"
            }
          }}
  data:
    - secretKey: url
      remoteRef:
        key: aws-secrets-manager-secret
        property: url
    - secretKey: user
      remoteRef:
        key: aws-secrets-manager-secret
        property: user
    - secretKey: password
      remoteRef:
        key: aws-secrets-manager-secret
        property: password
    - secretKey: email
      remoteRef:
        key: aws-secrets-manager-secret
        property: email
    - secretKey: auth
      remoteRef:
        key: aws-secrets-manager-secret
        property: auth
```

AWS Secrets Manager content:

![image](https://user-images.githubusercontent.com/8746865/212401437-44b16264-c8a6-41ae-9bde-8a5cc5a6fcfe.png)

And this this the "rendered" data:

```
{"auths": {
  "": {
    "username": "",
    "password": "",
    "email": "",
    "auth": ""
  }
}}
```

Also, this problem is rather inconsistent (sometimes it happens, sometimes it doesn't, but mostly it does.).
I have tried reinstalling secrets manager, deleting es and secret, etc.
Any insight here?

**Comment by gusfcarvalho** [comment]
Can you create a another es without the template block and see if variables are loaded ok there?

**Comment by makemesteaks** [comment]
Yup that has been tested also, and the variables show up. Also, sometimes it also works with the template, sometimes it doesn't. Pretty inconsistent.

**Comment by gusfcarvalho** [comment]
It seems to me that this issue might be related to some inconsistency in fetching the secrets 🤔 when using templates, then that produces a blank one not sure why.

Does this happen in older ESO versions?

**Comment by makemesteaks** [comment]
Yes, it happens in all the versions. Unfortunately I will have to create those secrets in terraform.

**Comment by gusfcarvalho** [comment]
Can you send the logs of your ESO deployment? Maybe there’s an error track there that we can chase on

**Comment by vanceism7** [comment]
Small aside: The manifest OP posted here was really useful for getting my own dockerconfigjson setup. This would be a nice example to add to the official site as another `dockerconfigjson` example

**Comment by phoenix-henri** [comment]
I get the same issue when using Hashicorp Vault as a backend and i am on v0.8.1
