### ISSUE TITLE
Error when use 1password provider with selfsigned certificate

### ISSUE THREAD

**Issue by mr1jingles** [external-secrets/external-secrets#1950]
I trying to use 1password provider with custom certificate which I added to 1password-connect but I getting the error:

> {"level":"error","ts":1674562017.7938094,"logger":"controllers.ClusterSecretStore","msg":"unable to validate store","clustersecretstore":"/onepassword-css","error":"could not validate provider: Get \"https://onepassword-connect.onepassword-connect-ns:8443/v1/vaults?filter=title+eq+%22vault%22\": x509: certificate signed by unknown authority","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/secretstore.reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/common.go:67\ngithub.com/external-secrets/external-secrets/pkg/controllers/secretstore.(*ClusterStoreReconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/secretstore/clustersecretstore_controller.go:54\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234"}
> {"level":"error","ts":1674562017.8060331,"msg":"Reconciler error","controller":"clustersecretstore","controllerGroup":"external-secrets.io","controllerKind":"ClusterSecretStore","ClusterSecretStore":{"name":"onepassword-css"},"namespace":"","name":"onepassword-css","reconcileID":"91a569c2-7f6c-4db6-bec5-068c4ce729a6","error":"could not validate provider: Get \"https://onepassword-connect.onepassword-connect-ns:8443/v1/vaults?filter=title+eq+%22vault%22\": x509: certificate signed by unknown authority","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.0/pkg/internal/controller/controller.go:234"}
> 

How can I ignore the certificate error?

Kubernetes Version: v1.23.6
ESO Version: v0.7.2

Thanks!

**Comment by moolen** [comment]
currently you can't define a custom ca certificate for this provider or ignore this error. PRs welcome! 

Other providers support that as well. see `caBundle` or `caProvider` in [API specs](https://external-secrets.io/v0.7.2/api/spec/).
