### ISSUE TITLE
ExternalSecret fails to sync previous Google Secret Manager version by default

### ISSUE THREAD

**Issue by gaahrdner** [external-secrets/external-secrets#1951]
**Describe the solution you'd like**
`spec.target.version` should support a `latestEnabled`

**What is the added value?**
ExternalSecret will be able to continue to sync secrets when the latest version is disabled, and an older version is enabled.

**Give us examples of the outcome**

If we're using Google Secret Manager as a backend, and let's say someone puts in an incorrect value, it'd be nice to roll-back using the UI.  The ExternalSecret, when in `latestEnabled` mode, could walk through available versions until the latest one that is also enabled is found. 

**Observations (Constraints, Context, etc):**

```
Events:
  Type     Reason        Age                     From              Message
  ----     ------        ----                    ----              -------
  Warning  UpdateFailed  106s (x646 over 5h12m)  external-secrets  unable to access Secret from SecretManager Client: rpc error: code = FailedPrecondition desc = Secret Version [projects/REDACTED/secrets/REDACTED_SECRETS/versions/6] is in DISABLED state.
```
![Screen Shot 2023-01-24 at 3 02 41 PM](https://user-images.githubusercontent.com/739932/214413530-85cb8971-e671-401e-bf31-1153d68b6eda.png)

**Comment by gusfcarvalho** [comment]
Hi @gaahrdner ! Have you tried using versionAliases?

**Comment by gaahrdner** [comment]
> Hi @gaahrdner ! Have you tried using versionAliases?

Hi @gusfcarvalho , I have not, nor have I heard of them. I did a quick search but didn't see anything in the docs, I'll look closer tomorrow when I'm back in the office. Thanks!

**Comment by gusfcarvalho** [comment]
VersionAlias is not in external secrets, but rather in GCP secret manager, it allows you to Alias a given version, which then can be used in external secrets with the version field.

so that would allow you to control your scenario with GCP native secrets only :)

**Comment by gaahrdner** [comment]
Oh wow, thanks, this is a great solution! 🎉
