### ISSUE TITLE
DeletionPolicy support for the Webhook provider

### ISSUE THREAD

**Issue by ArtificialQualia** [external-secrets/external-secrets#1958]
We would like the ability to have secrets respect the DeletionPolicy attribute when using the Webhook provider, similar to the work done to the other providers in #1867 

Would this be as simple as returning a SecretNotFound error when a Webhook 404s like the work that was done in #1914?

**Comment by gusfcarvalho** [comment]
It would, and PRs are welcome!

We just didn't do it as we only have a few of "internally maintained" providers (where we keep all the features up to date). But really, it is a low hanging fruit for webhook :)

**Comment by ArtificialQualia** [comment]
Thank you for the prompt response.  I'll have to confer with my team before committing to this, but hopefully we should be able to provide a PR with this feature.
