### ISSUE TITLE
Add support to use cert-manager instead of built-in cert controller

### ISSUE THREAD

**Issue by jasminjenull** [external-secrets/external-secrets#1965]
We would like to use `cert-manager` to create the certs for the webhook instead of deploying the cert controller included in this chart. Currently this is not possible in the helm chart as the `ValidatingWebhookConfiguration` resources don't allow to add annotations to inject the `caBundle`. Besides that also the creation of the `webhook-secret.yaml` secret should be optional I guess, as this secret then should be created by `cert-manager`.

This way we could use a component that's already in place for us instead of deploying yet another one.

**Comment by gusfcarvalho** [comment]
hi @jasminjenull ! This is something that we look forward to have (a better compatibility with `cert-manager`), but unfortunately we will not be able to look onto this for a while.

Do you think you can provide a PR with the appropriate changes to the helm charts? 😄 

I'll be more than glad to review it.

**Comment by fernferret** [comment]
Hi @gusfcarvalho and @moolen. I've put something together for this. I added a few options to mine, for example, auto adding the annotations to the CRDs (for the conversion webhook) as well as the `ValidatingWebhookConfiguration` as this can be a bit annoying to do manually.

I see there was some progress that @moolen made, so I'm certainly not looking to step on anyone's work, but if no one else has claimed `cert-manager` integration, I'm happy to submit my work if you'd like!

What I've done (in a few words):

* Don't install the `webhook-secret.yaml` if `webhook.certManager.enabled: true`
* Create a `Certificate` resource if `webhook.certManager.createCert: true`
* Automatically add annotations to all CRDs and Webhooks if `webhook.certManager.addInjectorAnnotation: true`

This provides a great experience in that simply adding the following to the chart switches support over to cert-manager.

```yaml
webhook:
  certManager:
    enabled: true
    cert:
      issuerRef:
        kind: "ClusterIssuer"
        name: "my-issuer"
```

**Comment by moolen** [comment]
Hey @fernferret :wave: 
I like that propsal, this looks really good!

**Comment by uhthomas** [comment]
Hi @fernferret, I'm confused. I believe the intention of https://github.com/external-secrets/external-secrets/pull/2394 is to switch from `external-secrets-cert-controller` to `cert-manager`, but it seems that simply using `--set=webhook.certManager.enabled=true` only creates the certificate and does not affect the `external-secrets-cert-controller` deployment at all. Is this correct?

**Comment by uhthomas** [comment]
It seems `--set=certController.create=false` is also required? It might be nice to document this more clearly, or have `-set=webhook.certManager.enabled=true` imply `certController.create=false`.
