### ISSUE TITLE
port conflict for webhook on Fargate

### ISSUE THREAD

**Issue by csantanapr** [external-secrets/external-secrets#1981]
**What happened**:

Using the default helm chart to run external dns on AWS Fargate there is a port conflict `10250` this port number is the default port for `kubelet`

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Deploy EKS with Fargate, deploy helm chart to run pods on Fargate pods

The helm chart values.yaml default value `webhook.port` should be changed to another value like `9443`

**Comment by csantanapr** [comment]
If its ok I can submit PR to update https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/values.yaml#L205
To `webhook.port: 9443`

**Comment by ppodevlab** [comment]
> **What happened**:
> 
> Using the default helm chart to run external dns on AWS Fargate there is a port conflict `10250` this port number is the default port for `kubelet`
> 
> **What you expected to happen**:
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> 
> Deploy EKS with Fargate, deploy helm chart to run pods on Fargate pods
> 
> The helm chart values.yaml default value `webhook.port` should be changed to another value like `9443`

any reason to not modify this directly in your values and do it in the chart itself?
