### ISSUE TITLE
Unexpected merge behavior without template in ExternalSecret spec.target

### ISSUE THREAD

**Issue by madhurimachime** [external-secrets/external-secrets#1991]
**Describe the solution you'd like**
Without `template` in `spec.target`  `last-applied-configuration` from `ExternalSecret` not be copied to the `Secret`

**What is the added value?**
This preserves the merge logic - values from the secret provider will be merged into the existing secret instead of deleting any value from the `Secret` if it is not present in the `ExternalSecret`

**Give us examples of the outcome**

Eg: With `spect.target.template` in `ExternalSecret` (SECRET_ONE still present even if it is deleted from the `ExternalSecret`)

```
kind: Secret
apiVersion: v1
data:
  SECRET_ONE
  SECRET_TWO
```

Eg: Without `spec.target.template` in `ExternalSecret` (SECRET_ONE will not be preserved if deleted from the `ExternalSecret` because of the `kubectl.kubernetes.io/last-applied-configuration` annotation being copied.
```
kind: Secret
apiVersion: v1
data:
  SECRET_TWO
```

**Observations (Constraints, Context, etc):**
Currently because of [this](https://github.com/external-secrets/external-secrets/blob/v0.7.0/pkg/controllers/externalsecret/externalsecret_controller_template.go#L105) when `spec.target.template` is not set `Secret` ends up with the last applied configuration of the `ExternalSecret` resulting in the unexpected merge behavior.

**Comment by gusfcarvalho** [comment]
sorry @madhurimachine, I did not understand the issue. Can you please provide manifests for both cases so I can better understand what's happening here?

If the secret one is deleted from the externalSecret, it is expected for it to be deleted from the Secret - this has nothing to do with the labels applied to the Secret itself.
