### ISSUE TITLE
Behavior of ExternalSecretFind

### ISSUE THREAD

**Issue by cjc7373** [external-secrets/external-secrets#1996]
I saw some discussions said that `ExternalSecretFind` should use both `tags` AND `name` fields to match secrets. But [the documentation](https://external-secrets.io/v0.7.2/guides/getallsecrets/) doesn't clearly point it out.

In addition, I saw inconsistencies between the implementation of Azure Keyvault and HashiCorp Vault.
https://github.com/external-secrets/external-secrets/blob/fe3c78d2af1202331df6bfbc7237f5f310dd5c21/pkg/provider/azure/keyvault/keyvault.go#L485 It seems that Azure will check both `name` and `tags`.

https://github.com/external-secrets/external-secrets/blob/fe3c78d2af1202331df6bfbc7237f5f310dd5c21/pkg/provider/vault/vault.go#L484 While Vault will check either `name` or `tags`.

What's the expected behavior of ExternalSecretFind?

**Comment by imranalley** [comment]
I can pick this up - seems to be a simple enough change

**Comment by gusfcarvalho** [comment]
thanks @imranalley ! 😄
