### ISSUE TITLE
SecretStore has been removed after upgrade from 8.5.5 to v0.5.5

### ISSUE THREAD

**Issue by kostyanius** [external-secrets/external-secrets#2013]
Hello

today i was trying to update the external-secret plugin for AWS EKS.

I have initiated the command: helm upgrade  external-secrets external-secrets/external-secrets
After what i have noticed that all of my secrets have been lost.
After that i have initiated the rollback to pervious 2-nd version: 

~/ helm history external-secrets -n kube-system

REVISION        UPDATED                         STATUS          CHART                                   APP VERSION     DESCRIPTION
1               Wed Jun  1 11:12:51 2022        superseded      kubernetes-external-secrets-8.5.5       8.5.5           Install complete
2               Wed Jun  1 11:43:28 2022        superseded      external-secrets-0.5.5                  v0.5.5          Upgrade complete
3               Mon Feb 13 15:24:42 2023        superseded      kubernetes-external-secrets-8.5.5       8.5.5           Upgrade complete
4               Mon Feb 13 16:03:26 2023        deployed        external-secrets-0.5.5                  v0.5.5          Rollback to 2

But it does not help. Still see an error:

~/ kubectl describe externalsecrets.external-secrets.io --all-namespaces 

Events:
  Type     Reason           Age                   From              Message
  ----     ------           ----                  ----              -------
  Warning  InvalidStoreRef  16m (x30 over 3h41m)  external-secrets  could not get ClusterSecretStore "aws-secret-store-parameterstore", ClusterSecretStore.external-secrets.io "aws-secret-store-parameterstore" not found
  
 Please advise how to fix it ASAP.
 Thanks.

**Comment by gusfcarvalho** [comment]
Hi @kostyanius . You have upgraded your charts from KES to use ESO. This is not an expected flow that you could just upgrade forward, and a migration needed to be planned beforehand. I would suggest you to perform the rollback, and then properly plan your migration. 


for more reference: https://github.com/external-secrets/kes-to-eso

**Comment by kostyanius** [comment]
Thanks. Please advise how to do the rollback properly? I tried to do it using helm but looks like it was not a proper way. Thanks.

**Comment by kostyanius** [comment]
~/kes-to-eso$ . rollback.sh
deployment.apps/external-secrets scaled
Error from server (NotFound): deployments.apps "kubernetes-external-secrets" not found

**Comment by gusfcarvalho** [comment]
The proper way is indeed with helm. The tool would help you prepare it. Now that you’ve already upgraded it with helm you need to rollback with the same tool.

**Comment by kostyanius** [comment]
Well. I have conducted rollback to KES 8.5.5 but now i see my secrets from AWS parameter store are not updating in kluster secrets. Frpm the other side i see no errors in ( kubectl logs external-secrets-kubernetes-external-secrets-7964d97954-224cs -n kube-system) pod. Could you please advise how to make it work again? I just see olny such messages on log. Is it error or not?
![зображення](https://user-images.githubusercontent.com/9063908/218693073-7de8cb49-7a05-40dd-8d4f-b44695e6fd24.png)
