### ISSUE TITLE
ESO Stable release for Oracle Vault

### ISSUE THREAD

**Issue by imtiyazhasan1** [external-secrets/external-secrets#2014]
Hello All we would like to use ESO with Oracle Vault for OKE.
But we have observed that ESO does not have a stable release for OKE and Oracle Vault. it is alpha release.
I would like to know about the Stable release for ESO for oracle vault.

**Comment by moolen** [comment]
We can promote providers like oracle to a more mature level. To do that there needs to be decent unit & e2e test coverage and production burn time. 
However, we (from a maintainers perspective) do not have plans to put a lot of effort into this provider at this point in time. It is community maintained and open for collaboration. We try to avoid breaking changes where possible even on community maintained providers. 

We do to provide support for all providers on a best-effort basis and patch SDK versions weekly.

If the background of your question is whether or not you can/should use this in production i'd say: yes, please do it but please test it properly (just like with any other OSS) - and please contribute back to the project :wink: If there's better test coverage all users benefit from that.
