### ISSUE TITLE
Created Secret Store and External Secret Have No Status. Secret isn't injected from AKV. No Error Message in Logs

### ISSUE THREAD

**Issue by SuncorNate** [external-secrets/external-secrets#2022]
Hi community,

I created both SS and ES for injecting secret from Azure KV. Both can be created successfully but no actual Openshift secret is created. When lookup the status, neither of them has it. Service principal credential is tested as valid, keyvault access is also confirmed.
![image](https://user-images.githubusercontent.com/108746247/219495489-7790153a-526e-41ef-b2bd-b4d69dca9ff4.png)
![image](https://user-images.githubusercontent.com/108746247/219495674-77b7985e-757b-488b-b9d8-2b793e0aa847.png)

YAML files look like as following:
`
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-kv-backend
spec:
  provider:
    azurekv:
      tenantId: XXX
      vaultUrl: "https://XXX.vault.azure.net/"
      authSecretRef:
        clientId:
          name: azure-secret-sp
          key: ClientID
        clientSecret:
          name: azure-secret-sp
          key: ClientSecret`

`apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-kv-example
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-kv-backend
  target:
    name: XXX
  data:
  - secretKey: XXX
    remoteRef:
      key: secret/XXX`

Checked the controller logs and it doesn't have any useful info. Can anyone please advise what may cause the issue please?

Thank you in advance for the consideration.

**Comment by gusfcarvalho** [comment]
hi @SuncorNate ! Most likely you have an installation error on openshift. Did you create the needed manifests to perform the installation there? Can you share them?

**Comment by SuncorNate** [comment]
> hi @SuncorNate ! Most likely you have an installation error on openshift. Did you create the needed manifests to perform the installation there? Can you share them?

Thanks for the reply gusfcarvalho. We are using Azure Openshift, installation is done through OpenShift Operatorhub. Can you please advise which manifests are required so I can check? Thank you

**Comment by SuncorNate** [comment]
Issue was resolved by installing operator to a new namespace.
