### ISSUE TITLE
e2e tests for GCP

### ISSUE THREAD

**Issue by knelasevero** [external-secrets/external-secrets#205]
Implement e2e tests for the GCP SM provider.

AC:

- All happy paths covered
- Few edge cases, and expected failures covered

**Comment by moolen** [comment]
provider-specific tests:
* auth via secret
* maybe cross-region
* workload identity if applicable

**Comment by knelasevero** [comment]
workload identity is only testable if the cluster is GKE right? Same problem as we had for AWS, right? But I think we can use CS infra for that. I will figure out. Having a preemptible (spot) cluster should suffice.
