### ISSUE TITLE
e2e tests for Hashicorp Vault

### ISSUE THREAD

**Issue by knelasevero** [external-secrets/external-secrets#208]
Implement e2e tests for the Vault provider.

AC:

-All happy paths covered
-Few edge cases, and expected failures covered

**Comment by ricardoptcosta** [comment]
As stated by @moolen, for testing certificate auth we would need to:

- run vault in standalone mode.
- generate TLS key/certs
- mount them in vault
- configure vault to use the TLS key/certs
- configure an unseal mechanism (or script it in the Install() function here.)
- write the actual tests

**Comment by moolen** [comment]
I'll be working on this issue. Plan so far:

* setup vault as mentioned above
* add tests around authentication mechanisms: cert, token, jwt, k8s
