### ISSUE TITLE
Feature request : Support backend Scaleway Secret_manager

### ISSUE THREAD

**Issue by nighoa** [external-secrets/external-secrets#2081]
**Asking for backend support**

The goal of this ticket is just to ask if it's planned or not to include the new Scaleway Secret Manager as a compatible backend to store our secrets.

The API is here : https://developers.scaleway.com/en/products/secret_manager/api/v1alpha1

**Comment by fsodogandji** [comment]
A backend store has already been developed by scaleway:
https://www.scaleway.com/en/docs/tutorials/external-secrets/

However, there is no MR on the main repo yet (but very soon).  :-)

**Comment by nighoa** [comment]
Thanks a lot.

I will integrate in my architecture in the next days. 

Hope to see a MR soon :)
