### ISSUE TITLE
e2e tests for AWS Secrets Manager

### ISSUE THREAD

**Issue by knelasevero** [external-secrets/external-secrets#209]
Implement e2e tests for the AWS SM provider.

AC:

-All happy paths covered
-Few edge cases, and expected failures covered

**Comment by moolen** [comment]
provider-specific tests (same as #206, but should be tested for both providers):
* jwt authentication + assuming IAM roles
* secret/key authentication + assuming IAM roles
* region configuration

**Comment by knelasevero** [comment]
@moolen do you have the bandwidth to take this one? I don't think I have alone.

**Comment by moolen** [comment]
sure, i will take it.
