### ISSUE TITLE
Add support for Vault k/v store

### ISSUE THREAD

**Issue by mcavoyk** [external-secrets/external-secrets#21]
**Describe the solution you'd like**
SecretStore resources should support Vault as a backend. Authentication should support at least AppRole and Kubernetes Auth.

**Comment by sparkacus** [comment]
It would be great if secret mapping could also be automatic i.e. all key/values stored in a Vault secret sync with a Kubernetes secret

**Comment by sklarsa** [comment]
Also support for both k/v store versions (1 and 2) would be fantastic!

**Comment by mcavoyk** [comment]
> Also support for both k/v store versions (1 and 2) would be fantastic!

Support for both versions is planned 👍 . Working on this feature currently

**Comment by xxxbobrxxx** [comment]
Hi! It would be great if vault integration will support JWT authentication method (not only Kubernetes).

Your project is going to be very great. Thanks!

**Comment by aelbarkani** [comment]
Definitely, JWT/OIDC authentication would be great.
