### ISSUE TITLE
[helm] CRDs and GitOps

### ISSUE THREAD

**Issue by carlosjgp** [external-secrets/external-secrets#2112]
**Describe the solution you'd like**
I would like the ESO CRDs to stay on the cluster even when the Helm release is removed.
This could be achieved through the Helm annotation `helm.sh/resource-policy: keep`
https://helm.sh/docs/howto/charts_tips_and_tricks/#tell-helm-not-to-uninstall-a-resource

**What is the added value?**
When using GitOps tools to provision the ESO Helm chart there are some strategies to try to recover from bad deployments.
Some of these strategies try to rollback or uninstall the release triggering the following successions of events:

- Helm release rollbacked or uninstall
- CRDs are removed from the cluster
- `ExternalSecrets`, `SecretStores` and other CRs are also removed
- `ExternalSecrets` `creationPolicy` defaults to `Owner` and is the one we want
- Kubernetes `Secrets` are owned by the `ExternalSecrets` which have just been removed are also removed

**Give us examples of the outcome**

```
{{- if .Values.installCRDs }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.1
    {{- with .Values.crdsAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  creationTimestamp: null
  name: acraccesstokens.generators.external-secrets.io
spec:
  group: generators.external-secrets.io
<...>
```

**Observations (Constraints, Context, etc):**

So the problem is a very thin line between how the Gitops tool manages the Helm release and how ESO chart deploys its CRDs which need to be templated to allow the CRDs conversion

**Comment by moolen** [comment]
Hey, thanks for bringing this up, this is closely related to #1965 to allow interop with cert-manager. I have something on an old branch, let me dig this up.
