### ISSUE TITLE
serviceMonitor problem upgrading helm chart to v0.8.0

### ISSUE THREAD

**Issue by onedr0p** [external-secrets/external-secrets#2135]
Hi, 👋 

I just tried upgrading to the external secrets helm chart v0.8.0.

I'm using Flux and my helm deployment is here:

https://github.com/onedr0p/home-ops/blob/f197c0cc1160bbe92190550ec6013258e6ba7bcc/kubernetes/apps/kube-system/external-secrets/app/helmrelease.yaml

Error:

```
Helm upgrade failed: error while running post render on files: may not add resource with an already registered id: ServiceMonitor.v1.monitoring.coreos.com/external-secrets-cert-controller-metrics.kube-system
```

**Comment by onedr0p** [comment]
Looks like you combined all the servicemonitors into one file but forgot to delete the separate files.

https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/templates/cert-controller-servicemonitor.yaml

https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/templates/webhook-servicemonitor.yaml

If installing with the helm chart and enabling servicemonitors, rhe chart is broken.

**Comment by gusfcarvalho** [comment]
fixed in #2136

**Comment by gusfcarvalho** [comment]
hey @onedr0p ! please confirm if 0.8.1 fixed this bug. Tried locally here, but I have a limited understanding of ServiceMonitor per se :)

**Comment by onedr0p** [comment]
It's working here, thanks!
