### ISSUE TITLE
Add SecretStore and ClusterSecretStore status metrics 

### ISSUE THREAD

**Issue by creosonic** [external-secrets/external-secrets#2151]
**Describe the solution you'd like**

Would you please add _SecretStore_ and _ClusterSecretStore_ status prometheus metrics similar to the _externalsecret_status_condition_ metric?

**What is the added value?**

It would improve observability capabilities related to the secret stores status check.

Thank you!

**Comment by shuheiktgw** [comment]
Let me see if I could implement it 🙂
