### ISSUE TITLE
Will external secrets operator automatically refresh Vault AppRole Auth token?

### ISSUE THREAD

**Issue by data-race** [external-secrets/external-secrets#2163]
Hi folks. I am using hashicorp vault as external secrets operator's backend. External secrets operator uses AppRole authentication method to access Vault. 
Since  external secrets operator gets token using `roleId` and `secretId`, will external secrets operator automatically refresh the token?
Thanks!  Looking forward to your reply.

**Comment by moolen** [comment]
Hey :wave:

No, ESO does not refresh the token, it requests a token using `roleId` and `secretId`. If the appRole credentials expire ESO is not able to request a new token.
If you want to use short-lived credentials for ESO consider using [Kubernetes auth](https://external-secrets.io/v0.8.1/provider/hashicorp-vault/#kubernetes-authentication).

**Comment by data-race** [comment]
@moolen Thanks very much!

**Comment by data-race** [comment]
@moolen Hey.  I think I didn't make it clear. What if the `roleId` and `secretId` do not expire, but the token requested expires? Will ESO request new token?

**Comment by data-race** [comment]
I see. Thanks a lot!
