### ISSUE TITLE
Do not update/create Secret if deletionTimestamp is set on ExternalSecret

### ISSUE THREAD

**Issue by borgotta** [external-secrets/external-secrets#2176]
**Describe the solution you'd like**
Describe the end goal of this proposal. What is this new functionality or the new behaviour (or what problem does it fix)? 
Skip updates and creations of Secrets when deletionTimestamp is set on ExternalSecrets. 

**What is the added value?**
We will avoid indefinite loops of creating Secret that k8s GC is trying to delete. See example of the same issue by CertManager[1].

**Our case**

So it happens that we use ExternalSecrets in our Helm chart and deploy it with ArgoCD. Some of them are in helm hooks[2], so by syncing new release ArgoCD has to delete old hooks. Argo uses foreground mode for deletion[3]. Using this strategy it firsts marks ExternalSecret with deletionTimestamp attribute and a finalizer:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  ...
  deletionTimestamp: '2023-03-23T11:22:57Z'
  finalizers:
    - foregroundDeletion
```
After that k8s generic garbage collector kicks in. It first deletes Secret, because it has owner reference of parent ExternalSecret. Before GC gets to the ExternalSecret, our controller manages to recreate Secret, making it impossible to delete ES.

As a side note, I noticed this behaviour only when we added some kyverno policies. My guess is that it made some internal processes slower (including GC).

**App versions**
ExternalSecrets: 0.8.1
ArgoCD: 3.29.5

**What to do**
Kubebuilder documentation has a page on the topic[4]. However, I think adding a finalizer would be an overkill, I suggest adding logic for checking for set deletionTimestamp in Reconcile method. Something like: 
```go
if !cronJob.ObjectMeta.DeletionTimestamp.IsZero() {
    // Stop reconciliation as the item is being deleted
    return ctrl.Result{}, nil
}
```

1. https://github.com/cert-manager/cert-manager/issues/5866
2. https://v2.helm.sh/docs/charts_hooks/
3. https://kubernetes.io/docs/tasks/administer-cluster/use-cascading-deletion/#use-foreground-cascading-deletion
4. https://book.kubebuilder.io/reference/using-finalizers.html

**Comment by moolen** [comment]
Hey @borgotta, thanks for this report! Sure, feel free to work on it :heart:

**Comment by markuslackner** [comment]
Stumbled over the same problem today :-) Same setup (kyverno with argocd). Are there any news regarding the bug fix or is there a known workaround? Thx!
