### ISSUE TITLE
Generator double-refresh and missed refreshInterval

### ISSUE THREAD

**Issue by kristian-lesko** [external-secrets/external-secrets#2184]
**Problem description**
Hello there, I've noticed that when using a `Generator` (specifically, `VaultDynamicSecret`), the `refreshInterval` is sometimes not respected by external-secrets.

Sometimes, two renewals are done in a rapid succession, and the next renewal is then skipped. This poses a problem in case the dynamic credential in question is not valid long enough.

To give an example, these are the observed timestamps of secret renewals with `refreshInterval: 50m`:
```
2023-03-29T11:32:05.274487914Z
2023-03-29T12:22:07.222411091Z
2023-03-29T12:22:08.850840252Z  # double renew
2023-03-29T13:42:32.713098545Z  # twice the interval gap since previous renew
2023-03-29T14:52:09.17733245Z
2023-03-29T15:42:11.163154993Z
2023-03-29T16:32:12.679528211Z
2023-03-29T17:22:14.215748633Z
```

**Observations (Constraints, Context, etc):**
Looking at renewal logs for a **static** credential (ie. regular `SecretStore` with `vault` provider), the interval always seems to be respected; as far I can say, then, this looks like a problem specific to the `Generator` use case.

The workaround seems to be to use a `refreshInterval` **shorter than half the dynamic secret's validity** (e.g., for GitHub tokens valid for 60 minutes, using `refreshInterval: 29m` might help mitigate this). I'll be glad for any advice and/or a proper solution, though. Thanks a lot 🙂

**Comment by moolen** [comment]
For a better understanding: how did you get the following data?
Are those reconciliation timestamps from logs or `.status.refreshTime` timestamps?

```
2023-03-29T11:32:05.274487914Z
2023-03-29T12:22:07.222411091Z
2023-03-29T12:22:08.850840252Z  # double renew
2023-03-29T13:42:32.713098545Z  # twice the interval gap since previous renew
2023-03-29T14:52:09.17733245Z
2023-03-29T15:42:11.163154993Z
2023-03-29T16:32:12.679528211Z
2023-03-29T17:22:14.215748633Z
```

1. i'm wondering what would cause that double reconciliation :thinking:: If you change the `metadata` or `spec`, then this will cause a reconciliation (do you use argo, flux or any other gitops tools?).
2. even if its double reconciling it won't do a full sync, instead will requeue the reconciliation request

But: If you restart the controller at `t+49m` with `refreshInterval=50m` it will be reconciled at `t+99m`. I would consider this a bug, this shouldn't be the case:

https://github.com/external-secrets/external-secrets/blob/4d420d498a8bea8504f7cc594d848ad091b83357/pkg/controllers/externalsecret/externalsecret_controller.go#L173-L179

I guess the requeueAfter should be the time difference between now and last sync, not the static `spec.refreshInterval`. That way we get a better guarantee of reconciling it.

**Comment by kristian-lesko** [comment]
Hello @moolen,

The timestamps actually come from our Vault; these are the times when `external-secrets` requested a secret value. We do use Flux to deliver the ExternalSecret definition.

Additionally, I can confirm that when using a `refreshInterval` of less than half the secret's validity (currently, 29 minutes vs. 60 minutes secret TTL), all is fine and the Secret always contains a valid dynamic secret value 👍

**Comment by moolen** [comment]
> We do use Flux to apply the ExternalSecret definition.

I guess this could be the cause of the double reconciliation. Flux does a diff and applies changes if there is a difference.

What could lead to a difference (seen this in the past in context with ArgoCD) is the `refreshInterval`.

As a user you typically set it to a human readable value: `1h` which is also the default you would think.
Depending on how the de/serialisation is done the value could also be `1h0m0s` which is the same value but represented differently. That small difference could cause flux to apply the difference.

That's just a shot in the dark, it's hard to tell from a distance. It's probably best to dig in the audit logs who changed what. At least the workaround is working :smiley:

**Comment by mloskot** [comment]
I'm observing something similar and posted a complete reproducible story here
- https://github.com/external-secrets/external-secrets/discussions/2402

Perhaps my case is related to this issue.
