### ISSUE TITLE
New provider integration for passbolt

### ISSUE THREAD

**Issue by bakito** [external-secrets/external-secrets#2188]
**Describe the solution you'd like**
It would be nice if [passbolt](https://www.passbolt.com/)  could be used as an additional provider for external secrets.

**What is the added value?**
Secrets could be intecrated from passbolt.

**Observations (Constraints, Context, etc):**
Passbolt provides a go client libraty that can be used.
https://github.com/passbolt/go-passbolt

**Comment by egandro** [comment]
Using a webhook and  the go-passbolt-cli source looks really a simple (generic) way to go.

https://external-secrets.io/v0.8.1/provider/webhook/

The pain in the behind is now - making this setup.

- GPG key
- User
- Password
- BasicAuth User
- BasicAuth Password
- https (optional)

It would be much better if passbolt had this under the hood.

**Comment by bakito** [comment]
@egandro I create a passbolt feature request here: https://community.passbolt.com/t/as-a-sre-id-like-to-be-able-to-use-secrets-from-passbolt-in-the-external-secrets-operator-for-kubernetes/7065

**Comment by egandro** [comment]
@bakito willing to jump in, if I get help. 

The webhook looks nice but it's will create yet another docker image with secrets inside :) so I hope external secrets can do a direct implementation.

**Comment by egandro** [comment]
Any progress here? :)

**Comment by egandro** [comment]
Any progress? :)

**Comment by bakito** [comment]
Not from my side
