### ISSUE TITLE
Missing bitwarden example

### ISSUE THREAD

**Issue by titilambert** [external-secrets/external-secrets#2221]
**Describe the solution you'd like**

I just saw that the Bitwarden example is not listing in the example menu: https://external-secrets.io/v0.8.1/examples/gitops-using-fluxcd/

**What is the added value?**
Add a new example about how to support Bitwarden.

**Give us examples of the outcome**
We should see the content of: https://github.com/external-secrets/external-secrets/blob/main/docs/examples/bitwarden.md

**Observations (Constraints, Context, etc):**
I can see Bitwarden entry in the menu: : https://github.com/external-secrets/external-secrets/blob/main/hack/api-docs/mkdocs.yml#L106
So I guess something else is missing… I just don't know what.

**Comment by gusfcarvalho** [comment]
Hi @titilambert . This is just because we did not release 0.8.2. You can already check the docs in https://external-secrets.io/main/examples/gitops-using-fluxcd/
