### ISSUE TITLE
Implement the `controllerClass` on `VaultDynamicSecret` resources

### ISSUE THREAD

**Issue by fad3t** [external-secrets/external-secrets#2224]
Hello,

Similar to [2164](https://github.com/external-secrets/external-secrets/issues/2164), it seems there's currently no implementation of the controllerClass on `VaultDynamicSecret` resources.

This causes all instances of ESO installed on a cluster to attempt the reconciliation of the dynamic secret, while we would like to restrict this to a specific instance (using a `controllerClass`).

Any chance this gets to the roadmap?

Thanks!

**Comment by moolen** [comment]
Hey @fad3t, thanks for raising this! I agree, this should be possible. 

Though at the moment we want to focus on getting the existing v1beta1 SecretStore/ExternalSecret resources to GA. But if someone wants to pick up this issue feel free to, i'd be happy to review a PR :+1:

**Comment by rdeepc** [comment]
Hi @moolen, 

I would like to pick up this one. Thanks

**Comment by fad3t** [comment]
Hi @rdeepc, thanks!
I actually started looking at this, cf. https://github.com/fad3t/external-secrets/commit/ca8ea2c1ac1680f543a6470f97246b7ff64dbff6.
I was about to ask for some guidance (about proper logging and testing) but you might now how to better do this.
Let me know if there's anything I can help with.

**Comment by rdeepc** [comment]
Hi @fad3t,

You got a great start on that, I will add my changes with that and then we can review that, Thanks
