### ISSUE TITLE
Using Azure user managed identity that is not added as a VMSS identity fails 

### ISSUE THREAD

**Issue by jonasnorlund** [external-secrets/external-secrets#2235]
**Describe the solution you'd like**
Be able to use Azure User Managed Identities as workload identities in AKS that is not added to the identity of the VMSS for AKS. 

Today it's possible to use Azure User Managed Identities (=UMI) as workload identities to authenticate (using Azure RBAC) against multiple Azure services (= such as Azure SQL or AKV). This does not require the UMI to be added to the list of identities of the VMSS that AKS runs on top of. 

**What is the added value?**
In a multi tenant scenario or when the kubelet identity is not used to authenticate against AKV the UMI that is used for the workload identity must be added to the VMSS identity. Often in multi tenant scenarios this UMI resides outside of the context of AKS, could be in another subscription that is not managed by the AKS team. By removing this dependency it gets easier to use external secrets provider in multi tenant scenarios.   

**Observations (Constraints, Context, etc):**

When the UMI isn't added to the VMSS identity then the following error occurs.

{"level":"error","ts":1681828447.7208967,"logger":"controllers.ExternalSecret","msg":"could not get secret data from provider","ExternalSecret":"team-a/demo-secret","error":"azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://akv-xxxx.vault.azure.net/secrets/demo-secret/?api-version=2016-10-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"**Identity not found**\"} Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&client_id=xxxxxx-xxxx-xxxx-xxxx-xxxxxxx&resource=https%3A%2F%2Fvault.azure.net","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:190\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.1/pkg/internal/controller/controller.go:235"}

**Comment by gusfcarvalho** [comment]
Sorry @jonasnorlund, can you share your manifests and the eso version you are using?

Can you also share how are you configuring azwi?

**Comment by jonasnorlund** [comment]
Hi, I'm using eso version v0.7.2

I'm using bicep to setup the wli in Azure.  

`
resource federate 'Microsoft.ManagedIdentity/userAssignedIdentities/federatedIdentityCredentials@2022-01-31-preview' = {
name: 'fe-umi-wli-${name}'
  parent: umi
  properties: {
    audiences: [
      'api://AzureADTokenExchange'
    ]
    issuer: aksIssuerURL
    subject: 'system:serviceaccount:${name}:sa-wli'
  }
}
`

 
Below are the manifests. 

apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx 
  labels:
    azure.workload.identity/use: "true"
  name: sa-wli


apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: akv-team-a
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      identityId: "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx" 
      vaultUrl: "https://xxxxxxxxxx.vault.azure.net"
      serviceAccountRef:
        name: sa-wli

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: akv-team-a
  target:
    name: demo-secret
  data:
  -secretKey: demo-secret
    remoteRef:
      key: demo-secret

**Comment by gusfcarvalho** [comment]
Im not sure if your OIDC setup is correct. Did you try to deploy azure test workload as in here? https://azure.github.io/azure-workload-identity/docs/quick-start.html#7-deploy-workload 

Can you get the secret information with it?

**Comment by jonasnorlund** [comment]
Yes it works fine even if I don't have the UMI in the VMSS identity. 

I0419 06:53:17.295485       1 main.go:63] "successfully got secret" secret="This-is-my-WorkloadIdentity-Secret"

**Comment by moolen** [comment]
I'm not familiar with using Azure User Managed Identities as workload identities, can you point me to the docs where both things are used together?

I see you're using `authType: ManagedIdentity`, did you try it with `authType: WorkloadIdentity`?
Can you share the details/code on how to set it up so we can reproduce this?

**Comment by moolen** [comment]
Glad to hear it worked :+1: :smiley:
