### ISSUE TITLE
Verify stacking of unconfirmed like loops 

### ISSUE THREAD

**Issue by 812142** [external-secrets/external-secrets#2238]
**Describe the solution you'd like**
Describe the end goal of this proposal. What is this new functionality or the new behaviour (or what problem does it fix)? 

**What is the added value?**
Explain the value that it adds. e.g. "Secret refreshing will make internal secrets up to date with external secrets".

**Give us examples of the outcome**

Provide templates if you are proposing changes in the CRD. Provide example workflows or code snippets if they make sense to present.

**Observations (Constraints, Context, etc):**

Give here all extra information that could be interesting. Such as Golang version and Kubernetes version if you are reporting a bug/problem. You can also foresee technical constrains like "this could only be implementing using this specific technology or approach, because of this and that".

**Comment by gusfcarvalho** [comment]
Hi @812142 ! Can you provide more information please?

**Comment by gusfcarvalho** [comment]
I'm closing this issue. Feel free to reopen it with further context.
