### ISSUE TITLE
"getAllSecrets" from AWS Secret Manager and instead store them in separate ExternalSecret objects

### ISSUE THREAD

**Issue by drewwaranissonos** [external-secrets/external-secrets#2243]
**Describe the solution you'd like**

I'm reading through https://external-secrets.io/v0.8.1/guides/getallsecrets/ and I was wondering if it is possible to do something similar:

"getAllSecrets" from AWS Secret Manager, but instead store them in separate `ExternalSecret` objects instead of as keys in a single `ExternalSecret` object.

**What is the added value?**

We need this so that https://jenkinsci.github.io/kubernetes-credentials-provider-plugin/ can pick-up the (generated) Kubernetes Secret objects separately and make them available to Jenkins jobs.

**Give us examples of the outcome**

Standard `ExternalSecret` objects that we can map Jenkins Kubernetes Credentials Provider Plugin compatible labels and annotations into from the AWS Secrets Manager.

**Observations (Constraints, Context, etc):**

Preferably we want to be able to key off of the name pattern or metadata tags, but we can probably handle that with a `SecretStore` IAM role if needed.

We have a backup plan where we have scripts and templates that can generate an external secret per AWS Secrets Manager secret, but that is a lot of cruft that would require a lot of upkeep when external secrets are added or removed.

ETA: Just found https://github.com/external-secrets/external-secrets/issues/1509#issuecomment-1292444834 . 
ETA2: If I'm reading it right, that example doesn't actually do what it says it does.

Thank you!

**Comment by gusfcarvalho** [comment]
Hi @drewwaranissonos! Unfortunately, it is not possible to create multiple kubernetes secrets from the same ExternalSecret. you can still achieve the same by having a templating tool like helm to generate your manifests in a more dynamic way, though. I hope that helps a little bit.

**Comment by drewwaranissonos** [comment]
Thank you for the confirmation! That's the way we are going. Closing out.
