### ISSUE TITLE
ACR Pull Generator not functioning

### ISSUE THREAD

**Issue by mfacenet** [external-secrets/external-secrets#2244]
When using the ACR generator we see errors like this:

> AADSTS500011: The resource principal named https://xxx.azurecr.io/ was not found in the tenant named 0f44c5d4- 42b0-45c2-bf55-xxxxx. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
>          Trace ID: be41f73b-ca74-4535-852b-xxxxx
>         Correlation ID: 4932d5b7-41de-4a2e-9add-xxxxx
>          Timestamp: 2023-04-20 19:59:54Z

I believe this bug is related to the service call here:
https://github.com/external-secrets/external-secrets/blob/main/pkg/generator/acr/acr.go#L168
matching that against the MS documentation that URL is not well formed as 
https://learn.microsoft.com/en-us/rest/api/containerregistry/access-tokens/get?tabs=HTTP
or against the v2 api
https://learn.microsoft.com/en-us/rest/api/containerregistry/registries/regenerate-credential?tabs=HTTP

Based on what I read I would assume that the service in question should be registry.azurecr.io or just registry and not include https:// / on it, however I may be mistaken.

**Comment by moolen** [comment]
Hey, could you please share your yaml manifests?

**Comment by moolen** [comment]
> Based on what I read I would assume that the service in question should be registry.azurecr.io or just registry and not include https:// / on it, however I may be mistaken.

It must be the unique name of your registry, e.g. `contosoregistry.azurecr.io` from the example, see here: https://github.com/Azure/acr/blob/main/docs/AAD-OAuth.md#calling-post-oauth2exchange-to-get-an-acr-refresh-token

It shouldn't include http[s] AFAIK. Coud you try that out? It's hard to tell where the issue is without having the manifests.

**Comment by mfacenet** [comment]
`---
apiVersion: generators.external-secrets.io/v1alpha1
kind: ACRAccessToken
metadata:
  name: acr-pull-secret
spec:
  tenantId: 0f44c5d4-42b0-xxxxxx
  registry: xxxacr.azurecr.io
  environmentType: PublicCloud
  auth:
    workloadIdentity:
      serviceAccountRef:
        name: external-secrets-azure
        audiences: []`

**Comment by mfacenet** [comment]
> > Based on what I read I would assume that the service in question should be registry.azurecr.io or just registry and not include https:// / on it, however I may be mistaken.
> 
> It must be the unique name of your registry, e.g. `contosoregistry.azurecr.io` from the example, see here: https://github.com/Azure/acr/blob/main/docs/AAD-OAuth.md#calling-post-oauth2exchange-to-get-an-acr-refresh-token
> 
> It shouldn't include http[s] AFAIK. Coud you try that out? It's hard to tell where the issue is without having the manifests.

I've attached the manifest, I should have done so originally, however, the name has never included https:// or any uri base, that gets prepended here: https://github.com/external-secrets/external-secrets/blob/81b9546e0fa9dcef3f4697260270be5114aa76bf/pkg/generator/acr/acr.go#L236

**Comment by moolen** [comment]
How did you set up Azure Workload Identity (azwi? manually?)? 

Does workload identity work, e.g. by creating a pod using the serviceAccount, and does it provide you the correct permissions?

**Comment by mfacenet** [comment]
> How did you set up Azure Workload Identity (azwi? manually?)?
> 
> Does workload identity work, e.g. by creating a pod using the serviceAccount, and does it provide you the correct permissions?

This is on an AKS cluster, so Azure has managed the webhook and the OIDC config, WI does work and the managed identity here is used to also fill in a clustersecretstore that we've validated.  The identity was provisioned using terraform, the federation was manual.

**Comment by moolen** [comment]
I took a look at this, it seems it is broken. The Problem is that we're not able to acquire the initial aad access token via workload identity.
Trying to get an access token for scope `xxx.azurecr.io` gets rejected by Azure Active Directory. I tried a couple of things but couldn't get to the bottom of it.

Any help appreciated here :pray:

**Comment by yuriolisa** [comment]
@moolen, could you please assign ti to me?

**Comment by flash-me** [comment]
This is still an open issue.

cheers
flash ⚡
