### ISSUE TITLE
Allow syncing to be temporarily disabled to manual edit the managed Secret

### ISSUE THREAD

**Issue by jutley** [external-secrets/external-secrets#2245]
**Describe the solution you'd like**
Describe the end goal of this proposal. What is this new functionality or the new behaviour (or what problem does it fix)? 

Any automated syncing solution has the potential to get in the way. In my case, I have ExternalSecrets deployed across all my Kubernetes that all read from the same source. I would like to make some direct changes to the Secret for the sake of testing in a single cluster, but this doesn't seem to be possible.

I updated the ExternalSecret in my test cluster to use `refreshPolicy: '0'` (as well as a very large value) thinking that this would disable refreshes as described in the docs. I imagine this works in terms of periodic refreshes, but when I directly update the managed Secret, this seems to trigger a refresh and my changes are removed.

**What is the added value?**

Supporting this will allow for debugging use cases without having to redefine how we organize our sensitive data.

**Give us examples of the outcome**

```
kubectl edit externalsecret foo
# manually set refreshInterval: '0'

kubectl edit secret foo
# manually make changes
# changes won't get overwritten

kubectl edit externalsecret foo
# manually remove refreshInterval: '0'
```

**Observations (Constraints, Context, etc):**

We are using External Secrets Operator v0.7.2 (but I don't see any relevant changes in the CHANGELOG between this and latest (v0.8.1). Kubernetes is on v1.26.4. We are using AWS SecretsManager as our data source.

**Comment by gusfcarvalho** [comment]
this happens because with the default behavior of `creationPolicy: Owner`, we also watch for any Child secret changes. If you want for any reason to change secret values, you need to set `creationPolicy: Merge` or `creationPolicy: Orphan`.


You can check how these different policies work in here: https://external-secrets.io/v0.8.1/guides/ownership-deletion-policy/

**Comment by jutley** [comment]
Ah, thank you for the insight. I hadn't considered looking at the creationPolicy field for this behavior, but it does make sense. I'll go ahead and close this issue. Hopefully if anyone else runs into this they can find this thread!
