### ISSUE TITLE
Implement native Opentelemetry tracing in the project

### ISSUE THREAD

**Issue by knelasevero** [external-secrets/external-secrets#2264]
Similar to so many other projects: https://github.com/kyverno/kyverno/blob/9b41e2e0174c10b3548a5364e205911d6a0047c7/pkg/tracing/tracing.go

Improve observability of the project by implementing OpenTelemetry tracing.

**Comment by yuriolisa** [comment]
Could you please assign to me?

**Comment by yuriolisa** [comment]
- [ ] Create a standard for constants.
- [ ] Switch metrics folder from pkg/provider to pkg/.
- [ ] Create tracing pkg.

**Comment by 812142** [comment]
How do I assign to you?

**Comment by yuriolisa** [comment]
I'm implementing the tracing package and I'd like to hear any thoughts regarding the following approach: 

- The tracing package will implement an OTLP(OpenTelemetry Protocol.) exporter interface, which will handle the traces transforming to be delivered to the OTEL(OpenTelemetry) Collector.
- I have to implement a way to pass the CRDS to the OpenTelemetry Collector's URL. It can be implemented by creating a new field on CRDS to load environment variables or reading from a ConfigMap. 

@knelasevero , @gusfcarvalho, @moritzjohner-form3.

**Comment by moolen** [comment]
Sounds good to me!

> implement a way to pass the CRDS to the OpenTelemetry Collector's URL

I think i don't have enough context for this one. If i understand it right, this is the way to tell ESO where to send the traces to, right? Why do we need this per-CRD? Wouldn't it be enough to define one endpoint globally for all CRDs? Like with an CLI arg for the eso controller or webhook?

**Comment by knelasevero** [comment]
What do you mean by "passing the crds to OTL"? Do you have an example from any other repository?

**Comment by moolen** [comment]
IMO it would be a good start to have it global and add CRD-level tracing later if there's a need from users for it. Unless you have a immediate need for it i suggest to keep it simple.

**Comment by yuriolisa** [comment]
> What do you mean by "passing the crds to OTL"? Do you have an example from any other repository?

The otlptrace package implements an approach to set the variables related the to OpenTelemetry Collector, like [OTEL_EXPORTER_OTLP_ENDPOINT](https://pkg.go.dev/go.opentelemetry.io/otel/exporters/otlp/otlptrace#section-readme:~:text=protobuf%2Dencoded%20payloads.-,Configuration,-Environment%20Variables). I've proposed this because the way Kyverno implements the trace package is deploying a specific Collector on the same namespace, which doesn't need to be configured by environment variables.
