### ISSUE TITLE
Update/sync secret when kubectl apply or helm upgrade

### ISSUE THREAD

**Issue by adovy** [external-secrets/external-secrets#2266]
**Describe the solution you'd like**
Update the secret when doing the release (kubectl apply, helm upgrade)

**What is the added value?**
Updating the secrets automatically will make the releases easier

**Give us examples of the outcome**

Maybe it could be new `creationPolicy`, i.e. **Recreate**

**Observations (Constraints, Context, etc):**

When doing the release we would like to that external-secrets would sync the secret from the provider

**Comment by gusfcarvalho** [comment]
You can simply achieve that by adding an annotation to your helm package that contains your externalSecrets. This way, your helm upgrade will automatically trigger a reconcile loop.
