### ISSUE TITLE
Help finding a way to store Etags between requests

### ISSUE THREAD

**Issue by mrasnake-doppler** [external-secrets/external-secrets#2267]
**Describe the solution you'd like**

Hello, I am a New Contributor looking to improve to the Doppler provider sub-package. My main goal is to find a place to store the ETag between requests so that it can be provided in subsequent request calls.

**What is the added value?**

Passing ETags provides a reference to what secrets have already been retrieved and wether there are any changes. Instead of pulling all of the secrets with every call (which can get expensive and time consuming). This would allow the api to respond with 304 - "no change" when appropriate and save significant compute time. 

PS would like to Label: "Help wanted" and "Good first Issue" but I do not believe I have the permissions.

**Comment by gusfcarvalho** [comment]
Im not sure if there is an easy (or any) solution to that problem, as the provider code (and the client beneath it) could eventually be called concurrently for multiple different contexts.

if doppler package supports it, this could be just a simple internal variable to the client.

**Comment by gusfcarvalho** [comment]
I added good first issue label. Help wanted label are to flag things that need help to be implemented, which does not seem to be the case here 😁
