### ISSUE TITLE
base64 conversion issue

### ISSUE THREAD

**Issue by sam-germany** [external-secrets/external-secrets#2272]
![r45](https://user-images.githubusercontent.com/66065583/235265398-4f6c838d-a414-46b6-8ad0-23386d833bd4.png)

we are doing till now this type of conversion, but with this new version i am not able to achive this conversion, can you please help me to solve this issue

**Comment by gusfcarvalho** [comment]
You need to change your templating to the new format, using the b64dec helper function. You can check some examples in here: https://external-secrets.io/v0.8.1/guides/templating/

**Comment by sam-germany** [comment]
the main issue is that with the new external secret operator we are not alloweed to use " stringData:"  key, is their is any workaround to get the same result ?

**Comment by gusfcarvalho** [comment]
You don’t need to use stringData. Just use data and it will work.

**Comment by sam-germany** [comment]
![e43](https://user-images.githubusercontent.com/66065583/235457779-a5242bc0-ce5c-4a7f-8046-2c09cf1f46bf.png)


No it is not giving the expected restult, you can check, this externalsecret create a secret but when we do a base64 encode it return "<%= Buffer.from(data.s1, "base64").toString("ascii") %>"   , it is not converting the .jks key

**Comment by gusfcarvalho** [comment]
as I referenced in the guide, the templating language is different. You need to change the templating language to the new format.
