### ISSUE TITLE
Error with external-secrets, ArgoCD, kustomize, and custom Namespace

### ISSUE THREAD

**Issue by honahuku** [external-secrets/external-secrets#2273]
**Describe the solution you'd like**
To be able to use external-secrets with ArgoCD and kustomize without encountering the stat /tmp/certs/tls.crt: no such file or directory error, while using a custom Namespace and deploying SecretStore in the same Application as external-secrets.

**What is the added value?**
By solving this issue, users will be able to manage external-secrets using ArgoCD and GitHub with a code-based approach and deploy it more flexibly with kustomize.

**Give us examples of the outcome**
The ideal outcome would be the following configuration working without any errors:

ArgoCD refers to user-defined manifests instead of Helm
kustomization.yaml in the referenced directory specifies helmCharts
SecretStore is deployed in the same Application as external-secrets
A custom Namespace is used
You can refer to the following manifests as examples:

[external-secrets](https://github.com/honahuku/manifest/tree/1a237415446350e3da512379f389a38f8a3ea883/external-secrets)
[application](https://github.com/honahuku/manifest/blob/1a237415446350e3da512379f389a38f8a3ea883/root/application.yaml)

**Observations (Constraints, Context, etc):**
The full error message is as follows. This occurred in external-secrets-webhook:

```text
{"level":"info","ts":1682764719.5310128,"logger":"setup","msg":"validating certs"}
{"level":"error","ts":1682764719.5310957,"logger":"setup","msg":"invalid certs. retrying...","error":"stat /tmp/certs/tls.crt: no such file or directory","stacktrace":"github.com/external-secrets/external-secrets/cmd.waitForCerts\n\t/home/runner/work/external-secrets/external-secrets/cmd/webhook.go:188\ngithub.com/external-secrets/external-secrets/cmd.glob..func3\n\t/home/runner/work/external-secrets/external-secrets/cmd/webhook.go:82\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968\ngithub.com/external-secrets/external-secrets/cmd.Execute\n\t/home/runner/work/external-secrets/external-secrets/cmd/root.go:221\nmain.main\n\t/home/runner/work/external-secrets/external-secrets/main.go:21\nruntime.main\n\t/opt/hostedtoolcache/go/1.19.7/x64/src/runtime/proc.go:250"}
```

The versions of the tools and applications are as follows:

Argo CD v2.6.7
Go Version go1.18.10
kustomize v4.5.7
Helm v3.10.3
kubectl v0.24.2
K8s Rev: v1.21.5+k3s2

Additionally, this issue may be related to the following issues:

https://github.com/external-secrets/external-secrets/issues/997
https://github.com/external-secrets/external-secrets/issues/1026

**Other information:**
I have found two methods to address this issue:

1. Change the Namespace to default
[external-secrets](https://github.com/honahuku/manifest/tree/51a6e5e829d562b297e826c4ee8f56841cb3da3b/external-secrets)

1. Use Helm directly in ArgoCD instead of Kustomization

Relevant part in application.yaml
https://github.com/honahuku/manifest/blob/519a7edac82545248f86d6e1f06e2bad70753a3d/root/application.yaml#L163-L203

However, with the second method, there is an issue where the SecretStore cannot be deployed in the same Application as external-secrets. To address this, I created a new Application called config and deployed the SecretStore there. But I feel this is not the best solution.

On the other hand, the first method has the problem of not being able to use a custom Namespace. Is there any better solution available?

**Comment by gusfcarvalho** [comment]
Hi @honahuku ! your kustomization that you posted is also using helmCharts. Is this intended?

I do not see why this issue would be happening. You should be possible to just have a kustomization layer on top of our manifests to change the namespaces appropriately.

> However, with the second method, there is an issue where the SecretStore cannot be deployed in the same Application as external-secrets. To address this, I created a new Application called config and deployed the SecretStore there. But I feel this is not the best solution.

This issue is inherent with helm charts, since we template our CRDs to inject the webhook configuration. If you're not running on `v1alpha1` resources, what you can do simply is add these flags:

```
--set webhook.create=false
--set certController.create=false
--set crd.conversion.enabled=false
```

**Comment by honahuku** [comment]
Thanks for the suggested solution!
I'm currently working on it, so please bear with me for a bit.

**Comment by honahuku** [comment]
Hello, @gusfcarvalho!

I understand that you intentionally included helmCharts in your kustomize.  
To make the situation clearer, please take a look at the diff between these two commits:  
[before-applying-webhook-disabling...after-applying-webhook-disabling](https://github.com/honahuku/manifest/compare/before-applying-webhook-disabling...after-applying-webhook-disabling)

The only change I made here is adding the values to disable the creation of the webhook, as you suggested.  
In the commit tagged [before-applying-webhook-disabling](https://github.com/honahuku/manifest/tree/before-applying-webhook-disabling/external-secrets), an error occurs in `external-secrets-webhook`, and external-secrets cannot be used, as I mentioned before.  
In the commit tagged [after-applying-webhook-disabling](https://github.com/honahuku/manifest/tree/after-applying-webhook-disabling/external-secrets), `external-secrets-webhook` is disabled, so no error occurs and it can be used.

I was able to resolve the issue using your suggested method. However, I'm still curious why disabling the `external-secrets-webhook` makes it work, and whether the `external-secrets-webhook` itself doesn't cause any problems with the functioning of external-secrets.
Additionally, if it's okay with you, I'd like to add documentation on how to use external-secrets with a combination of ArgoCD and kustomize. May I send a pull request?

**Comment by DpoBoceka** [comment]
I'm having exactly the same issue.
Isn't disabling ValidatingWebhookConfiguration an undesirable thing? Can this compromise be addressed somehow in a helm template?

**Comment by moolen** [comment]
Just setting the namespace on all resources is not enough, you'll also need to set some cli args like here: 
https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/templates/cert-controller-deployment.yaml#L54

There's probably more, just as a hint

**Comment by yehoshuadimarsky** [comment]
I have the same issue, super frustrating. Any luck?

**Comment by gusfcarvalho** [comment]
hi @yehoshuadimarsky. Did the workarounds stated above not work for your use case?

**Comment by cameronraysmith** [comment]
@gusfcarvalho, which complete set of workarounds would you currently recommend based on the complete history of this discussion?

Still https://github.com/external-secrets/external-secrets/issues/2273#issuecomment-1529141991 alone, or something else?

**Comment by mtrin** [comment]
you need to specify the namespace for the helm generator as well because the non-kubernetes settings:
```
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: custom-ns
helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io/
    version: 0.9.13
    releaseName: external-secrets-operator
    namespace: custom-ns
    includeCRDs: true
```
the above deployed ok for me

**Comment by SergeyMuha** [comment]
I also faced this issue `"level":"info","ts":1748361852.8796685,"logger":"setup","msg":"validating certs"}
{"level":"error","ts":1748361852.879976,"logger":"setup","msg":"invalid certs. retrying...","error":"stat /tmp/certs/tls.crt: no such file or directory`
and after some investigation I found the root cause.

Webhook works with tls and you have to generate it. Helm chart creates   external-secrets-webhook Secret but if you disable certController this secret will have no data. That is why you see "error":"stat /tmp/certs/tls.crt: . Because secret is empty.

So if you want to use webhook for security reason you have to enable certController. Or you can use certmanager instead
https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/values.yaml#L329
