### ISSUE TITLE
Add cluster variable to Grafana dashboard

### ISSUE THREAD

**Issue by sagikazarmark** [external-secrets/external-secrets#2294]
**Describe the solution you'd like**

[Default Kubernetes dashboards](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14) (that come with kube-prometheus-stack) have a `cluster` variable to account for multi-cluster installations.

Add it to the official ESO dashboard to account for multi-cluster installations.

**What is the added value?**

It will make cluster available as a filter (if any). Transparent if data is only scraped from a single cluster (or the cluster label is not set)

**Give us examples of the outcome**

It's sometimes beneficial to see if a certain issue affects multiple clusters, but most of the cases we just want to get an overview of a single installation. By adding this option, in multi-cluster scenarios users can filter external-secrets instances per cluster.

**Comment by ttradesman** [comment]
I love that a Grafana dashboard is provided with the helm chart, but it would indeed be great to support the cluster variable.
