### ISSUE TITLE
Deleted externalsecrets still have metrics exported

### ISSUE THREAD

**Issue by gabrielbatir** [external-secrets/external-secrets#231]
I was trying to figure out some alerting rules based on the metrics exported by the external secrets operator and I noticed that if I delete an externalsecret I still get the externalsecret_status_condition metric for it. This looks like a bug.

**Comment by moolen** [comment]
> This looks like a bug

This is the default behavior of the prometheus client library. We can surely reset the counter when an API Object has been deleted 👍 .

**Comment by gabrielbatir** [comment]
It would be great if this could be fixed.
From what I understood externalsecret_status_condition has a value of 1 when the secret was created successfuly and 0 when there was an issue and the secret was not created. I was trying to create an alert based on that. 
If there are many secrets that could not be created in the last 5 minutes there might be an issue somewhere in the chain.
If that counter does not reset the alert would be useless. Also the load on prometheus will increase forever.
Thank you.

**Comment by spirosoik** [comment]
I think introducing a new state is the right way here. Something like `externalsecret_status_condition{condition="Deleted",name="",namespace="",status="False"} 1` because may you want to know that someone deleted accidentally. I have PR ready for this and you can have a look

**Comment by spirosoik** [comment]
Hey @moolen let's close this
