### ISSUE TITLE
[vault-provider] Ability to specify secret version

### ISSUE THREAD

**Issue by framsouza** [external-secrets/external-secrets#2315]
While using kvv2, there are some use cases where we want to specify the vault secret version to be synced and do not assume that it's always the latest version. 

It would be great if there's the capability to add an annotation with the specific vault version of the secret that will be synced.

**Comment by moolen** [comment]
You can specify the `remoteRef.version`, does that work for you? 
Examples are here: https://external-secrets.io/v0.8.1/api/externalsecret/

**Comment by framsouza** [comment]
that will do the thing, thanks @moolen
