### ISSUE TITLE
Can't proxy helm repository in Nexus3: ...external-secrets-0.8.1.tgz : 404 Not Found

### ISSUE THREAD

**Issue by rlaflamme** [external-secrets/external-secrets#2331]
Hello!
We are using helm packages behind a nexus3 helm proxy repository.

Here are my settings: (note: settings are exactly the same for our other helm repositories and they worked)

Nexus3:
Name: helm-external-secrets
Format: helm
Type: proxy
URL: https://my-company.com/nexus3/repository/helm-external-secrets/
Online: checked
Proxy
  Location of the remote repository being proxied: https://charts.external-secrets.io/
Auto blocking enabled: yes
Maximum component age: 1440
Maximum metadata age: 1440
Storage
  Blob store: default
  Strict content type validation: checked
Routing Rule:
  none
Negative Cache
  Not found cache TTL:  1440
HTTP
  Authentication: not checked
  Http request settings: not checked
Cleanup Policies: <default>

Roles:
  Role ID: helm_external_secrets_reader
Role Name:
Helm External Secrets Reader
Privileges:
  nx-repository-view-helm-helm-external-secrets-browse
  nx-repository-view-helm-helm-external-secrets-read

Users:
anonynous
  Granted: Helm External Secrets Reader

The issue:

#helm repo add my-external-secrets  https://my-company.com/nexus3/repository/helm-external-secrets
#helm install external-secrets my-external-secrets/external-secrets --debug
install.go:173: [debug] Original chart version: ""
Error: failed to fetch https://my-company.com/nexus3/repository/helm-external-secrets/external-secrets-0.8.1.tgz : 404 Not Found
helm.go:81: [debug] failed to fetch https://my-company.com/nexus3/repository/helm-external-secrets/external-secrets-0.8.1.tgz : 404 Not Found
helm.sh/helm/v3/pkg/getter.(*HTTPGetter).get
        /builddir/build/BUILD/helm-3.5.4/_build/src/helm.sh/helm/v3/pkg/getter/httpgetter.go:73
helm.sh/helm/v3/pkg/getter.(*HTTPGetter).Get
        /builddir/build/BUILD/helm-3.5.4/_build/src/helm.sh/helm/v3/pkg/getter/httpgetter.go:41
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
        /builddir/build/BUILD/helm-3.5.4/_build/src/helm.sh/helm/v3/pkg/downloader/chart_downloader.go:99
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
        /builddir/build/BUILD/helm-3.5.4/_build/src/helm.sh/helm/v3/pkg/action/install.go:675
main.runInstall
        /builddir/build/BUILD/helm-3.5.4/_build/src/helm.sh/helm/v3/cmd/helm/install.go:185
main.newInstallCmd.func2
        /builddir/build/BUILD/helm-3.5.4/_build/src/helm.sh/helm/v3/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
        /usr/share/gocode/src/github.com/spf13/cobra/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
        /usr/share/gocode/src/github.com/spf13/cobra/command.go:958
github.com/spf13/cobra.(*Command).Execute
        /usr/share/gocode/src/github.com/spf13/cobra/command.go:895
main.main
        /builddir/build/BUILD/helm-3.5.4/_build/src/helm.sh/helm/v3/cmd/helm/helm.go:80
runtime.main
        /usr/lib/golang/src/runtime/proc.go:225
runtime.goexit
        /usr/lib/golang/src/runtime/asm_amd64.s:1371

**Comment by moolen** [comment]
Hey, we aren't able to reproduce this issue with nexus (we don't have it running somewhere to test). I guess this is a misconfiguration on your end, other helm repos are set up in a similar manner (nginx ingress, cert-manager etc.) - under the hoods it's just a http server serving an [index.yaml](https://external-secrets.io/index.yaml) that points to `.tar.gz` files.

Can you provide some logs from nexus that show more details of why you got an 404?

**Comment by rlaflamme** [comment]
Of course!
Here's what I got from my nexus3  logs

10.14.6.239 - - [23/May/2023:10:12:36 -0400] "GET /nexus3/repository/helm-external-secrets/index.yaml HTTP/1.1" 200 - 29400 566 "Helm/3.11" [qtp1692609952-78784]
10.14.6.239 - - [23/May/2023:10:12:36 -0400] "GET /nexus3/repository/helm-external-secrets/external-secrets-0.8.2.tgz HTTP/1.1" 404 - 2001 65 "Helm/3.11" [qtp1692609952-78065]
10.14.6.239 - - [23/May/2023:10:12:37 -0400] "GET /nexus3/repository/helm-external-secrets/external-secrets-0.8.2.tgz HTTP/1.1" 404 - 2001 1 "Helm/3.11" [qtp1692609952-78784]
10.14.6.239 - - [23/May/2023:10:12:43 -0400] "GET /nexus3/repository/helm-external-secrets/external-secrets-0.8.2.tgz HTTP/1.1" 404 - 2001 1 "Helm/3.11" [qtp1692609952-78219]
10.14.6.239 - - [23/May/2023:10:12:55 -0400] "GET /nexus3/repository/helm-external-secrets/external-secrets-0.8.2.tgz HTTP/1.1" 404 - 2001 1 "Helm/3.11" [qtp1692609952-78237]
10.14.6.239 - - [23/May/2023:10:13:19 -0400] "GET /nexus3/repository/helm-external-secrets/external-secrets-0.8.2.tgz HTTP/1.1" 404 - 2001 1 "Helm/3.11" [qtp1692609952-78430]

**Comment by moolen** [comment]
That looks like the nexus access log (helm requesting a tarball that fails). 
Can you find out what requests nexus issues towards `charts.external-secrets.io` or github.com? It should go to e.g. `https://github.com/external-secrets/external-secrets/releases/download/helm-chart-0.8.2/external-secrets-0.8.2.tgz`

**Comment by rlaflamme** [comment]
Unfortunately I can't see no more logs going to github.  Since my last post I have only retries Here's what I get when I try to installt it from helm tool.   

[root@yoda tmp]# helm install external-secrets lq-external-secrets/external-secrets --dry-run --debug
install.go:173: [debug] Original chart version: ""
Error: failed to fetch https://my-company.com/nexus3/repository/helm-external-secrets/external-secrets-0.8.2.tgz : 404 Not Found
helm.go:81: [debug] failed to fetch https://my-company.com/nexus3/repository/helm-external-secrets/external-secrets-0.8.2.tgz : 404 Not Found
helm.sh/helm/v3/pkg/getter.(*HTTPGetter).get
        /builddir/build/BUILD/helm-3.5.4/_build/src/helm.sh/helm/v3/pkg/getter/httpgetter.go:73
helm.sh/helm/v3/pkg/getter.(*HTTPGetter).Get
        /builddir/build/BUILD/helm-3.5.4/_build/src/helm.sh/helm/v3/pkg/getter/httpgetter.go:41
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
        /builddir/build/BUILD/helm-3.5.4/_build/src/helm.sh/helm/v3/pkg/downloader/chart_downloader.go:99
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
        /builddir/build/BUILD/helm-3.5.4/_build/src/helm.sh/helm/v3/pkg/action/install.go:675
main.runInstall
        /builddir/build/BUILD/helm-3.5.4/_build/src/helm.sh/helm/v3/cmd/helm/install.go:185
main.newInstallCmd.func2
        /builddir/build/BUILD/helm-3.5.4/_build/src/helm.sh/helm/v3/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
        /usr/share/gocode/src/github.com/spf13/cobra/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
        /usr/share/gocode/src/github.com/spf13/cobra/command.go:958
github.com/spf13/cobra.(*Command).Execute
        /usr/share/gocode/src/github.com/spf13/cobra/command.go:895
main.main
        /builddir/build/BUILD/helm-3.5.4/_build/src/helm.sh/helm/v3/cmd/helm/helm.go:80
runtime.main
        /usr/lib/golang/src/runtime/proc.go:225
runtime.goexit
        /usr/lib/golang/src/runtime/asm_amd64.s:1371

**Comment by rlaflamme** [comment]
[external-secrets-index-yaml.zip](https://github.com/external-secrets/external-secrets/files/11548411/external-secrets-index-yaml.zip)

**Comment by rlaflamme** [comment]
I got something.  Please take a look a the zip file.  It contains 2 index files for external-secrets tgz.  One from a Nexus repository. The second one is a direct link to the helm repo.  The issue is the value of the URL from the Nexus proxy.  It contains only the tgz file instead of the full URL

**Comment by rlaflamme** [comment]
Looks like a Nexus3 issues.  We are using  an  old version OSS 3.25.1-04.
The index is re-written but it is missing the URL origin since it is diffrent from the URL of the index.
https://external-secrets.io/ vs  https://github.com/external-secrets/external-secrets/releases/download/....
This bug has been fixed since 2.28.0
https://issues.sonatype.org/browse/NEXUS-24682

Thank you again for you help.

Regards

Rober
