### ISSUE TITLE
Connection reset by peer from AWS secrets manager

### ISSUE THREAD

**Issue by doryer** [external-secrets/external-secrets#2333]
**Describe the bug**
Seems the external secrets operator in all of our environments that connected to the same secrets manager, suddenly getting errors 
`RequestError: send request failed
caused by: Post "https://secretsmanager.eu-west-1.amazonaws.com/": read tcp connection reset by peer`
The operator is retrying and eventually syncing the secret, but meantime he is exposing errors in the metric `externalsecret_sync_calls_error` and in the logs as well.

**To Reproduce**

It happens from time to time and without some operation, so hard for me to describe how to re-produce.
k8s version: 1.23.8
ESO version: 0.7.0

**Expected behavior**
Not to get errors from AWS

**Additional context**
It happens for us in the same time in all of our regions which connected to the same AWS account secrets manager in the same region, so for me it seems from issue on AWS side but no health events or reports from AWS.

**Comment by moolen** [comment]
> It happens for us in the same time in all of our regions which connected to the same AWS account secrets manager in the same region, so for me it seems from issue on AWS side but no health events or reports from AWS.

Networking bugs are the worst ones to track down :fearful:. I'm afraid there isn't much we can do, this is very likely an issue within your infrastructure and not related to ESO.

**Comment by doryer** [comment]
@moolen Thanks for the response , you have any suggestions what to check that it could be related to the infrastructure that can cause this kind of issue ?

**Comment by moolen** [comment]
I'd move down the stack:
1. HTTP_PROXY configuration if any
1. cluster CNI (check network policies)
1. issues on the host
1. issues on the subnet
1. any egress filtering/routing middleware or proxies?
1. VPC endpoint config & policies

Are the requests routed over the public internet does it stay within your VPC?
