### ISSUE TITLE
Owner policy does not work as intended

### ISSUE THREAD

**Issue by pisto** [external-secrets/external-secrets#2346]
v0.8.2 installed via helm chart.

**Describe the bug**
The documentation states with a `crationPolicy: Owner` an existing Secret would not be overridden on creation of the ExternalSecret resource with the same name (https://external-secrets.io/v0.8.2/guides/ownership-deletion-policy/#owner-default). This is not the case, an existing secret is actually overridden.

**To Reproduce**
```bash
# create a secret
kubectl create secret generic existing-secret --from-literal foo=bar -o yaml
# observe from the output foo=YmFy

# create an external secret with the same name with creationPolicy=Owner
kubectl create -f - <<EOF
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: existing-secret
spec:
  refreshInterval: "0"
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      data:
        foo: baz
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: password
EOF

# observe foo=YmF6
kubectl get secret existing-secret -o yaml
```

**Additional context**
This is important when migrating existing secrets to external secrets. Having the externalsecret "wait" for the deletion of the existing secret allows for more complex deploying and migration operations.

**Comment by gusfcarvalho** [comment]
Hi @pisto ! Does your secret already contains an owner? Or is it currently not set?

**Comment by pisto** [comment]
Owner is not set (repro steps create a secret without an owner).

**Comment by gusfcarvalho** [comment]
This is the expected behavior, in this case, as no owner is set up, ESO will set up the ownership and start to own that secret. If you create a secret with an owner definition, then ESO will not update it at all (and just fail instead).

**Comment by pisto** [comment]
Tested, it works as you described, thank you. It would be nice to mention more specifically this behavior in the docs.
