### ISSUE TITLE
Ability to rely on namespace creation rather than refreshTime for ClusterExternalSecrets

### ISSUE THREAD

**Issue by framsouza** [external-secrets/external-secrets#2351]
The purpose of this enhancement request is to propose an improvement to the functionality of the ESO by introducing the ability to rely on namespace creation events instead of the current refresh time-based approach for managing `ClusterExternalSecrets`.

Currently, the ESO utilizes a refresh time mechanism to periodically synchronize secrets from external secret stores to the Kubernetes cluster. While this approach has been effective, it can result in delays between the creation or modification of a secret in the external store and its availability in the cluster.

To address this limitation and enhance the real-time synchronization of secrets, we propose leveraging namespace creation events as triggers for refreshing and synchronizing `ClusterExternalSecrets` within the corresponding namespaces. By doing so, secrets can be made available in a timelier manner, reducing the time lag and ensuring that applications have access to the latest secrets immediately after creation or modification.

**Comment by shuheiktgw** [comment]
I think this is a reasonable request! Let me see if I could help with it 🙂 
/assign
