### ISSUE TITLE
Webhook to Lambda URL using AWS_IAM

### ISSUE THREAD

**Issue by Vanheelsing** [external-secrets/external-secrets#2370]
Hello everyone,

I am having trouble authenticating my webhook store. My lambda URL allows the SA Role to invoke it but the webhook even though it has the SA with the curreto assume-role annotation doesn't seem to support JWT.
My Store is configured as:
<pre><code>apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: webhook-test-binary-file
spec:
  provider:
    webhook:
      url: "https://asjhndjkhj2323kandjhia0lbamp.lambda-url.eu-central-1.on.aws/"
      result:
        jsonPath: "$.binary"
      headers:
        Content-Type: application/json</code></pre>

I thought i would be able to add the same auth system as the SecretStore or SSM parameters like:

<pre><code>      auth:
        jwt:
          serviceAccountRef:
            name: my-serviceaccount</code></pre>

But it's not possible so my question is without making my Lambda's URL use the "NONE" method (that makes it completly public) is there a way to authenticate my request from the WebhookStore using the role under the annotations of the SA?

**Comment by moolen** [comment]
Do you use AWS API Gateway in front of the lambda or how do is the lambda invoked?
The webhook provider is agnostic of any cloud provider and is a simple HTTP request builder. 

You can attach headers for authentication purposes, but your backend (API Gateway or other) needs to support that. See [Managing Access in API Gateway](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-control-access-to-api.html).

**Comment by Vanheelsing** [comment]
No API gateway, only Lambda Function URLS...
