### ISSUE TITLE
ESO seems to assume role twice with ClusterSecretStore

### ISSUE THREAD

**Issue by umegaya** [external-secrets/external-secrets#2399]
**Describe the bug**
this may rather question than bug report. 
I try to use ESO via cluster-secret-store and cluster-external-secret. 
cluster-secret-store is provided by aws secret manager, authorized by JWT.

provider part of cluster-secret-store is roughly like this. `arn:aws:iam::${account_id}:role/${role_name}` has already setup properly for accessing to aws secret manager.
``` yaml
provider:
  aws:
    service: SecretsManager
    role: arn:aws:iam::${account_id}:role/${role_name}
    region: ${region}
    auth:
      jwt:
        serviceAccountRef:
          name: my-serviceaccount
          namespace: sa-namespace
```

when I create cluster-secret-store, I got ValidationFailed
```
$ kubetcl get clustersecretstore 
NAME                                  AGE     STATUS             CAPABILITIES   READY
my-cluster-secret-store   5d19h   ValidationFailed   ReadWrite      False
```

`my-cluster-secret-store` reported access denied for user `arn:aws:sts::${account_id}:assumed-role/${role_name}/external-secrets-provider-aws`.
```
kubetcl describe clustersecretstore 
...
Warning  ValidationFailed  77s (x7 over 4m1s)  cluster-secret-store  (combined from similar events): AccessDenied: User: arn:aws:sts::${account_id}:assumed-role/${role_name}/external-secrets-provider-aws is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::${account_id}:role/${role_name}
```

after I added assume role policy to `arn:aws:iam::${account_id}:role/${role_name}` like below so that role session `arn:aws:sts::${account_id}:assumed-role/${role_name}/external-secrets-provider-aws` can assume role `arn:aws:iam::${account_id}:role/${role_name}`, ESO started working perfectly.

``` json
{
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:sts::${account_id}:assumed-role/${role_name}/external-secrets-provider-aws"
            },
            "Action": "sts:AssumeRole"
        }
```

I think ARN of user who denied access indicates ESO already had succeeded to assume role `arn:aws:iam::${account_id}:role/${role_name}`, but try to assume role `arn:aws:iam::${account_id}:role/${role_name}` again for some reason. 

if this is correct, is that expected behaviour?  if so, why ESO do this?

**To Reproduce**
1. sorry, our project does not allow to show complete manifests public, but it follows this example https://external-secrets.io/v0.8.3/api/clustersecretstore/ if you need to know specific details of our manifest, I can provide that details with some modification.
2. k8s 1.24 on eks and ESO 0.8.3
3. just install ESO 0.8.3 via helm and create cluster secret store should reproduce the behaviour.

**Expected behavior**
if my guess is correct, ESO should not assume role twice because first assuming role should give ESO to enough privilege to fetch secret from AWS secret manager.

**Comment by moolen** [comment]
Hey, thanks for reporting this, can you share your helm values? I'm interested in the args of the eso controller. Did you enable experimental features through cli args?

**Comment by moolen** [comment]
This is likely to be related to the bug fixed in #2376 (which looked to only happen when `--experimental-enable-aws-session-cache` is enabled), but it could be triggered as well when the secret client is reused :thinking:

**Comment by umegaya** [comment]
> can you share your helm values?

hi, @moolen ! only values that is applied for helm ESO installation is, `--set installCRDs=true`.

> Did you enable experimental features through cli args?

I'm not so sure what `cli args` mean, but containers in each pod that consist of ESO installation run with following options:

1. from deployment `external-secrets`
```
$ kubectl describe po external-secrets-7bcdb646cd-kl9m4 -n external-secrets
...
Containers:
  external-secrets:
    Container ID:  containerd://3836a9c7b96925a9213bb1c62de305f6f1935bdd2b58f6f334ccf6f36beb8193
    Image:         ghcr.io/external-secrets/external-secrets:v0.8.3
    Image ID:      ghcr.io/external-secrets/external-secrets@sha256:776e52b094f4aa2a9d8745e22d8f9aa0b8a0c06285198b237375b5951a75a519
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      --concurrent=1
    State:          Running
      Started:      Thu, 08 Jun 2023 18:32:25 +0900
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-dc6rf (ro)
```

2. from deployment `external-secrets-cert-controller`
```
$ kubectl describe po external-secrets-cert-controller-fddc945dc-kzqhq -n external-secrets
...
Containers:
  cert-controller:
    Container ID:  containerd://ca6741a0e229d96efea8347cb476ac2e45e44610fff3080a952db05f7b0cd0a4
    Image:         ghcr.io/external-secrets/external-secrets:v0.8.3
    Image ID:      ghcr.io/external-secrets/external-secrets@sha256:776e52b094f4aa2a9d8745e22d8f9aa0b8a0c06285198b237375b5951a75a519
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      certcontroller
      --crd-requeue-interval=5m
      --service-name=external-secrets-webhook
      --service-namespace=external-secrets
      --secret-name=external-secrets-webhook
      --secret-namespace=external-secrets
    State:          Running
      Started:      Thu, 08 Jun 2023 18:28:28 +0900
    Ready:          True
    Restart Count:  0
    Readiness:      http-get http://:8081/readyz delay=20s timeout=1s period=5s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-vmq7m (ro)
```

3. from deployment `external-secrets-webhook`
```
$ kubectl describe po external-secrets-webhook-95b78fb4-twqbd -n external-secrets
...
Containers:
  webhook:
    Container ID:  containerd://8447eb2d2639a8dacc7f9df84c0a483c6afbdfbb8035454bec6fa022799079bc
    Image:         ghcr.io/external-secrets/external-secrets:v0.8.3
    Image ID:      ghcr.io/external-secrets/external-secrets@sha256:776e52b094f4aa2a9d8745e22d8f9aa0b8a0c06285198b237375b5951a75a519
    Ports:         8080/TCP, 10250/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      webhook
      --port=10250
      --dns-name=external-secrets-webhook.external-secrets.svc
      --cert-dir=/tmp/certs
      --check-interval=5m
      --metrics-addr=:8080
      --healthz-addr=:8081
    State:          Running
      Started:      Thu, 08 Jun 2023 18:28:28 +0900
    Ready:          True
    Restart Count:  0
    Readiness:      http-get http://:8081/readyz delay=20s timeout=1s period=5s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /tmp/certs from certs (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-448kw (ro)
```

 hope that helps. 

regards,

**Comment by moolen** [comment]
I'm not sure if this is intentional or not: First, you're using the IRSA authentication mechanism to assume a role in your AWS account, then (based on `provider.aws.role`) you'll assume another role with the IRSA session that was just created.

Is this role-hopping intentional? If so, then for sure the IRSA requires the permissions to do `sts:AssumeRole` on `arn:aws:iam::${account_id}:role/${role_name}`. 

Note: `provider.aws.role` is optional and there is no need to use it unless you want to do role chaining. The IRSA Kubernetes service-account already has a role assigned to it.

**Comment by liyaka** [comment]
I have exactly the same problem. My configuration:

- default helm installation version 0.9.2, the only parameter:
`--set serviceAccount.annotations.eks.amazonaws.com/role-arn=arn:aws:iam::XXX:role/dev-external-secrets`

- added ClusterSecretStore:
```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: cluster-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      role: arn:aws:iam::XXX:role/dev-external-secrets
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
```
I get this error:
```
Warning  ValidationFailed  13m (x26 over 151m)  cluster-secret-store  AccessDenied: User: arn:aws:sts::XXX:assumed-role/dev-external-secrets/external-secrets-provider-aws is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::XXX:role/dev-external-secrets
           status code: 403,
```

**Comment by liyaka** [comment]
Now i've noticed that i have provider.aws.role defined - removed it and now it works!

**Comment by shuheiktgw** [comment]
Closing since there seems to be no problem to solve here
