### ISSUE TITLE
Setting metadata on ExternalSecrets generated by a ClusterExternalSecret

### ISSUE THREAD

**Issue by 12345ieee** [external-secrets/external-secrets#2400]
**Is your feature request related to a problem? Please describe.**
I need a way to set certain labels on all the kubernetes resources that are automatically generated.
It is possible to do so for Secrets generated by an ExternalSecret, via the: `target.template.metadata` object, but it's not possible to do so (as far as I can see) for ExternalSecrets generated by a ClusterExternalSecret.

**Describe the solution you'd like**
That a new resource field `externalSecretMetadata` is added to the `ClusterExternalSecretSpec`, at the same level as `externalSecretName`, which behaves identically to the `target.template.metadata` in ExternalSecret, but sets the metadata for the ExternalSecret instead.

**Comment by shuheiktgw** [comment]
This sounds like a decent feature to have to me. Let me see if I can help with it 🙂
