### ISSUE TITLE
Documentation on 'creationPolicy: Owner' does not state what happens to Orphaned secrets

### ISSUE THREAD

**Issue by HariSekhon** [external-secrets/external-secrets#2416]
**Describe the bug**

External Secret with `creationPolicy: Owner` overwrote the entire `argocd-secret`, wiping out the other secret keys and breaking ArgoCD

Related to https://github.com/argoproj/argo-cd/issues/10393

**To Reproduce**

External Secrets version: v0.8.1
Kubernetes GKE: v1.22.17-gke.8000

manifest:

https://github.com/HariSekhon/Kubernetes-configs/blob/master/argocd/base/argocd-azure-ad-external-secret.yaml

```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-azure-ad-sso
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Owner
  data:
    - secretKey: oidc.azure.clientSecret
      remoteRef:
        key: argocd-azure-ad-secret
```

**Expected behavior**

Expected it to safely refuse to overwrite the secret in case of forgetting to change `creationPolicy: Owner` to `creationPolicy: Merge`.

According to the documentation here:

https://external-secrets.io/v0.8.1/guides/ownership-deletion-policy/

```
Creation Policy
The field spec.target.creationPolicy defines how the operator creates the a secret.

Owner (default)
The External Secret Operator creates secret and sets the ownerReference field on the Secret. 
This secret is subject to garbage collection if the initial ExternalSecret is absent. If a secret 
with the same name already exists that is not owned by the controller it will result in a conflict. 
The operator will just error out, not claiming the ownership.
```

**Addition Info**

Log:

```shell
$ kubectl logs deploy/external-secrets

{"level":"info","ts":1685857213.8669896,"logger":"provider.vault","msg":"initializing vault cache with size=%d"}
{"level":"info","ts":1685857213.8672721,"logger":"setup","msg":"starting manager"}
{"level":"info","ts":1685857213.8677623,"msg":"Starting server","path":"/metrics","kind":"metrics","addr":"[::]:8080"}
{"level":"info","ts":1685857213.8680146,"msg":"Starting EventSource","controller":"secretstore","controllerGroup":"external-secrets.io","controllerKind":"SecretStore","source":"kind source: *v1beta1.SecretStore"}
{"level":"info","ts":1685857213.8681495,"msg":"Starting Controller","controller":"secretstore","controllerGroup":"external-secrets.io","controllerKind":"SecretStore"}
{"level":"info","ts":1685857213.8682804,"msg":"Starting EventSource","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","source":"kind source: *v1beta1.ExternalSecret"}
{"level":"info","ts":1685857213.8683174,"msg":"Starting EventSource","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","source":"kind source: *v1.PartialObjectMetadata"}
{"level":"info","ts":1685857213.8683264,"msg":"Starting Controller","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret"}
{"level":"info","ts":1685857213.8688862,"msg":"Starting EventSource","controller":"clustersecretstore","controllerGroup":"external-secrets.io","controllerKind":"ClusterSecretStore","source":"kind source: *v1beta1.ClusterSecretStore"}
{"level":"info","ts":1685857213.86893,"msg":"Starting Controller","controller":"clustersecretstore","controllerGroup":"external-secrets.io","controllerKind":"ClusterSecretStore"}
{"level":"info","ts":1685857213.8693812,"msg":"Starting EventSource","controller":"clusterexternalsecret","controllerGroup":"external-secrets.io","controllerKind":"ClusterExternalSecret","source":"kind source: *v1beta1.ClusterExternalSecret"}
{"level":"info","ts":1685857213.8694806,"msg":"Starting EventSource","controller":"clusterexternalsecret","controllerGroup":"external-secrets.io","controllerKind":"ClusterExternalSecret","source":"kind source: *v1.PartialObjectMetadata"}
{"level":"info","ts":1685857213.8695176,"msg":"Starting Controller","controller":"clusterexternalsecret","controllerGroup":"external-secrets.io","controllerKind":"ClusterExternalSecret"}
{"level":"info","ts":1685857213.8702075,"msg":"Starting EventSource","controller":"pushsecret","controllerGroup":"external-secrets.io","controllerKind":"PushSecret","source":"kind source: *v1alpha1.PushSecret"}
{"level":"info","ts":1685857213.8703034,"msg":"Starting Controller","controller":"pushsecret","controllerGroup":"external-secrets.io","controllerKind":"PushSecret"}
{"level":"info","ts":1685857214.1698434,"msg":"Starting workers","controller":"clustersecretstore","controllerGroup":"external-secrets.io","controllerKind":"ClusterSecretStore","worker count":1}
{"level":"info","ts":1685857214.1699183,"msg":"Starting workers","controller":"secretstore","controllerGroup":"external-secrets.io","controllerKind":"SecretStore","worker count":1}
{"level":"info","ts":1685857214.171373,"msg":"Starting workers","controller":"pushsecret","controllerGroup":"external-secrets.io","controllerKind":"PushSecret","worker count":1}
{"level":"info","ts":1685857214.171776,"msg":"Starting workers","controller":"clusterexternalsecret","controllerGroup":"external-secrets.io","controllerKind":"ClusterExternalSecret","worker count":1}
{"level":"info","ts":1685857214.1727352,"msg":"Starting workers","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","worker count":1}
{"level":"info","ts":1686749479.3423395,"logger":"controllers.ExternalSecret","msg":"reconciled secret","ExternalSecret":"argocd/argocd-azure-ad-sso"}
```

**Comment by gusfcarvalho** [comment]
Hi @HariSekhon. Can you share your Argocd secret before it was erased? This is most likely to the fact that Argo is not owning it with a ownerReference field

**Comment by gusfcarvalho** [comment]
And in the case of empry ownerReference, ESO will just set itself as owner and start managing the secret.

**Comment by gusfcarvalho** [comment]
Note that the secret manifest you have there in your repo, if not applied with Argo, will not have any owner set to it.

**Comment by HariSekhon** [comment]
Luckily I took a backup before apply, here is what it was before:

```yaml
apiVersion: v1
data:
  admin.password: <REDACTED>
  admin.passwordMtime: <REDACTED>
  admin.tokens: <REDACTED>
  oidc.azure.clientSecret: <REDACTED>
  server.secretkey: <REDACTED>
  webhook.github.secret: <REDACTED>
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"argocd","app.kubernetes.io/name":"argocd-secret","app.kubernetes.io/part-of":"argocd"},"name":"argocd-secret","namespace":"argocd"},"type":"Opaque"}
  creationTimestamp: "2021-06-11T12:06:41Z"
  labels:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
  resourceVersion: "1120320343"
  uid: 0fef094f-27e2-4d64-b91f-9ea88e849130
type: Opaque

```

**Comment by HariSekhon** [comment]
@gusfcarvalho this part of the doc implies that it wouldn't overwrite an existing secret it does not have ownership of:

```
If a secret with the same name already exists that is not owned by the controller it will result in a conflict. 
The operator will just error out, not claiming the ownership.
```

Perhaps this behaviour needs to be fixed for safety to not overwrite if an ownerReference field is not found?

**Comment by gusfcarvalho** [comment]
the intended behavior of `creationPolicy: Owner` is:

If the secret does not exist, the controller will create one and set `ownerReference` to the ExternalSecret resource Namespaced Name.

If the field `ownerReference` is set and it does not manage the ExternalSecret resource name, the an error will be emited

If the secret exists and the `ownerReference` field is not found, the controller treats this secret as orphaned, takes the ownership of it by setting `ownerReference` and updates it.

This last one is arguable if it should be intended, but it does allow for more complex usage leveraging `creationPolicy: Orphan`, so I'm inclined to not change it as this would be a breaking change.

I believe we could indeed make the docs more clear on this behavior.


Sorry for your poor experience :(

**Comment by sebagomez** [comment]
that's a tricky one... my initial thought would be no, I don't want ESO to take ownership of a Secret I already had in my cluster. Also, If I created an `ExternalSecret` with `creationPolicy: None` but then I add the `Owner`, do I want it to grab the original secret o fail?
I believe failing is the safest option.

**Comment by HariSekhon** [comment]
@sebagomez I also think failing and refusing to blat the secret is the safer option.

This behaviour can cause terrible outages and be difficult to recover from if those adjacent lost secrets were not already stored elsewhere or backed up before applying.

There is precedence with Bitnami Sealed Secrets that they don't replace existing secrets unless you add an annotation to explicitly mange them:

```
kubectl annotate secrets "$secret" 'sealedsecrets.bitnami.com/managed=true' --overwrite
```

**Comment by m-adawi** [comment]
I had a similar situation while trying ESO for the first time today. I had a secret that I manually created earlier, was trying ExternalSecret and apparently had it create a secret with the same name, but I deleted the ExternalSecret and found out that it deleted my old secret as well. I think it should error out that the secret already exists, that's what I understood from the documentation

**Comment by LucasPimentel123** [comment]
Hey, just ran into the same problem as the one related in this issue a few days ago. I decided to add a note in the Creation Policy docs to explain intended behavior of `creationPolicy: Owner`. This can be found in the PR #2928  . I hope it helps!
