### ISSUE TITLE
How to mount binary file into my container without encode or decode

### ISSUE THREAD

**Issue by damirserlley** [external-secrets/external-secrets#2425]
I am having issues adding p12 cert in my secret manager we are not able to read the file after mounting the secret file so we think is a problem between google secrets manager and the external secrets operator.  Since Kubernetes stores secrets in base64  i guess we can double encode the data and then we can use the data as base64 encoded string inside of my application. Any idea how to mount this properly or other solution to this?

**Comment by gusfcarvalho** [comment]
Hi @damirserlley ! You can use template functions to b64decode your .p12 cert. I believe this issue is more related to how you are storing your secret in GCP SM

**Comment by damirserlley** [comment]
So you are saying binary files should work find without doing the manual encode and the decode? i am storing the secret using gcp ui load button so it should work 
Not sure if this is related to the issue i mention above
https://github.com/kubernetes/kubernetes/issues/89906

**Comment by gusfcarvalho** [comment]
It is not 😄. Most likely, the GCP is storing it already encoded, which is why you cannot see it.
