### ISSUE TITLE
AzureKV Store capabilities based on permissions of provider

### ISSUE THREAD

**Issue by Jarno458** [external-secrets/external-secrets#2435]
I have created a ClusterSecretStore using an azure keyvault provider that itself is authenticated using a service principal, The cluster store has status: Valid and Capebilities: ReadWrite, however the service pricipal used here only has Get permissions on the keyvault, so it would be great if the stores Capebilities where: ReadOnly

I have tried to somehow specify manually for the Store to be ReadOnly but i don't seem to be able to control this setting

**Comment by moolen** [comment]
Hey @Jarno458, the capabilities describe what you can do with that particular ESO provider, irrespective of the authentication credentials used.
Some ESO providers can push secrets (ReadWrite), others can just pull secrets (ReadOnly). The setting is hard coded in the source.

**Comment by Jarno458** [comment]
oke guess we can close this than
