### ISSUE TITLE
Separation of kubecontexts between inner controllers

### ISSUE THREAD

**Issue by buji-code** [external-secrets/external-secrets#2478]
I'm using other cloud providers to host my own provisioning of Kubernetes control-plane running the base components: _apiserver, etcd, scheduler & controller-manager_. 
I'd like to use the authorization benefits of running my control-plane in those cloud providers (for example GKE Identity Workload) and integrate it with ExternalSecrets that are being managed from within my control-plane. In this case I'd like to run the ES operator on the "host" (GKE) together with my control-plane components and manage the ClusterSecretStore/SecretStore with the same context, while managing the ExternalSecrets in my own control-plane context (the one that I provisioned above the "host" cloud provider).

A possible solution might be passing a different kubeconfig to the ES operator indicating the ExternalSecrets controller where to watch for ExternalSecrets resources, while keeping the in-cluster context for the SecretStore controller to watch for the ClusterSecretStore/SecretStore. For example, adding a new argument: `--external-secrets-kubeconfig=<path-to-kubeconfig>` when mounting the kubeconfig data to the Pod running the ES operator.

**Comment by gusfcarvalho** [comment]
AFAIK you can already do that. Just specify KUBECONFIG environment variable together with your mount path and it should work 😁

**Comment by buji-code** [comment]
@gusfcarvalho Don't the KUBECONFIG env variable set the context for all the controllers together?

**Comment by gusfcarvalho** [comment]
Why would be the benefit over just having them in the same control plane? The secret store controller only provides a “validation check” on the provider. You might even just skip this validation altogether

**Comment by gusfcarvalho** [comment]
Also, how would the ExternalSecrets know to which cluster to get the SecretStores from? 🤔

I see a lot of operational issues having this, but didn’t quite see the benefit. 

For me it feels less secure than just exposing  a kubernetes provider in your control plane targeting the host kubernetes

**Comment by buji-code** [comment]
@gusfcarvalho Thank you, I think I have a fault in my design. Closing 😄
