### ISSUE TITLE
AWS Cross account secrets no longer accessible after moving from KES to ESO

### ISSUE THREAD

**Issue by mdellavedova** [external-secrets/external-secrets#2488]
**Describe the bug**
Hi, re-opening [this](https://github.com/external-secrets/external-secrets/issues/390) issue as I'm having the same problem, with a twist:
I have 3 EKS clusters in 3 separate regions (eu-west-1, us-east-1 and ap-southeast-1). I was previously KES and IRSA auth to access a secret in a separate account, and this worked fine across all regions. (it's actually still working fine in older clusters which are still running KES). Since moving to ESO and using the same auth method (service account using a role that has the same policy as the old clusters which use KES) I can only access the secret from eu-west-1. 
The other 2 ESO instances (us-east-1 and ap-southeast-1) are not able to access the secret. the issue seems to be KMS permissions:
`{"level":"error","ts":1689090071.6549695,"logger":"controllers.ExternalSecret","msg":"could not get secret data from provider","ExternalSecret":"twistlock/twistlock-secrets","error":"AccessDeniedException: Access to KMS is not allowed\n\tstatus code: 400, ","stacktrace":"github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:189\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:122\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:323\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"} {"level":"error","ts":1689090071.6683495,"msg":"Reconciler error","controller":"externalsecret","controllerGroup":"external-secrets.io","controllerKind":"ExternalSecret","ExternalSecret":{"name":"twistlock-secrets","namespace":"twistlock"},"namespace":"twistlock","name":"twistlock-secrets","reconcileID":"9a29d08b-c5b3-4657-aff3-c3ce819f6072","error":"AccessDeniedException: Access to KMS is not allowed\n\tstatus code: 400, ","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:274\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.5/pkg/internal/controller/controller.go:235"}`

**To Reproduce**
1. provide all relevant manifests
2. provide the Kubernetes and ESO version: 
EKS v1.26.4
ESO helm chart 0.9.1
**Expected behavior**
secrets to be accessible from all regions as when using KES

**Screenshots**

**Additional context**

**Comment by gusfcarvalho** [comment]
Can you provide your SecretStore manifests please?

**Comment by mdellavedova** [comment]
Hi, sure this is the `ap-southeast-1` one: 
`apiVersion: v1
items:
- apiVersion: external-secrets.io/v1beta1
  kind: ClusterSecretStore
  metadata:
    labels:
      argocd.argoproj.io/instance: cluster-bootstrap-resources-apse1-1
    name: aws-secretsmanager
  spec:
    provider:
      aws:
        auth:
          jwt:
            serviceAccountRef:
              name: external-secrets
              namespace: cluster
        region: ap-southeast-1
        service: SecretsManager
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""`

**Comment by moolen** [comment]
Thanks for your info. Did you configure a `spec.roleArn` in KES?

```yaml
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: hello-service
spec:
  backendType: secretsManager
  # optional: specify role to assume when retrieving the data
  roleArn: arn:aws:iam::123456789012:role/test-role
```

**Comment by mdellavedova** [comment]
> Thanks for your info. Did you configure a `spec.roleArn` in KES?
> 
> ```yaml
> apiVersion: "kubernetes-client.io/v1"
> kind: ExternalSecret
> metadata:
>   name: hello-service
> spec:
>   backendType: secretsManager
>   # optional: specify role to assume when retrieving the data
>   roleArn: arn:aws:iam::123456789012:role/test-role
> ```

Hi, no, I haven't. The role arn is only added to the service account through the `eks.amazonaws.com/role-arn` annotation (same as the ESO setup)

**Comment by moolen** [comment]
Do you use IRSA with ESO (mounted the SA in the controller? If so, can you try to remove `auth.jwt` from the SecretStore?

Other than that i'm out if ideas. Do you use the very same service accounts with both KES and ESO? Did you double check AWS IAM permissions?
