### ISSUE TITLE
Allow passing kubeconfig to configure the ESO context

### ISSUE THREAD

**Issue by buji-code** [external-secrets/external-secrets#2496]
I'm trying to run the ESO in one cluster while setting it to watch another.

I'd expect to have this behavior:
Flag like on kubebuilder operators _--kubeconfig=path-to-kubeconfig_

For now, I'm getting an error:
`Error: unknown flag: --kubeconfig`

**Comment by moolen** [comment]
You can set `KUBECONFIG` env var pointing to a valid kubeconfig file, that should work out of the box.

**Comment by buji-code** [comment]
thanks
