### ISSUE TITLE
Add UserPass authentication method to hasicorp vault provider

### ISSUE THREAD

**Issue by c0ffee** [external-secrets/external-secrets#2538]
**Is your feature request related to a problem? Please describe.**
The authentication method userPass is missing, sadly the SaaS provider which I use in my project only support this method.

**Describe the solution you'd like**
Adding the support for the userPass authentication method according to the already supported ones. 

**Describe alternatives you've considered**
In the future the provider will add different authentication methods, nervertheless it would be good to support userPass here too

**Additional context**
https://developer.hashicorp.com/vault/docs/auth/userpass

**Comment by gusfcarvalho** [comment]
hi! Can you give some more details how this saas provider work? Is it implementing open source vault and only allowing userpass as auth method?

**Comment by c0ffee** [comment]
Hi
yeah I would imagine they are using the open source variant and added a user backend because it is fully integrated in their portal.

**Comment by c0ffee** [comment]
@moolen thanks for merging! any chance that we can create anew release with this feature soon?

**Comment by moolen** [comment]
I can do a release but am on :palm_tree: after that. Got to look for someone to be available for providing hotfixes :sweat_smile: 
I'll come back to you in a day or two :hourglass_flowing_sand:
