### ISSUE TITLE
stale resources in clustersecretstore_status_condition metric

### ISSUE THREAD

**Issue by shaunofneuron** [external-secrets/external-secrets#2542]
**Describe the bug**
After creating some alerts using clustersecretstore_status_condition I had to bounce the eso pods to get a failing ClusterSecretStore to stop showing up in the metric.  The alert I had setup in question:

```
clustersecretstore_status_condition{condition="Ready",status="False"} == 1
```

I also noticed that there is no "Deleted" condition in the metrics as there is with the ExternalSecret metric `externalsecret_status_condition`.

**To Reproduce**
1. Create a ClusterSecretStore (in my case I intentionally created one that would fail but still a valid CR).
2. Observe the `clustersecretstore_status_condition` metric results, it should register the new ClusterSecretStore with the status.
3. Delete the ClusterSecretStore
4. Observe the `clustersecretstore_status_condition` metric results, there should still exist a result for the deleted ClusterSecretStore with the condition of "Ready", status of "False" and value of `1`.
5. Delete the eso pods
6. Observe the `clustersecretstore_status_condition` metric results, there should no longer exist a result for the deleted ClusterSecretStore.

**Expected behavior**
Deleted ClusterSecretStores either have a new metric condition state of "Deleted" which would automatically stop showing after some amount of time or no metric result at all. 

**Screenshots**

<img width="1708" alt="cluster-secret-store-metric" src="https://github.com/external-secrets/external-secrets/assets/6895147/55d30099-d76d-40c4-bc43-625bc64572e7">

**Comment by shuheiktgw** [comment]
Let me see if I can help with it 🙂 (I'm the one who implemented it so I kind of feel I'm responsible for the problem)
