### ISSUE TITLE
We are unable to deploy new external-secrets templates to cluster

### ISSUE THREAD

**Issue by erineG** [external-secrets/external-secrets#2544]
We have generated new template, then we are trying to deploy those templates to our Kubernetes clusters. But we are unable to be successful through the pipeline as well as from the command line.
we are seeing below error :

> Error from server (InternalError): error when applying patch:
{"spec":{"data":[{"remoteRef":{"key":"arbitrary/ab5e67c7-b56e-660c-6910-92c8437b8732"},"secretKey":"appConfigApiKey"}]}}
to:
Resource: "[external-secrets.io/v1beta1](http://external-secrets.io/v1beta1), Resource=externalsecrets", GroupVersionKind: "[external-secrets.io/v1beta1](http://external-secrets.io/v1beta1), Kind=ExternalSecret"
Name: "compliance-appconfig-credentials", Namespace: "compliance"
for: "us-south-dev/scc-dev-dal/compliance-appconfig-credentials.yml": Internal error occurred: failed calling webhook "[validate.externalsecret.external-secrets.io](http://validate.externalsecret.external-secrets.io/)": failed to call webhook: Post "[https://external-secrets-webhook.external-secrets.svc:443/validate-external-secrets-io-v1beta1-externalsecret?timeout=5s](https://external-secrets-webhook.external-secrets.svc/validate-external-secrets-io-v1beta1-externalsecret?timeout=5s)": x509: certificate is not valid for any names, but wanted to match external-secrets-webhook.external-secrets.svc

**Comment by IdanAdar** [comment]
@moolen Any pointers?

**Comment by moolen** [comment]
> x509: certificate is not valid for any names, but wanted to match external-secrets-webhook.external-secrets.svc

@erineG how do you deploy ESO? When using helm, can you share your values? It looks like the certificate is not being generated with the correct hostnames. Are all ESO pods up?

**Comment by erineG** [comment]
Hi @moolen . we deploy ESO using our tekton pipeline, and all ESO pods are up and running with no issue.
 here is the helm chart used:
certController:
  image:
    repository: icr.io/external-secrets/external-secrets
    tag: v0.9.1-ubi
extraVolumeMounts:
- mountPath: /var/run/secrets/tokens
  name: sa-token
extraVolumes:
- name: sa-token
  projected:
    defaultMode: 420
    sources:
    - serviceAccountToken:
        audience: iam
        expirationSeconds: 3600
        path: sa-token
image:
  repository: icr.io/external-secrets/external-secrets
  tag: v0.9.1-ubi
installCRDs: true
webhook:
  extraVolumeMounts:
  - mountPath: /var/run/secrets/tokens
    name: sa-token
  extraVolumes:
  - name: sa-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: iam
          expirationSeconds: 3600
          path: sa-token
  image:
    repository: icr.io/external-secrets/external-secrets
    tag: v0.9.1-ubi`

**Comment by moolen** [comment]
Can you inspect the tls certificate of the validating webhook (expiry, issuer, DNS names...) and look for issues in the logs of the cert controller?
The cert is not valid, we need to find out why.

**Comment by erineG** [comment]
@moolen here is the output of the cert controller log:
I ran the command:  kubectl logs external-secrets-cert-controller-6f755f784f-m9l2m -n external-secrets

here is the output:



{"level":"info","ts":1690569029.9095457,"logger":"controllers.webhook-certs-updater","msg":"updated webhook config","Webhookconfig":{"name":"secretstore-validate"}}
{"level":"info","ts":1690569029.9258265,"logger":"controllers.webhook-certs-updater","msg":"updating webhook config","Webhookconfig":{"name":"externalsecret-validate"}}
{"level":"info","ts":1690569029.9365609,"logger":"controllers.webhook-certs-updater","msg":"injecting ca certificate and service names","cacrt":"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURSakNDQWk2Z0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREEyTVJrd0Z3WURWUVFLRXhCbGVIUmwKY201aGJDMXpaV055WlhSek1Sa3dGd1lEVlFRREV4QmxlSFJsY201aGJDMXpaV055WlhSek1CNFhEVEl6TURJeQpOREE0TlRZeE9Gb1hEVE16TURJeU1UQTVOVFl4T0Zvd05qRVpNQmNHQTFVRUNoTVFaWGgwWlhKdVlXd3RjMlZqCmNtVjBjekVaTUJjR0ExVUVBeE1RWlhoMFpYSnVZV3d0YzJWamNtVjBjekNDQVNJd0RRWUpLb1pJaHZjTkFRRUIKQlFBRGdnRVBBRENDQVFvQ2dnRUJBTTA3Yi80QnNVWkk3eklaN3Y3MW5TVklGdDQzLy9IWW4xd05XZmw4SlBUZApiK3crQ1V3ek5YSjBlUjhDaXhsa2tOeGdHRHNjT25KU2ZCWEpkd0RpS2I4UDNQUyt0V05qdXF3NE51STJ0RmJiCkx2eUVOaW9OMWFUV2hzdXdiWG5hM2lKaDVjcjhIZE9CSjBZVlZ3ZlNYRkVUQVk1dU5lRDl3Nzk3R2JXSFVkemMKZjhKZGY4cmxMY1djVkR6RUNvUGZRajNBVmwrTDV5UUVWNFp1R1Y5c3A1TVUwMTlZQUk2eUx4ZVhUZUZIbXdUaQpZa2dwVXh2STMzckErcEhOOCtMa0tIQXVWd1FSMXZ1bk8xUllncExpN2RFWUxiYVlEWlgybnZBeEJPZEcvS01iCnh1OUQxaHFPWVUwcWNZcERYU1NjR0thN0k1ZDBZTThPaWhRdzQrR0xRV1VDQXdFQUFhTmZNRjB3RGdZRFZSMFAKQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRk9acFZKMlFwWUhUdTFCdQpHTmdCTjFPZTR4clhNQnNHQTFVZEVRUVVNQktDRUdWNGRHVnlibUZzTFhObFkzSmxkSE13RFFZSktvWklodmNOCkFRRUxCUUFEZ2dFQkFNVmV1VVJ5cStLWHQ4dU8wUkx2c1NlWVpXN0pUdzBySHBPS0hMRFg2L3oyM3BwcU1BeHUKc3pjbUhOd010aXMvN2FERnJ5OHRlY0ppaFNZZ1JaTEZXT0lTUmsraFlzVmRUK2pYbUs2aGJCL2RIRzhTMUYwNAorWVNUR3MrY09kZDJVbHZLeGRsb1pZUHB0V21UaXFIZCtYUndHRnFrZUlmL1pQa1RVODdTc25zenFQTUhyUzZPCm4vNnBWWEhGTENMSndiZytzTDhBVEpyQ3NsV1E3NHc3VDNZbnVDWmhxdkd4VnZwUGdlQTUwZjVGK010aTFpRGcKNGxKKzVOQUlxQVNSRFo3dHBsNUdIVC85aHlxcGVHck1rOVo5cVF6bEg0Qnd4anZDNXFxQmFUc0hPcnE4YTdTZQpEYk54cjBvb3R0R0UvODYrbmJGN3ZLMlNCU3lnZW1QTng2RT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=","name":"externalsecret-validate"}
{"level":"info","ts":1690569029.9491441,"logger":"controllers.webhook-certs-updater","msg":"updated webhook config","Webhookconfig":{"name":"externalsecret-validate"}}

**Comment by erineG** [comment]
as for the wekhook pod , here is the log output:
I ran the command: `kubectl logs external-secrets-webhook-6db857bb4f-nrtdx -n external-secrets`

2023/07/28 18:34:49 http: TLS handshake error from 127.0.0.6:53037: EOF
2023/07/28 18:34:49 http: TLS handshake error from 127.0.0.6:49107: EOF
2023/07/28 18:34:50 http: TLS handshake error from 127.0.0.6:42573: EOF
2023/07/28 18:34:50 http: TLS handshake error from 127.0.0.6:35563: EOF
2023/07/28 18:34:50 http: TLS handshake error from 127.0.0.6:51859: EOF
2023/07/28 18:34:50 http: TLS handshake error from 127.0.0.6:34263: EOF
2023/07/28 18:34:50 http: TLS handshake error from 127.0.0.6:50685: EOF
2023/07/28 18:34:50 http: TLS handshake error from 127.0.0.6:48757: EOF
2023/07/28 18:34:51 http: TLS handshake error from 127.0.0.6:53213: EOF
2023/07/28 18:34:51 http: TLS handshake error from 127.0.0.6:59845: EOF
2023/07/28 18:34:51 http: TLS handshake error from 127.0.0.6:49279: EOF

**Comment by moolen** [comment]
Thank you, could you please paste your webhook TLS certificate DNS SAN?

The following command should show that:
```
$ kubectl -n external-secrets get secret external-secrets-webhook -o json | jq -r '.data."tls.crt"' | base64 -d | openssl x509 -noout -text | grep -i dns
DNS:external-secrets-webhook, DNS:external-secrets-webhook.external-secrets, DNS:external-secrets-webhook.external-secrets.svc
```

**Comment by erineG** [comment]
Thank you for the follow up:
Here is the output of the above command: 
command: `
` kubectl -n external-secrets get secret external-secrets-webhook -o json | jq -r '.data."tls.crt"' | base64 -d | openssl x509 -noout -text | grep -i dns
                DNS:external-secrets-webhook.external-secrets.svc
➜  ~

**Comment by moolen** [comment]
Interesting, that's not what i expected. Now we got to move towards the control plane and get a perspective from there.
Do you have any chance to get to the control-plane nodes or is that all managed?

The remaining questions are:
1. what certificate is presented when the control plane tries to access `external-secrets-webhook.external-secrets.svc:443`. Expected issue: SAN mismatch. But what SAN does it show?
2. Does DNS point somewhere completely else? What are the search domains configured on the node? Do you use the default zone `cluster.local` ?

From this point on i can't really provide the steps/commands to execute, as this is very environment specific. I hope the general questions above :point_up_2: provide enough information to help you out :pray:.

**Comment by erineG** [comment]
For our environment, All nodes and managed. 
at this point Can I uninstall the ESO and reinstall it again? Do you think it my fix the issue?

**Comment by moolen** [comment]
yeah sure, why not. However, that will also uninstall the CRDs and with that all ExternalSecrets, SecretStores etc. Be aware of that. 
Don't do this in production :smile:

**Comment by erineG** [comment]
Yeah I AM in dev and weird think is that this is only happening in dev

**Comment by erineG** [comment]
update:
I uninstalled the ESO from the cluster, then reinstalled it, now everything seems to work fine. I will monitor for some time.

**Comment by Kaali09** [comment]
@moolen We are also facing an similar issue and we tried ESO version upgrade and landed with similar error. Could you please suggest on this to fix the issue?

**Comment by moolen** [comment]
Please try a TLS handshake and see if the certificate presented is the expected one (it matches the DNS name)
