### ISSUE TITLE
Circular dependency with `kube-prometheus-stack`

### ISSUE THREAD

**Issue by Rohlik** [external-secrets/external-secrets#2547]
Hey guys 👋🏼,
we are using `external-secrets` chart along with [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack).  
Our `kube-prometheus-stack` depends on some secrets which are created/managed by `external-secrets`.
This leads to issues while you are building a new k8s/EKS cluster and you cannot deploy `external-secrets` because of missing CRD `ServiceMonitor` from `kube-prometheus-stack` and you can't deploy `kube-prometheus-stack` either, because you need secrets 😔.   

Error message from healmrelease `external-secrets`:  

> Helm install failed: unable to build kubernetes objects from release manifest: [resource mapping not found for name: "external-secrets-metrics" namespace: "external-secrets" from "":
> no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"

What do you think about using something like:  
``{{- if and ( .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" ) .Values.serviceMonitor.enabled -}}``  
instead of just: https://github.com/external-secrets/external-secrets/blob/1ad4a66ab1f630dfb84a445570d5f1c4715da59f/deploy/charts/external-secrets/templates/servicemonitor.yaml#L1
What do you think?

Using Helm v3.10.2 and k8s v1.27.3

**Comment by moolen** [comment]
Hey @Rohlik great suggestion, that sounds good to me!

**Comment by ppatel1604** [comment]
@moolen @Rohlik I can perform this change if it is not being worked by anyone else. Can you please assign it to me?
