### ISSUE TITLE
External Secrets Operator does not refresh lastTransitionTime

### ISSUE THREAD

**Issue by rakrueger** [external-secrets/external-secrets#2555]
**Describe the bug**
According to the [FAQ](https://external-secrets.io/main/introduction/faq/), the field `lastTransitionTime` is supposed to change when the secret was last synced. So it should change when a new key value pair is added to an existing secret or if a value has changed in the external vault and this change was transferred to Kubernetes. I see that the `refreshTime` updates after every sync but when a change has happened the `lastTransitionTime` remains the same and thus corresponds to the `creationTimestamp`. The actual change of the value is synced correctly and it is working like a charm.

**To Reproduce**
I am using the latest ESO version [v0.9.1](https://github.com/external-secrets/external-secrets/releases/tag/v0.9.1) and the Kubernetes version 1.26.3. The external vault is an Azure Key Vault. Here is an example ExternalSecret manifest file:

```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
  creationTimestamp: "2023-07-25T10:19:47Z"
  generation: 2
  name: XXX
  namespace: XXX
  resourceVersion: "XXX"
  uid: XXX
spec:
  dataFrom:
  - find:
      conversionStrategy: Default
      decodingStrategy: None
      name:
        regexp: XXX--
    rewrite:
    - regexp:
        source: XXX--(.*)
        target: $1
    - regexp:
        source: XXX
        target: XXX
  refreshInterval: 10m
  secretStoreRef:
    kind: SecretStore
    name: XXX
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: XXX
status:
  binding:
    name: XXX
  conditions:
  - lastTransitionTime: "2023-07-25T10:19:47Z"
    message: Secret was synced
    reason: SecretSynced
    status: "True"
    type: Ready
  refreshTime: "2023-07-27T15:01:43Z"
```
I changed the values in the external vault several times on July 26 +27 and also added new key value pairs to the secret but `lastTransitionTime` stayed the same.

**Expected behavior**
Change the value of `lastTransitionTime` when a value in the external vault has changed thus leading to a change in the Kubernetes secret.

**Additional context**
Besides that, thanks for this great tool :)

**Comment by shuheiktgw** [comment]
Hi @rakrueger 👋 Thank you for reporting the issue! I checked the current implementation and you are right. It does not update the lastTransitionTime if the condition does not change. 

https://github.com/external-secrets/external-secrets/blob/5ef0a44957ba4e9e437658b0e45b5a2f5f6f0e8e/pkg/controllers/externalsecret/util.go#L50-L53

The implementation itself seems fine to me, but I believe the FAQ should point to refreshTime instead of lastTransitionTime. Would you like to create a PR to fix it?

**Comment by shuheiktgw** [comment]
Closing in response to https://github.com/external-secrets/external-secrets/pull/2640
