### ISSUE TITLE
onepassword ClusterSecretStore breaks operator if no namespace for accessToken-secret is provided

### ISSUE THREAD

**Issue by sleyer** [external-secrets/external-secrets#2572]
**Describe the bug**
When using a ClusterSecretStore to access secrets in onepassword. if no namespace is provided to the secret token, the external-secret operator pod goes into a crashloop. 

**To Reproduce**
For example, if I apply this ClusterSecretStore to my cluster (see the commented out namespace-field): 

```
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: clustersecretstore-onepassword
spec:
  provider:
    onepassword:
      auth:
        secretRef:
          connectTokenSecretRef:
            key: token
            name: onepassword-connect-token
            # namespace: external-secrets # this is mandatory
      connectHost: http://onepassword-connect.external-secrets.svc.cluster.local:8080
      vaults:
        my-new-vault: 1
```

The operator pod starts to crash-loop with this error: 

```
{"level":"info","ts":1690981808.6374583,"msg":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","controller":"clustersecretstore","controllerGroup":"external-secrets.io","controllerKind":"ClusterSecretStore","ClusterSecretStore":{"name":"clustersecretstore-onepassword"},"namespace":"","name":"devops-onepassword","reconcileID":"ef6e9f95-aa98-4975-85cd-5bb7ee79c70f"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x23dec64]

goroutine 226 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:115 +0x1fa
panic({0x30d63c0, 0x6571d40})
	/opt/hostedtoolcache/go/1.19.10/x64/src/runtime/panic.go:884 +0x212
github.com/external-secrets/external-secrets/pkg/provider/onepassword.(*ProviderOnePassword).NewClient(0xc000011458, {0x3fa30b8, 0xc000ed6b10}, {0x3fc61b8, 0xc0010fe000}, {0x3fb1040, 0xc00051ad80}, {0x0, 0x0})
	/home/runner/work/external-secrets/external-secrets/pkg/provider/onepassword/onepassword.go:88 +0x184
```

kubernetes version: 1.23.17
ESO version: v0.9.1

**Expected behavior**

I believe the operator should handle this more gracefully and log a meaningful error message that tells users what to do.  A misconfigured provider should not take the whole operator down. 

Additionally, I don't see this documented in the onepassword guide, which it probably should be.

**Screenshots**

**Additional context**

Yes, it is mentioned as a comment in the source code, 
https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/onepassword/onepassword.go#L86C13-L86C13

I don't know if other providers have a similar issue.

**Comment by shuheiktgw** [comment]
Hi, @sleyer 👋 Thank you for reporting the issue! You are right and I think we should add validation here. Would you like to work on it? 

https://github.com/external-secrets/external-secrets/blob/1cf7c3a6e31d699c78d0034810a5db21a871e249/pkg/provider/onepassword/onepassword.go#L123-L135

**Comment by rahulii** [comment]
@shuheiktgw this func already checks if the namespace is nil - https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/onepassword/onepassword.go#L133

**Comment by shuheiktgw** [comment]
Hmm, thank you for looking into it @rahulii! You are right and I tried to reproduce it locally but received the following error when I applied the manifest above.

```
Error from server (Forbidden): error when creating "css.yaml": admission webhook "validate.clustersecretstore.external-secrets.io" denied the request: received invalid 1Password SecretStore resource: cluster scope requires namespace
```

@sleyer Did you enable admission webhook? I'm closing this issue since it is not reproducible but feel free to reopen it if necessary 🙂

**Comment by sleyer** [comment]
> Did you enable admission webhook? 

Yes I did. I'll try to create a minimal reproducible example later.

**Comment by sleyer** [comment]
I recreated the issue in a clean local rancher installation. Here is what I did: 
Create a new values file `ExternalSecretValues.yaml`: 

```yaml
webhook:
  create: false
installCRDs: true
certController:
  create: false
revisionHistoryLimit: 5
serviceMonitor:
  enabled: true
```
Create a new manifest `OnePasswordStore.yaml `: 

```yaml
webhook:
  create: false
installCRDs: true
certController:
  create: false
revisionHistoryLimit: 5
serviceMonitor:
  enabled: true
```

Install into rancher: 
```
kubectl ns create external-secrets
kubens external-secrets
helm install external-secrets external-secrets/external-secrets -f ExternalSecretValues.yaml
kubectl apply -f OnePasswordStore.yaml 
```

The secrets operator pod then crash loops as outline above.

**Comment by shuheiktgw** [comment]
Hi @sleyer, thanks for following it up! It seems you disabled the Webhook here. Would you remove the configuration and try it again? 🙏 

```
webhook:
  create: false
```

**Comment by sleyer** [comment]
With webhook and certController enabled, I get: 

```
kubectl apply -f OnePasswordStore.yaml 
Error from server (Forbidden): error when creating "kubernetes/OnePasswordStore.yaml": admission webhook "validate.clustersecretstore.external-secrets.io" denied the request: received invalid 1Password SecretStore resource: cluster scope requires namespace
```

So I guess validation does work. However, shouldn't the Operator at least survive a faulty store, even without the webhook validation?

**Comment by shuheiktgw** [comment]
> However, shouldn't the Operator at least survive a faulty store, even without the webhook validation?

Hmm, unfortunately, that won't work. The webhook is a crucial aspect of Oparator, and if you turn it off, you're responsible for ensuring that it functions properly, not us. It's like removing a guardrail in front of a hole, and then blaming someone else for not installing a guardrail after you fall into it 🙂
