### ISSUE TITLE
Ability to specify serviceAccountRef in kind: ExternalSecret not in kind: SecretStore for vault auth

### ISSUE THREAD

**Issue by iluwaa** [external-secrets/external-secrets#2577]
**Is your feature request related to a problem? Please describe.**
To grant permissions for service account we are using https://developer.hashicorp.com/vault/docs/concepts/policies#templated-policies so we must create kind: SecretStore per every kind: ServiceAccount in namespace to prevent access of all ServiceAccounts to all secrets for that namespace.

**Describe the solution you'd like**
Ability to specify ServiceAccount for auth in kind: ExternalSecret not in kind: SecretStore to decrease count of kind: SecretStore.

**Describe alternatives you've considered**
Create a kind: SecretStore per kind: ServiceAccount

**Comment by moolen** [comment]
Hey, we have a feature called "referent authentication", which allows you to define a `Kind=ClusterSecretStore`, which is shared among all namespaces. For authentication you define a  `serviceAccountRef` without (!!!) specifying the `namespace`. Then the service account from the namespace of the `Kind=ExternalSecret` will be used. Note: the service account name must be the same across namespaces to make that work.

This allows you to implement the least privilege principle without having to configure the same `Kind=SecretStore` for every namespace.

If above :point_up_2: limitation doesn't work for you i suggest using helm/kustomize/your tool of choice to provision those `Kind=SecretStore` per namespace.
It was a deliberate design decision to not store authentication data on the ExternalSecret.

Please let me know if you need further guidance to use that feature :bow:

**Comment by iluwaa** [comment]
We can't use one secret store per namespace because we want to separate access to secrets per service account, e.g. service account "redis" can read secrets only from secrets/<namespace>/redis

**Comment by gusfcarvalho** [comment]
@iluwaa hello! The problem with this approach is that from a security perspective, it means the provider authentication information starts being on the ExternalSecret instead of the SecretStore. This could be used very easily to cause a security breach, unless users specifically deploy their own admission controller setup.

I’d still have authentication information in its separate CRD.


PS: if you need to have in the same Secret data from different credentials in vault, you can always use creationPolicy: Merge

**Comment by iluwaa** [comment]
@gusfcarvalho  Thx for response, it is not our way, but now all clear.

**Comment by iluwaa** [comment]
@gusfcarvalho Thx for response, it is not our way, but now all clear.
