### ISSUE TITLE
External secrets doesn't encoded values in some secrets

### ISSUE THREAD

**Issue by Angel-if** [external-secrets/external-secrets#2578]
Hello, 
I faced some weird issues with my application and during the investigation, I discovered that some values in secrets from the secret manager haven't been encoded as base64. In some secrets, it doesn't encrypt a whole secret as base64 and in some other, it encodes only username and db_name , but leaves the password as plain text.
Could you tell me if somebody faced the same issue and successfully fixed it?
As a temporary workaround, we encode missed values and change them manually in Secret Manager
I used the latest version 0.7.2, but upgrading to 0.9.2 doesn't help.

**Comment by Skarlso** [comment]
Could you please include sample objects for whatever you are using? ExternalSecret, PushSecret, templating, data, daraFrom... etc.. :)
