### ISSUE TITLE
ESO pod crashes repeatedly

### ISSUE THREAD

**Issue by mahiidalavai** [external-secrets/external-secrets#2596]
Hi,

We are users of IBM Cloud Secrets Manager and we are upgrading ESO from version 0.5.2 to a version higher than 0.8.2 ahead of the deprecation of IBM Cloud Secrets Manager V1 in October 2023.

We have observed the following issue with versions 0.9.1 and 0.9.2

For Imported Certificate type secrets held in IBM Cloud Secrets Manager, when no key is present e.g. when we store CA certificates, then the ESO pod crashes repeatedly. In older releases these secrets would have been synched successfully resulting in Openshift Secrets with a tls.crt property present and an empty tls.key property

To recreate the issue 
1.	Create an Imported Certificate type secret in IBM Cloud Secrets Manager with a certificate present but no private key
2.	Create an External Secret yaml mapping certificate and private_key properties to a secret in Openshift/ Kubernetes tls.crt and tls.key properties

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-cert
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: imported_cert/<your secret id>
        property: certificate
      secretKey: tls.crt
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: imported_cert/<your secret id>
        property: private_key
      secretKey: tls.key
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: <your secret store>
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: redis-cert
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: kubernetes.io/tls

3.	The ESO pod should crash

 
Pod log should report errors similar to those below

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
         panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2348d13]
 
goroutine 142 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
         [/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:115](mailto:/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:115) +0x1fa
panic({0x30d63c0, 0x6571d40})
         /opt/hostedtoolcache/go/1.19.10/x64/src/runtime/panic.go:884 +0x212
github.com/external-secrets/external-secrets/pkg/provider/ibm.getImportCertSecret(0xc00155d6d0?, 0xc001fa0a70, {{0xc000cdc940, 0x32}, {0x0, 0x0}, {0xc0009e3cc4, 0xb}, {0x0, 0x0}, ...})
         /home/runner/work/external-secrets/external-secrets/pkg/provider/ibm/provider.go:234 +0xd3
github.com/external-secrets/external-secrets/pkg/provider/ibm.(*providerIBM).GetSecret(0xc000cd0da0, {0x7fb33ac59f18?, 0x30?}, {{0xc000cdc940, 0x32}, {0x0, 0x0}, {0xc0009e3cc4, 0xb}, {0x0, ...}, ...})
         /home/runner/work/external-secrets/external-secrets/pkg/provider/ibm/provider.go:171 +0x4e5
github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).handleSecretData(_, {_, _}, _, {{{0x2c1b648, 0xe}, {0xc001d3c000, 0x1b}}, {{0xc0009e3c80, 0xd}, ...}, ...}, ...)
         /home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller_secret.go:96 +0xd3
github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).getProviderSecretData(0xc00073ccb0, {0x3fa30b8, 0xc001d0e1b0}, 0xc000c7a000)
         /home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller_secret.go:78 +0x2be
github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile(0xc00073ccb0, {0x3fa30b8, 0xc001d0e1b0}, {{{0xc0009e3c78, 0x8}, {0xc0009e3c80, 0xd}}})
         /home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:203 +0xec5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x3fa30b8?, {0x3fa30b8?, 0xc001d0e1b0?}, {{{0xc0009e3c78?, 0x2eb4fa0?}, {0xc0009e3c80?, 0x10?}}})
         [/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118](mailto:/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118) +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000b98b40, {0x3fa3010, 0xc001038ec0}, {0x32fe240?, 0xc000aa5c00?})
         [/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314](mailto:/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314) +0x3a5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000b98b40, {0x3fa3010, 0xc001038ec0})
         [/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265](mailto:/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265) +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
         [/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226](mailto:/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226) +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
         [/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:222](mailto:/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:222) +0x333
 

We have communicated the details of this issue with the IBM contributors directly and have logged the issue here for tracking purposes.

**Comment by IdanAdar** [comment]
This is correct. That said, we are fixing the provider to produce an error instead of crashing!

**Comment by IdanAdar** [comment]
Additional fix: https://github.com/external-secrets/external-secrets/pull/2629 will be included in 0.9.4

**Comment by mahiidalavai** [comment]
@IdanAdar Is 0.9.4 is available for installation or yet to released, If not yet released, which date we can expect this release.?

**Comment by moolen** [comment]
We'll be providing a release soon (next days)
