### ISSUE TITLE
Extrack Keys and Certificate from PKCS12#12 Archive

### ISSUE THREAD

**Issue by chiliast123** [external-secrets/external-secrets#2607]
For this reference link: https://external-secrets.io/latest/guides/common-k8s-secret-types/#tls-cert-example

apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret  
metadata:
     name: template-tls-example
spec:
    refreshInterval: 1h 
    secretStoreRef:
        name: example
        kind: SecretStore
    target:
       name: secret-to-be-created # this is how the Kind=Secret will look like
       template:
          type: kubernetes.io/tls
          data:
              tls.crt: "{{ .mysecret | pkcs12cert | pemCertificate }}"
              tls.key: "{{ .mysecret | pkcs12key | pemPrivateKey }}"
   data: 
# this is a pkcs12 archive that contains 
# a cert and a private key
   - secretKey: mysecret
   -  remoteRef:
          key: ssl-certificate-p12-example

Hello, sorry to bother, but I need help! why it didn't work on the Alibaba Cloud? the others is fine, if I removed the template part, it worked perfectly. so it's the template section can't work on Alibaba, I don't know why, so asking for help. 
thank you very much
Best Regards

**Comment by gusfcarvalho** [comment]
did you remove the `type` from it? If so, can you share the error that you've got? "Not working" might mean a lot of things, it's really hard to help without the needed information :)
