### ISSUE TITLE
Big increase memory usage version 0.9.2

### ISSUE THREAD

**Issue by rvos-73** [external-secrets/external-secrets#2608]
**Describe the bug**
We updated from 0.9.1 to 0.9.2 and the memory usage increased from ~100MB to 900MB

**Expected behavior**
Similar memory requirements as 0.9.1

**Additional context**
External secrets is not actively used yet. There are no external secret CR's, so it's just the ESO application starting up. At startup, the memory usage spiked to >1GB on one of our clusters. This cluster has 128 namespaces, mayby it's related to this.

**Comment by shuheiktgw** [comment]
Hmm, two of the suspicious changes are the following:

- https://github.com/external-secrets/external-secrets/pull/2486
- https://github.com/external-secrets/external-secrets/pull/2505

For https://github.com/external-secrets/external-secrets/pull/2486, I doubt it could increase the memory consumption by 800MB. For example, Namespace Spec and Status are basically nothing, so labels and annotations are ones that could consume memory. Let's assume each Namespace has 100 labels and 100 annotations, each label (annotation) consists of 200 characters, and there are 500 Namespaces in the cluster. Even if the controller-runtime caches all the Namespaces, it consumes (100 + 100) * 200 * 500 * 2 bytes = 40 megabytes, quite far from 800 MB. 

For https://github.com/external-secrets/external-secrets/pull/2505, I think this could increase memory consumption if controller-runtime caches not only metadata but also data of all the Secrets in the cluster. I need to dig into the controller-runtime to see how it is implemented, so give me some time.

**Comment by shuheiktgw** [comment]
@rvos-73 In the meantime, would you tell me roughly how many Secrets you have in your cluster?

**Comment by gusfcarvalho** [comment]
@rvos-73 can you try to disable ClusterExternalSecrets to see if the behavior changes?

Also, can you share what are the configuration options that you used to deploy external-secrets?

**Comment by shuheiktgw** [comment]
Sorry that I cannot take time to investigate it further. I'm a little swamped with work this week. I'll look into it tomorrow🙂
