### ISSUE TITLE
GCP:  support more authentication methods

### ISSUE THREAD

**Issue by moolen** [external-secrets/external-secrets#261]
Right now we only support explicit service account bindings with `Kind=Secret`. We could support a similar approach like in the aws provider:

1. use explicit configuration from `Kind=SecretStore`: GCP service account, Kubernetes SA JWT (workload identity) etc. ([api opts](https://pkg.go.dev/google.golang.org/api/option#WithTokenSource))
2. fallback to controller environment: [SDK defaults](https://cloud.google.com/docs/authentication/production) (via environment variables, instance metadata API)

for reference, the secrets-store-csi-driver has implemented that here:
https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp/blob/main/auth/auth.go

ref:
https://github.com/external-secrets/external-secrets/blob/0613b904b620d5332c38ab3ba7c0aa4e740dd2c5/pkg/provider/gcp/secretmanager/secretsmanager.go#L72-L77

**Comment by mouhsen-ibrahim** [comment]
Actually I already implemented workload identity for my company and I am using it there, I will create a PR soon for this

**Comment by Atoms** [comment]
Any updates on this ? :)

**Comment by knelasevero** [comment]
I can't take this one right now. @mouhsen-ibrahim you mean that you did a similar thing in another project? Or at a fork of external-secrets?

**Comment by renaudguerin** [comment]
@mouhsen-ibrahim Super interested in your workload identity support PR !
This is blocking me from migrating to ESO (I've just started with KES which does support WI)

**Comment by mouhsen-ibrahim** [comment]
@knelasevero @renaudguerin Sorry for the delay, here is my PR #339
