### ISSUE TITLE
can't get access in pod external secret, please help.

### ISSUE THREAD

**Issue by chiliast123** [external-secrets/external-secrets#2615]
![mmexport1692179548577](https://github.com/external-secrets/external-secrets/assets/122135142/c4ee84a4-94ad-497d-b1f5-6d316b4730b1)

**Comment by gusfcarvalho** [comment]
Access to external-secrets pod is not part of our base image.

if you want to do that (we explicitly recommend you not to), you’ll need to create your own custom image on top of ours, or build external-secrets yourself

**Comment by chiliast123** [comment]
okay, thank you

**Comment by chiliast123** [comment]
what I have to do if I want to get access to external-secrets pod, what’s the dockerfile looks like? I tried to build a custom image but I get this:&nbsp;


OCI runtime create failed: comtainer_linux.go：349: starting container process caused “exec: \“/bin/sh\”：stat /bin/sh: no such file or directory: unknown

发自我的iPhone


------------------ Original ------------------
From: Gustavo Fernandes de Carvalho ***@***.***&gt;
Date: Wed,Aug 16,2023 7:36 PM
To: external-secrets/external-secrets ***@***.***&gt;
Cc: chiliast123 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [external-secrets/external-secrets] can't get access in podexternal secret, please help. (Issue #2615)





 
Access to external-secrets pod is not part of our base image.
 
if you want to do that (we explicitly recommend you not to), you’ll need to create your own custom image on top of ours, or build external-secrets yourself

**Comment by moolen** [comment]
You can run `kubectl debug` to create an ephemeral container. That allows you to debug issues.
