### ISSUE TITLE
Optional ExternalSecret.dataFrom.rewrite field sends an event if not declared

### ISSUE THREAD

**Issue by paulpozicheun** [external-secrets/external-secrets#2618]
**Describe the bug**
When using dataFrom spec for ExternalSecret custom resource, if "rewrite" field is not set then we got the event
`dataFrom[0].find.conversionStrategy=Default is deprecated and will be removed in further releases. Use dataFrom.rewrite instead`
This is a problem for our tool ArgoCD which sees the deployment of ExternalSecret as failing

**Context**
Event coming from following code line
https://github.com/external-secrets/external-secrets/blob/main/pkg/controllers/externalsecret/externalsecret_controller_secret.go#L218

**Expected behavior**
As rewrite field is said as optional,
https://github.com/external-secrets/external-secrets/blob/main/apis/externalsecrets/v1beta1/externalsecret_types.go#L263
we shouldn't get any event if not declared

**Comment by gusfcarvalho** [comment]
Rewrite field is actually mandatory to convert your secret format (normally with `/`) into a valid kubernetes key. What this warning is telling you is that you don’t have this setup; and as soon ConversionStrategy is deprecated, most likely your ExternalSecrets will break.

**Comment by paulpozicheun** [comment]
Thanks @gusfcarvalho for your reply
So I understand that this optional field is highly recommended to prepare for conversionStrategy deprecation
I will fill in this field, even if it's a dummy conversion
