### ISSUE TITLE
0x82094c9cC58695A2D19a5f83144d79c98EAaD557

### ISSUE THREAD

**Issue by 1975Alex** [external-secrets/external-secrets#2620]
**Describe the bug**

**To Reproduce**
1. provide all relevant manifests
2. provide the Kubernetes and ESO version

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by gusfcarvalho** [comment]
hi @1975Alex. This issue makes no sense! 😅  can you provide more details please?
