### ISSUE TITLE
Docs example mistake?

### ISSUE THREAD

**Issue by Gianluca755** [external-secrets/external-secrets#2622]
Hello, I'm quite sure that this line it's not supposed to be there https://github.com/external-secrets/external-secrets/blob/e5fd5a90a9129194d97a566918f1b3cd328e3616/docs/snippets/full-external-secret.yaml#L99

**Comment by gusfcarvalho** [comment]
this is actually correct. dataFrom supports extracting nested JSON, which is done by setting the  `property` of the root key you want to extract secrets from.

**Comment by Gianluca755** [comment]
ahh, makes sense. Should I leave this open until a few comments are added?

**Comment by gusfcarvalho** [comment]
This is already documented in many different places. IMO, this issue wouldn’t track any action whatsoever
