### ISSUE TITLE
Bcrypt - Template function

### ISSUE THREAD

**Issue by hanseltime** [external-secrets/external-secrets#2656]
**Is your feature request related to a problem? Please describe.**
I would like to start managing ArgoCD as IAC from my primary cloud platform - AWS.   In order to create and manage access passwords for ArgoCD for users in secrets manager, the application uses bcrypt hashes of passwords in the secret it references.

I am unable to transform the bcrypt version of the password and so now have to stand up a "bcrypt the value in secrets manager" policy which is not easily captured in configuration compared to something like `{ bcrypt .password }`.

**Describe the solution you'd like**
I would like to have a brcypt function available that basically proxies the golang bycrypt library [GenerateFromPassword function](https://pkg.go.dev/golang.org/x/crypto/bcrypt).

Example usage:

```
// Using default cost
{ bcrypt .password }
// Using specified cost
{ bcrypt .password 4 }
```

**Describe alternatives you've considered**
The alternative I will be going with is to create a CDK construct for "Argo Passwords" that bcrypts the secret in the external source.  There will be manual documentation around this for myself and others to remember that updating this secret requires a transform step.

**Additional context**

N/A

**Comment by muckelba** [comment]
Just stumbled across the **exact** same issue and would love this being implemented 😄

**Comment by hanseltime** [comment]
Just want to add here, that I went looking into the source and it looks like sprig currently does bcrypt with default cost value set using the golang bcypt library.

```yaml
{{ .secretValue | bcrypt }}
```

You can find the implementation here: https://github.com/Masterminds/sprig/blob/581758eb7d96ae4d113649668fa96acc74d46e7f/crypto.go#L54
