### ISSUE TITLE
External-secret error AccessDeniedException for cross AWS Account secret manager

### ISSUE THREAD

**Issue by majidfaridi** [external-secrets/external-secrets#2685]
**Describe the bug**
Trying to fetch the secret in AWS Account 1 (in which AWS EKS and ESO are installed ) from AWS Account 2 (in which the secret resists) but I faced this error:

Warning  UpdateFailed  1s (x12 over 12s)  external-secrets  AccessDeniedException: User: arn:aws:sts::AWSACCOUNTID1:assumed-role/EKSSecretsReaderRole/external-secrets-provider-aws is not authorized to perform: secretsmanager:GetSecretValue on resource: appsecret/test/new-test because no identity-based policy allows the secretsmanager:GetSecretValue action
           status code: 400,`

Note: I have to mention that I can perfectly get any secret from AWS Account 1 but I can not get a secret from AWS Account 2 (cross AWS account)!!

**What I did**
1. I Installed AWS EKS, and ESO (installed in external-secrets namespace)
2. Create AWS policy and Role in AWS Account 1
3. Create a secret in secret manager in AWS Account 2 with a specific policy 
4. Give access to KMS on AWS Account 2 to Role of AWS Account 1
5. Create and service account ( service account name external-secrets ) in the external secret  namespace with annotation of role in AWS Account1
6. Create a cluster secret store and give access to the service account of external-secret.
7. Both secrets exist in both AWS Accounts in the us-east-2 region

-------
Role Trust relationships:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::AWSACCOUNT1ID:oidc-provider/oidc.eks.us-east-2.amazonaws.com/id/11111112222333333"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-east-2.amazonaws.com/id/11111112222333333:aud": "sts.amazonaws.com",
                    "oidc.eks.us-east-2.amazonaws.com/id/11111112222333333:sub": "system:serviceaccount:external-secrets:external-secrets"
                }
            }
        }
    ]
}

-------
Polic has attached to the role:
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "secretsmanager:GetResourcePolicy",
                "secretsmanager:GetSecretValue",
                "secretsmanager:DescribeSecret",
                "secretsmanager:ListSecretVersionIds"
            ],
            "Resource": [
                "arn:aws:secretsmanager:us-east-2:AWSACCOUNT1ID:secret:appsecret/dev/*",
                "arn:aws:secretsmanager:us-east-2:AWSACCOUNT1ID:secret:appsecret/stage/*",
                "arn:aws:secretsmanager:us-east-2:AWSACCOUNT2ID:secret:appsecret/test/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": "kms:Decrypt",
            "Resource": [
                "arn:aws:kms:us-east-2:AWSACCOUNT1ID:key/KMSIDINAWSACCOUNT1",
                "arn:aws:kms:us-east-2:AWSACCOUNT2ID:key/KMSIDINAWSACCOUNT2"
            ]
        }
    ]
}

-------
Policy has attached to secret on AWS Account 2:
{
  "Version" : "2012-10-17",
  "Statement" : [ {
    "Effect" : "Allow",
    "Principal" : {
      "AWS" :  "arn:aws:iam::AWSACCOUNT1ID:role/EKSSecretsReaderRole"
    },
    "Action" : "secretsmanager:*",
    "Resource" : "*"
  } ]
}

-------
Added policy to KMS in AWS Account 2:
{
  "Sid": "AllowUseOfTheKeyFromAWSACCOUNT1IDEKSSecretsReaderRole",
  "Effect": "Allow",
  "Principal": {
      "AWS": [
          "arn:aws:iam::AWSACCOUNT1ID:role/EKSSecretsReaderRole"
      ]
  },
  "Action": [
      "kms:Decrypt",
      "kms:DescribeKey"
  ],
  "Resource": "*"
}

**Expected behavior**
I expect that when trying to apply my external secret object to fetch my secret from the cross AWS Account and create a secret from that object's external secret.

**Screenshots**
When I am trying to apply an external secret object it shows SecretSyncedError with this error:
Events:
  Type     Reason        Age                From              Message
  ----     ------        ----               ----              -------
Warning  UpdateFailed  1s (x12 over 12s)  external-secrets  AccessDeniedException: User: arn:aws:sts::AWSACCOUNTID1:assumed-role/EKSSecretsReaderRole/external-secrets-provider-aws is not authorized to perform: secretsmanager:GetSecretValue on resource: appsecret/test/new-test because no identity-based policy allows the secretsmanager:GetSecretValue action
           status code: 400,

**Additional context**
EKS version: 1.26
ESO helm chart version: v0.8.3

In the end, I have to say again I get any secret from the same AWS account that EKS has been installed but I can not get a secret from a cross AWS Account!!

**Comment by moolen** [comment]
Hey, can you share your `ExternalSecret` and `SecretStore` resources?
Typically i would configure the `SecretStore` to authenticate with IRSA using a role in `AWS_ACCOUNT_1`. That role only allows `sts:assumeRole` permissions, so that ESO is able to assume a role in `AWS_ACCOUNT_2`.

That role in `AWS_ACCOUNT_2` has all the permissions needed to read secrets + decrypt using KMS.

**Comment by majidfaridi** [comment]
Hi Moolen, Thanks for your answer, sure 

here is my external secret config:
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
  name: new-app-externalsecret
  namespace: external-secrets
spec:
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: appsecret/test/new-test
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: development-css
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: new-app-secret

-----
and this external-secret object is going to use clustersecretstore which is:
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: development-css
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets

-----
and this clustersecret is going to use service account in external-secrets namespace:
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::AWSACCOUNT1ID:role/EKSSecretsReaderRole
  labels:
    app.kubernetes.io/instance: external-secrets
  name: external-secrets
  namespace: external-secrets

**Comment by majidfaridi** [comment]
Hey Moolen, I just want to say thank you for your tips that helped me a lot, I fixed the problem by doing the below changes: 

1. I added allows the role to sts:assumeRole permissions in Account1 to assume the role of account2.
2. Added this line `role: arn:aws:iam::AWSACCOUNTID2:role/AllowReadSecret` to the ClusterSecretStore object.

by changing the above config my External-secrets is able to create a secret.

Again Thank you so much. :)

**Comment by moolen** [comment]
Hey, glad to hear it worked! 

I think the setup you described above should work, too. I think you just need to specify the `key: appsecret/test/new-test
` as a valid ARN. Otherwise ESO tries to fetch the secret `appsecret/test/new-test` from `ACCOUNTID1`.  

---
ARN is `arn:${Partition}:secretsmanager:${Region}:${Account}:secret:${SecretId}`, which will not just contain the name of the secret, but it also appends a dash followed by a string of characters that are unique to that secret.

The following CLI command will provide the complete ARN of the secret considering that appsecret/test/new-test is the name of your secret:

```
aws secretsmanager describe-secret --secret-id appsecret/test/new-test
```

You would also find the complete ARN of the secret in the Secrets Manager console -> by selecting the name of the secret -> under "Secret details" section.


[Taken from here](https://repost.aws/questions/QUr9ooir71Sb20KUcVfEY1uA/aws-elasticbeanstalk-ec2-role-aws-elasticbeanstalk-ec2-role-is-not-authorized-to-perform-secretsmanager-getsecretvalue-although-the-default-role-is-updated-to-include-policy) :sweat_smile:
