### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by smartaquarius10** [external-secrets/external-secrets#2694]
Hello,

I have never contributed to any other open source github application. I really need to contribute here in the external-secrets repo. Can someone guide me how to start. 

Would be grateful for your support. Thank you.

Regards,
Tanul

**Comment by gusfcarvalho** [comment]
Hi @smartaquarius10 ! You can start with any issue to contribute - the easiest ones are marked with 'good first issue'.

You can ask questions to the issue on the issue itself, and any implementation/code questions can also be asked in Kubernetes slack, on #external-secrets-dev channel.

**Comment by smartaquarius10** [comment]
Thanks @gusfcarvalho.. Will check this
