### ISSUE TITLE
API Guide Returning 404

### ISSUE THREAD

**Issue by tath81** [external-secrets/external-secrets#2695]
**Describe the bug**

Navigating to https://external-secrets.io/v0.9.4/api/guides gives a status code 404.

**Comment by moolen** [comment]
hey, where did you get that link from? We've restructured the docs a couple of times. You're probably looking for: https://external-secrets.io/latest/guides/introduction/

**Comment by tath81** [comment]
Originally when I browsed the `Guides` section the redirection did not work which threw the 404. It seems to be working now. I'll close this out thx.
