### ISSUE TITLE
ECRAuthorizationTokenList not registered in schemebuilder

### ISSUE THREAD

**Issue by kentlaiss** [external-secrets/external-secrets#2696]
I am trying to write some test code, and got an error that ECRAuthorizationTokenList is not registered in the scheme. I noticed this in the registration of the scheme
https://github.com/external-secrets/external-secrets/blob/3dcd3df41c8797bf890af5e0eb278314a27b4b7c/apis/generators/v1alpha1/register.go#L88

Should the second parameter be ECRAuthorizationTokenList instead?

**Comment by moolen** [comment]
Yeah, that looks like it, good catch!
