### ISSUE TITLE
Kubernetes provider should allow creation of secret of types other than Opaque

### ISSUE THREAD

**Issue by aveyrenc** [external-secrets/external-secrets#2709]
**Is your feature request related to a problem? Please describe.**
When using a PushSecret to copy a secret from one cluster to another, the Kubernetes provider currently [hardcodes](https://github.com/external-secrets/external-secrets/blob/v0.9.4/pkg/provider/kubernetes/client.go#L328) the target secret's type to Opaque

**Describe the solution you'd like**
We should be able to override the target secret's type, or maybe copy the type from the source secret. For example, this would allow copying secrets used by `imagePullSecrets`, which are using the `kubernetes.io/dockerconfigjson` type.

**Comment by HamzaMasood1** [comment]
May I take this one?

**Comment by HamzaMasood1** [comment]
So just to clarify, when copying a secret from one k8s cluster to another k8s cluster, I will try to retain the type of the secret instead of the hard coded value.

**Comment by minhoryang** [comment]
@HamzaMasood1 how's the progress going?
