### ISSUE TITLE
Using HTTP Proxy

### ISSUE THREAD

**Issue by mtanida** [external-secrets/external-secrets#2712]
**Is your feature request related to a problem? Please describe.**
My Cluster cannot access the providers directly, since it does not have direct Internet access. Instead, it must go through a proxy server. Is there a way to configure the Provider to go through an HTTP proxy? In my case, i am using the GCP Provider.

**Describe the solution you'd like**
I would like some mechanism to specify an HTTP proxy

**Describe alternatives you've considered**

**Additional context**

**Comment by moolen** [comment]
Did you try to set `HTTP_PROXY` and `HTTPS_PROXY` environment variables on the ESO pod?
AFAIK the GCP / gRPC golang sdk supports that out of the box.

**Comment by mtanida** [comment]
I haven't tried that yet. But thank you - I'll see if that works out of the box

**Comment by mtanida** [comment]
OK - defining http_proxy, https_proxy, and no_proxy environment variables in extraEnv in my values files worked. Thanks.
