### ISSUE TITLE
While changing the readiness probe for cert-controller in values.yaml the cert-controller deployment readiness doesn't get changed

### ISSUE THREAD

**Issue by rnadeem-amzn** [external-secrets/external-secrets#2713]
Change the value of readiness port for cert-manger in values.yaml, it will not changed in the deployment.yaml of cert-controller since the readiness port is hardcoded in the cer-controller-deployment.yaml file. (line no 74-78)

          readinessProbe:
            httpGet:
              port: 8081
              path: /readyz
            initialDelaySeconds: 20

It should be 

          readinessProbe:
            httpGet:
              port: {{ .Values.certController.readinessProbe.port }}
              path: /readyz

**Comment by shuheiktgw** [comment]
Thank you, @rnadeem-amzn! You are totally right, and I fixed it in https://github.com/external-secrets/external-secrets/pull/2732
