### ISSUE TITLE
ESO controller not respecting `controllerClass` for pushSecrets

### ISSUE THREAD

**Issue by fad3t** [external-secrets/external-secrets#2714]
As a follow-up of https://github.com/external-secrets/external-secrets/issues/2164, I think there's something wrong with the `controllerClass` of ESO when it's about `pushSecrets`.

For example, I have:
- two controllers, with controllerClass A and B;
- a secretStore linked to controller A;
- a pushSecret referencing this secretStore.

I'm expecting this `pushSecret` to be processed by controller A only - however I see in controller B logs the following:
```
{"level":"error","ts":1695128565.8747964,"msg":"Reconciler error","controller":"pushsecret","controllerGroup":"external-secrets.io","controllerKind":"PushSecret","PushSecret":{"name":"pushsecret","namespace":"<namespace>"},"namespace":"<namespace>","name":"pushsecret","reconcileID":"c5cc02f9-6392-45ef-9269-ba5f79c9ac69","error":"could not get secrets client for store <secretStore>: can not reference unmanaged store","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:265\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.1/pkg/internal/controller/controller.go:226"}
```

Not sure anyone has time for this, I'll try to have a look one of these days and propose something is that's at my fingertips :)

**Comment by gusfcarvalho** [comment]
ControllerClass for PushSecret, I’m not sure they are introduced yet. If they are, for sure only in fairly recent versions. What ESO version are you using?

**Comment by fad3t** [comment]
Hi @gusfcarvalho, I'm running the latest version, v0.9.4.

**Comment by gusfcarvalho** [comment]
I confirmed, this hasn’t been implemented yet. So this is why it’s not working :)

**Comment by fad3t** [comment]
I ended up using a single controller, with one `SecretStore` per namespace. This does the trick and remains quite simple.
So this can be closed.
