### ISSUE TITLE
Support string functions in template

### ISSUE THREAD

**Issue by keyolk** [external-secrets/external-secrets#2716]
I want to build some documents based on existing secrets with the ESO.
For that, I think it would be nice if we could use some string functions like
- hasPrefix
- Contains

Is there any reason that it doesn't support this?
Seems no functions except here https://github.com/external-secrets/external-secrets/blob/main/pkg/template/v2/template.go#L28

It can be used like 
```go
  target:
    template:
      engineVersion: v2
      data:
        secret.json: |
        {{- $secret := dict }}
        {{- range $key, $value := . }}
        {{- if Contains $key "test" }}
        {{- $_ := set $secret $key $value }}
        {{- end }}
        {{- toJson $secret | nindent 10}}
```

**Comment by gusfcarvalho** [comment]
we support all sprigs strings functions https://masterminds.github.io/sprig/strings.html, including `contains` and `hasPrefix` 😅  maybe there is aproblem with the manifest itself?

One thing I already have noticed, `contains` needs to be lowercase, and you have upper case in your example

**Comment by keyolk** [comment]
Oh didnt know that! Thx alot
