### ISSUE TITLE
support `sourcreRef.generatorRef` in `.data[]` entries

### ISSUE THREAD

**Issue by kangjk1017** [external-secrets/external-secrets#2720]
Hello,

I have come across an issue with the example YAML file provided in the official documentation.
- document : https://external-secrets.io/v0.9.4/api/externalsecret/
- example yaml : https://github.com/external-secrets/external-secrets/blob/a025b77e49ffdb778cdc7acd5192ae2aa313cfaf/docs/snippets/full-external-secret.yaml#L88C12-L88C12

According to the source code, sourceRef.generatorRef should only be used on dataFrom, not on data.
The operation of `handleSecretData` does not refer to `generator`.
However, the example in the documentation seems to imply that it works with spec.data, which is not the case.
- source code : https://github.com/external-secrets/external-secrets/blob/main/pkg/controllers/externalsecret/externalsecret_controller_secret.go#L78C12-L78C28

The guide should be updated to reflect this. Please let me know if any further clarification is needed.

Thank you!

**Comment by moolen** [comment]
Thanks for the time writing up this issue, i'd say we can and should support sourceRef with generator in `data` (like it is documented).

**Comment by gusfcarvalho** [comment]
There is just one problem with using generators on data. If users do two consecutive calls on a generator (to get e.g. the username and the password), it will create the credentials twice, generating a username and a password that don’t even match 

I think that was the reason that we dropped the implementation there @moolen

**Comment by moolen** [comment]
good point, a user would have to specify a `property` for this use-case. Then it doesn't make sense to have a generator there.
Then i guess it would be good to remove it from the docs (and fix the type, so we get static validation for that).
