### ISSUE TITLE
Is there a limit on ExternalSecret name length ?

### ISSUE THREAD

**Issue by paulpozicheun** [external-secrets/external-secrets#2776]
**Describe the bug**
When creating an ExternalSecret with name of more than 46 characters, the ES is synced but no secret is created and ES is refreshed by ESO every minute

**To Reproduce**
1. Provider is Azure KeyVault
2. OpenShift version = 4.10.52
3. ESO version = v0.9.3
4. Create an ExternalSecret with name of more than 46 characters

**Expected behavior**
Check that no secret is created from ExternalSecret and that it is refreshed continuously by ESO

**Screenshots**
No screenshot

**Additional context**
Is it coming from ESO limitation or from our environment configuration ?

**Comment by moolen** [comment]
hey! This is a known issue of 0.9.3, see here: https://github.com/external-secrets/external-secrets/issues/2647
It has been fixed in subsequent versions.

**Comment by paulpozicheun** [comment]
Ouh ! Shame on me ! I didn't follow the ESO history
Sorry and thx for your answer @moolen

**Comment by moolen** [comment]
don't no worries :)
