### ISSUE TITLE
FOSS License Scan is failing, but results are available to maintainers only

### ISSUE THREAD

**Issue by pre** [external-secrets/external-secrets#2795]
The FOSS License Scan is failing, but the 3rd party service does not disclose the results for non-maintainers.

Could you please create ticket for each failing scan and/or report here which scans are failing? 

Thank you!

<img width="1060" alt="image" src="https://github.com/external-secrets/external-secrets/assets/63895/294ae3dc-4068-40af-99b4-909e62fdc498">

**Comment by moolen** [comment]
hey @pre, i've sent you an invite for FOSSA, now you should be able to see all the stuff. 

The failing license scans are a bit of a PITA to maintain. 
Whenever a dependency version changes and there is a false positive in it, we have to manually approve the new version  :REEEE:
