### ISSUE TITLE
Add enum validation markers to the provider CRDs

### ISSUE THREAD

**Issue by shuheiktgw** [external-secrets/external-secrets#2820]
**Is your feature request related to a problem? Please describe.**
In https://github.com/external-secrets/external-secrets/pull/2819, I've added some validation markers to the enum fields, but later I found some enum fields in the providers' CRD miss those markers as well. For example https://github.com/external-secrets/external-secrets/blob/593eb139990bc0deeb437dfffc8b4d46bcfeea4f/apis/generators/v1alpha1/generator_vault.go#L42

This would be a good issue to work on for new contributors, so I'll just leave it as is 🙂 

**Describe the solution you'd like**
Add proper enum validation markers

**Additional context**
- https://github.com/external-secrets/external-secrets/pull/2819

**Comment by lakhanjindam** [comment]
@shuheiktgw i have attached a PR related to the issue, please review
