### ISSUE TITLE
PushSecret cannot delete secret from AWS Secrets Manager immediately

### ISSUE THREAD

**Issue by AndriySidliarskiy** [external-secrets/external-secrets#2830]
**Describe the bug**
PushSecret cannot delete secrets from AWS Secrets Manager immediately so it means when you delete push secrets he moves the secret in the secrets manager to 7 days retention so you cannot create another secret with the same name.

**Comment by moolen** [comment]
Agree, this is a bug, we should set `ForceDeleteWithoutRecovery=true` in the operator!

**Comment by AndriySidliarskiy** [comment]
@moolen can i do this in helm charts or not?

**Comment by moolen** [comment]
Nop, but this requires only a 1 line code change.

Can you do it? Happy to review :D

**Comment by AndriySidliarskiy** [comment]
but seems it`s done https://github.com/external-secrets/external-secrets/blob/06301854d0f7b575895d5b0bed411fc36d585ba2/e2e/suites/provider/cases/aws/secretsmanager/provider.go#L137

**Comment by moolen** [comment]
Thats just the e2e tests, needs to be done in pkg/provider/aws/secretsmanager in the DeleteSecret func call

**Comment by korenyoni** [comment]
I have a PR for this here: https://github.com/external-secrets/external-secrets/pull/2854

**Comment by witchbutter** [comment]
Why is this only available in SecretStore and not ClusterSecretStore?
