### ISSUE TITLE
Best initial secret bootstrapping pattern

### ISSUE THREAD

**Issue by maxkokocom** [external-secrets/external-secrets#2833]
**Is your feature request related to a problem? Please describe.**
I would like to ask for recommended pattern to a chicken and an egg problem of initial secret creation. If I am using AWS as my backend I still need to create initial secret by hand, by terraform (plaintext state file), by another secret solution like SOPS etc. It does seem a bit problematic. 

**Describe the solution you'd like**
I would like an example how to solve it in a nicer way, for example using EKS IRSA or other solutions depending on the backend.

**Comment by moolen** [comment]
Hey @maxkokocom, particularly for EKS: yes, you should use IRSA :100: recommended. 
There are slight differences on how to integrate ESO with IRSA, the different approaches are documented here: https://external-secrets.io/latest/provider/aws-secrets-manager/#eks-service-account-credentials

**Comment by moolen** [comment]
I just found an Article on the AWS blog describing the process: https://aws.amazon.com/blogs/containers/leverage-aws-secrets-stores-from-eks-fargate-with-external-secrets-operator/, there are many more out the on the interwebs. You can also check out our linked blog articles: https://external-secrets.io/latest/eso-blogs/

**Comment by maxkokocom** [comment]
Thank you very much!
