### ISSUE TITLE
Fake Provider's ValueMap field is inconsistent

### ISSUE THREAD

**Issue by shuheiktgw** [external-secrets/external-secrets#2845]
**Describe the bug**
While working on https://github.com/external-secrets/external-secrets/issues/2835, I noticed the fake provider has a field called [ValueMap](https://github.com/external-secrets/external-secrets/blob/05303859928ddbed95a841516702a79d13fc8f95/apis/externalsecrets/v1beta1/secretstore_fake_types.go#L25), which is only referenced from the GetSecretMap method.

There are two types of providers, one has two layered secrets, such as Google Secret Manager Provider and the other one has three layered secrets, such as Kubernetes Provider.  IIUC, the Fake Provider belongs to the former group, but it contains three layered secrets (ValueMap). This is unintuitive, and if we need to support the GetSecretMap method for the fake provider, instead of adding the ValueMap field, it would be much more consistent if we take the same approach as [the Google Secret Manager Provider does](https://github.com/external-secrets/external-secrets/blob/99194e0237559f906c7e199cae90c2e4bffc17a5/pkg/provider/gcp/secretmanager/client.go#L475).

WDYT? 🤔 

**Suggestions**

1. Deprecate the ValueMap field and remove it from the Fake Provider documentation.
2. Fix the GetSecretMap method by taking the same approach as the Google Secret Manager Provider. Note that we must keep supporting the old behavior until we remove the ValueMap field itself for backward compatibility.

**Comment by vsantos** [comment]
Hello @shuheiktgw, I'm quite new to open-source, and I'm wondering if I can work on this fix to learn more about the external-secrets project and its processes. Is that okay? Maybe if I take a while to finish? Since this bug doesn't sound critical, it seems an excellent opportunity to start with.

**Comment by shuheiktgw** [comment]
Sure!

**Comment by shuheiktgw** [comment]
Just FYI, but we still need to remove the old value map field, so I'll keep the issue open until then.
- https://github.com/external-secrets/external-secrets/pull/2884
