### ISSUE TITLE
AWS - ExternalSecret ERROR "could not get secret data from provider"

### ISSUE THREAD

**Issue by mpzfm1** [external-secrets/external-secrets#2858]
We have installed ESO Operator from "Operator Hub" into ocp4.12

Then, we have configured correctly a "secretstore" ( in status its in valid state and in aws console we can see it has connected correctly from IAM access advisor) but, when we create a externalsecret pointing to that secretstore we receive the following error:

"could not get secret data from provider" ( in the status of the externalsecret object) , and the output log of the pod is:

{
    "level": "error",
    "ts": 1699293578.8549397,
    "logger": "controllers.ExternalSecret",
    "msg": "could not get secret data from provider",
    "ExternalSecret": {
        "name": "secretspoc-back-externalsecret-app",
        "namespace": "pruebas"
    },
    "error": "RequestError: send request failed\ncaused by: Post \"https://secretsmanager.eu-west-1.amazonaws.com/\": **net/**http: invalid header field value for \"Authorization\"",****
    "stacktrace": "github.com/external-secrets/external-secrets/pkg/controllers/externalsecret.(*Reconciler).Reconcile\n\t/home/runner/work/external-secrets/external-secrets/pkg/controllers/externalsecret/externalsecret_controller.go:212\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:227"
}

thanks

**Comment by moolen** [comment]
Can you share your SecretStore spec? 
This `invalid header field value for "Authorization"` is typically when you use static credentials and have a linebreak, carriage-return or other invalid symbol in the header. This typically happens when you create the kubernetes secrets from hand. E.g. with:

```
echo "my_secret_password" | base64
```
and copy that into a secret. that does NOT work, because `echo` appends a newline `\n` at the end.

**Comment by mpzfm1** [comment]
`apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  creationTimestamp: '2023-11-07T07:03:44Z'
  generation: 1
  labels:
    app: secretspoc-back
  managedFields:
    - apiVersion: external-secrets.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:labels':
            .: {}
            'f:app': {}
        'f:spec':
          .: {}
          'f:data': {}
          'f:refreshInterval': {}
          'f:secretStoreRef':
            .: {}
            'f:kind': {}
            'f:name': {}
          'f:target':
            .: {}
            'f:creationPolicy': {}
            'f:deletionPolicy': {}
            'f:name': {}
            'f:template':
              .: {}
              'f:data':
                .: {}
                'f:BBDD_PASSWORD_APP': {}
                'f:BBDD_USER_APP': {}
              'f:engineVersion': {}
              'f:mergePolicy': {}
              'f:type': {}
      manager: Mozilla
      operation: Update
      time: '2023-11-07T07:03:44Z'
    - apiVersion: external-secrets.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:conditions': {}
      manager: external-secrets
      operation: Update
      subresource: status
      time: '2023-11-07T07:03:44Z'
  name: secretspoc-back-externalsecret-app
  namespace: soporte-trazageo-d-ri
  resourceVersion: '241035744'
  uid: 35ea33e4-b531-4437-8bdc-4b3a27a3e9b8
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: d/rds/trazageo/secretspoc/secretspoc_app
        property: username
      secretKey: username
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: d/rds/trazageo/secretspoc/secretspoc_app
        property: password
      secretKey: password
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: rotado-secrets-ocp4-clustersecretstore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: secretspoc-back-secret
    template:
      data:
        BBDD_PASSWORD_APP: '{{ .password }}'
        BBDD_USER_APP: '{{ .username }}'
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
status:
  conditions:
    - lastTransitionTime: '2023-11-07T07:03:44Z'
      message: could not get secret data from provider
      reason: SecretSyncedError
      status: 'False'
      type: Ready
`

**Comment by mpzfm1** [comment]
Great, thankss very much, now its working
