### ISSUE TITLE
Unable to setup ClusterSecretStore with externalSecret

### ISSUE THREAD

**Issue by mpzfm1** [external-secrets/external-secrets#2861]
Hi everyone, we have been able to set up correctly (into OCP 4.12) with no errors the environment with:

- secretstore (in the namespace "support" which also contains the secret for authentication with AWS)
- externalsecret in the same namespace

However, we can't set it up with "clustersecretstore". It seems like it can't read from the secret that contains the AWS credentials. In which namespace should it be?

Thanks

**Comment by moolen** [comment]
Can you share your ClusterSecretStore, please?

**Comment by mpzfm1** [comment]
![Captura](https://github.com/external-secrets/external-secrets/assets/73255806/945c6595-8f02-4628-ad74-b494890b8b74)

yes of course,  i think that its mandatory to have the secret containing the aws credentials in the same namespace as the externalsecret????

i wanted to avoid it in order to be available to developers who works in the namespace....

**Comment by gusfcarvalho** [comment]
For ClusterSecretStores, you can add `namespace` to select which namespace to pull the secrets from. The default is the namespace of the ExternalSecret.

**Comment by mpzfm1** [comment]
o great, according to the documentation there is no "namespace" option in "clustersecretstore" inside "remoteRef:

https://external-secrets.io/v0.4.3/api-clustersecretstore/

but i workssssss thanksss
