### ISSUE TITLE
Secret metadata is being overridden

### ISSUE THREAD

**Issue by Shanti-G** [external-secrets/external-secrets#2864]
**Describe the bug**

_Our setup:_
We have secrets management set up that leverages ESO at its core. 
ESO syncs up the secret along with required metadata like versions in the form secret labels from IBM Cloud Secrets Manager. As a part of our automation, new secret labels get added to the secret in addition to the labels synced up by ESO.

_Issue:_
Till versions prior to 0.9.6, the labels and annotations that ESO updates are merged with existing labels.
From version 0.9.6, any existing labels which are added by our automation are being overridden with the metadata fetched by ESO.
This is breaking our automation and preventing us from updating to the latest version.

**To Reproduce**
1. External Secrets Definition:
```
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: logdna-icd-agent
spec:
  refreshInterval: '30m'
  secretStoreRef:
    name: icd-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: logdna-icd-agent
    template:
      metadata:
        labels:
          versions-total: "{{ .versions_total }}"
          secret-id: "{{ .id }}"
      engineVersion: v2
      data:
        logdna-agent-key: "{{ .payload }}"
  dataFrom:
  - extract:
      key: icd-baseline-configuration-secrets/arbitrary/_logdna_dev_us_south_logdna_agent_ingestionkey
      metadataPolicy: Fetch
```

The sync'ed up secret:
```
apiVersion: v1
data:
  logdna-agent-key: xxx
immutable: false
kind: Secret
metadata:
  annotations:
    reconcile.external-secrets.io/data-hash: xxx
  creationTimestamp: "2023-11-09T08:30:15Z"
  labels:
    reconcile.external-secrets.io/created-by: d6eba87d878bf9209668ce97d36441d3
    secret-id: 159ad3e4-2421-0a36-6151-3c637990a7ab
    versions-total: "7"
  name: logdna-icd-agent-dummy
  namespace: compose-system
  ownerReferences:
  - apiVersion: external-secrets.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ExternalSecret
    name: logdna-icd-agent-dummy
    uid: b82c545a-f64c-489a-a6f5-13f515b77001
  resourceVersion: "77978066"
  uid: c8b0a94d-478f-4a36-896b-caa33e46e601
type: Opaque
```

Our automation updates the secret labels, where 2 labels are added:
```
apiVersion: v1
data:
  logdna-agent-key: xxx
immutable: false
kind: Secret
metadata:
  annotations:
    reconcile.external-secrets.io/data-hash: xxx
  creationTimestamp: "2023-11-09T08:30:15Z"
  labels:
    achieved-versions-total: "7"               # -> labels added by our automation
    daemonset/logdna-icd-agent: version-7      # -> labels added by our automation
    reconcile.external-secrets.io/created-by: d6eba87d878bf9209668ce97d36441d3
    secret-id: 159ad3e4-2421-0a36-6151-3c637990a7ab
    versions-total: "7"
  name: logdna-icd-agent-dummy
  namespace: compose-system
  ownerReferences:
  - apiVersion: external-secrets.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ExternalSecret
    name: logdna-icd-agent-dummy
    uid: b82c545a-f64c-489a-a6f5-13f515b77001
  resourceVersion: "77978066"
  uid: c8b0a94d-478f-4a36-896b-caa33e46e601
type: Opaque
```

However, after the refresh interval, the ESO re-syncs the secret and overrides them:
```
apiVersion: v1
data:
  logdna-agent-key: xxx
immutable: false
kind: Secret
metadata:
  annotations:
    reconcile.external-secrets.io/data-hash: xxx
  creationTimestamp: "2023-11-09T08:30:15Z"
  labels:
    reconcile.external-secrets.io/created-by: d6eba87d878bf9209668ce97d36441d3
    secret-id: 159ad3e4-2421-0a36-6151-3c637990a7ab
    versions-total: "7"
  name: logdna-icd-agent-dummy
  namespace: compose-system
  ownerReferences:
  - apiVersion: external-secrets.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: ExternalSecret
    name: logdna-icd-agent-dummy
    uid: b82c545a-f64c-489a-a6f5-13f515b77001
  resourceVersion: "77978066"
  uid: c8b0a94d-478f-4a36-896b-caa33e46e601
type: Opaque
```

3. provide the Kubernetes and ESO version
ESO version: 0.9.6

**Expected behavior**
We expect that existing metadata (labels and annotations) is not overridden by ESO, but rather be merged.

**Additional context**
We believe this issue is due to the PR: https://github.com/external-secrets/external-secrets/pull/2705 where it is deemed safe to override:
https://github.com/external-secrets/external-secrets/blob/c9b3f97425b07a57f73e3195f4b26d72b5099177/pkg/controllers/externalsecret/externalsecret_controller_template.go#L205

However, we do not expect this behaviour from ESO and would not want ESO to take complete control over the metadata. We would like ESO to merge the metadata instead.

**Comment by Shanti-G** [comment]
Hi @moolen, please can you take a look at this and share your thoughts. Thanks.
cc: @IdanAdar

**Comment by moolen** [comment]
Hey @Shanti-G, thanks for opening this issue. I agree that use-case should be covered. :thinking: 

I triaged the issue, the following diff restores the old behaviour:

```diff
diff --git a/pkg/controllers/externalsecret/externalsecret_controller_template.go b/pkg/controllers/externalsecret/externalsecret_controller_template.go
index 5e1eb334..b63bc715 100644
--- a/pkg/controllers/externalsecret/externalsecret_controller_template.go
+++ b/pkg/controllers/externalsecret/externalsecret_controller_template.go
@@ -203,8 +203,12 @@ func (r *Reconciler) applyTemplate(ctx context.Context, es *esv1beta1.ExternalSe
 // setMetadata sets Labels and Annotations to the given secret.
 func setMetadata(secret *v1.Secret, externalSecret *esv1beta1.ExternalSecret) {
        // It is safe to override the metadata since the Server-Side Apply merges those fields if necessary
-       secret.ObjectMeta.Labels = make(map[string]string)
-       secret.ObjectMeta.Annotations = make(map[string]string)
+       if secret.ObjectMeta.Labels == nil {
+               secret.ObjectMeta.Labels = make(map[string]string)
+       }
+       if secret.ObjectMeta.Annotations == nil {
+               secret.ObjectMeta.Annotations = make(map[string]string)
+       }
        if externalSecret.Spec.Target.Template == nil {
                utils.MergeStringMap(secret.ObjectMeta.Labels, externalSecret.ObjectMeta.Labels)
                utils.MergeStringMap(secret.ObjectMeta.Annotations, externalSecret.ObjectMeta.Annotations)
```

We do not use server-side apply with `creationPolicy=Owner`. It can be used with `creationPolicy=Merge` only at the moment.

Above patch will make ESO keep the labels that have been added.

```yaml
kind: Secret
metadata:
  labels:
    acme.corp/cost_center: booze
    acme.corp/namespace: foobar
    foo: bar # <-- added this manually with `kubectl label <....>`
    reconcile.external-secrets.io/created-by: b17284e081b5ae0956c3be8ebe3a67bc
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        # ...
      f:metadata:
        f:labels:
          .: {}
          # note: we do NOT own label `foo`, see below
          f:acme.corp/cost_center: {}
          f:acme.corp/namespace: {}
          f:reconcile.external-secrets.io/created-by: {}
    # ...
    manager: externalsecrets.external-secrets.io/fake-template-01
    operation: Update
    time: "2023-11-09T22:46:37Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:foo: {} # <-- here, this is still owned by kubectl-label
    manager: kubectl-label
    operation: Update
    time: "2023-11-09T22:46:44Z"
```

There is no first-class citizen support for server-side apply in controller-runtime, yet. Just the `.Patch()` API which is used with `creationPolicy=Merge`.

**Comment by Shanti-G** [comment]
Agreed, above patch looks good, as it allows the labels to be retained.
Would like to create a PR to revert the set of lines mentioned above, please let me know. Thanks.

**Comment by moolen** [comment]
sure, please go ahead, thank you :bow:

CC @shuheiktgw: gonna revert a couple of lines from #2705.

**Comment by shuheiktgw** [comment]
Hmm, sorry for the bug I infused 🙇 
Let me take a closer look...

**Comment by shuheiktgw** [comment]
First of all, simply reverting https://github.com/external-secrets/external-secrets/pull/2705 does not seem right to me. Then it just reintroduces https://github.com/external-secrets/external-secrets/issues/2682. 

First of all, I'm not too sure if this really is a bug. Editing the secrets managed by the operator does not seem to be a good idea, and if you want to add metadata, you can achieve that by adding it to the corresponding external secret. Then ESO handles it correctly.

That said, https://github.com/external-secrets/external-secrets/pull/2705 accidentally introduces a breaking change, so I feel responsible for restoring the old behavior. To achieve that, I think the better approach is to use SSA for [the createOrUpdate method](https://github.com/external-secrets/external-secrets/blob/9ff86eab5114edca5449633927d7959039db53a1/pkg/controllers/externalsecret/externalsecret_controller.go#L375) as @moolen suggested above. Let me tasks this issue over from here!

**Comment by Shanti-G** [comment]
@shuheiktgw would it be possible to restore the old behavior first and then address the latter issue.
We would like to upgrade the issue but blocked with this. Any thoughts?

**Comment by shuheiktgw** [comment]
@Shanti-G Sorry that I could not take the time to work on this issue... 🙇 (I've been swamped with other stuff lately)
I can finally spare some time to look into it this weekend, but if I can't (or realize it takes time to fix this problem) let us think how we can restore the original behavior first.

**Comment by Shanti-G** [comment]
Cool, no worries. Sounds good. Thank you.

**Comment by IdanAdar** [comment]
@Shanti-G Are we still working on this issue?

**Comment by shuheiktgw** [comment]
@Shanti-G Sorry I cannot wrap up my PR this weekend, but I confirmed https://github.com/external-secrets/external-secrets/pull/2900 works fine locally. I'll work on the rest tomorrow (mainly tests and descriptions).

**Comment by Shanti-G** [comment]
@shuheiktgw thanks for fixing this.

**Comment by Shanti-G** [comment]
Hi @moolen , when can we get a new release to include this fix?
