### ISSUE TITLE
Kubernetes secret is not created despite SecretStore and ExternalSecret being okay

### ISSUE THREAD

**Issue by amansharif** [external-secrets/external-secrets#2894]
**Describe the bug**
ESO has not created Kubernetes Secret even though SecretStore status is valid and ready as well as ExternalSecret status is SecretSynced.

**To Reproduce**
1. Please find the following manifests at the bottom
2. ESO version: v0.9.4

**Expected behavior**
Once SecretStore shows valid and ready, ExternalSecret shows SecretSynced Kubernetes secret should have been created.

**Screenshots**

**Additional context**
ESO pod logs also suggests that secret has been reconciled. Please find the log line in below

`{"level":"info","ts":1700653011.3761022,"logger":"controllers.ExternalSecret","msg":"reconciled secret","ExternalSecret":{"name":"es-trivy","namespace":*****}}
`

Manifests used

> apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"external-secrets.io/v1beta1","kind":"SecretStore","metadata":{"annotations":{},"name":"ss-trivy","namespace":*****},"spec":{"provider":{"azurekv":{"authType":"WorkloadIdentity","serviceAccountRef":{"name":"trivy-wi-sa"},"vaultUrl":***********}}}}
  creationTimestamp: '2023-11-22T11:36:50Z'
  generation: 1
  managedFields:
    - apiVersion: external-secrets.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:capabilities: {}
          f:conditions: {}
      manager: external-secrets
      operation: Update
      subresource: status
      time: '2023-11-22T11:36:50Z'
    - apiVersion: external-secrets.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          .: {}
          f:provider:
            .: {}
            f:azurekv:
              .: {}
              f:authType: {}
              f:environmentType: {}
              f:serviceAccountRef:
                .: {}
                f:name: {}
              f:vaultUrl: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2023-11-22T11:36:50Z'
  name: ss-trivy
  namespace: *****
  resourceVersion: '312931230'
  uid: 460032cd-a12c-47c2-b52f-295263869c38
  selfLink: /apis/external-secrets.io/v1beta1/namespaces/*****/secretstores/ss-trivy
status:
  capabilities: ReadWrite
  conditions:
    - lastTransitionTime: '2023-11-22T11:36:50Z'
      message: store validated
      reason: Valid
      status: 'True'
      type: Ready
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      environmentType: PublicCloud
      serviceAccountRef:
        name: trivy-wi-sa
      vaultUrl: ********

> apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"external-secrets.io/v1beta1","kind":"ExternalSecret","metadata":{"annotations":{},"name":"es-trivy","namespace":******},"spec":{"data":[{"remoteRef":{"key":"dockerconfigjson"},"secretKey":"dockerconfigjson"}],"refreshInterval":"1h","secretStoreRef":{"kind":"SecretStore","name":"ss-trivy"},"target":{"creationPolicy":"Owner","name":"trivy-dockerconfigjson","template":{"data":{".dockerconfigjson":"{{
      .dockerconfigjson | toString
      }}"},"type":"kubernetes.io/dockerconfigjson"}}}}
  creationTimestamp: '2023-11-22T11:36:50Z'
  generation: 1
  managedFields:
    - apiVersion: external-secrets.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          .: {}
          f:data: {}
          f:refreshInterval: {}
          f:secretStoreRef:
            .: {}
            f:kind: {}
            f:name: {}
          f:target:
            .: {}
            f:creationPolicy: {}
            f:deletionPolicy: {}
            f:name: {}
            f:template:
              .: {}
              f:data:
                .: {}
                f:.dockerconfigjson: {}
              f:engineVersion: {}
              f:mergePolicy: {}
              f:type: {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2023-11-22T11:36:50Z'
    - apiVersion: external-secrets.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          .: {}
          f:conditions: {}
          f:refreshTime: {}
          f:syncedResourceVersion: {}
      manager: external-secrets
      operation: Update
      subresource: status
      time: '2023-11-22T11:36:51Z'
  name: es-trivy
  namespace: *****
  resourceVersion: '312931296'
  uid: afe01e63-64e8-4197-9e37-0e707d52a629
  selfLink: >-
    /apis/external-secrets.io/v1beta1/namespaces/*****/externalsecrets/es-trivy
status:
  conditions:
    - lastTransitionTime: '2023-11-22T11:36:51Z'
      message: Secret was synced
      reason: SecretSynced
      status: 'True'
      type: Ready
  refreshTime: '2023-11-22T11:36:51Z'
  syncedResourceVersion: 1-b2ad2305512c8ea0458b712efe86dc9d
spec:
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: dockerconfigjson
      secretKey: dockerconfigjson
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: ss-trivy
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: trivy-dockerconfigjson
    template:
      data:
        .dockerconfigjson: '{{ .dockerconfigjson | toString }}'
      engineVersion: v2
      mergePolicy: Replace
      type: kubernetes.io/dockerconfigjson

**Comment by amansharif** [comment]
I've identified the issue that was causing trouble. It turns out that the root of the problem was my use of a base64 encoded secret in Azure Key Vault. This encoding oversight was the reason why the secret wasn't being created, despite all configurations appearing correct. When I switched to using the decoded string value, everything started functioning as expected.

However, I do want to highlight a potential improvement area. The system doesn't currently provide feedback or error messages when it encounters base64 encoded values, which it evidently doesn't accept. Ideally, there should be some form of notification or warning to indicate this incompatibility. This would be helpful for troubleshooting and ensuring smoother operations in the future.

**Comment by gusfcarvalho** [comment]
The lack of feeeback comes from kubernetes api itself, as since you’ve templated the secret, from externalsecrets point of view the templating was done (which was in a format not supported by kubernetes). 

I’m not sure how we could be more helpful without coupling the code with specific secret types.
