### ISSUE TITLE
Proposal: Integration of `Chef External Secrets Provider` into External Secrets Repository

### ISSUE THREAD

**Issue by sourav977** [external-secrets/external-secrets#2905]
Hello External Secrets maintainers,

We, the IBM team, have developed a `Chef External Secrets provider` that seamlessly integrates Chef data bags with Kubernetes secrets through the External Secrets framework. The implementation is complete and tested.

**Contribution Details:**
Provider: Chef External Secrets
Integration: Chef data bags to Kubernetes secrets
Documentation: Comprehensive documentation will be provided
Testing: Thoroughly tested in local and production Kubernetes environments

### Is your feature request related to a problem? Please describe.
This integration aims to enhance the management of secrets by bridging the gap between Chef-managed configurations, stored in Chef data bags, and Kubernetes secrets. The goal is to facilitate a cohesive and unified experience for users working with secrets in both Chef and Kubernetes environments. This enhances the integration between Chef and Kubernetes for managing secrets. 

### Describe the solution you'd like
We would like to propose the inclusion of the `Chef External Secrets provider` into the External Secrets repository. This will enable users to seamlessly integrate their Chef-based secret management with Kubernetes through the existing External Secrets framework.

In many enterprises, legacy applications and infrastructure are still tightly integrated with Chef for configuration management. Teams often rely on Chef data bags to securely store sensitive information such as application secrets and infrastructure configurations. These data bags serve as a centralized repository for managing and distributing sensitive data across the Chef ecosystem.

To illustrate, consider a legacy application that requires API keys for interacting with external services. In a Chef-managed environment, these API keys might be stored within a Chef data bag, providing a secure and centralized method for managing these sensitive credentials. The infra teams also leverage Chef data bags to store configuration details, ensuring consistent deployment and management of infrastructure components.

With the increasing adoption of Kubernetes, there is a growing need to bridge the gap between Chef-managed configurations and Kubernetes secrets. This is where the `Chef External Secrets provider` comes into play. The provider acts as a connector, seamlessly retrieving secrets from Chef data bags and transforming them into Kubernetes secrets. This integration allows legacy applications and infrastructure teams to continue leveraging their existing Chef-based workflows while smoothly extending their capabilities to Kubernetes.

For example, let's consider a Chef data bag named "my_app_secrets" that stores the API key for the legacy application:
```
{
  "id": "my_app_secrets",
  "api_key": "super_secret_key"
}
```
The `Chef External Secrets provider`, when integrated with External Secrets for Kubernetes, would automatically fetch this Chef data bag and create a corresponding Kubernetes secret, ensuring that the API key is available to the legacy application running within Kubernetes pods.

This seamless integration simplifies the transition for organizations with established Chef practices, enabling them to embrace Kubernetes without compromising their existing security and configuration management practices. We propose the inclusion of the `Chef External Secrets provider` in the External Secrets repository to provide a comprehensive solution for managing secrets across both Chef and Kubernetes environments.

### Describe alternatives you've considered
Integrating it directly into the existing External Secrets repository offers a more streamlined and consolidated solution for users managing secrets across diverse platforms. This approach aims to enhance user experience by providing a unified interface within the established External Secrets framework.

### Additional context
`Chef External Secrets provider` utilizes the [go-chef/chef](https://github.com/go-chef/chef) Golang library to connect to the Chef server. The Chef server documentation can be found [here](https://docs.chef.io/server/). We have thoroughly tested and documented the provider, and we believe it aligns with the goals and functionality of the External Secrets project.

We are open to collaboration and welcome feedback from the community to ensure the successful integration of the `Chef External Secrets provider` into the External Secrets repository.

**Comment by moolen** [comment]
Hey @sourav977 i took a quick look at the API etc and it looks like a good fit :+1:. Even though you can achieve some of features with the existing webhook provider i think there is a big benefit of having a separate provider and documentation for it :+1: 

Regarding ownership: we can not take full ownership of the provider, would you like to step in and maintain it for the  foreseeable future? :pray:

**Comment by sourav977** [comment]
@Skarlso 
Since the PR got merged yesterday, should we close it

**Comment by Skarlso** [comment]
Yep. Sounds good.
