### ISSUE TITLE
Add validations to ExternalSecretDataFromRemoteRef 

### ISSUE THREAD

**Issue by shuheiktgw** [external-secrets/external-secrets#2916]
**Is your feature request related to a problem? Please describe.**
Currently, we don't have any validations on [the ExternalSecretDataFromRemoteRef](https://github.com/external-secrets/external-secrets/blob/3599384660c5d4f51d1afd5f99dc9d9aa3a9a1ee/apis/externalsecrets/v1beta1/externalsecret_types.go#L258C6-L280), but while reading the source code I noticed [there are several pre-conditions we need to meet](https://github.com/external-secrets/external-secrets/blob/9ff86eab5114edca5449633927d7959039db53a1/pkg/controllers/externalsecret/externalsecret_controller_secret.go#L55-L61):

1. We should set either Find, Exact, or SourceRef & SourceRef.GeneratorRef. 
2. We should set SourceRef.GeneratorRef if we want to use SourceRef.

**Describe the solution you'd like**
Those conditions are not validated properly right now, so it would be better if we add validations [here](https://github.com/external-secrets/external-secrets/blob/8b0fa87f301abd5ac2d15a45493aa4609e433772/apis/externalsecrets/v1beta1/externalsecret_validator.go#L39).

**Comment by LucasPimentel123** [comment]
Hey, can I get this issue? I`m quite new to ESO and I think this is an issue I can work on. I`ve been looking into it for the past few days and I think I now how to deal with it.

**Comment by Skarlso** [comment]
Sure, go for it! 👍  :) Just make sure you assign it to yourself. :)
