### ISSUE TITLE
Fix typo in ExtermalSecretRewriteTransform

### ISSUE THREAD

**Issue by shuheiktgw** [external-secrets/external-secrets#2917]
**Describe the bug**
[ExtermalSecretRewriteTransform](https://github.com/external-secrets/external-secrets/blob/e0c1d93f9b290def64f054a5ac6d5ea5555771b6/apis/externalsecrets/v1beta1/externalsecret_types.go#L301) should have been ExternalSecretRewriteTransform...

**Comment by moolen** [comment]
Sure thing, assigned it to you :heart:
Let me know if you need any help
