### ISSUE TITLE
Docu page does not reflect latest docu state for datafrom for IBM Secret Manager

### ISSUE THREAD

**Issue by fdberlking** [external-secrets/external-secrets#2965]
**Describe the bug**

Documentation for provider IBM Secret Manager for **kv** (probably, this is also valid for all other secret types like arbitrary, service credentials, certs and so on) does not reflect the latest updates since the version switch from `v1alpha1` to `v1beta1`. For my example, I was using `ESO` in version `0.9.9`.

See https://github.com/external-secrets/external-secrets/blob/main/docs/guides/v1beta1.md.

**To Reproduce**

Following the [example](https://external-secrets.io/v0.9.10/provider/ibm-secrets-manager/#kv), I was running 

```
dataFrom:
  - key: 'kv/aaaaa-bbbb-cccc-dddd-eeeeee'
    property: 'key3'
```

which was failing due to

`The request is invalid: patch: Invalid value: "some message here"}}": strict decoding error: unknown field "spec.dataFrom[0].key", unknown field "spec.dataFrom[0].property"`

Only after changing my setup to

```
dataFrom:
  - extract:
      key: epa-ibm-services/kv/aaaaa-bbbb-cccc-dddd-eeeeee
      decodingStrategy: Base64
```

**Expected behavior**

externalSecrets are applied and synced without issues.

**Comment by fdberlking** [comment]
@haf-tech is already aware of my "complaints" :-)

**Comment by vsantos** [comment]
Hello @fdberlking, I can look into that and fix the documentation. (:
