### ISSUE TITLE
Webhook Pod outputs TLS handshake errors

### ISSUE THREAD

**Issue by EigoOda** [external-secrets/external-secrets#2983]
**Describe the bug**

Webhook Pod outputs TLS handshake error when commands are executed in 20 parallel.
commands are `kustomize build k8s/dev/app1 | kubectl diff -f -`, `kustomize build k8s/dev/app2 | kubectl diff -f -` ...
k8s/dev/app* directories have `ExternalSecrets` resource.

output logs
```text
2023/12/26 04:48:39 http: TLS handshake error from 10.183.1.159:43692: EOF
2023/12/26 04:48:39 http: TLS handshake error from 10.183.1.159:43708: read tcp 10.183.37.73:10250->10.183.1.159:43708: read: connection reset by peer
```

When executing the commands, a TLS handshake error occurred whenever there was a change in the Kubernetes manifests.
If no changes were made to the Kubernetes manifests when the command was executed, the TLS handshake error was random.

**To Reproduce**
1. provide all relevant manifests
2. provide the Kubernetes and ESO version
  - Kubernetes: 1.25.16
  - ESO: 0.9.7

**Expected behavior**
No errors output from webhook Pod.

**Comment by ypereirareis** [comment]
Hello!

Thanks for external secrets awesome tool.

I'm having the exact same problem after upgrading from version 0.4.4 to 0.9.10.

Thanks

**Comment by ypereirareis** [comment]
Hello,

To give more information regardings those errors
`2024/01/18 08:25:12 http: TLS handshake error from 172.25.85.106:45312: EOF`

The IP `172.25.85.106` is within control plane IP range.

Thanks

**Comment by moolen** [comment]
This appears to be a non-issue, lots of other project report the same issue, while it has no direct effect on the availability of the webhook. 
It seems kube-apiserver drops the connection prematurely and retries it.

related:
https://github.com/kumahq/kuma/issues/8247
https://github.com/open-policy-agent/gatekeeper/issues/2142
https://github.com/cert-manager/cert-manager/issues/4594
https://github.com/crossplane-contrib/provider-kubernetes/issues/175
https://github.com/kubernetes/kubernetes/issues/109022
https://github.com/golang/go/issues/50984

**Comment by ypereirareis** [comment]
Ok @moolen thanks for this confirmation.

**Comment by EigoOda** [comment]
@moolen 
Thank you to teach me the result and send other issues!
