### ISSUE TITLE
refreshInterval: never

### ISSUE THREAD

**Issue by runningman84** [external-secrets/external-secrets#299]
**Describe the solution you'd like**
I would like to have an option to disable refreshing...

**What is the added value?**
If you ypu have hunderts of secrets you will eventually get a rate limit. But if you only sync them during deployments there would not be any error.

**Give us examples of the outcome**

Provide templates if you are proposing changes in the CRD. Provide example workflows or code snippets if they make sense to present.

refreshInterval: never

**Observations (Constraints, Context, etc):**

The old kube external secret project used to have this option

**Comment by moolen** [comment]
You can set it to `RefreshInterval: 0` to disable refresh.

**Comment by runningman84** [comment]
This does not seem to work:
Error: UPGRADE FAILED: release wp-bedrock-sample failed, and has been rolled back due to atomic being set: failed to create resource: ExternalSecret.external-secrets.io "wp-bedrock-sample-wordpress-bedrock" is invalid: spec.refreshInterval: Invalid value: "integer": spec.refreshInterval in body must be of type string: "integer

**Comment by moolen** [comment]
sorry, that was a typo i guess:  `spec.refreshInterval: "0"` (with quotes).

I triple checked whether it works or not and i found a bug.

**Comment by moolen** [comment]
> But if you only sync them during deployments

You must set the `spec.refreshInterval: "0"` as mentioned above but this will completely disable the sync for ever. You must change the ExternalSecret.spec, it's labels or annotations with every deployment in order to trigger a sync.

**Comment by moolen** [comment]
This will be included in the next release (probably this week)
