### ISSUE TITLE
Release x.y

### ISSUE THREAD

**Issue by Glo7er** [external-secrets/external-secrets#2990]
This Issue tracks the next ESO release. Please follow the guideline below. If anything is missing or unclear, please add a comment to this issue so this can be improved after the release.

#### Preparation Tasks

- [ ] ask in `#external-secrets-dev` if we're ready for a release cut-off or if something needs to get urgently in
- [ ] docs: [stability & support page](https://external-secrets.io/main/introduction/stability-support/) is up to date
  - [ ] version table
  - [ ] Provider Stability and Support table
  - [ ] Provider Feature Support table
- [ ] docs: update [roadmap page](https://external-secrets.io/main/contributing/roadmap/)
- [ ] tidy up [Project Board](https://github.com/orgs/external-secrets/projects/2)
  - [ ] move issues to next milestone
  - [ ] close milestone

#### Release Execution

- [ ] Follow the [Release Process guide](https://external-secrets.io/main/contributing/release/)

#### After Release Tasks

- [ ] Announce release on `#external-secrets` in Slack

**Comment by IdanAdar** [comment]
There is a newer ticket.
