### ISSUE TITLE
Global image repository not used in components

### ISSUE THREAD

**Issue by cunningr** [external-secrets/external-secrets#2999]
Often helm charts will you give you opportunity to globally override the image repository to make it straightforward to mirror images to internal repos.  The `external-sercrets` helm chart appears to offer `.Values.image.repository` but then only uses that for the deployment.  The `webhook` and `certController` need to be overridden individually.

Am I mistaken or is this perhaps intentional?

https://github.com/external-secrets/external-secrets/blob/0bb4feae4a1da07820ec4b1668db199817a43f54/deploy/charts/external-secrets/templates/webhook-deployment.yaml#L48C105-L48C125

**Comment by moolen** [comment]
This is intentional (i guess it just became this way). Everything on the root level relates to the `external-secrets` pod, not the certController or webhook - they were created way later than the original operator pod. 

To keep compatibility we left the helm chart values as they were.

**Comment by cunningr** [comment]
ok understood - thanks for the response!
