### ISSUE TITLE
[Feat Req] Add support for installing only CRDs

### ISSUE THREAD

**Issue by PeterStolz** [external-secrets/external-secrets#3020]
**Is your feature request related to a problem? Please describe.**
Helm does not have an ordered way to create resources. Therefore I end up with the CRDs geeing installed after reference resulting in a failing installation. CertManager circumvents this by providing a one-linter to install just the CRDs
`kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.13.3/cert-manager.crds.yaml`
They also say that for safety CRDs should be installed outside of Helm
https://cert-manager.io/docs/installation/helm/#crd-installation-advice

**Describe the solution you'd like**
I would love to have a similar one-liner that installs only the CRDs. I checked in the source but the CRDs are distributed among a few files, so I am not sure what the ideal solution looks like.

**Describe alternatives you've considered**
I can install a helm chart with only external-secrets as a dependency and then install another one with the actual external secrets besides it.

**Additional context**
If there is already a simple way we could just add it to the Docs for other confused souls like me.

**Comment by moolen** [comment]
Hey @PeterStolz thank you for your suggestion. What one can do right now is use `kustomize` to apply all the CRDs:

```sh
kubectl apply -k "https://github.com/external-secrets/external-secrets//config/crds/bases?ref=v0.9.11"
```

Does that work for you?

**Comment by moolen** [comment]
i completely forgot, there's also the `bundle.yaml`: https://github.com/external-secrets/external-secrets/blob/main/deploy/crds/bundle.yaml which contains all the CRDs in one file

**Comment by PeterStolz** [comment]
Awesome. Thanks for the super fast response. I used the kustomize based command and it works like a charm.
I can integrate this properly into my ArgoCD.
Do you agree that it would be nice to mention this in the docs?

**Comment by moolen** [comment]
yes, totally agree!
