### ISSUE TITLE
Gitlab CI variables provider

### ISSUE THREAD

**Issue by knelasevero** [external-secrets/external-secrets#307]
You can store secret values as CI variables in gitlab, and we can retrieve them through the API. We can have a provider using this as a store. In the old CS solution we had a provider implementing this: https://github.com/ContainerSolutions/externalsecret-operator/tree/master/pkg/gitlab

**Comment by alekc** [comment]
@knelasevero this is fixed by https://github.com/external-secrets/external-secrets/pull/319 isn't it?
