### ISSUE TITLE
Custom provider integration

### ISSUE THREAD

**Issue by kiemlicz** [external-secrets/external-secrets#3074]
**Describe the solution you'd like**
I would like to integrate with passbolt service

Basically this is only a question: how to create a custom integration with passbolt, assuming 'generic' integration doesn't work?

Is the pull request to ESO the only way forward?
or there is some 'interface' that I can plug 'my integration only' to running ESO deployment?

**Comment by moolen** [comment]
Hey, we only have the [webhook provider](https://external-secrets.io/latest/provider/webhook/) as a generic integration way, this is the only way at this point. Feel free to open a PR for passbolt as long as it would work for other people as well.

**Comment by kiemlicz** [comment]
I guess I will

Thanks
