### ISSUE TITLE
Support for Yandex Lockbox

### ISSUE THREAD

**Issue by knelasevero** [external-secrets/external-secrets#308]
https://cloud.yandex.com/en/

Yandex cloud has a secret service named Yandex Lockbox and we could have a provider for it.

This [issue](https://github.com/external-secrets/kubernetes-external-secrets/issues/798) was opened on KES, and we could implement support for Yandex here since this project aims to replace KES.

**Comment by AndreyZamyslov** [comment]
@knelasevero Thank you for creating the issue!

Actually we already have a basic implementation: https://github.com/external-secrets/external-secrets/pull/323
Any help would be appreciated though
