### ISSUE TITLE
Add PEM to pkcs12 template function

### ISSUE THREAD

**Issue by WatcherWhale** [external-secrets/external-secrets#3095]
**Is your feature request related to a problem? Please describe.**
We want to use Azure KeyVault to provide certificates to an Application Gateway. The secrets will be pushed from a k8s cluster by external-secrets. However, we only have PEM formats available in this cluster and Application Gateway only supports base64-encoded PFX files.

**Describe the solution you'd like**
I would like to have a template function which converts a certificate PEM and a key PEM and transform it to a base64 encoded pfx file. This is the opposite behavior of the pkcs12cert and pkcs12key functions.

**Additional context**
I'm willing to contribute this feature myself, if desired.

**Comment by moolen** [comment]
Sounds good to me, feel free to contribute :)
