### ISSUE TITLE
e2e tests

### ISSUE THREAD

**Issue by moolen** [external-secrets/external-secrets#31]
We will integrate a lot of external APIs and we need to test them end-to-end. Ideally we test the "real" upstream APIs rather than fakes, however this will cost a few cents.

AC:
* find sponsors for AWS, Azure & GCP 
* consider running HasiCorp's Vault Cluster ~using an IaaS Provider~ in kind

**Comment by riccardomc** [comment]
I would like to start looking into this

**Comment by knelasevero** [comment]
@riccardomc Were you able to have a look over this?

@mcavoyk wants to try something with mock solutions for AWS and for Hashcorp Vault. We wouls still need credits for Azure and GCP anyways for meaningful tests.

I will also ask CS to see if CS Labs can provide something here.

**Comment by riccardomc** [comment]
I did only marginal work for this, then a new client and life got in the way. Please go ahead @mcavoyk and @knelasevero!

**Comment by knelasevero** [comment]
We have GCP project with budget. Azure missing, I think we will have it by tomorrow.

- [x] GCP project

- [ ] Azure subs

**Comment by riccardomc** [comment]
I also reached out to someone at AWS but didn't get an answer yet... will let you know if I get anywhere

**Comment by knelasevero** [comment]
I think this issue can be closed by https://github.com/external-secrets/external-secrets/pull/203

And then would make sense to open one issue per provider so we better track it

**Comment by knelasevero** [comment]
Openned new issues: #205, #206, #207, #208, #209
