### ISSUE TITLE
Constant secret updating with ParameterStore provider

### ISSUE THREAD

**Issue by eskp** [external-secrets/external-secrets#3149]
**Describe the bug**
Constant secret updating with ParameterStore provider. Deployed with Helm default values to EKS cluster with secrets stored on SSM.

Check interval is set to 1 minute.

**To Reproduce**
1. Default Helm deployment
2. K8s - v1.28.5
3. ESO - 0.9.12

**Expected behavior**
K8s secret should not be updated if there wasn't SSM value change.

**Comment by shuheiktgw** [comment]
Hi, @eskp. Thanks for reporting the issue!
Would you provide example manifests to reproduce the behavior?

**Comment by eskp** [comment]
Here is one of them:

``yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    meta.helm.sh/release-name: foo
    meta.helm.sh/release-namespace: foo
  creationTimestamp: "2024-02-14T18:11:48Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: foo
  namespace: foo
  resourceVersion: "71074441"
  uid: dc2aebed-8372-4041-b318-848640b25e73
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: /foo/bar
      metadataPolicy: None
    secretKey: foo
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-foo
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
status:
  binding:
    name: foo
  conditions:
  - lastTransitionTime: "2024-02-14T18:11:49Z"
    message: Secret was synced
    reason: SecretSynced
    status: "True"
    type: Ready
  refreshTime: "2024-02-28T01:05:11Z"
  syncedResourceVersion: 1-188a70c07b32cd6cded504e9de0833b7
  ``

**Comment by eskp** [comment]
The Event Count for this is currently on `9319` with the Message Updated Secret

**Comment by eskp** [comment]
@shuheiktgw were you able to reproduce?

**Comment by shuheiktgw** [comment]
Sorry, I'm currently swamped with other issues and PRs right now and cannot take the time to investigate it further.

**Comment by eskp** [comment]
The `Event` on `Externalsecret` describe:
`│   Normal  Updated  2m19s (x2487 over 41h)  external-secrets  Updated Secret                                                      `

**Comment by shuheiktgw** [comment]
Thanks, @eskp. I've looked into it and found some problems with the event publication. I'll create a PR to fix this problem. The problem is not specific to the ParameterStore. https://github.com/external-secrets/external-secrets/issues/3265 is caused by the same problem.

**Comment by eskp** [comment]
@shuheiktgw appreciate the update and glad you were able to discover the problem. Looking forward to the fix.
