### ISSUE TITLE
Webhook certificate issue on GKE autopilot

### ISSUE THREAD

**Issue by Binyamse** [external-secrets/external-secrets#3186]
**Describe the bug**

- A new setup was created with the installation of a Custom Resource Definition (CRD) using kubectl and an external secret using helm in a GKE Autopilot cluster. However, the deployment of the webhook is encountering an error with the message provided below.

` {"level":"error","ts":1708614502.2335103,"logger":"setup","msg":"invalid certs. retrying...","error":"stat /tmp/certs/tls.crt: no such file or directory","stacktrace":"github.com/external-secrets/external-secrets/cmd.waitForCerts\n\t/home/runner/work/external-secrets/external-secrets/cmd/webhook.go:215\ngithub.com/external-secrets/external-secrets/cmd.glob..func3\n\t/home/runner/work/external-secrets/external-secrets/cmd/webhook.go:84\ngithub.com/spf13/cobra.(*Command).execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115\ngithub.com/spf13/cobra.(*Command).Execute\n\t/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039\ngithub.com/external-secrets/external-secrets/cmd.Execute\n\t/home/runner/work/external-secrets/external-secrets/cmd/root.go:255\nmain.main\n\t/home/runner/work/external-secrets/external-secrets/main.go:22\nruntime.main\n\t/opt/hostedtoolcache/go/1.21.7/x64/src/runtime/proc.go:267"}`

**To Reproduce**
1. install CRDs using `kubectl apply -k external-secrets/config/crds/bases` (this is main branch of external-secret repo)
2. provide the Kubernetes and ESO version
Kubernetes:
```
Client Version: v1.27.4
Kustomize Version: v5.0.1
Server Version: v1.27.8-gke.1067004
```
ESO:
`0.9.13`

**Expected behavior**
Work fully

**Screenshots**

**Additional context**
The environment is GKE autopilot

**Comment by karlschriek** [comment]
Any feedback on this? We just bumped external-secrets up from a very old version to 0.9.19 and are running into exactly this. Is there are older version where we know this issue has not been introduced yet?

Running AKS with kubernetes version 1.27.9

**Comment by moolen** [comment]
The certcontroller generates TLS certs and a private key, the webhook server attempts to pick it up but it doesn't exist yet.
Can you share the logs of the other eso pods? Is there anything from certcontroller?
This error is expected when eso is installed for the first time, the webhook pod will restart/retry until the TLS files are present, this may take up to 60s
