### ISSUE TITLE
While creating external secret, I would like to create secret with target name on another namespace 

### ISSUE THREAD

**Issue by Ranjit-Kumar-Konjeti** [external-secrets/external-secrets#3191]
**Is your feature request related to a problem? Please describe.**
I am not able to create secret of target on another namespace. While creating external secret, I would like to create secret with target name on another namespace 

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-external-secret
  namespace: external-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: kubetest-secret-store
    kind: SecretStore
  target:
    name: test-app-secrets
    creationPolicy: Owner 
    ***namespace***: ***targetnamespace***

**Describe alternatives you've considered**

**Additional context**
Please add     ***namespace***: ***targetnamespace*** to the target, so the secret can get created in target namespace

**Comment by Ranjit-Kumar-Konjeti** [comment]
is it available for Azure provider? do you have any example which I an refer?

**Comment by shuheiktgw** [comment]
Closing since the issue seems to have been resolved 🙂
