### ISSUE TITLE
Scaleway is not working behind the proxy.

### ISSUE THREAD

**Issue by kinikiti** [external-secrets/external-secrets#3201]
**Describe the bug**
Scaleway external secrets are not working behind HTTP/HTTPS proxy.

**Expected behavior**
Scaleway secrets are synchronized if ESO runs behind the proxy.

**Additional context**
This was a [bug](https://github.com/scaleway/scaleway-sdk-go/issues/1991) in Scaleway SDK which is already fixed.

Can you please bump Scaleway SDK version?

**Comment by luxifer** [comment]
It seams the scaleway SDK has been updated to 1.0.0-beta.24 which embeds the fix for the proxy.

**Comment by luxifer** [comment]
See https://github.com/external-secrets/external-secrets/commit/34e421c031321e4eaf390deae923b058adfcc88e

**Comment by IdanAdar** [comment]
Since the PR was merged a while back, closing this ticket.
