### ISSUE TITLE
Publish helm chart also as an OCI package (e.g. on GHCR registry)

### ISSUE THREAD

**Issue by mkilchhofer** [external-secrets/external-secrets#3208]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

The helm chart is published using the classic approach with a static webserver and an index.yaml (GitHub pages):

```bash
helm repo add external-secrets https://charts.external-secrets.io
```

However in helm 3.8+ the OCI method went GA:
- https://blog.bitnami.com/2023/04/httpsblog.bitnami.com202304bitnami-helm-charts-now-oci.html?m=1
- https://helm.sh/docs/topics/registries/
- https://github.com/helm/helm/releases/tag/v3.8.0

I'd like to push the packaged helm charts also on ghcr.io (right besides the already existing container images) so we can pull/install the helm chart like this:

```bash
helm install external-secrets oci://ghcr.io/external-secrets/charts/external-secrets --version x.y.z
```

**Describe alternatives you've considered**
Still using the classic approach with GitHub pages and the index.yaml

**Additional context**
none

**Comment by mkilchhofer** [comment]
@knelasevero can you check whether the newly added packages are set to public inside settings?
Recent release pushed charts were successfully pushed to ghcr.

> Pushed: ghcr.io/external-secrets/charts/external-secrets:0.9.14
> Digest: sha256:4e800ef65ba38b968b96ff7c31fa8d23b613261f235e538e492ca76ceba28b3c
> 
> See: https://github.com/external-secrets/external-secrets/actions/runs/8491033122/job/23262638766

**Comment by knelasevero** [comment]
Just tried to make it public. Try it now please

**Comment by mkilchhofer** [comment]
@knelasevero looks good:
https://github.com/external-secrets/external-secrets/pkgs/container/charts%2Fexternal-secrets

Thank you very much!
