### ISSUE TITLE
Error: unknown flag: --live-addr

### ISSUE THREAD

**Issue by Hayden-Chang** [external-secrets/external-secrets#3212]
**Describe the bug**

Pod **external-secrets** can't start successfully.

`kubectl get pod -A` shows:

```
NAMESPACE          NAME                                               READY   STATUS             RESTARTS      AGE
external-secrets   external-secrets-6766d86d7-gthzm                   0/1     CrashLoopBackOff   4 (72s ago)   3m4s
external-secrets   external-secrets-cert-controller-76cdcfdcc-dv67k   1/1     Running            1 (86s ago)   3m4s
external-secrets   external-secrets-webhook-57f877cb54-6664c          1/1     Running            1 (86s ago)   3m4s
kube-system        coredns-5dd5756b68-fbxzv                           1/1     Running            1 (81s ago)   4m18s
kube-system        etcd-minikube                                      1/1     Running            1 (86s ago)   4m31s
kube-system        kube-apiserver-minikube                            1/1     Running            1 (76s ago)   4m31s
kube-system        kube-controller-manager-minikube                   1/1     Running            1 (86s ago)   4m31s
kube-system        kube-proxy-hz6sl                                   1/1     Running            1 (86s ago)   4m18s
kube-system        kube-scheduler-minikube                            1/1     Running            1 (86s ago)   4m31s
kube-system        storage-provisioner                                1/1     Running            3 (73s ago)   4m30s
```
`kubectl logs external-secrets-6766d86d7-gthzm -n external-secrets` shows:
```
Error: unknown flag: --live-addr
Usage:
  external-secrets [flags]
  external-secrets [command]
...
...
```
After I revert the this [pr](https://github.com/external-secrets/external-secrets/pull/3131), everything goes well.

**To Reproduce**

 1. Pull the latest repo
 2. Follow the [doc](https://external-secrets.io/main/introduction/getting-started/) to install the Helm chart locally

**Expected behavior**
Pod **external-secrets**  starts successfully.

**Screenshots**
![image](https://github.com/external-secrets/external-secrets/assets/62008508/e7199c03-3975-474a-ac96-e53735d354fd)
![image](https://github.com/external-secrets/external-secrets/assets/62008508/d3d48d77-335d-48e3-b8c8-9398121780b8)

**Additional context**

**Comment by Skarlso** [comment]
@fdberlking f*ck :DD I have to revert the commit, or otherwise we'll need to fix this. :(

**Comment by Skarlso** [comment]
https://github.com/external-secrets/external-secrets/pull/3131 Introduced the new flag. But the tests passed. Apparently we did it incorrectly. Or I don't know.

**Comment by Skarlso** [comment]
It's most likely because the chart is downloading the version that doesn't have that flag? It's really weird.

**Comment by Skarlso** [comment]
I'm going to revert said Pull Request than try to investigate what's wrong with it. https://github.com/external-secrets/external-secrets/pull/3213

**Comment by fdberlking** [comment]
> #3131 Introduced the new flag. But the tests passed. Apparently we did it incorrectly. Or I don't know.

Exactly 😄 I really do not understand why the problem comes up after I was running through all of this tests to make it actually available 😞

**Comment by Skarlso** [comment]
> > #3131 Introduced the new flag. But the tests passed. Apparently we did it incorrectly. Or I don't know.
> 
> Exactly 😄 I really do not understand why the problem comes up after I was running through all of this tests to make it actually available 😞

The revert will take a while to go through if you fix it before that, I'm happy to approve it. :D

**Comment by Skarlso** [comment]
I would expect so too. I have no idea what's wrong. 🤷

**Comment by Hayden-Chang** [comment]
> It's most likely because the chart is downloading the version that doesn't have that flag? It's really weird.

I'm a new to kubernetes and it's my first time to run this project. I'm a little worried that I made any mistakes. Can you reproduce it on your machine?

**Comment by Skarlso** [comment]
>I'm a new to kubernetes and it's my first time to run this project. I'm a little worried that I made any mistakes. Can you reproduce it on your machine?

Don't worry, you didn't. The linked PR is at fault somehow. But we have to figure out how. :D I'm reverting that commit from main then it should work.

**Comment by Skarlso** [comment]
@Hayden-Chang Can you please try again now? The PR was reverted.

**Comment by Hayden-Chang** [comment]
> @Hayden-Chang Can you please try again now? The PR was reverted.

It works well now. Thank you~

**Comment by Skarlso** [comment]
Nice, thanks for reporting.

**Comment by fdberlking** [comment]
> Nice, thanks for reporting.

Thus, could we close this one (and I come up with something to solve the other, flag related issue)?

**Comment by Hayden-Chang** [comment]
> > Nice, thanks for reporting.
> 
> Thus, could we close this one (and I come up with something to solve the other, flag related issue)?

Yes. Let me do it
