### ISSUE TITLE
Let PushSecret be configured to push SecretString instead of SecretBinary

### ISSUE THREAD

**Issue by lednerb1** [external-secrets/external-secrets#3244]
**Is your feature request related to a problem? Please describe.**
I'm not too fond of that secrets pushed to AWS SecretsManager are always in binary mode because I can't read/write them in the Web UI.

**Describe the solution you'd like**
I would like to be able to add a field `dataFormat: (Binary|String)` to the PushSecret manifest to solve the problem

**Describe alternatives you've considered**
None

**Additional context**
I don't know if that applies to other providers.

**Comment by Skarlso** [comment]
You are in luck. 😊

https://github.com/external-secrets/external-secrets/pull/3189

**Comment by Skarlso** [comment]
Note: it's not in the push secret directly because it's a provider specific information. For that, we have the metadata field.

**Comment by Skarlso** [comment]
Merged. 😊

**Comment by lednerb1** [comment]
Hey @Skarlso, sorry for pinging. Wanted to know if there's a release planned soon :)

**Comment by Skarlso** [comment]
No worries. It's better to ask in the external secrets slack channel though. I don't know when we'll release. 😊

**Comment by shayc1197** [comment]
Hi @Skarlso and all :),
Can anyone update what is the status?
I would like to use it.

**Comment by Skarlso** [comment]
@shayc1197 Instead of pinging on a 2 years old issue, did you check the documentation or at least the attached PR on how to use this feature? :)

**Comment by shayc1197** [comment]
Hi,

I spent the whole night trying to research and understand how to implement this, including going through the documentation, but I wasn’t able to get it working. :(

**Comment by Skarlso** [comment]
This is already implemented. That's why it's closed. It's even documented on the website and there is an attached linked pr for it. 🤔

**Comment by shayc1197** [comment]
Hi,

It’s working now — thank you very much for your help, I really appreciate it!
I apologize for taking up your time unnecessarily

I guess you might be my lucky charm 🙂
