### ISSUE TITLE
Migration script so we can make it easier to go from KES to ESO

### ISSUE THREAD

**Issue by knelasevero** [external-secrets/external-secrets#325]
**Describe the solution you'd like**
Maybe we start a new project and write a script there to read through KES based CRDs on the cluster and create ESO based ones with values that make sense and all that. In the end it would test if everything is correct, if things have the correct reference to secrets, and would delete the KES CRDs and deployments. (I am trying to sort something out in this direction)

**What is the added value?**
A lot of people will need to migrate from KES to ESO. Having an automated way to do that would deliver great value.

**Comment by knelasevero** [comment]
@Flydiverny You also did some investigation on this front right? Maybe we could schedule something since I have no experience with KES?

**Comment by spirosoik** [comment]
@knelasevero I can help, I have used KES a lot

**Comment by knelasevero** [comment]
@spirosoik let's discuss on the next community meeting? We need to make it a bit "blue-green" to avoid problems, specially for people using this in production. I was thinking about just a simple mindless bash script calling required stuff

**Comment by Flydiverny** [comment]
> @Flydiverny You also did some investigation on this front right? Maybe we could schedule something since I have no experience with KES?

Aye! I started some basic convert KES resource to close-ish ESO resource. Would need more work and need a way to handle defining backends.
Anyway I pushed what I played with here https://github.com/Flydiverny/kes-to-eso/blob/main/kes-to-eso.mjs

**Comment by gusfcarvalho** [comment]
Hi Guys! I'm assigning myself to this issue. I'm already close to have something minimally functional. I'll let you know when we move this a little bit forward.

**Comment by Flydiverny** [comment]
I think 2) makes sense for migration.
Slightly related https://github.com/external-secrets/kubernetes-external-secrets/issues/604 (~create secrets without ownership), if that were to be implemented in KES it could possibly be used in a migration guide

**Comment by knowfahad** [comment]
Is there a way to run this on Mac? I get the error:

`bin/kestoeso: cannot execute binary file`
