### ISSUE TITLE
Add SonarQube analysis to CI pipeline

### ISSUE THREAD

**Issue by serdarkalayci** [external-secrets/external-secrets#328]
**Describe the solution you'd like**
The CI pipeline of ESO project should be analyzed by SonarQube to keep the technical debt under control. We can solve issues (at least those which make sense) that are presented by SonarQube as we develop the project. [Sonar Cloud](https://sonarcloud.io) is free for open source projects. 

**What is the added value?**
Software projects especially open source projects with a high number of contributors tend to pile up technical debt. By applying SonarQube analysis into our CI pipeline we can keep track of our debt, security issues etc. Even more we can set quality gates to prevent a code that is below our expected quality standards (eg. a code that introduced a new critical security issue) to be built.

**Comment by knelasevero** [comment]
Hey @serdarkalayci thanks! Should I assign this issue to you?

**Comment by serdarkalayci** [comment]
Sure @knelasevero, go for it

**Comment by knelasevero** [comment]
@serdarkalayci accept the GitHub invite for read access on the repo
