### ISSUE TITLE
TLS handshake Timeout

### ISSUE THREAD

**Issue by pratapkumarnanda** [external-secrets/external-secrets#3305]
**Describe the bug**
Got below error during create a SecretStore for cross account secret manaer access

![image](https://github.com/external-secrets/external-secrets/assets/84849253/8814a66a-44da-4528-ab2c-404d47fb879d)

**To Reproduce**
I have created a secret in AWS shared account (Account A) and EKS cluster in Account B.  Objective to share secret from Account A with Account B by using IRSA role.

Step 1 Create a Secret in Account A and created role based policy
Step 2: Create a Role in Account B(EKS cluster) and and trust relationship to Account A
step 3:  create a Service account and bind service account with SecretStore
Step4: Got the above error

1. provide all relevant manifests
2. provide the Kubernetes and ESO version 
    EKS : version : 1.29 ESO version v0.1.9

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by pratapkumarnanda** [comment]
$ kubectl describe SecretStore -n dev
Name:         secretstore-app
Namespace:    dev
Labels:       <none>
Annotations:  <none>
API Version:  external-secrets.io/v1beta1
Kind:         SecretStore
Metadata:
  Creation Timestamp:  2024-03-29T11:48:12Z
  Generation:          1
  Resource Version:    14889481
  UID:                 3d286fed-6680-4320-a978-cda5eaeb342b
Spec:
  Provider:
    Aws:
      Auth:
        Jwt:
          Service Account Ref:
            Name:  eso-sa
      Region:      eu-central-1
      Role:        arn:aws:iam::373308071649:role/eks1-external-secrets-operator
      Service:     SecretsManager
Status:
  Conditions:
    Last Transition Time:  2024-03-29T11:48:53Z
    Message:               unable to validate store
    Reason:                ValidationFailed
    Status:                False
    Type:                  Ready
Events:
  Type     Reason            Age   From          Message
  ----     ------            ----  ----          -------
  Warning  ValidationFailed  36s   secret-store  WebIdentityErr: failed to retrieve credentials
caused by: RequestError: send request failed
caused by: Post "https://sts.amazonaws.com/": net/http: TLS handshake timeout

**Comment by pratapkumarnanda** [comment]
Can anyone guide me why I ma geeting TLS timeout during create SecretStore . I dont get any documentation on this issue . I have created a AWSCLI container and able to access secret using same ServiceAccount

**Comment by rickymulder** [comment]
> Looks to be there's a restriction outbound from the ESO pods to the `sts` endpoint.
> 
> When using IRSA, the service account reaches out to the `sts` service to get a temporary auth token before making AWS API calls. If it can't, then it would fail.
> 
> Do you have an egress policy on the ESO namespace or a restriction on outbound connections in the security group?

@pratapkumarnanda did you get a chance to validate my previous reply?

**Comment by HerrSolix** [comment]
> **Describe the bug** Got below error during create a SecretStore for cross account secret manaer access
> 
> ![image](https://private-user-images.githubusercontent.com/84849253/318050581-8814a66a-44da-4528-ab2c-404d47fb879d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQwMzAwNDEsIm5iZiI6MTcxNDAyOTc0MSwicGF0aCI6Ii84NDg0OTI1My8zMTgwNTA1ODEtODgxNGE2NmEtNDRkYS00NTI4LWFiMmMtNDA0ZDQ3ZmI4NzlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI1VDA3MjIyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMzNhNzMzOTU0NDQ1ZTcwOTE5ZThhZGY0ZTQ2MGE0NzdmZjFiNmUzMWMxM2Q4NzI0NDc1MTBiYWVmZGNiZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CWjf0D3W8e74MIJ4QUle70IV2ZJE2J2Bi2W0Ed7-DZE)
> 
> **To Reproduce** I have created a secret in AWS shared account (Account A) and EKS cluster in Account B. Objective to share secret from Account A with Account B by using IRSA role.
> 
> Step 1 Create a Secret in Account A and created role based policy Step 2: Create a Role in Account B(EKS cluster) and and trust relationship to Account A step 3: create a Service account and bind service account with SecretStore Step4: Got the above error
> 
> 1. provide all relevant manifests
> 2. provide the Kubernetes and ESO version
>    EKS : version : 1.29 ESO version v0.1.9
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Additional context** Add any other context about the problem here.

Is your EKS cluster private ? if so you would need to configure AWS_STS_ENDPOINT envVar [](https://external-secrets.io/v0.6.0/provider/aws-parameter-store/#custom-endpoints)
