### ISSUE TITLE
Allow IBM Cloud Secrets Manager Provider to use ContainerAuthentication

### ISSUE THREAD

**Issue by jack-evans** [external-secrets/external-secrets#331]
**Describe the solution you'd like**
Describe the end goal of this proposal. What is this new functionality or the new behaviour (or what problem does it fix)?

Currently, when I use the external secrets project I have to provide a reference to a kubernetes secret containing the API key to interact with IBM Cloud Secrets Manager. This means I have to develop a way of bootstrapping the cluster with this secret that I probably would store in IBM Cloud Secrets Manager.

In release v5.6.x of IBM go-sdk-core, the ContainerAuthenticator was introduced. See the [authentication documentation](https://github.com/IBM/go-sdk-core/blob/main/Authentication.md#container-authentication) for more details. This could be used to instead authenticate with IAM and then the subsequent token be used in the Secrets Manager calls, thus avoiding the need for the extra bootstrapping step.

An end user will then only have to  install external-secrets on the cluster and create some configuration to say heres my secrets manager instance (maybe provide a profile name as to restrict the access to just secrets manager) and away you go.

**What is the added value?**

- End user utilising IBM Cloud Secrets Manager doesn't have to write custom tooling for bootstrapping kubernetes secret with API key and then managing and maintaining that secret.

**Give us examples of the outcome**

Could add under the auth object an `authType` that would be `apikey|container` and have an extra object called `containerRef` where we supply the necessary config such as profile, token location etc

**Observations (Constraints, Context, etc):**

N/A

**Comment by knelasevero** [comment]
This makes sense to me. Not sure I understand the 'outcome' description. Would you be up to helping implementing this?

**Comment by jack-evans** [comment]
yes sorry not 100% sure on the best way to implement this in a way that would be consistent across the rest of the providers....

What I was originally thinking was:

```suggestion
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secretstore-sample
spec:
  provider:
    ibm:
      serviceUrl: "https://SECRETS_MANAGER_ID.REGION.secrets-manager.appdomain.cloud"
      auth:
+      type: "apikey|container"
        secretRef:
          secretApiKeySecretRef:
            name: ibm-secret
            key: apiKey
+       containerRef:
+        profile: "my-profile-to-access-secrets-manager"
+        tokenlocation: "path/to/where/token/is/mounted/on/the/pod"
+        iamEndpoint: "https://iam.cloud.ibm.com"
```

however I am now thinking moving it a layer down and gate it on the type of secretRef provided:

```suggestion
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secretstore-sample
spec:
  provider:
    ibm:
      serviceUrl: "https://SECRETS_MANAGER_ID.REGION.secrets-manager.appdomain.cloud"
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: ibm-secret
            key: apiKey
+         secretcontainerAuthSecretRef:
+          profile: "my-profile-to-access-secrets-manager"
+          tokenlocation: "path/to/where/token/is/mounted/on/the/pod"
+          iamEndpoint: "https://iam.cloud.ibm.com"
```

**Comment by knelasevero** [comment]
Yeah, makes a lot of sense to me to get it as another optional secretRef!

**Comment by knelasevero** [comment]
@jack-evans can I assign this to you?

**Comment by jack-evans** [comment]
Sure - I'll try and make some time to look into this when I can 🙂

**Comment by jack-evans** [comment]
Apologies @knelasevero - haven't had much time to work on this, I did start having a look into it but one of the things that did concern me was that the secretRefApiKey property in the CRD would have to become optional... so you would end up with 2 optional fields and we would have to write some logic to say "but you have to at least define one of them". Any thoughts in this area?

**Comment by mmnatas** [comment]
Hi, I just submitted code that attempts to implement the configuration described above.  This is functionality I need for a project, seemed like a good way to start contributing!

**Comment by IdanAdar** [comment]
This is now provided, no?

**Comment by moolen** [comment]
right! Thanks for scanning these old issues  :bow: :broom:
