### ISSUE TITLE
ESO PushSecret with Vault - audit logs filling at enormous rate

### ISSUE THREAD

**Issue by ngarafol** [external-secrets/external-secrets#3318]
We are slowly migrating to ESO and I observed that it seems like there are only ESO requests in vault audit logs, and at high volume rate of over 30 messages per second! 

I am wondering how are others dealing with this? I know that there is apparently no filtering feature for Vault audit logs, and those requests and responses look like something I could filter easily and save enormous log storage space. 

Upon further inspection, I found few projects that are using PushSecret and it causes message rate of 15-20k messages per hour, per project :)

**Comment by tuttheking81** [comment]
> We are slowly migrating to ESO and I observed that it seems like there are only ESO requests in vault audit logs, and at high volume rate of over 30 messages per second!
> 
> I am wondering how are others dealing with this? I know that there is apparently no filtering feature for Vault audit logs, and those requests and responses look like something I could filter easily and save enormous log storage space.
> 
> Upon further inspection, I found few projects that are using PushSecret and it causes message rate of 15-20k messages per hour, per project :)

**Comment by ngarafol** [comment]
@tuttheking81 did you want to write something?

**Comment by ngarafol** [comment]
There is something wrong with PushSecret definitely. Vault version used is 1.7.2, ESO is v0.9.11. I noticed there is pushsecret fix  for vault added to v0.9.14 so will try that one. 
Currently increasing refreshInterval parameter of pushsecret helped decrease amount of messages a little, but not as much as I expected.
