### ISSUE TITLE
Support dual stack clusters

### ISSUE THREAD

**Issue by M0NsTeRRR** [external-secrets/external-secrets#3340]
**Is your feature request related to a problem? Please describe.**
There is no way for me to set the ipFamilyPolicy and ipFamilies to "preferDualStack" in the current helm chart for services

**Describe the solution you'd like**
Add the possibility to set in the ipFamilyPolicy and ipFamilies

**Describe alternatives you've considered**
Patch the current helm chart with kustomize

**Comment by M0NsTeRRR** [comment]
I will create the MR for this issue but I need to know if you want each services to be configurable with dual-stack or a global configuration for all services is sufficient.

**Comment by Skarlso** [comment]
Probably global should be enough since if one of the services is dual-stack you probably want all of them to be.
