### ISSUE TITLE
[Docs] Azure Container Registry Generator invalid JSON

### ISSUE THREAD

**Issue by hagel86** [external-secrets/external-secrets#3365]
**Describe the bug**
The JSON object passed into `.dockerconfigjson` in the documentation is invalid, it contains a trailing `,` where it shouldn't.
https://github.com/external-secrets/external-secrets/blob/d26987bea770e2a576f694dba878dd0457b51379/docs/snippets/generator-acr-example.yaml#L25

**To Reproduce**
Follow the guide, you'll get an error similar to this:
``` 
"error": "Secret "azurecr-credentials" is invalid: data[.dockerconfigjson]: Invalid value: \"<secret contents redacted>\": invalid character '}' looking for beginning of object key string"
```

**Expected behavior**
There should be no errors.

**Comment by ppatel1604** [comment]
@IdanAdar I have raised a PR to update the generator-acr-example.yaml. I also find a similar reference in `/site/search/search_index.json`. Is that an auto generated file or I have to update it manually?
