### ISSUE TITLE
TLS failed to verify certificate

### ISSUE THREAD

**Issue by jascsch** [external-secrets/external-secrets#3389]
We are not to able to establish a secure connection to our hashicorp vault server.
The error message is:
`unable to log in to auth method: unable to log in with Kubernetes auth: Put "https://xxx/v1/auth/xx-les-dev/login": tls: failed to verify certificate: x509: certificate signed by unknown authority`

Can you please provide a guideline how to add a cacerts.pem to the values.yaml?

**Comment by gusfcarvalho** [comment]
hi @jascsch ! you can use the CAProvider field to inject your custom CA certificates. https://external-secrets.io/latest/api/spec/#external-secrets.io/v1beta1.CAProvider

**Comment by letajmal** [comment]
How about if we are using the gitlab provider

**Comment by mick-huska** [comment]
Can you add the CAProvider field to the Secret Server provider so we can inject our custom CA certs for an on-premise secret server solution?

**Comment by gusfcarvalho** [comment]
> Can you add the CAProvider field to the Secret Server provider so we can inject our custom CA certs for an on-premise secret server solution?

You should create a separate issue with more info on what you're trying to do and which provider are you using. Most providers (SecretStores) are community maintained, so we'll use the new issue to broker it to the right people that need to be involved.
