### ISSUE TITLE
docs - the incorrect link

### ISSUE THREAD

**Issue by gecube** [external-secrets/external-secrets#3442]
<img width="682" alt="Снимок экрана 2024-05-02 в 14 01 31" src="https://github.com/external-secrets/external-secrets/assets/2912732/70a7dad6-89fc-4ff4-8fdb-ef169d2acfd9">

Hi Sirs!

The link could not be open. I am kindly asking to fix the documentation.

**Comment by shuheiktgw** [comment]
Thanks for reporting the issue!
Seems to be resolve by https://github.com/external-secrets/external-secrets/pull/3445
