### ISSUE TITLE
GithubApp CRD is not included in the Helm chart

### ISSUE THREAD

**Issue by ljtfreitas** [external-secrets/external-secrets#3447]
**Describe the bug**

Hi 👋 ,

I would like to use the generator introduced in this PR: https://github.com/external-secrets/external-secrets/pull/3115

But the CRD file was not included in the `kustomization.yaml` file, so the related CRD is not included in the Helm release.

**To Reproduce**

Just check the latest releases since the PR was merged, or try to build a `make helm.build` locally, and it's possible to see the CRD is not included in the chart.

**Additional context**

I just included the `generators.external-secrets.io_githubaccesstokens.yaml` in the `kustomization.yaml`, in my local environment, and the problem was solved. I opened a PR with the change: https://github.com/external-secrets/external-secrets/pull/3446

**Comment by gusfcarvalho** [comment]
Hi @ljtfreitas ! also added the comment to the PR - but worth to put on the issue. Helm chart manifest releases (https://github.com/external-secrets/external-secrets/releases/tag/helm-chart-0.9.17) do contain the mentioned CRD. How are you consuming the manifest?

I do agree we have issues with our `Kustomization` release, but that's a path for users that are not relying on our mainstream release method (the helm chart). I would like to understand better the issue to assess its severity.

**Comment by ljtfreitas** [comment]
Sorry, I've tested with the 0.9.16 version. In fact my first attempt was installing through Kustomize (running `kubectl apply -k ...`), as I saw the CRD was not installed I tried through `helm install` but this specific CRD wasn't installed yet. Strange, this one was installed just using a local build 🤔 . I'll try to reproduce again.

Thank you

**Comment by ljtfreitas** [comment]
Looking the chart release in fact it's included 🤔, maybe I did something wrong here 🤷🏽‍♂️. I will close this and open a new issue about the Kustomization file.

Thank you.
