### ISSUE TITLE
Integration for Infisical Secret Manager

### ISSUE THREAD

**Issue by akhilmhdh** [external-secrets/external-secrets#3466]
**Is your feature request related to a problem? Please describe.**

Hey everyone,

This issue is created to track the integration of [Infisical Secret Manager](https://infisical.com) with External Secrets Operator. 

Kindly assign this issue to me. We are pleased to make this contribution ourselves

**Comment by akhilmhdh** [comment]
If there is any guide on implementing a provider or auto generator for the process kindly let me know.

(Searched documentation regarding this couldn't find any. The contributing guide showed 404. I think this is a bug.)
![Screenshot 2024-05-07 at 9 03 11 PM](https://github.com/external-secrets/external-secrets/assets/31166322/bdeee4db-7dcf-4a7d-94e2-c0e2d1368ec9)

**Comment by gusfcarvalho** [comment]
hi @akhilmhdh ! Implementing a provider is basically implementing the Provider interface available in `apis/secretstore` folder. It is straightforward to the point we did not really bother creating a guide. If you want to do so while you add your provider, I'd be happy to include this to the docs 😄
