### ISSUE TITLE
CR validation fails with ExternalSecret objects using Orphan creationPolicy

### ISSUE THREAD

**Issue by marbindrakon** [external-secrets/external-secrets#3475]
**Describe the bug**
When upgrading from 0.9.13 to 0.9.14 via the OLM operator, the upgrade is blocked due to CR validation failures where there are v1beta1 ExternalSecret objects with spec.target.creationPolicy set to `Orphan`

`Orphan` is not in the enum for the v1beta1 ExternalSecrets CRD but is for the v1alpha1 version. It is still documented as an option in the Lifecycle section of the documentation and was apparently working anyway prior to 0.9.14 at least for me. 

Is this intended to be deprecated / removed or does it need to be re-added to the CRD enum?

**To Reproduce**
1. Have ESO 0.9.13 running on OpenShift 4.15.11 (k8s 1.28.9) with a v1beta1 ExternalSecret object using the Orphan creationPolicy such as is created by this template: https://github.com/marbindrakon/signal9-lab-gitops/blob/main/charts/metal-node-assignment/templates/credentials.yaml
2. Allow OLM to attempt upgrading from 0.9.13 to 0.9.14
3. Observe that the upgrade is stuck with the following error
```error validating existing CRs against new CRD's schema for "externalsecrets.external-secrets.io": error validating external-secrets.io/v1alpha1, Kind=ExternalSecret "redacted": updated validation is too restrictive: [].spec.target.creationPolicy: Unsupported value: "Orphan": supported values: "Owner", "Merge", "None"```

**Expected behavior**
If deprecation / removal is intended, then the behavior is correct. Otherwise, I would expect the upgrade to proceed as normal.

**Comment by shuheiktgw** [comment]
We added validation a while ago.  Please use v1beta1 if you'd like to use the Orphan creation policy!
https://github.com/external-secrets/external-secrets/pull/2819

**Comment by marbindrakon** [comment]
Just to clarify, are you saying that Orphan is no longer supported in v1beta1 or it is supported still? 

It appears to be supported in the v1beta1 API golang file, but the CRD bundle at https://github.com/external-secrets/external-secrets/blob/main/deploy/crds/bundle.yaml does not include it in the enum so validation is failing even though it seem like it should succeed.
