### ISSUE TITLE
Website broken link(s) for Contributing section

### ISSUE THREAD

**Issue by dublx** [external-secrets/external-secrets#3479]
**Describe the bug**
When navigating the website, the pages inside Contributing section return 404

**To Reproduce**
Open https://external-secrets.io/latest/contributing-devguide.md
See 404

**Expected behavior**
Open https://external-secrets.io/latest/contributing-devguide.md
See correct content

**Screenshots**
![Screenshot 2024-05-10 at 11 24 16](https://github.com/external-secrets/external-secrets/assets/884596/2f1813bd-8a3b-41be-a7be-de3f3a5cce62)

**Additional context**

**Comment by shuheiktgw** [comment]
Hmm, May I ask where the line comes from? The correct URL is following:
https://external-secrets.io/latest/contributing/devguide/

**Comment by dublx** [comment]
Did you try to use the website and either top navigation bar links or hamburger menus. The incorrect links come from there.

**Comment by shuheiktgw** [comment]
How did you find this URL in the first place? 
https://external-secrets.io/latest/contributing-devguide.md

**Comment by gusfcarvalho** [comment]
This was already fixed - we removed those burger menus. See https://external-secrets.io/main for reference. When we publish a new release (likely on monday, this should be fixed :))
