### ISSUE TITLE
Add IBM Power (ppc64le) support

### ISSUE THREAD

**Issue by IdanAdar** [external-secrets/external-secrets#3499]
We'd like to see support for IBM Power (ppc64le architecture) added to ESO.
Other than https://github.com/external-secrets/external-secrets/blob/477945777d8cc969ed54854f34bef1c134fb748a/.github/workflows/ci.yml#L148 would there be more locations to add such support for? Do you think anything else is needed?

**Comment by accursoft** [comment]
https://github.com/external-secrets/external-secrets-helm-operator/blob/main/Makefile#L90
It's less clear what needs to be done to build the operator for ppc64le, is cross-compiling enabled?
