### ISSUE TITLE
ESO is not able to remove Secret fields that are not managed by itself

### ISSUE THREAD

**Issue by Ben10k** [external-secrets/external-secrets#3514]
**Describe the bug**
If there is a secret that is Owned by an ExternalSecret, and that Secret object gets modified by adding additional fields under `data`, ESO does not remove those newly added fields.

**To Reproduce**
1. Create an External Secret.
2. Add a new field to the created Secret.
3. Wait for reconciliation or force a sync on the External Secret.
4. Check the Secret object, and the manually created field is not removed.

**Expected behavior**
I expected that the manually updated secret would be updated back to the expected initial state.
I would also expect to have a configuration option which would allow me to enable or disable this behaviour.
Another option would be to have the `immutable` option of the secret together with `recreate`, so whenever the secret value updated on the SecretStore, the ESO would delete the secret and create a new one with the same name.

**Additional context**
It seems like the fields have different managers under `managedFields` and the Server-Side Apply does not update the fields that are not managed by itself.

I have tried a workaround of creating `immutable` Secret from the External Secret, but when the secret get's updated at the SecretStore, the update is not reflected on the Secret, and I would like to use this functionality.

**Comment by shuheiktgw** [comment]
Hi, thanks for reporting the issue! Unfortunately, this is an expected behavior and not a bug. We have to use managed fieds to keep track of the secret data the controller owns.
