### ISSUE TITLE
Support for GetAllSecrets in Vault kv1?

### ISSUE THREAD

**Issue by nick-knowlson-alayacare** [external-secrets/external-secrets#3518]
### Problem

The documentation describes the ability to fetch multiple secrets:
* https://external-secrets.io/latest/guides/getallsecrets/
* https://external-secrets.io/latest/provider/hashicorp-vault/#getting-multiple-secrets

But when I try to use this with Vault kv version v1, I get the following error:
```
cannot perform find operations with kv version v1
```

### Question

Is this because of a fundamental limitation with Vault kv1 that makes it unsuitable for this? Or was it more of a cost/benefit analysis - where it is possible but would take time and not enough people want it?

### Possible Solutions

Implement support for GetAllSecrets for Vault kv version v1?

or 

Update [Vault-specific documentation](https://external-secrets.io/latest/provider/hashicorp-vault/#getting-multiple-secrets) to say this functionality is limited to kv2 and why?

### Additional Context

* We are looking to move away from Vault, so are not likely to upgrade from kv1 to kv2.
* PR that implemented GetAllSecrets for Vault kv2: https://github.com/external-secrets/external-secrets/pull/784
* List of PRs implementing GetAllSecrets for other providers: https://github.com/external-secrets/external-secrets/issues/698

Thank you! Any time is appreciated.

**Comment by moolen** [comment]
I don't think someone else is available, we'd be happy to review a PR :)
The error is returned here. Looking at the code it could be enough to just remove it :thinking:

https://github.com/external-secrets/external-secrets/blob/06e1342dcc9744b225dee73cfa19a58556ba01a8/pkg/provider/vault/client_get_all_secrets.go#L37-L39

**Comment by nick-knowlson-alayacare** [comment]
> I don't think someone else is available, we'd be happy to review a PR :)

No worries I'll take a look then!

> The error is returned here. Looking at the code it could be enough to just remove it 

Thanks! I was kind of hoping it would be something along those lines. I'll try out some changes and test it.

**Comment by nick-knowlson-alayacare** [comment]
Hello! Other work tasks took priority, but I am coming back to this now. 

I've created a PR with a first pass at getting this working: https://github.com/external-secrets/external-secrets/pull/3790

It probably needs a few more things before merging, but I think it is pretty close?
