### ISSUE TITLE
Vault provider chokes on non-regex paths without permissions

### ISSUE THREAD

**Issue by AndreasBergmeier6176** [external-secrets/external-secrets#3539]
**Describe the bug**
When we use `dataFrom.find` with a regex e.g. `^teamb.*` I would expect the provider to never look at e.g. `teama`.
It still sadly does try to recurse into `teama` and since it has no permission to do so - fails.

```
cannot read secret data from Vault: Error making API request.

URL: GET https://vault.foo.bar/v1/gala/metadata/live/teama?list=true
Code: 403. Errors:

* 1 error occurred:
	* permission denied
```

**To Reproduce**
1. See example above
1. Remove list permission from `teama`

**Expected behavior**
Since the regex is anchored it should never recurse anywhere where the path does not match the regex. Here everything not `teamb`.

**Additional context**
From the code is seems like it naively recurses through all metadata without consulting regex. This implementation might be too naive.

**Comment by gusfcarvalho** [comment]
hi @AndreasBergmeier6176 . Can you please share your manifests?

**Comment by gusfcarvalho** [comment]
Of course, if you by any chance know a regexp magic to perform validation without even querying vault API, I'd happily review that PR 😄 My take this is not going to be an easy task as you'd need to implement logic for the full https://pkg.go.dev/regexp implementation (like `^(a|[bc])+[def]+/foo.` would IMO render it impossible to determine preflight all the `root` paths - but hey if you know how to, PRs are welcome)
