### ISSUE TITLE
Verify stacking of reconcile loops

### ISSUE THREAD

**Issue by alekc** [external-secrets/external-secrets#354]
I am not sure if it's an issue, but unless someone has definitive  answer it should be looked into it. 

At the moment  we use the requeue interval in order to deal with refreshes and it kind of works. My concern is about stacking. Let's say that we have a highly dynamic secret which is being refreshed every 5 min, and we set our refresh interval to 5 min as well. On the second run, we update values on configmap which we own, and our own status, that will trigger 2 different reconcile event, every one of which will be requeued. 

The question is: are we sure that these requeue events are merged together? Or do we look into potentially exponential growth of calls against kube api?

https://github.com/external-secrets/external-secrets/issues/353 should help with reducing number of overall loops, but if they are not merged, we probably need to think about overall logic and leverage jobs to trigger updates (or something similar). 

**Proposed test**
It should be easiesh to test out, if we print something on every reconcile loop, it will be sufficient to edit child config maps several times and see if the interval is observed or not.

**Comment by alekc** [comment]
ok Cool, so the only issue remaining then is the logical one. 

From what I got on those docs (and please bear with me, it's morning and I didn't take my coffee yet), let say we have created a externalsecret which has been synced to the kind=secret, refresh time is 24h. 
Then 23 h later another event happens (i.e. kind=secret annotation change or whatever). 
```
	case result.RequeueAfter > 0:
		// The result.RequeueAfter request will be lost, if it is returned
		// along with a non-nil error. But this is intended as
		// We need to drive to stable reconcile loops before queuing due
		// to result.RequestAfter
		c.Queue.Forget(obj)
		c.Queue.AddAfter(req, result.RequeueAfter)
		ctrlmetrics.ReconcileTotal.WithLabelValues(c.Name, labelRequeueAfter).Inc()
```
means that we will loose our refresh target, as it will be pushed 24h down the line isn't it? It's a minor issue in most scenarious, but unexpected one for the customer. It might be better to think about using something like https://github.com/robfig/cron in a separate go routine for precise handling of externalsecret object's refresh (any change to them will trigger the reconcile and propagation)

**Comment by knelasevero** [comment]
Like you say, this is a minor issue in most scenarios, even though it is unexpected for the user. I would personally think that keeping it simple would be better (following KISS approach). A Cron in a separate go routine sounds like unneeded complexity tbh.

I think it would make sense to tackle this if we have recurrent reports of problems in that regard, and I assume that we would not. I could be wrong. What do you think?

**Comment by alekc** [comment]
Yes, as I said it's a minor. For now we can deal with this by adding a mention in docs against refresh interval, something along the lines `Note: any change against the externalSecret object or the dependent configMap (in case of ownership set to Owner) will cause the drift in the next refresh date`  (native speaker can express it much better probably :p)

**Comment by moolen** [comment]
I'd say this is a bug and i think we can quite easily fix it when we return the time duration from now until the desired refresh time instead od the static refresh interval here:

https://github.com/external-secrets/external-secrets/blob/8258509c0eb5c9098da0adabf7e58895d70cb38c/pkg/controllers/externalsecret/externalsecret_controller.go#L167

**Comment by alekc** [comment]
Yes, that probably would do it, although a bit of consideration for the errors should be involved as well. 

Also, just fiy, that particular bit of code is potentially going to be affected by https://github.com/external-secrets/external-secrets/pull/349 depending on the route I am going to take on that ticket

**Comment by knelasevero** [comment]
Yeah, makes sense. And it is simple enough.

A colleague added sonar Cube to the project and it revealed very high numbers for cognitive complexity of the controller. Just wanted to make sure we try to keep things simple 😅

But yeah, makes sense
