### ISSUE TITLE
Provide openapi schemas for custom resources

### ISSUE THREAD

**Issue by vladarts** [external-secrets/external-secrets#359]
**Describe the solution you'd like**
We are building helm charts for internal usage generating json schemas to validate values files. Now we need to go through the steps:

- Clone the external-secrets repository
- Apply some modifications: add `// +k8s:openapi-gen=true` comment to the `apis/externalsecrets/v1alpha1` and `apis/meta/v1` packages
- Using [kube-openapi](https://github.com/kubernetes/kube-openapi) we are generating OpenAPI specs
- Using [openapi2jsonschema](https://github.com/instrumenta/openapi2jsonschema) we are generating Json Schema definitions and insert them to our Helm Charts schemas.

**What is the added value?**
It will be much easier for other developers to integrate with the external-secrets controller.

**Give us examples of the outcome**

For Kubernetes definitions we are using Json Schema from the official repository: https://github.com/kubernetes/kubernetes/tree/master/api/openapi-spec

**Comment by moolen** [comment]
How would you like to consume the openapi schema? would you download an artifact from the release page? I'd say it's already there in the CRD definition.

Could you reuse the openapi spec from the [crd](https://github.com/external-secrets/external-secrets/blob/main/deploy/crds/external-secrets.io_externalsecrets.yaml#L33)? I don't know your tooling, but you could read the CRD and extract the openapi node and use it for validation.

**Comment by xxxbobrxxx** [comment]
Hi!
It would be great if you will publish such schema in swagger format like kubernetes already do that: https://github.com/kubernetes/kubernetes/tree/master/api/openapi-spec

**Comment by Andreabenf** [comment]
Since we already have the openapi spec drom the crd, we could only translate it into the swagger format, right?
That way we won't be needing the `// +k8s:openapi-gen=true` coments.
