### ISSUE TITLE
docs: missing controller flags for hashicorp vault token cache

### ISSUE THREAD

**Issue by ericdstein** [external-secrets/external-secrets#3599]
**Describe the bug**

Couldn't find an option for documentation updates...

The following flags were added to [enable caching of hashicorp vault client](https://github.com/external-secrets/external-secrets/pull/1537) but the [docs](https://external-secrets.io/latest/api/controller-options/) don't mention these flags.
- experimental-enable-vault-token-cache
- experimental-vault-token-cache-size

I'd like to use these options but by not including them in documentation it appears to others at my company that they are not available or supported.

**To Reproduce**

N/A

**Expected behavior**

Docs show these as valid supported options.

**Screenshots**

N/A

**Additional context**

I can create the PR for this but wondering on this comment by @moolen ...
> We don't have a docs page yet that shows the different cli args available; In fact i'm in the process of restructuring the docs to add that page soon ™️. From my POV no need to add that.

**Comment by moolen** [comment]
> We don't have a docs page yet that shows the different cli args available; In fact i'm in the process of restructuring the docs to add that page soon ™️. From my POV no need to add that.

That docs page now exists, it's the one you've linked (that comment is about 2 years old :smile:).

It is an experimental flag (hence the name) and it is supported at the moment. I don't see a reason to remove it. We're just lacking the data whether or not people use it or need it, that prevents us from promoting the flag into a non-experimental stage.

**Comment by ericdstein** [comment]
@moolen in my testing thus far, caching the vault client works great and accomplishes what the original PR meant to achieve. I'm definitely not asking for it to be removed.

But I wonder how many users know about it if it's not mentioned in the docs. Since it was based on `--experimental-enable-aws-session-cache`, I'd think it'd be listed alongside that flag?

**Comment by moolen** [comment]
I agree, it should be there, too.

**Comment by werwolfby** [comment]
I was trying to find something in code about support caching, and found that flag (`experimental-enable-vault-token-cache`) in code only.

This is really need to be mentioned somewhere 😏!
