### ISSUE TITLE
1password.com support would be usable by a lot

### ISSUE THREAD

**Issue by KlavsKlavsen** [external-secrets/external-secrets#36]
**Describe the solution you'd like**
external-secrets should allow for mapping to passwords from ones store on 1password.com

**What is the added value?**
Supporting getting passwords from an ordinary password manager used by many, such as 1password.com - would mean you could simply map externalsecrets to the place you already keep your password - instead of having to move all passwords, or duplicating them.

I know a LOT of people who use 1password.com for its simplicity.. I personally don't - but know both companies and friends who do, and who need a better solution than the current sealed-secrets - which leads to secrets duplication (as they still store them in either in their passwordstore.org personal git repo, or 1password.com account).

**Comment by knelasevero** [comment]
We use it at Container Solutions, and we had a 1pass Backend implemented at our ContainerSolutions/externalsecret-operator solution. It was kinda hell to maintain, and we had to ship the 1pass binary together with our binary to be able to interact with them, since they won't expose a public API...

In the end we stopped having a use case internally for it and we decided to stop supporting 1pass.

I personally think this won't be possible and advisable to be implemented, unless they (1password) start exposing a public API.

**Comment by KlavsKlavsen** [comment]
@knelasevero in that case then yes - this should be done by having a container with 1password CLI client - and interacting with that.. its not "pretty".. But it should work fine.. Anyways - it was just an idea.. if no one has the need or inclination to write it - it won't come to pass :)
IMHO 1password should really write such a backend for external-secrets themselves.. and I'll be sure to plug the idea with them as soon as this project takes off - as I'm sure it will :)

**Comment by knelasevero** [comment]
Thanks a lot @KlavsKlavsen ! Shipping a third party binary in our releases isn't something that we look forward to :sweat_smile:. But we will keep a look and would love to have contributions. 

I will close this issue for now. But feel free to re-open if  something comes up! :smile:

**Comment by sarasensible** [comment]
@snarlysodboxer  are you currently working on this?  We are in the same boat and would like to use 1Password with External Secrets.

**Comment by snarlysodboxer** [comment]
@sarasensible Yes. We've written it, are testing it out and writing docs. Hope to submit a PR pretty soon.

**Comment by rgduncan** [comment]
@snarlysodboxer this feature would be huge for us and we're holding off on using SSM in anticipation of this backend. Do you have an estimate for when the PR will be submitted?

**Comment by snarlysodboxer** [comment]
Just fixing merge conflicts, then will submit. Sorry it's taken so long!

**Comment by snarlysodboxer** [comment]
Support for 1Password just got merged. I'm assuming it'll show up on external-secrets.io shortly. We can close this issue.

**Comment by knelasevero** [comment]
This will be out in the next release, but if you want to early test it you can by using the main image: https://external-secrets.io/v0.5.2/guides-using-latest-image/

I think we should release it this Wednesday after the community meeting.
