### ISSUE TITLE
UBI image currently is very bloated leading to Vulnerability Remediation churn 

### ISSUE THREAD

**Issue by bainsy88** [external-secrets/external-secrets#3606]
**Is your feature request related to a problem? Please describe.**

Currently the UBI based image is based off ubi-minimal which is has >100 packages most of which are not needed. This creates vulnerability churn so this commit swaps it out for something the equivalent of Distroless but using UBI packages

**Describe the solution you'd like**
Created an image directory in the first stage of the build that contains the minimum set of files to run a non-statically compiled Go app and be scannable by image vulnerability scanners. An RPM database is then created just for the packages in the image dir both this and the libs are then copied to the final base image.

**Describe alternatives you've considered**
Another option could have been to use UBI micro but this has more packages than this solution and also doesn't have a package manager which makes getting package updates more complicated when the CI is not running on RHEL. 

**Additional context**

**Comment by IdanAdar** [comment]
@moolen @bainsy88 we've tested the PR and all is good. Ready for merge.
