### ISSUE TITLE
pushsecret getting into error & popping about GCP SM secret is not managed by external secrets

### ISSUE THREAD

**Issue by yogeshsardana-ag** [external-secrets/external-secrets#3623]
**Describe the bug**
There's a problem with GCP SM provider for pushsecret as it unable to push the secret to GCP secrets manager secret as referenced in remote ref with the key of the GKE secret provided already in manifest. 

**To Reproduce**
1. YAML manifest created for pushsecret

apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
 name: test
 namespace: istio-ingress-test
spec:
 refreshInterval: 10s
 secretStoreRefs:
   - name: clustersecretstore
     kind: ClusterSecretStore
 selector:
   secret:
     name: argocd-test
 data:
   - match:
        secretKey: tls.key
        remoteRef:
         remoteKey: test-secret-eso-gsm

2. GKE secret in cluster:

$ kubectl describe secrets argocd-test --namespace istio-ingress-test
Name:         argocd-test
Namespace:    istio-ingress-test

Type:  kubernetes.io/tls

Data
====
ca.crt:   1740 bytes
tls.crt:  2078 bytes
tls.key:  2459 bytes

3. kubectl describe clustersecretstore clustersecretstore

$ kubectl describe clustersecretstore clustersecretstore
Name:         clustersecretstore
Namespace:    

API Version:  external-secrets.io/v1beta1
Kind:         ClusterSecretStore
Metadata:
  Creation Timestamp:  2024-06-18T13:20:52Z
  Generation:          1
  Resource Version:    14245
  UID:                 f142fc13-905e-4214-9ac4-774a4244c530
Spec:
  Provider:
    Gcpsm:
      Project ID:  gcp-test-project-1234
Status:
  Capabilities:  ReadWrite
  Conditions:
    Last Transition Time:  2024-06-18T13:21:41Z
    Message:               store validated
    Reason:                Valid
    Status:                True
    Type:                  Ready
Events:
  Type    Reason  Age                  From                  Message
  ----    ------  ----                 ----                  -------
  Normal  Valid   52s (x1453 over 5d)  cluster-secret-store  store validated
  
 4. gke SA has secrets manager admin perms already.
 
 5. versions:
gke: 1.27.13-gke.1201000
eso: v0.9.16
  
**Expected behavior**
secret should be written into the GCP SM secret created without error.

**Screenshots**

Error:

Events:
  Type     Reason   Age                From        Message
  ----     ------   ----               ----        -------
  Warning  Errored  2s (x46 over 11h)  pushsecret  set secret failed: could not write remote ref tls.key to target secretstore clustersecretstore: secret test-secret-eso-gsm is not managed by external secrets

**Additional context**
Any help would be commendable here..

**Comment by yogeshsardana-ag** [comment]
@moolen

**Comment by Skarlso** [comment]
That is an expected behaviour. ESO will not overwrite any secrets that it doesn't manage. Meaning if there is a secret with the same name existing already, ESO will not start managing that. It will error instead.

Please remove any existing secrets before pushing a secret to the remote provider.

**Comment by yogeshsardana-ag** [comment]
@Skarlso can you quote an example here given the use case & scenario I've, thing is I tried with having a copy of this secret (removing non-required annotations & metadata) but it's still giving same error.

**Comment by Skarlso** [comment]
What I meant is that the secret key that you are trying to push exists in GCP already. So it won't overwrite it IN GCP. not the Kubernetes secret.

**Comment by yogeshsardana-ag** [comment]
@Skarlso GCP secret "test-secret-eso-gsm" is empty, no version are there in it.

**Comment by Skarlso** [comment]
Sure. But it exists. 😀

**Comment by yogeshsardana-ag** [comment]
@Skarlso , not having a secret is GCP SM created secret already should push the GKE secret into GCP SM secret easily but that's not happening here so can't think of secret key already present in GCP SM, must be a bug guessing.

**Comment by Skarlso** [comment]
Could you please detail what you are doing to the secret in GCP SM?

The secret there, in order for PushSecret to work, has to NOT exists and if it DOES exist it needs these labels:

```
managed-by: external-secrets
```

If it doesn't have this, it will error with the above error that you have.

**Comment by Skarlso** [comment]
Noice! :) 🎉

**Comment by Skarlso** [comment]
Closing this. Please reopen if something still isn't working. 😗

**Comment by gerardgumboc-amcs** [comment]
> Could you please detail what you are doing to the secret in GCP SM?
> 
> The secret there, in order for PushSecret to work, has to NOT exists and if it DOES exist it needs these labels:
> 
> ```
> managed-by: external-secrets
> ```
> 
> If it doesn't have this, it will error with the above error that you have.

Hi @Skarlso. First, I would like to apologize for commenting on a closed thread. Was just wondering what version of ESO would this label work? I've tried adding these labels to ESO manifests (PushSecret, SecretStore and ExternalSecret) that we have and it seems I'm still getting the same error on my PushSecret:
`set secret failed: could not write remote ref ***redacted***-password to target secretstore ***redacted***-keyvault: cannot get secret ***redacted***-password: not managed by external-secrets`

Would we also need to add this as a tag on our Azure KeyVault?
