### ISSUE TITLE
Read kubeConfig from Secret in kubernetes provider

### ISSUE THREAD

**Issue by VT5BXA6659** [external-secrets/external-secrets#3627]
**Is your feature request related to a problem? Please describe.**
We do want to sync secrets to another cluster, for that we want to create a `SecretStore` with the `kubernetes` provider. Currently the provider needs to be configured with `server.url|ca` and the `auth` section. In our situation we do have a full kubeconfig stored in a secret we want to use.

**Describe the solution you'd like**
The idea would be to simply use the kubeconfig laying around in the given secret. Also being watched, or read every time to be sure the latest content is used.

**Describe alternatives you've considered**
Need to know the api server url and the ca at construction time of the `SecretStore` and transform the already present kubeconfig (extract the token to a separate secret) and use that secret

**Additional context**
I think it would not be that much effort to achieve this, maybe I can create a PR for it.

**Comment by moolen** [comment]
Requests sounds good to me, that has popped up in other issues as well. :+1:
