### ISSUE TITLE
Add values schema to the eso helm chart

### ISSUE THREAD

**Issue by petar-cvit** [external-secrets/external-secrets#3642]
**Is your feature request related to a problem? Please describe.**
Hey, could we add the [values.schema.json](https://helm.sh/docs/topics/charts/#schema-files) to the helm chart? We are working on a [tool](https://github.com/cyclops-ui/cyclops) rendering UIs for helm charts based on their schema and would love to be able to support ESO as well.

**Describe the solution you'd like**
Add the values.schema.json file. In my opinion, it does not have to define all of the available fields but a set of more important fields users would usually update.

**Describe alternatives you've considered**
none

**Additional context**
I would like to take the issue

**Comment by gusfcarvalho** [comment]
hi @petar-cvit ! do you have any ideas how we can perform this without having to create a schema manually? We do not have that many resources to create & maintain the schema if it is not automated...

**Comment by petar-cvit** [comment]
@gusfcarvalho I found some tools for generating the schema, but the [most popular one](https://github.com/karuppiah7890/helm-schema-gen) seems like it's no longer maintained. Will check if I can find an alternative

If that helps, I can create the initial version of the schema, but I understand you find it time consuming to maintain over time

**Comment by petar-cvit** [comment]
Hey @gusfcarvalho, I have found one other schema gen tool that can be used via GitHub actions https://github.com/losisin/helm-values-schema-json

I can add the first version of the schema myself and include only the basic set of fields. Covering only a subset of fields through the schema will not require you to update it frequently.

Let me know what you think

**Comment by PrateekKumar1709** [comment]
Hi @petar-cvit, I did some digging as well and found these as other viable options:
[helm-schema](https://github.com/dadav/helm-schema), https://github.com/SocialGouv/helm-schema and https://artifacthub.io/packages/helm-plugin/schema-gen/schema-gen

However I feel that the one you mentioned earlier - [helm-values-schema-json](https://github.com/losisin/helm-values-schema-json) is a better option.

I was thinking that we can use the Helm Values Schema JSON Plugin to generate the values.schema.json file and integrate this process into the existing GitHub Actions workflow for automation. This ensures the schema is always up-to-date with minimal maintenance effort.

**Comment by Skarlso** [comment]
@PrateekKumar1709 sounds great! Have at it mate. 😁
