### ISSUE TITLE
ok-to-test: add finish outcome by editing the specific comment

### ISSUE THREAD

**Issue by Skarlso** [external-secrets/external-secrets#3645]
It would be nice to have the outcome of the run nicely in the comment once it finished.

Further, right now, `/ok-to-test sha=asdfsaf` actually ignores the SHA part and just fetches the latest SHA on that specific PR. We ought to fix that, or just edit the docs and use it without the SHA part.

**Comment by gusfcarvalho** [comment]
this was implemented (see https://github.com/external-secrets/external-secrets/pull/3674#issuecomment-2221135011)
