### ISSUE TITLE
Not defined API Version in example on Hashicorp Vault doc

### ISSUE THREAD

**Issue by jeffmachado** [external-secrets/external-secrets#3661]
Hi,

[kind/documentation] [first issue]

Here in the following documentation there is no "apiVersion: v1" before line 93.
https://github.com/external-secrets/external-secrets/blob/374c7bf019be9678c99b90103cc17141dce3d1eb/docs/provider/hashicorp-vault.md?plain=1#L93

Copying/pasting in file to create the stack results in error describing that is not possible to create secret without the apiVersion (for sure :D)

**Comment by gusfcarvalho** [comment]
well, that Secret shouldn't really be copy pasted. It was just added to show what's the outcome from ESO. we may want to comment that to prevent users from having the same erorr 😄. Can you make a PR @jeffmachado ?
