### ISSUE TITLE
Support caProvider for BitwardenSecretsManager

### ISSUE THREAD

**Issue by nijave** [external-secrets/external-secrets#3676]
**Is your feature request related to a problem? Please describe.**
The BitwardenSecretsManager provider requires a certificate for serving HTTPS. This certificate can be generated by cert-manager. When it's generated by cert-manager, there's no way to inject the caBundle into ClusterSecretStore to allow for automatic rotation/re-issuance. 

**Describe the solution you'd like**
I'd like BitwardenSecretsManager to support `caProvider` similar to Kubernetes so the CA can be pulled from the Secret containing the CA which cert-manager is managing.

**Describe alternatives you've considered**
I could create a CronJob to routinely check and update the CA.
I could manually and periodically update the CA.

**Additional context**

**Comment by Skarlso** [comment]
Yep that sounds like a good request. I'm on vacation until the end of this week. If no one picks it up until then I'll do it after that. 😊

**Comment by Skarlso** [comment]
Doing this now. It just requires a bit of refactoring.
