### ISSUE TITLE
Shortform "es" for "externalsecrets" clashes with ElasticSearch "elasticsearches"

### ISSUE THREAD

**Issue by janlunddk** [external-secrets/external-secrets#3704]
**Describe the bug**
Not really a bug per se, but an inconvenience when multiple types of Kubernetes applications clashes.

When using the shortform `es` for èxternalsecret`, and you have elasticsearch installed, you will get either an empty result or an error.

**To Reproduce**
1. Install external secrets
2. Install elasticsearch
3. Create an external secret `my-es`in `mynamespace`
4. Run command `kubectl get es `my-es`-n mynamespace

Nothing will be returned, as there are no elasticsearch resources in that namespace.

Running other commands will expose the issue:
`kubectl annotate externalsecret my-es force-sync=$(date +%s) -n mynamespace`
Results in an error:
`Error from server (NotFound): elasticsearches.elasticsearch.k8s.elastic.co "my-es" not found`

**Expected behavior**
Well- initially the expectation was to be able to manage my external secrets using the shortform, however, digging into it makes it clear why it does not work.

**Additional context**
I know it is not optimal, but maybe the shortnames could be made a bit longer.

externalsecrets                   es => esx                      
clusterexternalsecrets        ces => cesx (Not strictly necessary, but just to keep some consistency)      

And I am not sure if it would make sense to make any changes for the stores as well. It is probably just a question of time before especially ss will clash with something else.

clustersecretstores               css                     
secretstores                      ss

**Comment by gusfcarvalho** [comment]
hi @janlunddk 😄 as you mentioned, thats not really a but per se.

> externalsecrets es => esx
> clusterexternalsecrets ces => cesx (Not strictly necessary, but just to keep some consistency)

we can't really do that as this is a breaking change to several users 😅
