### ISSUE TITLE
Support for secretRef in addition to CABundle for Bitwarden Provider

### ISSUE THREAD

**Issue by shanduur** [external-secrets/external-secrets#3726]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to manually manage the CABundle for the Bitwarden Provider. This manual process can lead to potential security risks and inefficiencies, especially since I'm already using CertManager for automated certificate management.

**Describe the solution you'd like**
Instead of using CABundle, I would like to specify `secretRef` holding the actual CA, as I am managing it via CertManager.

```go
// Reference to the secret containing the CA certificate for the Bitwarden server SDK. The SDK MUST run with HTTPS to ensure no MITM attacks can be performed.
// +required
secretRef esmeta.SecretKeySelector `json:"secretRef"`
```

**Describe alternatives you've considered**
N/A

**Additional context**
Using secretRef will streamline certificate management by leveraging CertManager's capabilities, improving security and reducing manual overhead. This change aligns with best practices for automated certificate management and enhances overall system robustness.

**Comment by Skarlso** [comment]
Yep.

However... Duplicate https://github.com/external-secrets/external-secrets/issues/3676 :) 

And will be closed by https://github.com/external-secrets/external-secrets/pull/3699
