### ISSUE TITLE
bump helm-docs image version in Makefile

### ISSUE THREAD

**Issue by mysteq** [external-secrets/external-secrets#3750]
**Is your feature request related to a problem? Please describe.**

Current image version 1.5.0 of jnorwood/helm-docs in Makefile only supports amd64, which makes "make reviewable" not runnable on a linux VM on MacOS arm without other changes.

**Describe the solution you'd like**

Update the helm-chart image version to i.e. 1.7.0, so it's possible to run the "make reviewable" on macos arm.

**Describe alternatives you've considered**

N/A

**Additional context**
N/A

**Comment by PrateekKumar1709** [comment]
Raised a PR for this:
https://github.com/external-secrets/external-secrets/pull/3806
