### ISSUE TITLE
Binary Secrets

### ISSUE THREAD

**Issue by ns-it-safadi** [external-secrets/external-secrets#3751]
**Describe the bug**
We have some keys  ( public key id_rsa for example) encoded with base64 on AWS secret manager, how Can I fetch it as its and save it in secret data section without encondig it?
this feature was done in previous tools "kubernetes-external-secrets" by setting flag isBinary in externalsecrets definition, and this value wont be encoded.

**To Reproduce**
1. cat ~/.ssh/id_rsa | base64
2. save encoded value as a secret in AWS secret manager
3. add this definition to your external-secret.yaml
`
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-public-key-file-secret
  namespace: msafadi-test
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: test-aws-css
    kind: ClusterSecretStore
  target:
    name: wimd-operator-app-file-secret
    creationPolicy: Owner
    template:
       engineVersion: v2
       data:
        id_rsa: "{{ .id_rsa_pub|b64dec }}"
  data:
  - secretKey: id_rsa_pub
    remoteRef:
      decodingStrategy: Auto
      key: "msafadi/public-keys"
      property: id_rsa
`
kubernetes version: 1.22.17
extrnal-secrets: v.0.9.20

**Expected behavior**
should save inside data section the value which is saved in AWS secret manager.

But unfortunetly it doesn't.

**Comment by Skarlso** [comment]
Hello.

What's the outcome? Did you try a none-templated plain approach? What was the result of that?

**Comment by ns-it-safadi** [comment]
results:
1- When I use one of two strategies
decodingStrategy: Base64 or Base64URL 
error msg: error retrieving secret at .data[0], key: msafadi/public-keys, err: could not apply decoding strategy to spec.data[0]: illegal base64 data at input byte 3468.

in controller I have this error
err: could not apply decoding strategy to spec.data[0]: illegal base64 data at input byte 3468","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:324\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:261\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.18.4/pkg/internal/controller/controller.go:222"}

2- When I remove this field or set it as Auto and without using filter b64dec in id_rsa: "{{ .id_rsa_pub|b64dec }}", 
id_rsa is encoded correctly using base64 and when I decode it, it shows me the value which I have it in secret manager in AWS.

3- but when I am using this filter id_rsa: "{{ .id_rsa_pub|b64dec }}", value of id_rsa: 
aWxsZWdhbCBiYXNlNjQgZGF0YSBhdCBpbnB1dCBieXRlIDM0Njg=
decoded "illegal base64 data at input byte 3468"

**Comment by Skarlso** [comment]
Sooo... use the 2 approach then? You said that's fetched correctly.

**Comment by ns-it-safadi** [comment]
yes, if I am not using this b64dec, it fetch the secret and encode it using base64 ( which I dont want to have it encoded).


This how isBinary: true was working in previous version kubernetes-external-secrets.

I tried to use in template instead of data to use stringData, but its not supported.

**Comment by Skarlso** [comment]
But if it's binary data you can't just retrieve it as is. It will be base64 encoded. Save it as string and it won't be anymore.

**Comment by ns-it-safadi** [comment]
so it means that we don't support isBinary option which we have it already implemented in previous library kubernetes-external-secrets.

why we can't save a string as a text plain in secrets?

**Comment by Skarlso** [comment]
Ah I think I know what you need. Chuck a `toString` into that pipeline of decoding. I think that's what you want there.

**Comment by Skarlso** [comment]
So basically try this. Use decoding set to `Auto` and then instead of b64dec use `toString`. That might result in what you want.

**Comment by ns-it-safadi** [comment]
I tried it, but still shows me that the value is encoded.

scenario:
lets say that we have this secret in AWS
id_rsa:  "cHVibGljX2tleQo=" ( encoded value by base64)

and I need to get this value and save it in secret.

Expected secret should be as below:

apiVersion: v1
data:
  id_rs1: cHVibGljX2tleQo=
immutable: false
kind: Secret
metadata:
  labels:
    reconcile.external-secrets.io/created-by: d9decfdf761103c1d1d24dc840abd4d1
  name: id_rsa_public_key
  namespace: msafadi-test
type: Opaque


THIS how isBinary: true works in kubernetes-external-secrets

**Comment by Skarlso** [comment]
Then use b64dec after tostring.

**Comment by ns-it-safadi** [comment]
this is the result of using {{ id_rsa_public | toString | b64dec }}

apiVersion: v1
data:
  id_rs: aWxsZWdhbCBiYXNlNjQgZGF0YSBhdCBpbnB1dCBieXRlIDM0Njg=
immutable: false
kind: Secret

**Comment by Skarlso** [comment]
Check out the discussion here https://github.com/external-secrets/external-secrets/discussions/581

**Comment by ns-it-safadi** [comment]
I solved the issue, thanks a lot for help.
toString|trim|b64dec works correctly.

in case of illegal base64 ( mostly the error is related to encoded secret in AWS, try to recreate it and remove whitespaces from encoded value"

**Comment by ns-it-safadi** [comment]
thank you.

**Comment by Skarlso** [comment]
AAAAAAWWWW TRIM :D Damn, nice find. :) Well done.
