### ISSUE TITLE
Delinea provider is listed twice on the documentation page, and Delinea Secret Server is missing

### ISSUE THREAD

**Issue by Shiakaron** [external-secrets/external-secrets#3795]
**Describe the bug**
Easiest way to describe the bug is with the link to the issue: https://external-secrets.io/latest/provider/delinea/ 

I am not sure how the docs page is put together but it is worth noting that I don't see the secretserver provider docs listed https://github.com/external-secrets/external-secrets/blob/v0.10.0/docs/provider/secretserver.md

**To Reproduce**
n/a

**Expected behavior**
I would expect the second delinea entry to be for the secretserver provider

**Screenshots**
![image](https://github.com/user-attachments/assets/ccbce609-db23-48af-babe-da03f444850e)

**Comment by Shiakaron** [comment]
I am not sure how to add a `docs` label on the issue

**Comment by pauliyobo** [comment]
Hello. the issue appears to be here:

https://github.com/external-secrets/external-secrets/blob/bc97ae06f669c17903ad3b170a71dd4fd47045c8/hack/api-docs/mkdocs.yml#L118-L119

I'm happy to submit a PR to fix it unless @Shiakaron or whoever would like to do it.

**Comment by oscerd** [comment]
I noticed the same and attempting a fix here: https://github.com/external-secrets/external-secrets/pull/3874
