### ISSUE TITLE
Outdated bitwarden-sdk-server chart dependency

### ISSUE THREAD

**Issue by brianramseyau** [external-secrets/external-secrets#3849]
**Describe the bug**
The bitwarden-sdk-server dependency chart has not been kept up to date with the latest oci builds.

**To Reproduce**
Check the Chart.yaml shows `v0.1.4` here: https://github.com/external-secrets/external-secrets/blob/a1722cbfaa5620fdab3c71f2269e70525a4d989b/deploy/charts/external-secrets/Chart.yaml#L19

**Expected behavior**
Check https://ghcr.io/external-secrets/charts/bitwarden-sdk-server 
current version of oci chart is `v0.3.1`

**Screenshots**
N/A

**Additional context**
Also present in the helm-specific tag (in case of CI updating the artifacts, etc being the case)
https://github.com/external-secrets/external-secrets/blob/helm-chart-0.10.2/deploy/charts/external-secrets/Chart.yaml#L19

**Comment by Skarlso** [comment]
You can override the image tag version during installation with --set bitwarden.image.tag=version but you're right that it's outdated.

**Comment by brianramseyau** [comment]
@Skarlso While I appreciate you can do that (something I already do, in fact) it is not the same thing by any means (image version vs chart version)

Taking a look at the compare between the current dependency version, and the current version in-repo here: https://github.com/external-secrets/bitwarden-sdk-server/compare/v0.1.4...v0.3.1

You can see there are some (arguably minor) features added to the chart, but over time if this is not updated it's going to diverge further and further. I felt it best to raise it when I noticed it starting to drift by several versions :) More critically is the image tag being out of date by default that may be more troubling for people just getting started.

As I run ArgoCD I can also just disable the sub-chart entirely and manage it entirely as a separate source, not that it matters at present with the minor drift.

Anywho, was more of an FYI than something thats critical.

**Comment by Skarlso** [comment]
Nah I absolutely agree I need to update the version. I just said that as a quick workaround. I'll update the version. Sorry I left it out of the release.

**Comment by brianramseyau** [comment]
Oh, there's no need to apologise at all. Things get missed, just good to surface it rather than ignore it. Easy stuff to miss 👍
