### ISSUE TITLE
Docs: Confusing Support information 

### ISSUE THREAD

**Issue by shazib-summar** [external-secrets/external-secrets#3863]
**Describe the bug**
At https://external-secrets.io/latest/introduction/stability-support/ it says

> we offer long-term support for our latest two (N, N-1) software releases

With the release of `0.10`, N and N-1 releases are `0.10` and `0.9`. The table on the page however depicts 0.8.x as supported too with the EOL date being "Release of 1.0"

I'm confused here as to whether 0.8.x is supported or not?

**To Reproduce**
Observe the compatibility table at [external-secrets.io/latest/introduction/stability-support](https://external-secrets.io/latest/introduction/stability-support/)

**Expected behavior**
Not sure. Seeking guidance.

**Screenshots**
<img width="525" alt="image" src="https://github.com/user-attachments/assets/8abd194c-893d-421d-af48-8e6d71d12ace">

**Additional context**
None

**Comment by shazib-summar** [comment]
I'm happy to create a PR to update the documentation once the confusion is resolved.

**Comment by gusfcarvalho** [comment]
yeah - Its not supported anymore :smile: even 0.9 is probably poorly supported

**Comment by gusfcarvalho** [comment]
(its just that we thought 0.10 wouldnt really exist and we would already be on 1.0 by now)
