### ISSUE TITLE
API Spec is found under two different paths and different in each instance of docs

### ISSUE THREAD

**Issue by 7Pawns** [external-secrets/external-secrets#3866]
**Describe the bug**
For each version in the docs, there are two paths for the API spec, hypothetically suppose to be the same, but are different from each other, and one has much more data.

**To Reproduce**
https://external-secrets.io/latest/api/spec/
https://external-secrets.io/latest/spec/
The one under /api is more comprehensive, and probably the correct and updated one.

**Expected behavior**
Should be only one, the correct one, or both the same (the second one referencing the first).

**Screenshots**
## https://external-secrets.io/latest/api/spec/
![image](https://github.com/user-attachments/assets/d4f3dbcf-b2e4-450f-93d6-4e1f300732a2)
## https://external-secrets.io/latest/spec/
![image](https://github.com/user-attachments/assets/dd77f480-e7d4-44e4-b500-cc6087f8cb2d)

**Additional context**

**Comment by Skarlso** [comment]
Looks like one is up-to-date the other isn't. This is the up-to-date one https://external-secrets.io/latest/api/spec/

**Comment by 7Pawns** [comment]
@Skarlso I opened a PR to fix this
