### ISSUE TITLE
add scarf.sh to external secrets images/site

### ISSUE THREAD

**Issue by gusfcarvalho** [external-secrets/external-secrets#3872]
Currently, we are searching for more maintainers to help us with external-secrets operator. However, we have very poor visibility on companies that are actually depending on it to do an outreach.

tooling available, such as our analytics or devstats do not contain useful information that we can use, so I'm proposing to use scarf.sh to help us with this outreach campaign.

Why https://scarf.sh ?
* meant for open source
* Meant for this kind of activities
* Already used by other CNCF projects
* Used by CNCF itself

What we would need to do:

1. Add scarf.sh pixel to our documentation
2. Move documentation from github pages into something like a CDN;
3. Add a new DNS Record with cncf for our registry (so we have oci.external-secrets.io). This would be a cname to scarf
4. Bump helm charts to use the new DNS record

**Comment by gusfcarvalho** [comment]
@moolen @Skarlso  I would like to know your thoughts in here before taking any action :smile:

**Comment by moolen** [comment]
LGTM.

**Comment by Skarlso** [comment]
Okay from me too.

**Comment by gusfcarvalho** [comment]
Relevant Service Desk Ticket https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1/CNCFSD-2443

**Comment by gusfcarvalho** [comment]
This was implemented btw
