### ISSUE TITLE
Proposal: New ExternalSecret policy to reference existing Secrets without deletion

### ISSUE THREAD

**Issue by Sn0rt** [external-secrets/external-secrets#3881]
**Is your feature request related to a problem? Please describe.**

In the current implementation, the Owner policy sets the ownerReference on the Secret when it is created, and the Orphan policy doesn't set an ownerReference at all. However, the Owner policy isn't ideal for some scenarios, such as:

1. When the Secret already exists in the cluster,
2. We want to establish a reference relationship between the Secret and the ExternalSecret, e.g., for ArgoCD UI visualization,
3. Actually. we don't want the Secret to be deleted when the ExternalSecret object is removed.
 
(Because external secert may not be written correctly at once during debugging, but some people do not want the life cycle of es object to be related to the life cycle of secert. After all, secert is not rendered independently by external secert.）

I understand that Kubernetes provides a mechanism to prevent this by setting blockOwnerDeletion: true and controller: false, which stops the child resource (Secret) from being deleted when the owner (ExternalSecret) is removed.

I propose creating a new policy that supports this scenario by:

Setting `blockOwnerDeletion: true` and `controller: false` on the ownerReference for the Secret, which will establish a reference without deleting the Secret when the ExternalSecret is removed.

Does this make sense for a new ExternalSecret creation policy?

**Describe the solution you'd like**

```go
const (
    // Reference sets the ownerReference on the existing Secret with blockOwnerDeletion: true and controller: false.
    // This prevents the Secret from being deleted when the ExternalSecret is deleted.
    CreatePolicyReference ExternalSecretCreationPolicy = "Reference"
)

```

**Describe alternatives you've considered**

N.A

**Additional context**

@gusfcarvalho

**Comment by gusfcarvalho** [comment]
hmm @Sn0rt what would happen after a second recreation? IIRC this would just fail as we cannot set the new owner ref - am I missing something here?


> When the Secret already exists in the cluster,

Is your need to really start owning something that was not really owned by an ExternalSecret object? 😄 This sounds a bit counter intuitive for me.

**Comment by Sn0rt** [comment]
> hmm @Sn0rt what would happen after a second recreation? IIRC this would just fail as we cannot set the new owner ref - am I missing something here?
> 
> > When the Secret already exists in the cluster,
> 
> Is your need to really start owning something that was not really owned by an ExternalSecret object? 😄 This sounds a bit counter intuitive for me.

About implementation: The details of the implementation have not been verified. This issue discusses whether the feature is reasonable. The implementation will be discussed later.

About the semantics of owner reference: emmm, it does sound a bit ambiguous.

For example, secert has been created in the cluster, and only the owner reference is used to describe their reference relationship. However, the life cycle is independent. Such a scenario is very useful when migrating from a secert management solution to an external secert.

Think about it from another perspective. Why does the Kubernetes API provide a field like `blockOwnerDeletion`?
