### ISSUE TITLE
Create new external secret beside existing one with different names it takes loooong time

### ISSUE THREAD

**Issue by ns-it-safadi** [external-secrets/external-secrets#3904]
**Describe the bug**
I have already created some external-secrets with prefix new-, used for comparison secrets before final migration process from old to new tool, so I have already one created external-secrets, so I wanted to have final external secret without prefix new-.

**To Reproduce**
1. create new exteral secret with any name
2. create second external secret with different name.

**Expected behavior**
 creating second external secrets takes long time to be sync

**Comment by gusfcarvalho** [comment]
hi @ns-it-safadi ! can you please share more information? From which tool are you migrating from?

**Comment by ns-it-safadi** [comment]
I Created 4 cluster secret stores with different regions on one cluster (we have different secrets in different aws regions), so after creating these clustersecretstores, it starts to have latency in creating each new external secret. each new external secrets takes long time up to 4 min.


to reproduce this case: 
- create cluster secret store with different regions ( eu-central-1, us-east-1, us-east-2).
- create external secret with prefix new- to compare it with actual one. ( it take long time to create this ES)
- when it will be, then remove previous secret and recreate FINAL external secret without prefix new-.  ( again long time to create External Secret (ES)).

**Comment by ns-it-safadi** [comment]
I tried next solution to have one cluster secret store, where I have  +1500 external secrets, with 
- one cluster secret store
- concurrent: 4
- refreshInterval: 5m 
The time of creating new external secret takes 11m.


What to do in this case? What its the best practice to create external secrets?

what's about controller class and how it could be used with External Secret?

**Comment by thesuperzapper** [comment]
@ns-it-safadi after https://github.com/external-secrets/external-secrets/pull/4086 the performance is significantly improved, so it's possible you will be fine after that update.

That PR should be in the 0.11.0 verson of ExternalSecrets.

**Comment by ns-it-safadi** [comment]
This issue could be closed, because we set resources and two additional annotations which help with that.
    experimental-enable-aws-session-cache: true
    enable-secrets-caching: true
    client-burst: 50
    client-qps: 25

**Comment by gusfcarvalho** [comment]
hi @ns-it-safadi ! are you by any chance on kubernetes slack? I'd like to ask you some information that might be sensitive to discuss in here 😄

**Comment by amirdamirov** [comment]
@ns-it-safadi
HI, Where exactly you defined annotations ?
