### ISSUE TITLE
Release 10.4

### ISSUE THREAD

**Issue by nick-knowlson-alayacare** [external-secrets/external-secrets#3921]
Hello! As per the [release process docs](https://external-secrets.io/main/contributing/release/), I am creating this issue to request a new release. The specific functionality I am interested in is https://github.com/external-secrets/external-secrets/issues/3518, specifically this PR https://github.com/external-secrets/external-secrets/pull/3790.

This Issue tracks the next ESO release. Please follow the guideline below. If anything is missing or unclear, please add a comment to this issue so this can be improved after the release.

#### Preparation Tasks

- [x] ask in `#external-secrets-dev` if we're ready for a release cut-off or if something needs to get urgently in
- [ ] docs: [stability & support page](https://external-secrets.io/main/introduction/stability-support/) is up to date
  - [ ] version table
  - [ ] Provider Stability and Support table
  - [ ] Provider Feature Support table
- [ ] docs: update [roadmap page](https://external-secrets.io/main/contributing/roadmap/)
- [ ] tidy up [Project Board](https://github.com/orgs/external-secrets/projects/2)
  - [ ] move issues to next milestone
  - [ ] close milestone

#### Release Execution

- [ ] Follow the [Release Process guide](https://external-secrets.io/main/contributing/release/)

#### After Release Tasks

- [ ] Announce release on `#external-secrets` in Slack

**Comment by Skarlso** [comment]
https://github.com/external-secrets/external-secrets/pull/3923

**Comment by Skarlso** [comment]
https://github.com/external-secrets/external-secrets/pull/3917 will be a breaking change for Pulumi provider.

**Comment by Skarlso** [comment]
Ok, all important one were closed that I planned during this release. I think I'll do a release tomorrow.

**Comment by Skarlso** [comment]
https://github.com/external-secrets/external-secrets/pull/3949

This is the last one. Once this one is merged, I'll do the release.

**Comment by Skarlso** [comment]
last one, I promise... :D https://github.com/external-secrets/external-secrets/pull/3955
It's a really tiny doc fix. :D

**Comment by Skarlso** [comment]
Done
