### ISSUE TITLE
uuid generator docs have broken links to examples

### ISSUE THREAD

**Issue by MarcusDunn** [external-secrets/external-secrets#3953]
**Describe the bug**
Examples are not rendered in the generator/uuid page

**To Reproduce**
check out https://external-secrets.io/latest/api/generator/uuid/

**Expected behavior**
I imagine some kind of examples

**Screenshots**
![image](https://github.com/user-attachments/assets/81b3460d-ff85-4ad2-a2b7-b94b4acba623)

**Comment by Skarlso** [comment]
ahhhh. thanks for spotting this
