### ISSUE TITLE
Problem when pulling secrets from cross account secret manager

### ISSUE THREAD

**Issue by Michaell99** [external-secrets/external-secrets#3961]
Hi guys,

Im trying to achieve cross region secret retrieval from a shared account to 6 different clusters.

I have set up a clustersecretstore with irsa and role it suppose to assume in order to retrieve the secrets.

I can see they are created and injected to the pod yet in the pods the secrets are undefined for some reason.

Is there a way to fix it or add extra logs so it will be possible to solve this problem?

**Comment by Skarlso** [comment]
>I can see they are created and injected to the pod yet in the pods the secrets are undefined for some reason.

How are they injected? Environment variables?

We need some more information like, how your objects look like and how you are injecting the values.

**Comment by Michaell99** [comment]
Sure I do everything with helm will provide here all the configuration:
`{{- if .Values.secrets.secret }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.app_name }}-external-secret
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: eks-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.app_name }}-secret
  data:
  {{- range .Values.secrets.data }}
    - secretKey: {{ .secretKey  }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
  {{- end }}
{{- end }}
`
And this is the deploy yaml
`          {{- if .Values.secret }}
          envFrom:
            - secretRef:
                name: {{ .Values.app_name }}-secret
          {{- end}}
`

**Comment by Michaell99** [comment]
Fixed it the role didnt assume correctly
