### ISSUE TITLE
Webook Connectivity Breaks with AWS CNI Custom Networking Enabled

### ISSUE THREAD

**Issue by IdoOzeri** [external-secrets/external-secrets#3962]
So far I'm a very happy ESO user. Today we've added the `100.64.0.0./16` block to the VPC and added 3 private subnets that will be used to allocate IP addresses to pods. We also configured the VPC CNI to use [custom networking](https://aws.github.io/aws-eks-best-practices/networking/custom-networking/) as per AWS recommendations. 

Since we did that, we cannot seem to create/delete `ExternalSecret` resources. The error is:
```
error: Internal error occurred: failed calling webhook validate.externalsecret.external-secrets.io : failed to call webhook: Post https://external-secrets-webhook.external-secrets.svc:443/validate-external-secrets-io-v1beta1-externalsecret?timeout=5s : Address is not allowed
```  

I read somewhere that running the webhook in `hostNetwork` mode should solve the problem, which it did! But I'd really like to understand the reason it stopped working. Is it an issue with the security group? Communication between the APIServer and the node? (they're both using the same security group). With the new CNI setup, the worker node is assigned with something like `10.1.57.36` while the container is assigned with `100.64.165.150`, but why would it matter to the webook service?

My ESO version is `0.9.11`.
Kubernetes version is `1.30`.
CNI Version: `1.18`

I'd appreciate your help understanding the root cause of this. 
Thanks in advance

**Comment by gusfcarvalho** [comment]
hi @IdoOzeri - it matters to the webhook service because it is kubernetes API server that targets it. Because of your CNI setup, it essentially lives on a different network than your control plane (managed by AWS). AFAIK in most cases you can never really create a proper networking path between them - I might be wrong though, its been a long time since I last checked this :)

**Comment by gusfcarvalho** [comment]
however - this is for sure not a bug within external-secrets. It is more of a 'setup dependent' issue, if you know what I mean 😄
