### ISSUE TITLE
[FEATURE] Parse yaml secrets in Bitwarden Secret manager secrets

### ISSUE THREAD

**Issue by joryirving** [external-secrets/external-secrets#4000]
**Is your feature request related to a problem? Please describe.**
Currently when using the new bitwarden-sdk feature, to use key/value pairs, they need to be formatted in JSON
```json
{
  "key": "value",
  "key1": "value1"
}
```
When trying to use YAML coded secrets, it throws the following error:
```yaml
key: value
key1: value1
```
```
Events:
  Type     Reason        Age              From              Message
  ----     ------        ----             ----              -------
  Warning  UpdateFailed  0s (x2 over 2s)  external-secrets  error unmarshalling secret: invalid character 'k' looking for beginning of value
```

**Describe the solution you'd like**
Since I've been using [bws-cache](https://github.com/rippleFCL/bws-cache) which is a workaround, it allows the use of YAML formatted secrets, which all my secrets are.

**Describe alternatives you've considered**
I could potentially rewrite all my secrets, but that's quite a lot of work.

**Additional context**
Bitwarden ESO support was implemented by @Skarlso in https://github.com/external-secrets/external-secrets/pull/3603 with the following issue: https://github.com/external-secrets/external-secrets/issues/2661

**Comment by Skarlso** [comment]
Hey. This problem isn't unique to Bitwarden I'm afraid. It is how multi-key secrets are handled for EVERY provider.

Which means implemented this is actually no small feat. :)

**Comment by Skarlso** [comment]
So... I can make it work, but it's not going to work the same way like JSON does.

JSON supports raw `[]byte`s while YAML support for it is not that great. I had to do some shenanigans. So that's why most likely none of the other providers will ever do this. :D 

Anyways... PR incoming.
