### ISSUE TITLE
PushSecret: GCPSM Provider does not implement IfNotExists updatePolicy

### ISSUE THREAD

**Issue by tosih** [external-secrets/external-secrets#4016]
**Is your feature request related to a problem? Please describe.**
I would like to use the IfNotExists updatePolicy when using the GCP Secrets Manager provider.
When trying to use that property, ESO errors out with `not implemented`: https://github.com/external-secrets/external-secrets/blob/main/pkg/provider/gcp/secretmanager/client.go#L131-L133

**Describe the solution you'd like**
Implement SecretExists function in `pkg/provider/gcp/secretmanager/client.go`

**Describe alternatives you've considered**
While there may be alternatives to the flow I am considering, I think implementing this change is straightforward and would open up possibilities for other GCP Secrets Manager users.

**Additional context**
I am working on a PR now to address this issue and will link it when ready.

**Comment by rolandkool** [comment]
@tosih I ran into this same issue today. Have you been able to get a fix working? I'd be interested in testing it.

**Comment by Skarlso** [comment]
@rolandkool there is no workaround, but I added an implementation for SecretExists.

**Comment by rolandkool** [comment]
Thanks @Skarlso !

**Comment by rolandkool** [comment]
@Skarlso , sorry to bother you about this again. I was testing this today and noticed that the `not implemented` error is indeed gone, and I now get this message:
```
  Normal   Synced   8s (x2 over 8s)       pushsecret  PushSecret synced successfully. Existing secrets in providers unchanged.
```
However, my Google Secret does not have any versions. Isn't this supposed to create a new Secret version with the data I want to push? The Google Secret itself, I do not want to manage with ESO because we have a custom replication policy on it.

**Comment by Skarlso** [comment]
If it already exists it will find it as far as I know and then start managing it. Push something that doesn't exist?

**Comment by rolandkool** [comment]
I created a Google Secret without any versions and when trying to push an initial version, it gives this message. Also tried to add a version with some bogus data to see if it would update it or add a new version, but I got same message.

**Comment by Skarlso** [comment]
Hm. If it doesn't have the managed label I don't think it does anything. Did you try with a completely none existent version?

**Comment by rolandkool** [comment]
Yes, new secret, no prior versions in it. Do I need to provide a verion id/number in the pushsecret?
We manage the Google Secret using Googles Config Connector, which also adds a `managed-by` label of its own.

**Comment by Skarlso** [comment]
I have to check how that works.

**Comment by tosih** [comment]
Hey, sorry I didn't get around to getting my changes into review. But I did notice something with your merged changes. You are checking if the SecretExists, but not if the value is matching, is that the contract for SecretExists?

**Comment by tosih** [comment]
I probably should add that GCP also has the concept of enabled and disabled secret versions. That can also affect the validity of a secret (secretVersion) existing. But maybe I should step back a level and just care if the secret exists or not?

**Comment by Skarlso** [comment]
Above as in yours or mine? 🤔

**Comment by tosih** [comment]
Yours 👍🏾
