### ISSUE TITLE
Pull and push secret via a Go API

### ISSUE THREAD

**Issue by MiguelMartinho** [external-secrets/external-secrets#4034]
**Is your feature request related to a problem? Please describe.**
Currently, as far as I'm aware there is no way of pulling or pushing a secret via Go API (without using Kubernetes secret) from another Go microservice.

**Describe the solution you'd like**
Is it possible to somehow use external-secrets to programmatic push or pull secret via an API or import some package library of external-secrets?

**Comment by Skarlso** [comment]
Hello.

Since everything is going through a secret, right now ESO doesn't have a REST API or Library that could be used _without a secret_.
