### ISSUE TITLE
Helm-chart values.yaml uses the old repository URL

### ISSUE THREAD

**Issue by dnikoloski** [external-secrets/external-secrets#4057]
**Describe the bug**
values.yaml uses the old repository URL `oci.external-secrets.io/external-secrets/external-secrets` instead of `ghcr.io/external-secrets/external-secrets`

**To Reproduce**
```bash
helm repo add external-secrets https://charts.external-secrets.io && helm repo update
helm install external-secrets external-secrets/external-secrets -n external-secrets --create-namespace --set installCRDs=true
```
**Expected behavior**
Deployment should pull the image and successfully deploy the application in the cluster, but it is pulling from the wrong repository and `ImagePullBackOff` error is shown, it should pull the image from `ghcr.io/external-secrets/external-secrets`

**Comment by dnikoloski** [comment]
It was said in `v0.10.4` that the default image repo will be `oci.` but the image for `v0.10.5` was publish on `ghcr.io`.

`docker pull oci.external-secrets.io/external-secrets/external-secrets:v0.10.5`
gives error:
```Error response from daemon: Get "https://oci.external-secrets.io/v2/": tls: failed to verify certificate: x509: certificate is valid for ingress.local, not oci.external-secrets.io```

`docker pull ghcr.io/external-secrets/external-secrets:v0.10.5` works fine, but `values.yaml` takes `oci.` as repository.

**Comment by gusfcarvalho** [comment]
hi @dnikoloski ! 

We are likely to move away from `ghcr`, and `oci` is right now a proxy to allow smooth migration from it to our users. I recommend to **not** use `ghcr` anymore - while this will keep on working for a while, there will be no more guarantees it will keep on working.

I believe the problem you're having is specific to your setup:
```
docker pull oci.external-secrets.io/external-secrets/external-secrets:v0.10.5
v0.10.5: Pulling from external-secrets/external-secrets
d6d80cd6c618: Download complete 
Digest: sha256:b97ebc9975ccc378a5f29e9fc77e52e1d76cdbf48acad078428392eb6114c33f
Status: Downloaded newer image for oci.external-secrets.io/external-secrets/external-secrets:v0.10.5
oci.external-secrets.io/external-secrets/external-secrets:v0.10.5
```

**Comment by dnikoloski** [comment]
Hi @gusfcarvalho,

I have delete the `kind` cluster and recreated a a new one, and the `pull image` error persists.

![image](https://github.com/user-attachments/assets/16e3b693-a381-4f9f-96e1-0847a7a18512)

Can you reproduce?

**Comment by gusfcarvalho** [comment]
no, in my setup this is not reproducible - everything works well with kind or any other install setup:

```
kind create cluster
helm repo update
helm install external-secrets external-secrets/external-secrets
 kubectl get pods
NAME                                                READY   STATUS    RESTARTS   AGE
external-secrets-cert-controller-58b55664bb-lbpds   0/1     Running   0          34s
external-secrets-d85bcbcf7-z5vkc                    1/1     Running   0          34s
external-secrets-webhook-68667fcd48-5p5l9           0/1     Running   0          34s
```

The issue seems really to be related with a TLSi tool (or ingress configuration) within your setup 😅

**Comment by dnikoloski** [comment]
Yeah, it has to be something wrong with my setup... I don't use any custom kind config, I also `kind create cluster` and the pulling error image persists. I will close this for now.

**Comment by dnikoloski** [comment]
The issue was DNS...

It's always DNS.

**Comment by luander** [comment]
In my setup (homelab) pihole was blocking oci.external-secrets.io for some reason. Whitelisting the domain solved it.
