### ISSUE TITLE
controller spams kubernetes API about webhook errors even though it's disabled

### ISSUE THREAD

**Issue by jbilliau-rcd** [external-secrets/external-secrets#4066]
**Describe the bug**

During a review of the Kubernetes API logs (we are using EKS, so checking Cloudwatch), I noticed the external-secrets-operator is spamming the k8s api multiple times a second, complaining about "external-secrets-operator-webhook not found":

`I1030 01:15:45.396874      11 store.go:1063] Decoding externalsecrets.external-secrets.io "/registry/external-secrets.io/externalsecrets/beta-acquisition-intake-api/beta-acquisition-intake-api-aws-secrets-eso" failed due to conversion webhook for external-secrets.io/v1beta1, Kind=ExternalSecret failed: Post "https://external-secrets-operator-webhook.kube-system.svc:443/convert?timeout=30s": service "external-secrets-operator-webhook" not found`

You can see how often it's happening here:

![image](https://github.com/user-attachments/assets/163bf9f1-5227-4dc5-b15c-d8115162c74e)

**To Reproduce**

We are using EKS 1.29 with ESO 0.9.16, deployed with helm chart. I have set `certController.create=false` and `web hook.create=false`, since we don't want or need all these additional components. 

**Expected behavior**
If ESO is deployed with the certController and webhook disabled, it shouldn't spam the k8s api looking for it. This may be incurring performance or rate limiting impacts that haven't bubbled up just yet. Trying to be proactive.

**Screenshots**
See above.

**Additional context**

**Comment by Skarlso** [comment]
Hello.

Would you mind please trying with the latest version? There have been some modifications regarding webhooks so maybe this has been fixed.

**Comment by jbilliau-rcd** [comment]
Just deployed `0.10.5`, same result. I am counting at least 100 times a minute it's doing this too, which seems problematic.

**Comment by jbilliau-rcd** [comment]
also, if it helps, this only happens when an `ExternalSecret` and `SecretStore` object exist. If I remove them, so the controller is just "dormant", the logs disappear.

**Comment by Skarlso** [comment]
Huh, that is really weird. I took a peek and I have yet to discovery where and why this happens.

**Comment by Skarlso** [comment]
```yaml
crds:
  ...
  conversion:
    enabled: true
```

Disable this setting and see if that helps. :) @jbilliau-rcd

**Comment by jbilliau-rcd** [comment]
That fixed it! Thanks @Skarlso , I owe ya one; I'll close this issue and hopefully it fill help some future person who comes across the same issue.

**Comment by Skarlso** [comment]
Yipiii. Nice one! :) 🎉 🎉

**Comment by jbilliau-rcd** [comment]
That would be nice....I had no idea that setting existed, what it did, or that I should set it unless I had posted this issue. I would suspect many others users are having this spam happen as well and just don't know.
