### ISSUE TITLE
Clarify type of `refreshInterval`

### ISSUE THREAD

**Issue by lindhe** [external-secrets/external-secrets#4079]
It is unclear to me what type the `ExternalSecret.spec.refreshInterval` field has:

https://github.com/external-secrets/external-secrets/blob/51fabd49a54f311e35df4de0a50d48ba2f8449ff/apis/externalsecrets/v1beta1/externalsecret_types.go#L345-L349

I would like to write `2.5h`, but I don't know if that is legal. I can trial-and-error my way to the answer, but I would prefer if the API spec was clearer with exactly what type `refreshInterval` is. 🙂

**Comment by Skarlso** [comment]
Go's time duration uses integers. It's a meta wrapper around time.Duration. `2.5h` isn't a valid number. `2h30m` is.

This is documented here on metav1.Duration for Kubernetes. I guess we can add `2h30m` as an example. :)

**Comment by lindhe** [comment]
Yeah, that would be a great improvement. If we also mention the Go Duration type, that would be even better because then people can search online and find details. 👍

Is the documentation that comment I linked, or elsewhere? If you point me in the right direction, I'm happy to write a PR. 🙂

**Comment by lindhe** [comment]
Sorry, I meant the docs for the API spec of ExternalSecrets' `refreshInterval`. If I change the comment I linked to in my original post, does that get reflected in the API spec as well (e.g. when running `kubectl explain es.spec.refreshInterval`? Or do I need to change it elsewhere?

**Comment by Skarlso** [comment]
Oh yeah, that should be okay.
