### ISSUE TITLE
ACRAccessToken workload identity authentication ignoring the namespace under serviceAccountRef

### ISSUE THREAD

**Issue by OthElWarr** [external-secrets/external-secrets#4108]
**Describe the bug**
I have an ACRAccessToken like described here https://github.com/external-secrets/external-secrets/blob/main/docs/snippets/generator-acr.yaml#L37.
I am using workload identity with a service account attached to a federated identity, I have one generator in one namespace and the service account in another.
The external secret creation fails because it can not find the service account.

**To Reproduce**
1. create SA in one namespace
2. create ACRAccessToken in another namespace
3. create an external secret attached to the ACRAccessToken

**Expected behavior**
As described in the doc https://github.com/external-secrets/external-secrets/blob/main/docs/snippets/generator-acr.yaml#L37
the ACRAccessToken should be able to get to the SA

**Additional context**
After looking at the source code I can see the namespace under serviceAccountRef is never accessed it is always using the namespace of the ACRAccessToken 
https://github.com/external-secrets/external-secrets/blob/main/pkg/generator/acr/acr.go#L254-L257
while based on the doc the expected is using the namespace under serviceAccountRef or defaulting to the ACRAccessToken namespace in case it is not provided

**Comment by moolen** [comment]
Please see https://github.com/external-secrets/external-secrets/issues/3552#issuecomment-2155372863, generators are namespaced. We have https://github.com/external-secrets/external-secrets/issues/2009 to implement cluster scoped generators.
