### ISSUE TITLE
Concurrency for PushSecret Resource is Limited to 1

### ISSUE THREAD

**Issue by framsouza** [external-secrets/external-secrets#4123]
While reviewing the performance of the PushSecret resource in the External Secrets Operator, I noticed that the max concurrent reconciles for PushSecret is set to 1, whereas other resources (e.g., ExternalSecret, SecretStore) have their concurrency set to 100. This disparity appears to be unintentional and is causing occasional spikes in the workqueue depth for PushSecret, as shown in the monitoring visualizations.

## Expected Behavior
All resources, including PushSecret, should have the ability to configure and utilize higher concurrency levels, such as 100, similar to ExternalSecret and SecretStore.

## Current Behavior
PushSecret's concurrency is limited to 1, and there is no known configuration or setting available to adjust this value specifically for PushSecret and AFAIU the concurrent should be applied for the resources.

## Steps to reproduce
1. Monitor the workqueue depth for PushSecret.
2. Observe the workqueue depth occasionally spiking due to the limited concurrency.
3. Verify that concurrent: 100 is already configured globally, but PushSecret still defaults to 1.

## Impact
This limitation can cause delays in reconciling PushSecrets, especially in environments with a higher number of PushSecrets or frequent updates.

Currently, there does not appear to be a workaround to increase the concurrency for PushSecret specifically.

![Screenshot 2024-11-18 at 10 55 46](https://github.com/user-attachments/assets/453aa1ad-4739-4d2e-8325-6b612e4a913a)

**Comment by Skarlso** [comment]
It just _looks like_ it's a missed option to pass in the max concurrency flag to the manager setup.

```go
			psmetrics.SetUpMetrics()
			if err = (&pushsecret.Reconciler{
				Client:          mgr.GetClient(),
				Log:             ctrl.Log.WithName("controllers").WithName("PushSecret"),
				Scheme:          mgr.GetScheme(),
				ControllerClass: controllerClass,
				RestConfig:      mgr.GetConfig(),
				RequeueInterval: time.Hour,
			}).SetupWithManager(mgr); err != nil {
				setupLog.Error(err, errCreateController, "controller", "PushSecret")
				os.Exit(1)
			}

```

That said, maybe it was just missed or maybe it was deliberate back then to see if everything works correctly.

**Comment by Skarlso** [comment]
I created a PR and let's see what the e2e test has to say about it.
