### ISSUE TITLE
Newly added Secrets take anywhere between 5 to 15 minutes to reconcile.

### ISSUE THREAD

**Issue by philipp-durrer-jarowa** [external-secrets/external-secrets#4180]
**Is your feature request related to a problem? Please describe.**
We manage about 2000 external secrets in 20+ namespaces. Whenever we create a new secret we need to wait until the refresh queue (our secrets have a refresh interval of 30 secs) is done and the new secrets get synced. Due to the volume of secrets we also had to disable the webhook because it started to regularly time out on deployments/applying of ArgoCD managed applications. This leads to newly created secrets taking anywhere from 5-15mins to get synced for the first time.

**Describe the solution you'd like**
There should be some logic that external-secret resources which never had a successful sync attempt get triggered first. There should be like a scan for all external-secrets and if one is found that never was synced before it should be placed in the front of the queue instead of the back.

**Describe alternatives you've considered**
Re-enabling the webhook and analysing why the connection to the webhook endpoint times out might be the alternative to this.

**Additional context**
N/A

**Comment by Skarlso** [comment]
Hello. Did you try out 0.11.0 yet? We significantly optimized the refresh of external secrets. I encourage you to try that out and see if it helps with your problem.

**Comment by philipp-durrer-jarowa** [comment]
I've updated to 0.11.0 and while it seems to create the secrets quicker it doesn't seem to set the "SecretSynced" status anymore.

**Comment by Skarlso** [comment]
Well... running 2000+ secrets with 30s intervals will destroy your API server no matter what we do about it.

**Comment by philipp-durrer-jarowa** [comment]
Does the refresh interval affect the first sync attempt? We could technically increase it to 5min or 10min or so.

**Comment by gusfcarvalho** [comment]
@philipp-durrer-jarowa  are you on kubernetes slack? If so, do you mind DM'ing me @gusfcarvalho in there? I just want to understand your business requirements for having refreshInterval: 30s, which might be a sensitive discussion to have on public channels 😄

**Comment by gusfcarvalho** [comment]
> Does the refresh interval affect the first sync attempt? We could technically increase it to 5min or 10min or so.

RefreshInterval tells how many 'jobs' are on queue for ESO to reconcile. ESO will reconcile 10 at a time (the concurrent value). If one reconcile takes e.g. 1 minute due to throttling, this means for every one reconcile, two jobs are added - making this an impossible race for the controller to win.

In a setup as big as yours, I wouldn't even recommend enabling higher values for client sided throttling, as you'll start to hammer hard the API server (which is probably already busy with more important stuff such as ArgoCD).

**Comment by gusfcarvalho** [comment]
One way to troubleshoot whats happening is to check if the `workqueue_depth` metric is growing. This should never grow and should always reach zero. Spike behavior is fine, but if you see it in a constant line or growing, it means you need to adjust your setup

**Comment by gusfcarvalho** [comment]
I'm changing the issue name, as @Skarlso already mentioned, the feature request you added is not really possible - and the problem you're seeing is not really related to external-secrets at all - it is a configuration problem 😄

**Comment by thesuperzapper** [comment]
Personally, I think we should increase the default QPS and Burst (I will raise a PR to do this), but I also am skeptical that people should ever be increasing the concurrency beyond 1.

**Comment by thesuperzapper** [comment]
I have raised a PR to make the default QPS/Burst 50/100:
- https://github.com/external-secrets/external-secrets/pull/4202

**Comment by thesuperzapper** [comment]
Ok, I also found a bunch of other API calls that we can reduce, namely that we are spam creating events on the cluster when we fail to reconcile an ExternalSecret for any reason.

For example, if an ExternalSecret was failing to reconcile for any reason, it would retry many times very quickly, and may create hundreds of events on the cluster.

I think we can reduce this by storing a lot of the event info in the ExternalSecret status, but also reducing how quickly we retry after a failure (currently an exponential back off starting at 15ms up to a max of 15min).

**Comment by thesuperzapper** [comment]
Another thing I realized is that once an ExternalSecret is in the exponential back-off (because it's failing for some reason) even if you update the ExternalSecret or fix the error which is causing it to not sync, it could take up to 15 minuets to try again (which is the max error backoff).

**Comment by philipp-durrer-jarowa** [comment]
Thanks for digging into it, sounds like very reasonable improvements.

**Comment by gusfcarvalho** [comment]
> even if you update the ExternalSecret or fix the error which is causing it to not sync, it could take up to 15 minutes to try again (which is the max error backoff).

is this a new behavior with 0.11.0? I am sure for older versions any new updates causes a force reconcile immediately.

**Comment by gusfcarvalho** [comment]
> Thanks for digging into it, sounds like very reasonable improvements. @gusfcarvalho we don't have a real business reason for the aggressive refresh interval and we will go and switch them to 5mins or larger.

@philipp-durrer-jarowa you might need to change it to at least 15min… as this is the value that you’re seeing it’s taking for secrets to be synced.

**Comment by thesuperzapper** [comment]
> > even if you update the ExternalSecret or fix the error which is causing it to not sync, it could take up to 15 minutes to try again (which is the max error backoff).
> 
> is this a new behavior with 0.11.0? I am sure for older versions any new updates causes a force reconcile immediately.

No, this is always the case, note that it is an __exponential__ back off so it does take a while to get to 15 minutes.

**Comment by thesuperzapper** [comment]
Also, only syncing once every 15 minutes is probably way too long for most business cases, If a secret is rotated, being out of date for 15 minutes is probably going to cause an outage.

And I'm talking about when people set the refresh interval explicitly here, because we can still fix the retry exponential back off thing and make it max out at 5 minutes.

**Comment by gusfcarvalho** [comment]
> > > even if you update the ExternalSecret or fix the error which is causing it to not sync, it could take up to 15 minutes to try again (which is the max error backoff).
> > 
> > 
> > is this a new behavior with 0.11.0? I am sure for older versions any new updates causes a force reconcile immediately.
> 
> @gusfcarvalho No, this is always the case, note that it is an **exponential** back off so it does take a while to get to 15 minutes.

On that, I just did a local test and if we do update the manifest, we are re-triggering a new reconcile loop for the failed manifest s immediately (even with refreshInterval: 0), so this becomes less of a problem 😄

**Comment by gusfcarvalho** [comment]
> Also, only syncing once every 15 minutes is probably way too long for most business cases, If a secret is rotated, being out of date for 15 minutes is probably going to cause an outage.
> 
> And I'm talking about when people set the refresh interval explicitly here, because we can still fix the retry exponential back off thing and make it max out at 5 minutes.

A retry every 5 minutes just might cause rate limiting to kick in more strongly on providers... typically ExternalSecrets on normal conditions should have higher refreshIntervals, so this might not be a good max.

but I agree we should increase the min to `1min`

**Comment by thesuperzapper** [comment]
> On that, I just did a local test and if we do update the manifest, we are re-triggering a new reconcile loop for the failed manifest s immediately (even with refreshInterval: 0), so this becomes less of a problem 😄

@gusfcarvalho was the ES in a true "error loop" as in the controller logs were showing "Reconciler Error", or was it just in a "sync failed".

**Comment by thesuperzapper** [comment]
> A retry every 5 minutes just might cause rate limiting to kick in more strongly on providers... typically ExternalSecrets on normal conditions should have higher refreshIntervals, so this might not be a good max.
> 
> but I agree we should increase the min to `1min`

I was actually saying 1 second not 1 min because we do want to quickly retry for some errors (e.g. API conflicts), so anything longer is probably way to long (default is 5ms).

**Comment by gusfcarvalho** [comment]
> > On that, I just did a local test and if we do update the manifest, we are re-triggering a new reconcile loop for the failed manifest s immediately (even with refreshInterval: 0), so this becomes less of a problem 😄
> 
> @gusfcarvalho was the ES in a true "error loop" as in the controller logs were showing "Reconciler Error", or was it just in a "sync failed".

Yup - Reconciler error logs appearing. It does gets added to the stack appropriately without waiting for a new reocncile loop (which is why I was expecting)

**Comment by gusfcarvalho** [comment]
> > A retry every 5 minutes just might cause rate limiting to kick in more strongly on providers... typically ExternalSecrets on normal conditions should have higher refreshIntervals, so this might not be a good max.
> > but I agree we should increase the min to `1min`
> 
> @gusfcarvalho I was actually saying 1 second not 1 min because we do want to quickly retry for some errors (e.g. API conflicts), so anything longer is probably way to long (default is 5ms).

yeah, also good.

**Comment by gusfcarvalho** [comment]
@philipp-durrer-jarowa can this be closed? 😄

**Comment by philipp-durrer-jarowa** [comment]
Sure, merry christmas incase you celebrate it.
