### ISSUE TITLE
Remove kubebuilder kustomize manifests

### ISSUE THREAD

**Issue by mcavoyk** [external-secrets/external-secrets#42]
With a helm chart available, the kustomize manifest is just unnecessary config in the repo. 

My suggestion would to follow similar route as [cert-manager](https://github.com/jetstack/cert-manager/tree/master/deploy/manifests)'s deployment manifests if we want to publish manifest artifacts with Github releases. This uses a default helm values file and `helm template` to generate the yaml to `kubectl apply`.

**Comment by jonatasbaldin** [comment]
+1 for this.
