### ISSUE TITLE
Add randomized offset to mitigate reconciliation spikes

### ISSUE THREAD

**Issue by AleksejsCudovs** [external-secrets/external-secrets#4231]
**Is your feature request related to a problem? Please describe.**

When all ExternalSecret resources in a Kubernetes cluster are created at approximately the same time, or if the External Secrets Operator was down for a while and reconciles all tasks at once, the Reconciler processes all tasks simultaneously. This results in request spikes and AWS API throttling in large clusters.

**Describe the solution you'd like**

Introduce a randomized offset to the RequeueAfter duration in the reconciliation logic. This randomization would distribute the reconciliation tasks over time, mitigating the simultaneous execution issue.

**Describe alternatives you've considered**

Manually recreating all `ExternalSecret` resources gradually distributed over time.

**Additional context**

This problem was observed when multiple ExternalSecret resources were created simultaneously in a cluster. The graphs attached illustrate the issue, showing how reconciliation events align and cause spikes. A randomized offset would help spread these tasks over time.

![Screenshot from 2024-12-19 16-01-59](https://github.com/user-attachments/assets/49748d99-a8a2-4440-83f2-9d5acceb0861)
![Screenshot from 2024-12-19 16-02-08](https://github.com/user-attachments/assets/e0a9fb99-1d45-4c7e-af6f-dc4afa40b92a)

**Proposed solution**

The patch is pretty straightforward.

```
diff --git a/cmd/root.go b/cmd/root.go
index 3b6c99d2..72843836 100644
--- a/cmd/root.go
+++ b/cmd/root.go
@@ -80,6 +80,7 @@ var (
        enableFloodGate                       bool
        enableExtendedMetricLabels            bool
        storeRequeueInterval                  time.Duration
+       requeueRandomizedOffset               time.Duration
        serviceName, serviceNamespace         string
        secretName, secretNamespace           string
        crdNames                              []string
@@ -224,6 +225,7 @@ var rootCmd = &cobra.Command{
                        RestConfig:                mgr.GetConfig(),
                        ControllerClass:           controllerClass,
                        RequeueInterval:           time.Hour,
+                       RequeueRandomizedOffset:   requeueRandomizedOffset,
                        ClusterSecretStoreEnabled: enableClusterStoreReconciler,
                        EnableFloodGate:           enableFloodGate,
                }).SetupWithManager(mgr, controller.Options{
@@ -302,6 +304,7 @@ func init() {
        rootCmd.Flags().BoolVar(&enableConfigMapsCache, "enable-configmaps-caching", false, "Enable configmaps caching for ALL configmaps in the cluster (WARNING: can increase memory usage).")
        rootCmd.Flags().BoolVar(&enableManagedSecretsCache, "enable-managed-secrets-caching", true, "Enable secrets caching for secrets managed by an ExternalSecret")
        rootCmd.Flags().DurationVar(&storeRequeueInterval, "store-requeue-interval", time.Minute*5, "Default Time duration between reconciling (Cluster)SecretStores")
+       rootCmd.Flags().DurationVar(&requeueRandomizedOffset, "requeue-randomized-offset", 0, "Randomized offset to add to the requeue interval.")
        rootCmd.Flags().BoolVar(&enableFloodGate, "enable-flood-gate", true, "Enable flood gate. External secret will be reconciled only if the ClusterStore or Store have an healthy or unknown state.")
        rootCmd.Flags().BoolVar(&enableExtendedMetricLabels, "enable-extended-metric-labels", false, "Enable recommended kubernetes annotations as labels in metrics.")
        fs := feature.Features()
```

``` 
diff --git a/pkg/controllers/externalsecret/externalsecret_controller.go b/pkg/controllers/externalsecret/externalsecret_controller.go
index d18e1a4b..171c415c 100644
--- a/pkg/controllers/externalsecret/externalsecret_controller.go
+++ b/pkg/controllers/externalsecret/externalsecret_controller.go
@@ -20,6 +20,7 @@ import (
        "errors"
        "fmt"
        "maps"
+       "math/rand"
        "slices"
        "strings"
        "time"
@@ -135,6 +136,7 @@ type Reconciler struct {
        RestConfig                *rest.Config
        ControllerClass           string
        RequeueInterval           time.Duration
+       RequeueRandomizedOffset   time.Duration
        ClusterSecretStoreEnabled bool
        EnableFloodGate           bool
        recorder                  record.EventRecorder
@@ -563,7 +565,11 @@ func (r *Reconciler) getRequeueResult(externalSecret *esv1beta1.ExternalSecret)
 
        // if there is time remaining, requeue after the remaining time
        if timeSinceLastRefresh < refreshInterval {
-               return ctrl.Result{RequeueAfter: refreshInterval - timeSinceLastRefresh}
+               requeueAfter := refreshInterval - timeSinceLastRefresh
+               if r.RequeueRandomizedOffset > 0 {
+                       requeueAfter += time.Duration(rand.Int63n(int64(r.RequeueRandomizedOffset)))
+               }
+               return ctrl.Result{RequeueAfter: requeueAfter}
        }
 
        // otherwise, requeue immediately

```

**Comment by AleksejsCudovs** [comment]
Please let me know your opinion on whether this solution is appropriate. I can make additional changes and/or create a merge request.

**Comment by Skarlso** [comment]
Hello.

Thanks for the suggestion. Introducing a jitter could certainly solve some of the headaches, however, it could introduce a lot of others. For example, since the jitter doesn't disappear after this event it will introduce problems during further processing when expected reconciliation should happen.

Sadly, the actual solution is a bit more involved. It would entail some kind of provider aware rate limiting, with monitoring of response times from the provider, progressive back-offs with priority queue implementation and some way of tracking this. I could also imagine updating the ES object and add information such as:

```yaml
    rateLimit:
      requestsPerSecond: 100
      burstLimit: 150
    backoff:
      initialDelay: 5s
      maxDelay: 300s
      factor: 2
    prioritization:
      enabled: true
      criticalNamespaces:
        - kube-system
        - security
```

The unpredictable reconcile time could cause problems.

That said, this might be a good first thing to do I guess. What if we would only do this during startup and then reconcile normally afterwards? I guess that wouldn't alleviate the problem when many ESs reconcile at the same time.

The other problem with the randomize is that it could potentially miss reconcile windows for an ES or reconcile them too close to each other. 

Hmmm... Second / Third opinions @thesuperzapper @moolen @gusfcarvalho ?

**Comment by thesuperzapper** [comment]
The only real solution is to build our own rate limiting for normal reconciles (e.g. some kind of rate limited which wraps the reconcile function, separate to the exponential backoff and global rate limits).

For reference, this is what crossplane does.

However, I am not sure we know enough about what the specific "event" means (which only includes a name/namespace for a specific ES) to do any per-provider rate limits.

**Comment by thesuperzapper** [comment]
Also, a lot of the problems people have are because of the current exponential backoff on failure being way too quick at the beginning (it tries like 10 times in the first few seconds).

I imagine that once we fix that, it would take a seriously large amount of external secrets to cause problems.

**Comment by gusfcarvalho** [comment]
In this case I think the problem is due to normal operations.

Also, AWS rate limits are 10k calls per second… which is not at all aligned with what’s shown in the picture.

I think this is unrelated to ExternalSecrets and something else is triggering the rate limit 🙂

**Comment by gusfcarvalho** [comment]
Also worth to point out ☝️  provider rate limits are global and not really bound to only external-secrets. If crossplane, other external-secrets instances, crazy lambda functions, a very unhappy user hammering the API with a CLI bash script on loop - all of these will trigger rate limits and there is nothing we can do about it.

IMO, provider rate limits is something we should not take account for at all 😄

**Comment by gusfcarvalho** [comment]
Finally, @AleksejsCudovs what I suggest you to do is to review ExternalSecret manifests... chances are there are optimizations that can be done at manifest level (using `dataFrom.find` as opposed to `data`) that will strongly help with the number of calls a given external-secrets operator does. 

I even recently wrote a blog post about it: https://externalsecrets.com/blog/aws-paramater-store-rate-limit/ 😄

**Comment by Skarlso** [comment]
Thank you for chiming in Peeps. :)

**Comment by AleksejsCudovs** [comment]
Thank you all for the detailed response! Let me provide a bit more context.  

The graphs I shared are from a test cluster, just to demonstrate that simply introducing an offset helps address the issue. Currently, we manage multiple clusters with approximately 5,000 secrets in total, and this number is constantly growing. Using `dataFrom.find` is indeed a great optimization that can significantly reduce the number of requests. However, as the number of secrets continues to grow, it’s only a matter of time before we hit the same limits again.  

I agree with you that we shouldn’t rely on provider rate limiting, as it can be triggered by various factors outside our control. Instead, let’s focus on the behavior of the External Secrets Operator.  

Currently, upon startup, the operator attempts to reconcile all secrets simultaneously and updates the `refreshTime` for all `ExternalSecret` resources to nearly the same value. This synchronization then triggers reconciliations for all resources at the same time, causing unnecessary CPU, network traffic, and request spikes.  

My suggestion is to distribute the reconciliation events more evenly across the `refreshInterval`. This would help balance the load over time and avoid the spikes caused by synchronized reconciliations.  

Please let me know your thoughts.

**Comment by gusfcarvalho** [comment]
> Thank you all for the detailed response! Let me provide a bit more context.
> 
> The graphs I shared are from a test cluster, just to demonstrate that simply introducing an offset helps address the issue. Currently, we manage multiple clusters with approximately 5,000 secrets in total, and this number is constantly growing. Using `dataFrom.find` is indeed a great optimization that can significantly reduce the number of requests. However, as the number of secrets continues to grow, it’s only a matter of time before we hit the same limits again.
> 
> I agree with you that we shouldn’t rely on provider rate limiting, as it can be triggered by various factors outside our control. Instead, let’s focus on the behavior of the External Secrets Operator.
> 
> Currently, upon startup, the operator attempts to reconcile all secrets simultaneously and updates the `refreshTime` for all `ExternalSecret` resources to nearly the same value. This synchronization then triggers reconciliations for all resources at the same time, causing unnecessary CPU, network traffic, and request spikes.
> 
> The default behavior is fine for most use cases. However, for environments with a large number of `ExternalSecret` resources, this can lead to significant reconciliation spikes, which can easily be avoided by distributing reconciliation events more evenly across the `refreshInterval`.
> 
> Please let me know your thoughts.

The behavior you're seeing is probably driven from the fact that you have many `concurrent` set up - this means reconciles are in parallel. There isn't any operation we can do at startup time that would prevent all of the concurrent flags to trigger virtually at the same time. 

By the number of Secrets you have, you'll end up rate limiting anyways unless you specify a random timer of a couple of minutes - which then you should probably just spec out your manifests better

All of these are workarounds to me for a problem we do not own (the API being rate limited for whatever the reason).

**Comment by gusfcarvalho** [comment]
Out of curiosity, did you try reducing the number of `concurrent` you have set up? I believe this will be enough to even this distribution out anyways.

**Comment by gusfcarvalho** [comment]
Also worth to point out - if ExternalSecrets objects are created evenly distributed - even on a fresh startup of ESO reconciler, this issue should not happen as `status.RefreshTime` is already set. The real issue happens when all of the objects are reconciled for the first time at the same time. -> so maybe we can add a jitter to this operation only.

**Comment by AleksejsCudovs** [comment]
ESO resets the RefreshTime to the same value if it has been down for more than the refreshInterval.

**Comment by gusfcarvalho** [comment]
> ESO resets the RefreshTime to the same value if it has been down for more than the refreshInterval.

right, because we mark as Done from the start of the reconcile time.

IMO 👆 that could be better done within `//otherwise requeue immediately` - adding a random duration from `refreshInterval` should be enough (and within spec). WDYT?

**Comment by AleksejsCudovs** [comment]
A bit more numbers. Currently, we have the following settings: `refreshInterval: 5m` and `--concurrent=8`. We are not yet using `dataFrom.find`and total number of keys exceeds 20,000. While it's acceptable for secrets to not update immediately given these numbers, the current behavior still causes unnecessary spikes during reconciliations.  

Adding jitter at startup and/or in the `//otherwise requeue immediately` case appears to be a promising solution to distribute reconciliations more evenly. I will experiment with different values and share the results.

**Comment by gusfcarvalho** [comment]
Now that I'm reading - I like the requeuing gracefully option the best 😄 as in theory we are already out of refreshInterval contract anyways.

**Comment by gusfcarvalho** [comment]
> I'm considering different corner cases that can cause `RefreshTime` synchronization:
> 
> 1. Many `ExternalSecret` resources are created simultaneously.
> 2. The ESO has been down for longer than the `refreshInterval` leading to `RefreshTime` in the past.
> 3. A short network issue causes delays in `getProviderSecretData`, and `RefreshTime` ends up clustering together when the network resolves.
> 
> Do you know of any additional scenarios?
> 
> Rather than addressing each case separately, perhaps it's worth introducing a `RequeueAfter` randomizer option? For example, instead of setting `refreshInterval: 1m`, configure it as `rand(refreshInterval: 2m)`.
> 
> What do you think?

I like the randomizer idea as long as this is not like more parameters for us to maintain! and that's where it gets tricky.

for 1 and 3: can you reproduce rate spike errors when just creating ExternalSecrets (case 1) in your test cluster? Because for me it will really only be a problem if anyone has `concurrent` as big as the number of objects created. In your case, only 8 objects would really reconcile at the same time, the next batch would already naturally be in the future as it is when the next reconcile happens. 

That's why I think only 2 really needs addressing (but maybe I'm wrong). At least case 1 can be easily tested to see if that's actually the case!

**Comment by AleksejsCudovs** [comment]
Thank you all for the great conversation. Simply decreasing the `--concurrent` value, as suggested, also works. However, the main drawback of this approach is the need to fine-tune the value based on the cluster size and continuously monitor it as the number of secrets grows. That's why I still believe that spreading the reconciliations evenly across the `refreshInterval` is an easy and universal solution to mitigate all kinds of corner cases. With that said, I think we can consider this issue resolved and close it.
