### ISSUE TITLE
Any plans for CNCF incubating/graduation phase?

### ISSUE THREAD

**Issue by esantoro** [external-secrets/external-secrets#4232]
Hello!

I would like to start using this project. It fits my use case very well, and the project looks alive.

One perplexity: any plans regarding reaching the incubating state in the CNCF landscape?

Thanks for the great work so far!

**Comment by Skarlso** [comment]
Hello! Thanks for the interest. :) You can track the incubation phase here: https://github.com/cncf/toc/issues/1486

Cheers.

**Comment by esantoro** [comment]
Thank you very well, the tracker for the incubation phase is exactly what i needed.

Keep up the good work and best of luck on the application for incubation phase!
