### ISSUE TITLE
Start with tweaks approach for test cases structs before we have more tests

### ISSUE THREAD

**Issue by knelasevero** [external-secrets/external-secrets#44]
**Describe the solution you'd like**
We could have a base test case struct with most of the default happy path fields set at the top, and use tweak anonymous functions to customize the test case for each specific desired scenario.

**What is the added value?**
Sometimes we have to include a lot of fields set, for validation or because it is a required field, and when reading tests you have to really look closer to find what is changing between each case. With tweaks changing exactly what is needed for each scenario it is easier to quickly see what the test is about, and what is relevant to the test.

**Give us examples of the outcome**

My wife was grabbing some clean up tasks from k/k and she is doing exactly that for some tests. Saw Moritz starting documentation early in the project and imagined this being another thing worth doing before we have big test suites.

Here is the reference issue on the k/k: https://github.com/kubernetes/kubernetes/issues/99005

Her PR with tweaks and stuff: https://github.com/kubernetes/kubernetes/pull/99165

## Obs:

I think this is a umbrela issue and we can let people grab specific tests, or specific test files:

- [ ] TestGetSecret in pkg/provider/aws/secretsmanager/secretsmanager_test.go (@gabibeyer)
- [ ] TestGetSecretMap in pkg/provider/aws/secretsmanager/secretsmanager_test.go

People that want to do this can comment in this issue, and start working on it. I will add other ones to this list that have multiple case scenarios (anyone can just suggest any as well, and I update the issue here).

**Comment by knelasevero** [comment]
@moolen @mcavoyk what do you think?

**Comment by mcavoyk** [comment]
Yes, I recommend this approach along with table driven tests 👍

**Comment by gabibeyer** [comment]
I would be happy to start on the first bullet: `TestGetSecret in pkg/provider/aws/secretsmanager/secretsmanager_test.go` if it's not already taken! :hand:

**Comment by knelasevero** [comment]
Thanks @gabibeyer its yours! :smile:
