### ISSUE TITLE
Feature: Integration with Fleet/Rancher for multicluster secrets

### ISSUE THREAD

**Issue by ADustyOldMuffin** [external-secrets/external-secrets#443]
**Describe the solution you'd like**
We manage multiple clusters using Rancher, and we also use External Secrets for our secrets. We have a need to be able to push secrets to multiple clusters from a single location, and would like to explore if External Secrets would be interested in adding an integration to facilitate this.

**What is the added value?**
Eases the difficulty of having to add secret stores/secrets for every single cluster, and instead would allow us to distribute a secret across multiple clusters (for example a secret that allows us to connect to a specific secret store provider). 

**Give us examples of the outcome**

I'm not sure what the CRD would look like, but something like a `DistributedExternalSecret` which might create another CRD called a `Bundle` which [Fleet](https://fleet.rancher.io/) would then distribute.

They currently have an open [issue](https://github.com/rancher/fleet/issues/202) about distributing secrets across multiple clusters, so there is a need for it. 

I'm interested in other's thoughts or ideas on how this might be done in other ways as well.

**Comment by moolen** [comment]
I think the `SecretSink` proposal should cover this, implementation is tracked in #976.

**Comment by ADustyOldMuffin** [comment]
I actually think this is resolved with the Kubrerntes provider where we can set it up to point to our rancher server instance which contains all the ExternalSecrets.
