### ISSUE TITLE
Consider using Paul, Derek or Prow

### ISSUE THREAD

**Issue by knelasevero** [external-secrets/external-secrets#45]
**Describe the solution you'd like**
I think we could have some kind of automation bot.

**What is the added value?**
Help with some managerial tasks. Specially useful if we want some approvers and maintainers not necessarily added to the org.

**Give us examples of the outcome**

Wanna vouch for Paul here. We use it in some internal projects, and it was developed by a fellow CSer. My favorite feature being the ability to label a PR with 'merge', when you kinda know that the CI will pass with the last commit that you sent, and you don't want to sit in front of the laptop waiting for it to click merge. Paul will merge PRs labelled with 'merge' in the next hour if CI passed. It is also very simple to configure (and contribute to, if we need something specific). I think Prow is too complicated for such a small project like ESO. Derek is also an option.

Paul: https://github.com/apps/paul-the-alien
Derek: https://github.com/alexellis/derek
Prow: https://github.com/kubernetes/test-infra/tree/master/prow

**Comment by mcavoyk** [comment]
Definitely agree with some automated tooling to help with some tasks. I'll take a look at these options this weekend.

**Comment by knelasevero** [comment]
Just testing :)
