### ISSUE TITLE
E2E test for AWS-SSM - Different Regions

### ISSUE THREAD

**Issue by gusfcarvalho** [external-secrets/external-secrets#456]
Add e2e tests for AWS-SSM that focus on pulling secrets from different regions.

Issue split from #209

**Comment by imranalley** [comment]
I can pick this up! :)

**Comment by imranalley** [comment]
Just had a chat with gustavo and learned that this was a duplicate and already resolved :D will look for something else to contribute to

**Comment by moolen** [comment]
Alright, good to know, gonna close this then :+1:
