### ISSUE TITLE
Ability to set log level

### ISSUE THREAD

**Issue by reakaleek** [external-secrets/external-secrets#462]
**Describe the solution you'd like**
The ability to set the log level in the values file for the helm chart.

**What is the added value?**
Info logs are quite chatty and in my case, log level error would be enough.

**Comment by reakaleek** [comment]
> You can already pass loglevel as an extraarg

Hi, thank you for pointing this out. Do you have a documentation reference on which arg I need to set?

**Comment by joaopaulosr95** [comment]
@reakaleek you should take a look here
https://github.com/external-secrets/external-secrets/blob/main/main.go#L55

and here
https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/values.yaml#L41

Just set `logLevel: "error"` and you should be fine

**Comment by reakaleek** [comment]
> @reakaleek you should take a look here
> https://github.com/external-secrets/external-secrets/blob/main/main.go#L55
> 
> and here
> https://github.com/external-secrets/external-secrets/blob/main/deploy/charts/external-secrets/values.yaml#L41
> 
> Just set `logLevel: "error"` and you should be fine
> 

Thank you very much!
