### ISSUE TITLE
Tests fail when race detector enabled

### ISSUE THREAD

**Issue by snarlysodboxer** [external-secrets/external-secrets#473]
### Environment

OS: Mac OS

Go Version: `go1.17.2 darwin/amd64`

## What happened?
`make test` causes one failed test.
The output is huge, but this seems to be the main part: (let me know if you want me to post the rest)
```
FAIL    github.com/external-secrets/external-secrets/pkg/controllers/externalsecret     7.641s
=== RUN   TestAPIs
Running Suite: Controller Suite
===============================
Random Seed: 1636054446
Will run 0 of 0 specs

objc[94513]: Attempt to use unknown class 0x7ff842827360.
SIGABRT: abort
PC=0x7ff800ff3dfe m=11 sigcode=0
```
However if I run `go test -v $(go list ./... | grep -v e2e)` (without the `-race` flag) then all the tests pass.

## What did you expect to happen?
All the tests to pass with the `-race` flag included, as seen in the `Makefile`.

## Steps to reproduce
1. Checkout the main branch and run `make test`.

## Notes & Logs
Maybe my environment has something to do with it?
I discovered the tests fail if you have something running on port 8080.

**Comment by moolen** [comment]
I think this got fixed.
tests now run with `-race` enabled and `MetricsBindAddress` is disabled in controller `suite_test.go`. Feel free to reopen if i missed something.

**Comment by snarlysodboxer** [comment]
I am still experiencing this issue. - The bind address part seems solved, but race detection still causes theses errors:

```
=== RUN   TestAPIs
Running Suite: Controller Suite - ~/go/src/github.com/external-secrets/external-secrets/pkg/controllers/clusterexternalsecret
=============================================================================================================================================
Random Seed: 1649982092

Will run 4 of 4 specs
objc[93100]: Attempt to use unknown class 0x7ff85b9da778.
SIGABRT: abort
PC=0x7ff81a1e1dba m=12 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x7ff81a1e1dba
stack: frame={sp:0x7000022dfe28, fp:0x0} stack=[0x700002261338,0x7000022e0f38)
...
```
and
```
=== RUN   TestValidate
objc[93162]: Attempt to use unknown class 0x7ff85b9da778.
SIGABRT: abort
PC=0x7ff81a1e1dba m=0 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x7ff81a1e1dba
stack: frame={sp:0x7ff7bfefe2a8, fp:0x0} stack=[0x7ff7bfe80378,0x7ff7bfeff3e0)
0x00007ff7bfefe1a8:  0x0000000000000002  0x0000000000000002
...
```

I am followed [the guide](https://github.com/external-secrets/external-secrets/blob/main/docs/contributing-devguide.md) on getting started and building and running the tests.

Again, `main` branch, ran `git pull origin upstream` in my fork last night. Tests still succeed when disabling the race detector.

**Comment by gusfcarvalho** [comment]
@snarlysodboxer are you by any chance using a mac? If so, can you please try to set `export MallocNanoZone=0` and rerun the test?

**Comment by snarlysodboxer** [comment]
@gusfcarvalho Yes, using a Mac, mentioned that in the original post, sorry if it wasn't clear!

Just ran `make test` after `export MallocNanoZone=0` and it worked! No stack dumps or errors this time. How do we fix for others?

**Comment by gusfcarvalho** [comment]
I believe for linux-bases systems it already works OOTB. Not sure about windows, though.

The issue with mac is actually related to an issue with `go -race` in mac generally speaking.  See for reference: https://github.com/golang/go/issues/49138#issuecomment-951321823
