### ISSUE TITLE
Add Keeper as a supported Backend

### ISSUE THREAD

**Issue by ghost** [external-secrets/external-secrets#476]
**Describe the solution you'd like**
Keeper is a pretty popular secret manager that might be a good candidate to add as a supported backend.

**What is the added value?**
Any organization who uses Keeper would be able to retain it as the single source of truth for secrets and not need to use another backend.

**Give us examples of the outcome**

Provide templates if you are proposing changes in the CRD. Provide example workflows or code snippets if they make sense to present.

**Observations (Constraints, Context, etc):**

Keeper has some documentation on interacting with a vault via Go already [here](https://github.com/keeper-security/secrets-manager-go). I'm mostly submitting this issue as a way to gauge community support for Keeper as a backend. If I made it and submitted a pull request, would anyone use it? What kind of features are you all interested in?

**Comment by alexis-wefight** [comment]
I'm interested with the Keeper backend integration to retrieve secrets. Keeper has a very intuitive UI to manage secrets in a full SaaS offering.

**Comment by pedroparraortega** [comment]
we are insterested on this provider. I will try to start working on it

**Comment by moolen** [comment]
This has been implemented, see :point_up_2:
