### ISSUE TITLE
Retention/deletion/prune policy

### ISSUE THREAD

**Issue by artem-nefedov** [external-secrets/external-secrets#497]
**Describe the solution you'd like**

Would be great to have the ability to control what happens to Secret object when ExternalSecret is deleted (either with new value for "creationPolicy", or a new field such as "deletionPolicy", "retentionPolicy", "prune", etc.).

**What is the added value?**

Currently it's only possible to retain Secret when using `creationPolicy: Merge`, which implies you need to create the Secret separately first. In my case, I need ExternalSecret to be able to create and update Secret, but still preserve Secret when the parent object is deleted.

**Comment by moolen** [comment]
Will be implemented in scope of #695

**Comment by artem-nefedov** [comment]
@moolen I've read through #695, and I'm not sure that it covers request in this ticket. It says that `deletionPolicy=None` will delete Secret **if the provider returns no data**, and that is already the current behavior. But my request was about the ability to preserve Secret regardless of whether provider returns the data or not.

**Comment by gusfcarvalho** [comment]
Hi @artem-nefedov ! Sorry to jump in, but I wanted to understand better your use case. Right now, if a given ES generates a given Secret with creationPolicy:Owner, if ES cannot find the source anymore it is going to be in a secretSyncedError , but will not delete the Secret itself. Are you experiencing something different than this behavior? Are you intending to preserve deleted `keys` from a given source?

**Comment by artem-nefedov** [comment]
Hi @gusfcarvalho . My feature request is not related to "source" being changed/deleted. I just need the ability to always keep `Secret` object whenever `ExternalSecret` object is deleted (while still allowing `Secret` to be created and/or updated). Maybe it was not clear from the description.

**Comment by moolen** [comment]
I see! So basically there should be no garbage collection via `ownerReference`. My bad, that was a misunderstanding!
