### ISSUE TITLE
Fetch all secrets from a given external store and map them to a Kind=Secret [azure]

### ISSUE THREAD

**Issue by knelasevero** [external-secrets/external-secrets#498]
Right now we have a getSecretMap that expects a single secret in the external provider to be a JSON string and then we grab the keys and make them multiple keys in a Kind=Secret in kubernetes.

Now we want a feature that allows for us to get all the secrets in an external provider and make them sink as keys in a Kind=Secret in Kubernetes.

This would have to change the interface signature to include a new method, we could call it getAllSecrets(). Right now we can start with only implementing this for azure, but we would have to implement this for all providers.

A proposal of how this could look like (spec/crd) is already in this discussion: https://github.com/external-secrets/external-secrets/discussions/470

**Comment by ahmedmus219** [comment]
Hi 
I started with this [commit ](https://github.com/ahmedmus-1A/external-secrets/commit/257f6e8ea52c29f8f3f57e84d6ec91dce7cd3ca7), unfortunately I needed to add the new method into the provider interface , and accordingly all the providers needed to be touched.

**Comment by knelasevero** [comment]
@moolen this is very different from what you proposed, what do you think?

**Comment by moolen** [comment]
implemented in https://github.com/external-secrets/external-secrets/pull/805
