### ISSUE TITLE
Implement a basic CI pipeline

### ISSUE THREAD

**Issue by jonatasbaldin** [external-secrets/external-secrets#5]
## Expected Behavior
We should have a pipeline to test the code and deploy the Docker image, respectively:
- Run `make test` on every pull request/commit
- Run `make docker-build` and `make docker-push` when tagging (using semantic versioning)
- Implement code coverage (codecov.io)

Still need to decide:
- Platform? I'd use GitHub actions, simple and already here
- For the Docker image, maybe [GitHub Container Registry](https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry) (since DockerHub now has the pull limits)

## Actual Behavior
There's no pipeline :(

**Comment by moolen** [comment]
@knelasevero is the implementation of a linter in scope of this feature? If not i'd like to add [golangci-lint](https://golangci-lint.run/) and maybe a license header check.

**Comment by knelasevero** [comment]
Hey @moolen :) , I think both are somewhat related, but you can raise a different issue and work on it if you want, so I don't block you. I've been a bit busy with some other stuff and will probably have time for it this week.

**Comment by Flydiverny** [comment]
I've enabled github container registry and pushed KES there https://github.com/orgs/external-secrets/packages/container/package/kubernetes-external-secrets

I've also put down an open source request on docker hub to get around the pull limits. But looks like using github should be fine!
