### ISSUE TITLE
Oracle Cloud secrets return the name of the secret rather than the body

### ISSUE THREAD

**Issue by HexF** [external-secrets/external-secrets#504]
Hey,

This follows on from my troubles in #501, but now I have it grabbing secrets and loading them in - without crashing.

My setup is largely the same as in #501 on the Kubernetes configuration side.
On the oracle cloud side, I have a vault containing a single secret named `production`, which contains a JSON object full of secret keys.

Now, when I dont provide a `property` on the remoteRef I get just the name of the secret `production` as the value in the secret, but if I provide a key I get nothing, I assume that is because its trying to parse the name as JSON, which obviously isn't JSON data.

This portion of the oracle provider seems relevant:
https://github.com/external-secrets/external-secrets/blob/35569c759b61b7e40b0439f01c6762577d77ec61/pkg/provider/oracle/oracle.go#L143-L145

I get the feeling the oracle provider hasnt been tested in a production environment.
I would fix these issues myself, However I'm not too familar with Go.
Help is much appreciated.

cc: @KianTigger

**Comment by knelasevero** [comment]
You are right! Also, unit tests are wrongly looking at SecretName as if it was value... 

We really missed this while reviewing... 

Quickly looking at the code `Secret The details of the secret. Secret details do not contain the contents of the secret itself.` I don't know how to easily actually get the secret value with this client. WHoever gets this issue would need to figure that out :sweat_smile:

**Comment by alexdyas** [comment]
Confirmed, I get the same result as @HexF. I'm keen to have a working version of this, ping me if I can help with testing etc.

**Comment by moolen** [comment]
I was a little confused when looking at the OCI Vault API. It seems like we need to use the `secrets` package to actually retrieve the secrets. related: https://github.com/oracle/oci-go-sdk/issues/324

**Comment by moolen** [comment]
I can not test the integration as i don't have an oci account. If someone has some time to finish my draft below or can share credentials please let met know. The fix should be pretty straight forward: https://gist.github.com/moolen/4014679b94310c5c8955a6dde5a73945

**Comment by knelasevero** [comment]
I have some people in CS wanting to contribute and I wanted to use this one in our next mob session to walk them into making the contrib :) we can create another trial account on our side

**Comment by moolen** [comment]
Awesome! Sure, then go ahead and fix it in the mob programming session :heart:

**Comment by alexdyas** [comment]
I'm willing to give it a quick test, although I'm struggling with applying the patch. I've tried various git commands, `git apply oracle.patch`, `git am oracle.patch`, but I'm getting errors. What is the correct command line please?

**Comment by moolen** [comment]
That's just a sketch, it probably won't work: it's untested :sweat_smile:

**Comment by alexdyas** [comment]
I don't want to trample on your mob session however, this is just for my curiosity.
