### ISSUE TITLE
Separate the SecretStore Provider into two interfaces

### ISSUE THREAD

**Issue by mcavoyk** [external-secrets/external-secrets#53]
Currently the Provider interface has functionality for `New(...)`, and `GetSecret(...)`. This ends up being a bit confused as the controller gets a Provider from the internal schema, but then calls New() on the Provider to get.. another Provider

Provider's `New(...)` then has to be careful not to mutate itself, but to return a New instantiation of its own type, if a Provider failed to do so, the mutation may have undefined side-effects on future ExternalSecrets using the same provider during the runtime of the controller.

## Proposal
```golang
type Provider interface {
 	// New returns a SecretsClient for the given store definition
	New(...) (SecretsClient, error)
}

type SecretsClient interface {
	// GetSecret returns a single secret from the provider
	GetSecret(...) ([]byte, error)

	// GetSecretMap returns multiple k/v pairs from the provider
	GetSecretMap(...) (map[string][]byte, error)
}
```

Besides the increased clarity for the controller using this interface, this also simplifies the use-case for the same cloud provider having multiple SecretsClient discussed in https://github.com/external-secrets/external-secrets/issues/27#issuecomment-785588054. AWS SecretsManager and AWS Parameter Store could share the same Provider interface, and based on the `Service` type field - return different SecretsClient.

**Comment by moolen** [comment]
This was implemented in #55 

/close
