### ISSUE TITLE
Question - data and datafrom

### ISSUE THREAD

**Issue by sergiofteixeira** [external-secrets/external-secrets#541]
hello, 

when using vault backend can we use data and datafrom for specific secrets?

**Comment by knelasevero** [comment]
Hey!

sorry, I could not follow. What do you mean? With Vault, if you use data, you have to use property together.

If you use datafrom, you will get all key/values in a given secret.

**Comment by knelasevero** [comment]
Hey! Closing this issue for now. Please feel free to re-open to seek us at https://kubernetes.slack.com/messages/external-secrets
