### ISSUE TITLE
Improve docs examples that generate problems often

### ISSUE THREAD

**Issue by knelasevero** [external-secrets/external-secrets#582]
Will list some:

- [x] 'controller: dev' k/v is needed in the API spec doc, but not in the getting started examples. Our general quick user will just install the helm chart as is, and that key makes the controller ignore the SS

- [x] we had some users reporting problems with our getting started guides (maybe the ones with Auth methods that we don't use that often). We need to go though all of them and check that they work properly

**Comment by gusfcarvalho** [comment]
regarding #498 should we for now update the appropriate docs as well while this one isn't complete?
