### ISSUE TITLE
OCI secret by name instead of the unmaintainable ID

### ISSUE THREAD

**Issue by EladGabay** [external-secrets/external-secrets#587]
Hello,
Currently (soon, once  https://github.com/external-secrets/external-secrets/pull/569 is done)  the OCI Vault provider gets a secret by its ID which is unpredictable and less maintainable than name.
The advantage of ID is that we don't need to know the Vault ID. 
However if we have a specific Vault ID, we can gets secrets by name.
There are 2 options to add this support:
1. Get the Vault ID in the SecretStore CRD, then we can just use the name in the ExternalSecret.
2. Get Vault ID and the secret name in the ExternalSecret.

Because I need this support ASAP I'm going to implement this. Which option do you prefer?

Thanks!

**Comment by EladGabay** [comment]
I'd suggest to add an optional field of the Vault ID to SecretStore, then if it exists, take the ExternalSecret key as a name, otherwise as an OCID like now.

**Comment by knelasevero** [comment]
I think I prefer the vault Id as required field in the SS, so the intended usage is clear. Basically option 1 from your suggestion. :)

**Comment by knelasevero** [comment]
I know that going for option 1 is a breaking change, but we should take advantage of the CRD being in alpha and get the specs to what we think makes more sense.
