### ISSUE TITLE
Helm Chart Enhancement - Ability to manage "automountServiceAccountToken"

### ISSUE THREAD

**Issue by jbehrends** [external-secrets/external-secrets#593]
My organization is trying to adhere to Checkov rule [CKV_K8S_38](https://docs.bridgecrew.io/docs/bc_k8s_35) to ensure that Service Account Tokens are only mounted where necessary.  There currently is not an option to manually configure the service account token by creating an optional helm value to set 'automountServiceAccountToken' to false, as well as the ability to mount the token if needed.

**Comment by moolen** [comment]
That policy generally makes sense but IMO doesn't apply to the controller because it requires a SA token to work. I don't see a case where manually mounting service accounts would be useful. 

Or do you have a attack scenario where that would help?

**Comment by jbehrends** [comment]
I don't have a specific scenario, no.  

Sorry it was an ask from our InfoSec team to open this case/issue and verify with the project maintainers that not being able to set "automountServiceAccountToken" was by design. 

This can probably be closed.
