### ISSUE TITLE
Implement the Providers interface

### ISSUE THREAD

**Issue by jonatasbaldin** [external-secrets/external-secrets#6]
## Expected Behavior
Have an interface to setup all the Providers (AWS SM, GCP SM, Vault etc).

We should have a common interface with the methods used by all Providers, something like:
```golang
type Client interface {
	New(...) (Client, error)
	GetSecret(...) ([]byte, error)
	GetSecretMap(...) (map[string][]byte, error)
}
```

We should also have some form of registration of the implemented backends during the controller startup.

## Actual Behavior
Not implemented yet.

**Comment by moolen** [comment]
This was implemented in #9.
