### ISSUE TITLE
docs: generate on release + multiversion support

### ISSUE THREAD

**Issue by moolen** [external-secrets/external-secrets#627]
We've had a couple of support issues where the documentation referred to a feature that wasn't released yet. I propose two minor improvements for our documentation pipeline:

#### 1. Generate Documentation on release
We should generate and deploy the documentation *only* when releasing a new version (i.e. from the release pipeline or perhaps manually from master).

#### 2. Versioned Documentation

mkdocs has support for deploying [multiple versions](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#versioning). We should also consider adding a warning when [viewing an old version](https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#version-warning).

**Comment by gusfcarvalho** [comment]
I am taking this one.
