### ISSUE TITLE
docs: HashiCorp Vault - Typo in figure

### ISSUE THREAD

**Issue by PeterSR** [external-secrets/external-secrets#635]
On the doc page https://external-secrets.io/provider-hashicorp-vault/ the very first figure, that shows how `external-secrets` works together with Vault, has misspelled "ExternalSecret" as "ExternaSecret" (missing the "l").

Direct link to figure: https://external-secrets.io/pictures/diagrams-provider-vault.png

**Comment by hydeenoble** [comment]
@gusfcarvalho I would like to pick this issue up if you don't mind

**Comment by moolen** [comment]
sure, go ahead :)

**Comment by hydeenoble** [comment]
Just confirm @moolen. Please is there a particular way these images are generated?

**Comment by moolen** [comment]
Oh, sure. That isn't documented anywhere :cold_sweat:. So basically we have this `diagrams.drawio` [here](https://github.com/external-secrets/external-secrets/blob/main/docs/pictures/diagrams.drawio) that can be opened with [diagrams.net](https://www.diagrams.net/). There are tabs with one graphic each. So there's probably a `provider-vault` tab that contains that graphic. 

Make changes to that graphic and export it by simply selecting all the objects on the canvas and hit export as png (with selected objects only on). 

Hope that helps.

**Comment by hydeenoble** [comment]
Thanks, @moolen that really helped, I have a PR open here #1080

**Comment by hydeenoble** [comment]
I know this issue is closed, However, Just a quick note @moolen, wouldn't it be nice to add this information you provided somewhere in the documentation so making changes to images in the future would be a problem. What do you think?
