### ISSUE TITLE
Vault: support AWS auth via IRSA

### ISSUE THREAD

**Issue by moolen** [external-secrets/external-secrets#643]
### Discussed in https://github.com/external-secrets/external-secrets/discussions/616

<div type='discussions-op-text'>

<sup>Originally posted by **michelesr** January 21, 2022</sup>
Is it possible to authenticate to Hashicorp Vault using IAM role for serviceaccounts? Vault supports IAM based authentication but the external-secrets operator doesn't mention it in the documentation.

If it's not supported, should I open a feature request issue?</div>

Use-case: Vault runs outside of AWS, external-secrets run inside an EKS cluster. It doesn't necessarily makes sense to use the Kubernetes auth provider (you would need to create 1 auth method per cluster in vault). We can simply exchange an IRSA token with AWS credentials and pass them to vault to an [aws-auth](https://www.vaultproject.io/docs/auth/aws) enabled endpoint.

We must ensure that we support multiple strategies when adding a `aws` auth provider. IRSA is one example, we could add more like static credentials read from a `Kind=Secret`, using transient credentials from the controller Pod etc.

**Comment by andreeee** [comment]
Bump!

**Comment by santiago8781** [comment]
x2
