### ISSUE TITLE
Metrics: add provider API calls metric

### ISSUE THREAD

**Issue by moolen** [external-secrets/external-secrets#648]
We want to know how many API calls are being made towards a specific secret provider API. 
For a first iteration i would propose to add a simple `counter` metric with
(1) `provider` label that defines which provider is being requested: `aws/secretsmanager`, `aws/parameterstore`, `gcp/secretsmanager`, `vault/kv`, `azure/keyvault`, etc..

(2) `result` label that defines if the call has been successful or not: `SUCCESS` or `ERROR`
```
provider_calls{provider="aws/secretsmanager", result="SUCCESS"} 42
```

To get deeper insights it may be valuable to have a label for the ExternalSecret namespace and/or name. This information however is not passed into the provider.

**Comment by spirosoik** [comment]
@moolen I can get this :)

**Comment by spirosoik** [comment]
guys I am back to implement this. So I will spend time during the weekend :)

**Comment by merlindorin** [comment]
@moolen @spirosoik not sure if this is a good idea (I'm changing my mind on this point recently due to the eventual data volume in large scale cluster)... but simply industrializing the HTTP client can be very useful and enough in most cases (for example https://github.com/slok/go-http-metrics).

**Comment by moolen** [comment]
Related on that topic:
When using `Kind=ServiceMonitor` a user can drop metrics that he/she isn't interested in. Had the issue last week with high cardinality labels.

Here's an example, if someone stumbles upon this:
https://github.com/istio/installer/blob/master/istio-telemetry/prometheus-operator/templates/servicemonitors.yaml#L304-L308

**Comment by moolen** [comment]
Is there any progress that someone wants to share? 
I'm going to take a look at this one and open a draft PR once i got an idea about how to approach this.
