### ISSUE TITLE
IBM Cloud Secrets Manager

### ISSUE THREAD

**Issue by moolen** [external-secrets/external-secrets#66]
IBM Cloud also has a SecretsManager, we should integrate it into ESO.

The pull request in KES outlines the most important aspects, see here: https://github.com/external-secrets/kubernetes-external-secrets/pull/656

**Comment by allen-servedio** [comment]
Hi @knelasevero - we were wondering where you were with this issue. We are interested in trying this out in IBM Cloud and are willing to assist with this if needed.

**Comment by knelasevero** [comment]
Hi @allen-servedio! We are using this issue to do some mob programming and introduce some newcomers to the project internally here at Container Solutions. I think that we will probably open a PR this week, latest next week

**Comment by allen-servedio** [comment]
Sounds great @knelasevero ! Let us know if you need any help...

**Comment by knelasevero** [comment]
Hey @allen-servedio , ibm Provider is merged but we have additional things still missing https://github.com/external-secrets/external-secrets/issues/242

Would you like to take #242 ?

**Comment by allen-servedio** [comment]
Thanks @knelasevero for doing this so quickly. We are going to look at adding the secret types and one of my team members will get back to you.
