### ISSUE TITLE
CRDs don't give any error or ready status

### ISSUE THREAD

**Issue by vitorfhc** [external-secrets/external-secrets#669]
I created a ServiceAccount, a ClusterSecretStore, and an ExternalSecret, but they never give the ready status.

```yaml
# $ kubectl get sa cluster-store

apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<acc id>:role/<role>
    meta.helm.sh/release-name: external-secrets
    meta.helm.sh/release-namespace: external-secrets
  creationTimestamp: "2022-02-02T20:56:22Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: cluster-store
  namespace: external-secrets
  resourceVersion: "1566408"
  uid: 1bf7830e-9301-4848-91c0-2993fa4b3d2a
secrets:
- name: cluster-store-token-rwp7z
```

```yaml
# $ kubectl get css cluster-store -o yaml

apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  annotations:
    meta.helm.sh/release-name: external-secrets
    meta.helm.sh/release-namespace: external-secrets
  creationTimestamp: "2022-02-02T20:30:08Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: cluster-store
  resourceVersion: "1560615"
  uid: 34c71f80-2e04-420b-aa75-157eec516520
spec:
  provider:
    aws:
      auth: 
         jwt: 
           serviceAccountRef:
              name: cluster-store
      region: us-east-1
      role: arn:aws:iam::<acc id>:role/<role>
      service: SecretsManager
```

```yaml
# $ kubectl get es external-secret -o yaml

apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  annotations:
    meta.helm.sh/release-name: external-secrets
    meta.helm.sh/release-namespace: external-secrets
  creationTimestamp: "2022-02-02T20:30:08Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: external-secret
  namespace: external-secrets
  resourceVersion: "1560618"
  uid: a4471a31-aa46-48ac-8a21-5abb01e2114d
spec:
  data:
  - remoteRef:
      key: <key>
    secretKey: <secret key>
  refreshInterval: 30m
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-store
  target:
    creationPolicy: Owner
    name: secret-name
```

By describing any of them I get empty `events`.  I don't know how to debug why it's not working. Could I get any helps, please?

I am not sure if it can't authenticate with AWS but my IRSA works fine, I tested with another pod.

**Comment by vitorfhc** [comment]
After a little research, I found out the [core helm chart](https://github.com/external-secrets/external-secrets/tree/main/deploy/charts/external-secrets) was not deployed. I deployed and now I have this:

```
could not get secret data from provider:
key "<secret remote key>" from ExternalSecret "<ext secret name>":
WebIdentityErr: failed to retrieve credentials
caused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity
```

My `values.yaml`:

```
extraEnv:
- name: AWS_REGION
  value: us-east-1
- name: AWS_DEFAULT_REGION
  value: us-east-1

installCRDs: true

podSecurityContext:
  fsGroup: 1001
```

**Comment by gusfcarvalho** [comment]
Hi @vitorfhc how are you?
When you define a `spec.role` in your secretStore, external-secrets performs a sts-assume-role, which by default needs to be authorized with the sts:AssumeRole permission.

If your permissions are already set to the role bound to your Token, you can skip configuring the `spec.role` field. This way, external-secrets will try to communicate with its original role.

**Comment by gusfcarvalho** [comment]
I realized my previous text was a bit confusing, so I'll try to rephrase it with an example:

if  `Role A` is bound to your token and you want to get secrets allowed to `Role B` (and not `Role A`), you should configure `spec.role` to `Role B`. Otherwise, if the secrets are available within `Role A` permissions, you can skip the `spec.role` configuration

**Comment by moolen** [comment]
If i interpret it correctly the following things happen:
1. the eso controller pod gets the service account mounted (these are now default/fallback credentials for _everyone_)
2. your provider references the very same service account (these override the default from above)
3. you assume a role (the one it already has) 

Please try to NOT mount the SA to the eso controller pod (remove 1), instead just reference it from your provider (keep 2). Also do not assume the role you already have (remove 3). 

Then it should work as intended.

**Comment by vitorfhc** [comment]
It is still a little bit confusing for me @moolen @gusfcarvalho

If I understood it correctly I should remove the service account I was using with IRSA from my ESO controller, which I did:

```yaml
# $ kubectl get as external-secrets -o yaml
# >>> no IRSA role <<<

apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: external-secrets
    meta.helm.sh/release-namespace: external-secrets
  creationTimestamp: "2022-02-03T19:05:10Z"
  labels:
    app.kubernetes.io/instance: external-secrets
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/version: v0.3.11
    helm.sh/chart: external-secrets-0.3.11
  name: external-secrets
  namespace: external-secrets
  resourceVersion: "1859197"
  uid: bfce782b-e36c-4f1c-a8d1-e9180efa1e09
secrets:
- name: external-secrets-token-58b98
```

I also removed `spec.role` from the store:

```yaml
# $ kubectl get -o yaml CSS

apiVersion: v1
items:
- apiVersion: external-secrets.io/v1alpha1
  kind: ClusterSecretStore
  ...
  spec:
    provider:
      aws:
        auth:
          jwt:
            serviceAccountRef:
              name: cluster-store-sa
              namespace: external-secrets
        region: us-east-1
        service: SecretsManager
...
```

But I am still using this service account for the store:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account>:role/<role>
    ...
  labels:
    app.kubernetes.io/managed-by: Helm
  name:cluster-store
  ...
secrets:
- name: cluster-store-token-86c27
```

Shouldn't it work? I am still getting:

```
could not get secret data from provider: key "sre/gh-actions/app-id" from ExternalSecret "github-actions-es": WebIdentityErr: failed to retrieve credentials
caused by: AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity
```

**Comment by vitorfhc** [comment]
As far as I got it, we have two options: authentication provided by the controller or by the store.

I just changed the controller to have IRSA, removed `spec.role`, and IRSA from the store and it worked.

What I did above - in the last comment - was to keep the authentication as a store's responsibility but it didn't work. Did I do it right?

**Comment by moolen** [comment]
> Did I do it right?

From the yamls you have submitted it looks good. A `Not authorized to perform sts:AssumeRoleWithWebIdentity` error indicates that the trust relationship between the SA and the IAM Role is not set up correctly, [see here](https://stackoverflow.com/questions/66405794/not-authorized-to-perform-stsassumerolewithwebidentity-403#answer-67400755). The devil lies in the details, double check everything.

> I just changed the controller to have IRSA, removed spec.role, and IRSA from the store and it worked.

Yeah, that's an alternative, but then essentially everyone who is able to create an `ExternalSecret` and a `SecretStore` can read all secrets that can be reached with the policy attached to the controller. If that's not a concern, then you can stick to this solution.

**Comment by vitorfhc** [comment]
Then I am closing this issue since it's working. Soon I will try to move the authentication to the store instead.

Thanks for the help!
