### ISSUE TITLE
Standardize provider fields

### ISSUE THREAD

**Issue by knelasevero** [external-secrets/external-secrets#689]

**Comment by gusfcarvalho** [comment]
Adding context after our GA planning call:

    - Close to Provider versioning
    - Conversion Webhook logic for upgrade path (v1beta1 -> v1)
    - how serviceAccounts and secrets are used
    - common fields like 'path' and 'server'?
        - common fields mean found more than 5 times across a file, or 10 times across the project.
    - root level provider structure should follow:
        - auth
        - server (find a better name - maybe target)
            - url
            - cabundle, caprovider
            - endpoint
            - ...
    - After discussing, Standadization of fields seems way easier if we figure out provider versioning with CRDs.
