### ISSUE TITLE
Implement GetAllSecrets for the providers that could support it

### ISSUE THREAD

**Issue by knelasevero** [external-secrets/external-secrets#698]
We will need follow-up issues here. We need to check if the providers have APIs that support this and where it makes sense.

- [x] #757
- [x] #758
- [x] #498
- [x] #759
- [x] #756

**Comment by gusfcarvalho** [comment]
Following our community meeting, we can use this issue to describe what GetAllSecrets should do in general.

Main points leveraged were:

- What should we do if we have a Key name collision ?
- Should it be possible to support versions?

One possibility for the key collision we can either not allow any key collision to happen (fail the reconcile if we detect a key collision). 

Another one is to add a pattern to the k8s secret key itself:
given two secrets `foo` and `bar` with:
```
{
  "key":"value"
}
```
we can match them on ExternalSecrets with either `data.foo.key`/`data.bar.key` (nesting json) or as `data.foo-key`/`data.bar-key` as well. This can be an approach done always or only when we detect collision. I do think if we do it only when we detect collision can be a very weird experience to use GetAllSecrets (with potentially secrets changing names along the way).
```

**Comment by gusfcarvalho** [comment]
the `data` was just to mention the k8s Secret `data` section on the yaml :P the keys would actually be `foo-bar`, etc.

In your example, both `foo$bar` and `foo^bar` would still possibly have their own keys within them, right? Your replace idea makes sense, but I wanted to explore another issue:
example in:
`foo$bar`
```
{
"db":"host",
"user":"user",
"password":"password"
}
```

`foo^bar`
```
{
"db":"host",
"username":"user",
"password":"password"
}
```
the expected outcome with your idea in k8s secret would be like this?
```
name: my-secret
data: 
  "foo_U+0024_bar_db":  aG9zdA== #host
  "foo_U+0024_bar_user":  dXNlcg== # user
  "foo_U+0024_bar_password":  cGFzc3dvcmQ= #password
  "foo_U+005E_bar_db": aG9zdA== #host
  "foo_U+005E_bar_username": dXNlcm5hbWU= #username
  "foo_U+005E_bar_password": cGFzc3dvcmQ= #password
```
The other option would be something like this:
```
name: my-secret
data: 
  "foo_U+0024_bar": eyJkYiI6Imhvc3QiLCJ1c2VyIjoidXNlciIsInBhc3N3b3JkIjoicGFzc3dvcmQifQ== # Json with all foo$bar keys
  "foo_U+005E_bar": eyJkYiI6Imhvc3QiLCJ1c2VyIjoidXNlcm5hbWUiLCJwYXNzd29yZCI6InBhc3N3b3JkIn0= # Json with all foo^bar keys
```
Which one should we pursue? IMO, it should be the second one.

**Comment by moolen** [comment]
I think we shouldn't care about the content of the secret - my idea was that we just return the "raw" data. (so it behaves more more like `Data`).

**Comment by moolen** [comment]
Yeah, i stumbled upon that aswell when looking at the aws implementations.
Both SSM Parameter Store ([docs](https://docs.aws.amazon.com/sdk-for-go/api/service/ssm/#SSM.GetParametersByPath)) and Secrets Manager ([name prefix match](https://docs.aws.amazon.com/sdk-for-go/api/service/secretsmanager/#Filter)) are able to support that.

Another sidenote: i was wondering if we want to support specifying two (or more) matching strategies at the same time (e.g.: `regexp + tags` or `path + tags`) ?
Or should the user forced to specify exactly one matching strategy?

**Comment by gusfcarvalho** [comment]
IMO, it makes sense to combo them with `and` operations (i.e. "I want all the secrets from 'path:team-1' and match the names 'conf-my-app-.*' and tags 'env':'prod'")...

What I am not sure if it's 
1) sufficiently compatible with providers;
2) this type of combo approach is indeed a valid use case, and not me just overthinking.

**Comment by moolen** [comment]
Agree, should be `and` ed.

1. `path` is not supported by all providers. Azure and GCP do not allow listing secrets by path. I think it's fine to just return an `not supported` error if the user wants to use a unsupported `find` strategy.
2. combo would be IMO great from a user perspective. But we can (should?!) add that later on. Lifting the validation restrictions (Min,Max=1 to Min=1) is a backward compatible change. I think we should start small here.

**Comment by gusfcarvalho** [comment]
small update, we cannot use `U+0024` as `+` is not allowed character for k8s secret keys.  propose we just do a `_U0024_` approach.

**Comment by moolen** [comment]
We discussed in the last community meeting that it may be a good idea to offer some sort of a  `conversionStrategy` that transforms the incoming secret keys `foo/bar/baz` into something compatible with Kubernetes secret keys `foo_bar_baz`.

Primary goal should be to offer a good UX when using the GetAllSecrets feature. This can be done by offering a sensible default that should work in 90% of cases and offers a way to derive from that to cover the remaining cases.

We discussed that we might want to add a `conversionStrategy` field. This is can have (for now) two values:
1. `Default`: it simply replaces the incompatible characters with a `_` (we called it rancher-style replacement)
2. `Unicode`: it replaces incompatible chars with their unicode representation like described above `$ -> _U0024_`

It can be used by two APIs: `dataFrom[].find` and `dataFrom[].extract`. I guess it makes sense to put that field into both apis:

```yaml
dataFrom:
- find:
    conversionStrategy: "Unicode"
    name: 
      regexp: "foobar.*"
```

```yaml
dataFrom:
- extract:
    key: "foobar"
    conversionStrategy: "Unicode"

```

Caveats:
We do not support user-defined values. We support only enum-type values for `conversionStrategy`. So the user will not be  able to create his own conversion strategy without a breaking change.

**Comment by gusfcarvalho** [comment]
> It can be used by two APIs: `dataFrom[].find` and `dataFrom[].extract`. I guess it makes sense to put that field into both apis:
> 
> ```yaml
> dataFrom:
> - find:
>     conversionStrategy: "Unicode"
>     name: 
>       regexp: "foobar.*"
> ```
> 
> ```yaml
> dataFrom:
> - extract:
>     key: "foobar"
>     conversionStrategy: "Unicode"
> ```
> 
> Caveats: We do not support user-defined values. We support only enum-type values for `conversionStrategy`. So the user will not be able to create his own conversion strategy without a breaking change.

For extract, it would be to convert if the secret keys are not compliant, is that correct?

**Comment by gusfcarvalho** [comment]
I'll propose some changes around this on hashivault implementation, plus add some documentation to it.

**Comment by gusfcarvalho** [comment]
Changes are up at #784. Although, I think this could also be done on a different PR (I can split them if you want :sweat_smile:)

**Comment by knelasevero** [comment]
I am back from my trip and will have some time on the following days. I can grab the implementation for the gcp getAll. Will bring up a draft PR soon.

**Comment by moolen** [comment]
All providers mentioned above implemented `GetAllSecrets()`.
