### ISSUE TITLE
Support Remote kubernetes clusters

### ISSUE THREAD

**Issue by jack-evans** [external-secrets/external-secrets#709]
Similar to Flux2, it would be really cool if External Secrets supported the ability for a given ES to be reconciled within one cluster and the resulting Secret created on another. 

This would allow environments/clusters where you want to ensure that only customer using secrets are on (e.g. control plane vs data planes) and no secret is on the cluster that may expose the rest of your secrets to the cluster.

**Comment by gusfcarvalho** [comment]
Hi ! This issue is a duplicate from #547, and already has a draft PR for it #707 :)

**Comment by moolen** [comment]
I think this is slightly different if i understand it correctly. The idea is that the secret will be created in a different cluster - so you basically push secrets to a different cluster. This use-case should be covered in #641. And would with the current proposal be a two-step process:
1. create an `ExternalSecret` to create the secret in the same cluster
2. create an `SecretSink` to push that secret to the external cluster

**Comment by jack-evans** [comment]
> I think this is slightly different if i understand it correctly. The idea is that the secret will be created in a different cluster - so you basically push secrets to a different cluster. This use-case should be covered in #641. And would with the current proposal be a two-step process:
> 
> 1. create an `ExternalSecret` to create the secret in the same cluster
> 
> 2. create an `SecretSink` to push that secret to the external cluster

Correct that is the kind of functionality I was looking for

**Comment by moolen** [comment]
I opened #976 to track progress on the `SecretSink` proposal, this will allow pushing secrets to another cluster.
