### ISSUE TITLE
unable to create session: invalid ClusterSecretStore: missing AWS AccessKeyID Namespace

### ISSUE THREAD

**Issue by fscojr** [external-secrets/external-secrets#720]
Good evening guys, how are you ?

I'm trying to create a ClusterSecretStore using the following configuration

apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
   name: saccarclusterstore
   namespace: kube-system
spec:
   provider:
     aws:
       service: SecretsManager
       region: sa-esat-1
       auth:
         secretRef:
           accessKeyID:
             name: awssm-secret
             key: access-key
             namespace: kube-system
           secretAccessKey:
             name: awssm-secret
             key: secret-access-key
             namespace: kube-system

But the following error is displayed.

unable to create session: invalid ClusterSecretStore: missing AWS AccessKeyID Namespace

When checking the created object, I noticed that the clustersecretstore is not receiving the secret value

   spec:
     provider:
       aws:
         auth:
           secretRef: {}
         region: sa-esat-1
         service: SecretsManager

I'm using openshift 4.8, installed via helm.
Same scenario when installed via operator

**Comment by moolen** [comment]
hey, first thing: the region `sa-esat-1` should be `sa-east-1`, right?
Could you please provide a properly formatted yaml? I bet it's a indentation issue.

**Comment by gusfcarvalho** [comment]
Hi @fscojr ! Is your issue still ongoing?
