### ISSUE TITLE
Problem with keys with a dot with Hashicorp Vault

### ISSUE THREAD

**Issue by tommy-heyde-olsen** [external-secrets/external-secrets#725]
I just upgraded to 0.4.2 and noticed that I get the following error when trying to sync secrets from Hashicorp Vault:

```
Warning  UpdateFailed  23s (x5 over 2m57s)  external-secrets  could not get secret data from provider: key "path/to/secret" from ExternalSecret "name-of-secret": cannot find secret data for key: "key.json"
```

This was working with 0.3.5 (haven't tried other versions). I did notice that the `GetSecret` function was changed 10 days ago in this commit: https://github.com/external-secrets/external-secrets/commit/2ac4053648c62e220f152a828e2eac6c6124a04a -- and I suspect that this change is the culprit behind it.

I specifically upgraded to this version to be able to fetch the whole secret without any `property` added, but it seems to break backwards compatibility with keys with a dot in.

**Comment by gusfcarvalho** [comment]
Hi! Can you share your ExternalSecrets deployment file, with any redactions where appropriate?

**Comment by moolen** [comment]
yeah, that's right - that broke. The key is now interpreted as `gjson` expression.

**Comment by gusfcarvalho** [comment]
One workaround would be to backslash the `.`, so something like `key\.json` should work.

**Comment by moolen** [comment]
Let me take a look and attempt to fix it.

**Comment by tommy-heyde-olsen** [comment]
Wow! Really quick response and solution. Thank you 🙏🏻 

I did try `key\.json` but that got interpreted like so:

```
Secret "name-of-secret" is invalid: data[key\.json]: Invalid value: "key\\.json": a valid config key must consist of alphanumeric characters, '-', '_' or '.' (e.g. 'key.name',  or 'KEY_NAME',  or 'key-name', regex used for validation is '[-._a-zA-Z0-9]+')
```

**Comment by gusfcarvalho** [comment]
Hey @tommy-heyde-olsen ! This is weird, I tested it earlier today and seemed to work. I’ll try again later today and post it to you. 

Anyways the fix is already implemented, in the next release you won’t need this workaround anymore

**Comment by todaynowork** [comment]
Hello, I find this issue in AWS SM today. Is this fixed already for AWS SM service? I believe I install from the master branch today.

Thanks,
Du
