### ISSUE TITLE
Sign the artifacts (binaries/images) using cosign

### ISSUE THREAD

**Issue by cpanato** [external-secrets/external-secrets#731]
The idea is to sign the release artifacts using cosign when doing the release.
The project is already using  GitHub actions and that makes things easier to implement 😃

This is an initial step for a more secure release and lets the consumers have the ability to verify the release artifacts.

I can help to implement this feature if the team decides to move this idea forward.

**Comment by moolen** [comment]
hey @cpanato thanks for bringing this up. It makes sense to implement it, feel free to contribute! 

Let us know if you need anything, we can generate the key pair and store it as GitHub secret. The public key probably needs to be stored accessible for all users, either in the repository itself or via github pages. Do you recommend a approach?

**Comment by cpanato** [comment]
@moolen thanks for the reply, i will start working on this on the weekend

we can use the keyless approach and publish the certificates/signatures for the binaries and for the images that will be attached to the signature that is pushed together

**Comment by cpanato** [comment]
however if you prefer having a key pair we can do as well
