### ISSUE TITLE
support AWS SecretsManager with VPC endpoint

### ISSUE THREAD

**Issue by gikvin** [external-secrets/external-secrets#739]
**Describe the solution you'd like**
Option to add AWS Secrets Manager VPC endpoint url in SecretStore or ClusterSecretStore custom resource

**What is the added value?**
air-gapped environment support ( clusters not located in AWS )

**Comment by gusfcarvalho** [comment]
Hey @gikvin ! I believe it is possible to set up your VPC endpoint to the controller itself right now. Create a `values.yaml` file with the following content, and install external-secrets using it:
```
extraEnvs:
   AWS_SECRETSMANAGER_ENDPOINT: <your custom endpoint here>
```
   
Would that already be enough for your use case?

**Comment by gikvin** [comment]
Hi @gusfcarvalho, thanks for your suggestion, it is enough and it helped. Small correction, extraEnv is expecting array:
```
- name: AWS_SECRETSMANAGER_ENDPOINT
   value: https://endpoint
```

**Comment by mztnnrt** [comment]
Thanks, this information was helpful form me.

**Comment by mztnnrt** [comment]
Thanks, this issue was helpful for me.

> https://github.com/external-secrets/external-secrets/issues/739#issuecomment-1046212656
> https://github.com/external-secrets/external-secrets/issues/739#issuecomment-1046212656

Small collection, `extraEnv` not `extraEnvs`, works below in my environment.

```yaml
extraEnv:
  - name: AWS_SECRETSMANAGER_ENDPOINT
    value: "..."
```

and expected array as written @gikvin.
