### ISSUE TITLE
OLM operatorhub.io v0.4.3 stable channel not available. Is it intentional?

### ISSUE THREAD

**Issue by slopezz** [external-secrets/external-secrets#746]
**Describe the solution you'd like**

In both k8s and Openshift OperatorHub.io catalogs, for `v0.4.3` release the **stable** channel has disappeared, only **alpha** channel is available:

- Previous K8s operatorhub catalog `v0.4.2`:   
   - k8s: https://github.com/k8s-operatorhub/community-operators/blob/8c22186526f552d59f62fd086501c2d30c99d6c3/operators/external-secrets-operator/0.4.2/metadata/annotations.yaml#L7
   - Openshift: https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/f8e12f8bd0ac21a73163a6c487a9cba0bb345e9a/operators/external-secrets-operator/0.4.2/metadata/annotations.yaml#L7

- Current  operatorhub catalog `v0.4.3`: 
   - k8s: https://github.com/k8s-operatorhub/community-operators/blob/5f50bb3427f1061f67d630b14f337de4db3b32d3/operators/external-secrets-operator/0.4.3/metadata/annotations.yaml#L7
   - Openshift:  https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/20c20561a7034904a78284ca28c0f75ddc366855/operators/external-secrets-operator/0.4.3/metadata/annotations.yaml#L7 

It is a change made on purpose? because the idea is only keep publishing **alpha** channels?

When you install an operator via OLM, you need to create an operator **Subscription** custom resource, where you specify the **channel** to use:
- Some operators public different releases on alpha/stable channels
- Others just always have the same versions on both channels (it was the case of ESO)

In our case we are using right now the **stable** channel, and our ESO deployments are broken because of the bug at `v0.4.2` where secrets cannot be updated because secretKey contains a `.`:
```
{"level":"error","ts":1645457529.966774,"logger":"controllers.ExternalSecret","msg":"could not update Secret","ExternalSecret":"prometheus-ec2/prometheus-ec2-config","SecretStore":"/vault-mgmt","error":"could not get secret data from provider: key \"kubernetes/stg-saas/ocp4/prometheus-ec2/prometheus-ec2-config\" from ExternalSecret \"prometheus-ec2-config\": cannot find secret data for key: \"prometheus.yml\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/...
```

We have seen on  **v0.4.3** release notes that is a bug that have been fixed.

However, the operator on different clusters have not been automatically upgraded to **v0.4.3** because our **Subscriptions** are using **stable** channel, and right now **v0.4.3** is only available at **alpha** channel.

We don't mind using **alpha** channel, but would like to know if:
- It was a mistake an **stable** channel was not added and should be added on a fix PR on both k8s and openshift catalogs?
- The change is on purpose, from now on only **alpha** channel will be provided?

Thanks in advance!

**What is the added value?**

Defining which OLM **Subscription** channel is going to be used.

**Give us examples of the outcome**

People using ESO via OLM will create proper operator **Subscriptions** custom resources if they know which channel/channels are available.

**Observations (Constraints, Context, etc):**

Operators on **stable** channel not upgraded to `v0.4.3`, so using buggy  `v0.4.2` with secrets not being updated.

**Comment by moolen** [comment]
Hey @slopezz, sorry for the inconvenience. I think this change was by accident. Let me try to promote the existing `0.4.3` release to stable. If we can't promote it then we'll create a new release to have a stable channel again.

**Comment by gusfcarvalho** [comment]
Hi @slopezz I believe that was my fault.. I'm not totally familiar with releasing OLM artifacts, and I might have somehow skipped some important step along the way :sweat:

**Comment by moolen** [comment]
TIL:
> channel promotion is achieved by creating a new operator version

docs: https://olm.operatorframework.io/docs/best-practices/channel-naming/#channel-promotion

I'm going to cut a new release `0.4.4`.

**Comment by slopezz** [comment]
No worries guys, thank you for being so fast!

I will wait for the `0.4.4` **stable** then, there is no rush  :)

A bit offtopic: Regarding the original repo where we created the OLM ESO helm metaoperator that you finally forked https://github.com/3scale-ops/external-secrets-operator, we are going to archive it, updating the README to point anyone to your fork https://github.com/external-secrets/external-secrets-helm-operator, which is the one being actively maintained by you. Is that OK for you?

**Comment by moolen** [comment]
sure, go ahead :+1: 
`0.4.4` was just released and should appear soon on operatorhub.

I'm going to close this issue. Please let us know if you still have any issues. We're happy to help :)
