### ISSUE TITLE
"could not reconcile ExternalSecret" error in GKE pod even if the externalsecret is deleted

### ISSUE THREAD

**Issue by minnie-jeong-otsk** [external-secrets/external-secrets#751]
Hi guys, hope you're having a great day.

I created an ExternalSecret named external-secret-test for test use, checked it's working fine, and deleted it. 
But when I do kubectl logs for external secret pod, I get a bunch of error msg updating as below. 

`{"level":"error","ts":1644999795.2597,"logger":"controllers.ExternalSecret","msg":"could not reconcile ExternalSecret","ExternalSecret":"default/external-secret-test","SecretStore":"/cluster-secret-store","error":"could not get secret data from provider: key \"uploader-301-config-dev\" from ExternalSecret \"external-secret-test\": unable to access Secret from SecretManager Client: rpc error: code = NotFound desc = Secret [projects/1081233272645/secrets/uploader-301-config-dev] not found or has no versions.","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.3/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.3/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.3/pkg/internal/controller/controller.go:214"}
`

I've double-checked the external-secret-test does not exists.
`minnie_jeong@cloudshell:~$ kubectl get externalsecret -n default`
`No resources found in default namespace.`

How can I get rid of this error msg ?
I'm using ghcr.io/external-secrets/external-secrets:v0.3.10

**Comment by gusfcarvalho** [comment]
Hi @minnie-jeong-otsk ! The `ts` field refers to the date which the message appeared (in this case Wednesday, 16 February 2022 08:23:15 UTC). Can you check if the time of this message happened while the external secret was still on the cluster?

**Comment by minnie-jeong-otsk** [comment]
Hi @gusfcarvalho 

I was not familiar of the `ts` field. I've checked the kubectl logs again with tail option, and found that it didn't appear after I deleted external-secret-test, so there was no issue after all. 

Thanks for your explanation!
