### ISSUE TITLE
DELETE unsupported version v0.5.5.

### ISSUE THREAD

**Issue by lbampo** [external-secrets/external-secrets#754]
Remove the v0.5.5 image/tag. The latest supported tag is v.0.4.4.

![Screenshot from 2022-02-22 12-40-44](https://user-images.githubusercontent.com/55100194/155297620-bd8460d4-04bc-40db-bf04-9669efd91e9f.png)

By fixing the above, It will fix all issues/configurations concerning automating the pulling of images with the latest tags.

Image with the tag v0.5.5 was created 9 months ago, however it does not seem to be supported and the image is significantly smaller than usual, suggesting it's not the correct/latest image being used. This image is causing my configuration to fail.

Thanks.

**Comment by gusfcarvalho** [comment]
hey all! sorry for the delay. Image is deleted. Thanks for the heads up!
