### ISSUE TITLE
Triggering a sync manually

### ISSUE THREAD

**Issue by NivStav-RecoLabs** [external-secrets/external-secrets#760]
**Describe the solution you'd like**
Manually trigger an `ExternaSecret` sync out of its normal schedule.

**What is the added value?**
For secrets that change on an irregular basis, being able to manually trigger a sync is useful.
Having a semi-static secret refresh every x hours is not needed and if the update schedule is not constant you can't set a timer on it.

I couldn't find it the docs or the issues, does this functionality exist already?

**Comment by gusfcarvalho** [comment]
Hi @NivStav-RecoLabs ! It's actually said [here](https://external-secrets.io/v0.4.4/api-externalsecret/#update-behavior). In short, the best way to do it is have an automation to `kubectl annotate`. You can do it with Lambda functions, for instance.

**Comment by NivStav-RecoLabs** [comment]
Thanks @gusfcarvalho !
