### ISSUE TITLE
Is `ClusterSecretStore` supported for IBM provider ?

### ISSUE THREAD

**Issue by techierishi** [external-secrets/external-secrets#792]
**Describe the solution you'd like**
I would like `ClusterSecretStore` to work for IBM provider.

**What is the added value?**
It will help me create only one secret store per cluster and all `ExternalSecret` can reference one single `ClusterSecretStore`. 

I am asking this as I could not see any example for `ClusterSecretStore` in the snippet for IBM.

**Comment by gusfcarvalho** [comment]
Yes it is! The only difference between SecretStore and clusterSecretStore is the need to add the namespace to any SecretRef
Or ServiceAccountRef :)

**Comment by gusfcarvalho** [comment]
Hi @techierishi ! Did you manage to make it work?

**Comment by techierishi** [comment]
Yes managed to make it work. Thanks for the explanation.
