### ISSUE TITLE
Implement `ExternalSecret.spec.target.template.data` and `ExternalSecret.spec.target.template.templateFrom`

### ISSUE THREAD

**Issue by jonatasbaldin** [external-secrets/external-secrets#8]
## Expected Behavior
Have the CRD implementation of the `ExternalSecret.spec.target.template.data` and `ExternalSecret.spec.target.template.templateFrom`, following the [crd-spec](https://github.com/external-secrets/external-secrets/issues/6).

## Actual Behavior
Not implemented.

**Comment by moolen** [comment]
I'm gonna close this in favor of #179.
