### ISSUE TITLE
Failed to create a PR against this repo

### ISSUE THREAD

**Issue by kinyat** [external-secrets/external-secrets#801]
**Describe the solution you'd like**
I created my first PR in https://github.com/external-secrets/external-secrets/pull/800 however it is closed due to `You seem to have opened more PR's than this Repo Allows` but I have never created one before.

I have checked the [doc](https://external-secrets.io/v0.4.4/contributing-process/) but it does not help :(
 
**What is the added value?**
More people more helps better the project.

**Give us examples of the outcome**
People can contribute to the project.

**Comment by knelasevero** [comment]
The bot closes PRs after a limit of 15... and dependabot spamed PRs 10 hours ago :sweat_smile: We need to increase the limit, or remove it.

https://github.com/external-secrets/external-secrets/pull/794
