### ISSUE TITLE
Add support to Public Certificate of IBMCloud Secrets Manager

### ISSUE THREAD

**Issue by nitzann** [external-secrets/external-secrets#847]
**Describe the solution you'd like**
external-secrets should be able to extract and store a public cert type of IBM cloud secret

**What is the added value?**
Users that need to store public certificates data in a Kubernetes secret will be able to do so

**Give us examples of the outcome**

Should work just like any other IBMCloud supported secret, specifically it will be similar to imported_cert type. Available properties are `certificate`, `intermediate`, `private_key`

**Observations (Constraints, Context, etc):**

N/A

**Comment by nitzann** [comment]
I have forked the project, and can submit a PR for adding this support

**Comment by gusfcarvalho** [comment]
Implemented with #849
