### ISSUE TITLE
Please add Liveness probe to Helm Chart

### ISSUE THREAD

**Issue by ajchiarello** [external-secrets/external-secrets#881]
**Describe the solution you'd like**
I have had occasional issues with the external-secrets container locking up and refusing to sync secrets. Restarting the container fixes this issue, but I would like the deployment to automatically detect this situation and restart the container on its own. A Liveness probe would accomplish this.

**What is the added value?**
This would increase the reliability of external-secrets, as containers that were no longer functioning would be automatically replaced.

**Comment by moolen** [comment]
It would be helpful if we know the root cause of your issue, can you share any insights on that? 
Unfortunately it is quite hard to implement a meaningful `livenessProbe`. IMO just checking if `/metrics` responds with a 2xx isn't really helpful because the reconciler could be deadlocked.

**Comment by ajchiarello** [comment]
Hi @moolen - I'm not sure what the root cause is, but I'm open to suggestions about how to diagnose it. What I have observed is that the external-secrets container will stop syncing secrets from the Vault backend every now and then. It's pretty infrequent - I'm running it on 30+ clusters, and I've only seen about three times in the last three months. When this happens, I can't interact with the container at all - exec times out, and I can't get to the current logs. Restarting the container brings everything back to normal.

**Comment by moolen** [comment]
> exec times out, and I can't get to the current logs

Hmm, that points towards an issue with the node itself. Maybe Kubelet or the container runtime. I'd suggest to ssh into the node and try exec a shell in the container and fetch logs from there. Further, check if the process is running and try to do attach a `strace` to it to see if it is doing anything at all. No intermittent failure _should_ cause a issue with the controller.

We have an alert that triggers if no reconciliations happen. That may help to detect the issue at least.

**Comment by ajchiarello** [comment]
Thanks! I'll set up the alert, and try the steps you suggested. I'm not sure about it being a node issue, since nothing else on the node was impacted, but I agree that getting more information about what is happening is the next step.
