### ISSUE TITLE
What is the certcontroller for?

### ISSUE THREAD

**Issue by EmilyShepherd** [external-secrets/external-secrets#885]
**Describe the solution you'd like**
I've been reviewing the documentation and the README for the helm chart, I would like to better understand what the certController is for, and how it differs from the main controller.

**What is the added value?**
It would be good to understand why _two_ seperate controller instances need to be deployed, and what the value of certcontroller is - also why it needs control over CRDs and webhooks?

**Comment by EmilyShepherd** [comment]
Amazing! Thanks @gusfcarvalho :smile: That explaination makes a lot of sense.

> certController is not yet released

Hah, that'll teach me for looking at `main` and forgetting to check what is in the _actual_ release :facepalm:.

**Comment by phin1x** [comment]
@EmilyShepherd is it planed to add cert manager as an alternative to the bundled certController?

**Comment by moolen** [comment]
@phin1x we actually need it for two `Kinds`: `CustomResourceDefinition` and `validatingAdmissionWebhook`. I'm not sure if `cert-manager` can inject `caBundle` into a conversion webhook :thinking: 
That may be one thing that can be contributed on cert-manager.

**Comment by phin1x** [comment]
@moolen the cert manager ca injector can to both: https://cert-manager.io/docs/concepts/ca-injector/. cert manager is also the recommended solution for webhooks if you using kubebuilder.

**Comment by gusfcarvalho** [comment]
I believe you only need to have cert-manager to use the same `secret-name` as the secret created by `external-secrets`. I believe you will need to manually add annotations to CRDs and ValidatingWebhookConfiguraiton currently.

So, 
1) `helm install ... --set certController.create = false`
2) get the secret name with `kubectl get secrets -l external-secrets.io/component=webhook`
3) create a Certificate pointing to that secret name.
4) run
```
kubectl annotate crd externalsecrets.external-secrets.io  cert-manager.io/inject-ca-from-secret= <my-ns>/<my-secret-name>
kubectl annotate crd secretstores.external-secrets.io  cert-manager.io/inject-ca-from-secret= <my-ns>/<my-secret-name>
kubectl annotate crd clustersecretstores.external-secrets.io  cert-manager.io/inject-ca-from-secret= <my-ns>/<my-secret-name>
kubectl annotate validatingwebhookconfiguration secretstore-validate  cert-manager.io/inject-ca-from-secret= <my-ns>/<my-secret-name>
kubectl annotate validatingwebhookconfiguration externalsecret-validate  cert-manager.io/inject-ca-from-secret= <my-ns>/<my-secret-name>
```

**Comment by gusfcarvalho** [comment]
I think we can provide some helm configuration setup (regarding the name of the secret, and annotations for `ValidatingWebhookConfigurations` and  `CustomResourceDefinitions`)

**Comment by amccague** [comment]
Is there a clean set of helm configurations that can be used to disable the cert controller and use cert-manager instead for a given `cert-manager.io/cluster-issuer`?

**Comment by moolen** [comment]
You can disable it: https://github.com/external-secrets/external-secrets/blob/6677c1e52d068aa8c19cf0dc736ad44ed268f3cf/deploy/charts/external-secrets/values.yaml#L287

Then make sure the webhook pod and CRDs get certificates configured. I don't have that from the top of my head. If you went through it feel free to report back so we can add it to the docs
