### ISSUE TITLE
Allow IAM role names instead of only full ARNs for AWS SecretStore provider

### ISSUE THREAD

**Issue by calebwoofenden** [external-secrets/external-secrets#894]
**Describe the solution you'd like**
In a `SecretStore` resource using the `aws` provider, I must pass a full IAM role ARN to the `role` field. If I only pass the role name, it fails with
```
Warning  ValidationFailed  3m29s  secret-store  ValidationError: <RoleName> is invalid
```
It would be simple enough for it to use a default value for the AWS account ID and figure out the ARN from that. `ExternalSecret` objects are able to find AWS secrets from just their names.

**What is the added value?**
Simplifies helm templates a bit.

**Comment by moolen** [comment]
The aws sdk does not allow to pass in a simple role name as it does not necessarily know in which account it runs in.

**Comment by calebwoofenden** [comment]
> The aws sdk does not allow to pass in a simple role name as it does not necessarily know in which account it runs in.

How is the ESO able to accept just names for AWS secrets rather than full ARNs then?

**Comment by gusfcarvalho** [comment]
> How is the ESO able to accept just names for AWS secrets rather than full ARNs then?

If you happen to know a way to implement this, feel free to open a PR! 😁

IMO, it is a lot of code to omit something we should not omit, since the role Field is for ESO to do a sts:AssumeRole.

**Comment by moolen** [comment]
> How is the ESO able to accept just names for AWS secrets rather than full ARNs then?

That's how the aws-sdk is designed. see: https://github.com/aws/aws-sdk-go/blob/v1.43.33/service/secretsmanager/api.go#L4011-L4017 and https://github.com/aws/aws-sdk-go/blob/v1.43.33/service/sts/api.go#L1458-L1461
