### ISSUE TITLE
Unable to run tests using Darwin arm64 (Apple M1)

### ISSUE THREAD

**Issue by b4ld** [external-secrets/external-secrets#921]
Currently we cannot use setup-env.

Problem:
Architectural limitations while creating the environment test from Envtest lib. 

`setup-envtest list --os darwin--arch arm64`
This option is not available on env-test options list, not allowing to create the environment needed to run Suit tests.

Possible solutions: 
Use external cluster options, for that we can enable "UseExistingCluster" option on "Envtest.environment".

**Comment by gusfcarvalho** [comment]
For anyone with this issue:

You can pass `USE_EXISTING_CLUSTER` environment variable to control the behavior of ENVTEST.
