### ISSUE TITLE
ForceOwner creation policy

### ISSUE THREAD

**Issue by sagikazarmark** [external-secrets/external-secrets#935]
**Describe the solution you'd like**
When using CD (ArgoCD, Flux) to deploy applications that rely on ESO created secrets, there is sometimes a race condition between ESO and the application that creates a default secret when none is found (ArgoCD Operator is one example: it creates a secret with a generated key in it for ArgoCD Export resources. When applied together with an ExternalSecret resource, ArgoCD usually wins and creates the secret first)

By defining a `ForceOwner` creationPolicy ESO would take over an existing secret (either by replacing an existing owner reference or adding another one).

**What is the added value?**
This would resolve all race condition related issues.

**Give us examples of the outcome**

```yaml
...

creationPolicy: ForceOwner

...
```

**Observations (Constraints, Context, etc):**

Using `Merge` as an alternative could work in some cases, because the other party would eventually create the secret. The problem is when there are conflicting keys within the secret ESO also fails.

I opened a discussion in ArgoCD Operator as well: argoproj-labs/argocd-operator#600

**Comment by sagikazarmark** [comment]
@gusfcarvalho Thanks for the quick answer.

Yeah, I realize this policy wouldn't be particularly safe or useful for all use cases, however, it would help in scenarios where other applications create defaults if something isn't provided.

I checked our ESO version and it looks like we are stuck on an older one (0.3.8) that doesn't include that fix. I'm going to upgrade ESO and see if I can still reproduce the problem with Merge, but I guess it's going to fix my problem.

Thanks again!

**Comment by moolen** [comment]
FYI (maybe it is related): There was an issue that `creationPolicy=Merge` that was fixed in `0.4.0` that was related to fieldOwnership. With the PR mentioned we force the field owner to be `external-secrets`: https://github.com/external-secrets/external-secrets/issues/583#issuecomment-1013484482

**Comment by gusfcarvalho** [comment]
Hi @sagikazarmark ! Upgrading ExternalSecrets allowed `creationPolicy=Merge` to work as expected in your use case?

**Comment by sagikazarmark** [comment]
@gusfcarvalho It did!

Although testing the change was a bit more tricky because of the other application, it ended up working fine on a clean install which is mostly what I was after (getting rid of the race condition between the two).

I'm wondering if this should be mentioned in the documentation somewhere (troubleshooting guide or where creation policy is explained).

I'd definitely mention conflicting keys somewhere, but it might also make sense to mention this exact use case.

WDYT? I'd be happy to draft a PR if we can agree on a general direction.

**Comment by sagikazarmark** [comment]
@moolen Well, reading through the documentation: I think the lifecycle docs mostly covers this scenario. In my case the problem was caused by a combination of an old version and the lack of understanding how Merge is supposed to work.

With those out of the way, I believe we are covered.

Thanks again for the help!
