### ISSUE TITLE
Unable to view ExternalSecret objects with kubectl when KES is also installed in a cluster

### ISSUE THREAD

**Issue by calebwoofenden** [external-secrets/external-secrets#945]
I'm working on migrating our clusters from the deprecated KES to the new ESO. In the meantime, we have both installed in our clusters. When I run `kubectl get externalsecrets`, I only get results for ones created with the apiVersion for KES. Maybe there is a command I could use to get ones created with the ESO apiVersion that I just don't know about - I've spent a while searching around but haven't had any luck yet.

**Comment by gusfcarvalho** [comment]
You need to specify the full CRD name once both KES and ESO define `ExternalSecrets`. It should be something like `kubectl get externalsecrets.external-secrets.io`. I believe kubectl auto completion would also help you out.

**Comment by calebwoofenden** [comment]
This worked. Thanks!
