### ISSUE TITLE
Local Development Guidelines Update

### ISSUE THREAD

**Issue by jonatasbaldin** [external-secrets/external-secrets#95]
Hi there,

This is not an issue, more like an idea to contribute to the Development Guidelines. I'm using these commands to get the operator up and running in a Kind cluster locally (if you want to test some K8S integration that needs more than `make run`).

```bash
# get cluster up and running
kind create cluster
```

```bash
# does everything else
export TAG=v2
export IMAGE=eso-local

GOOS=linux make build
docker build . -t $IMAGE:$TAG
kind load docker-image $IMAGE:$TAG
make helm.generate
helm upgrade --install external-secrets ./deploy/charts/external-secrets/ --set image.repository=$IMAGE --set image.tag=$TAG
```

If need a new version, I just update `TAG` and run the last script all over again.

What do you think about adding this info to the contribution guidelines?

**Comment by knelasevero** [comment]
I like this :)

BTW we now have  github discussions enabled in the repo: https://github.com/external-secrets/external-secrets/discussions

We can use it for forum like threads when it makes sense

**Comment by knelasevero** [comment]
Oh, I think that we need to tell devs to install kubebuilder on our dev guides, this is missing right now:

would be something like our ci

```
export  KUBEBUILDER_VERSION='2.3.1'

curl -L https://github.com/kubernetes-sigs/kubebuilder/releases/download/v"$KUBEBUILDER_VERSION"/kubebuilder_"$KUBEBUILDER_VERSION"_linux_amd64.tar.gz &gt; kubebuilder_"$env.KUBEBUILDER_VERSION"_linux_amd64.tar.gz          

tar -xvf kubebuilder_"$env.KUBEBUILDER_VERSION"_linux_amd64.tar.gz          

sudo mv kubebuilder_"$env.KUBEBUILDER_VERSION"_linux_amd64 /usr/local/kubebuilder
```

**Comment by alekc** [comment]
Just adding this one here for now before opening a new issue pr:

To have a different install of kubebuilder (local to project)
```
export KUBEBUILDER_TOOLS_VERSION='1.20.2'

curl -sSLo envtest-bins.tar.gz "https://storage.googleapis.com/kubebuilder-tools/kubebuilder-tools-$KUBEBUILDER_TOOLS_VERSION-linux-amd64.tar.gz"

 mkdir kubebuilder
 tar -C ./kubebuilder --strip-components=1 -zvxf envtest-bins.tar.gz
 export KUBEBUILDER_ASSETS=$(pwd)/kubebuilder/bin/
 make test
```

Also, we should bring in https://github.com/kubernetes-sigs/controller-runtime/pull/1488
