### ISSUE TITLE
Missing or wrong link for kubernetes backend

### ISSUE THREAD

**Issue by cmoulliard** [external-secrets/external-secrets#951]
**Observations**

The following URL - https://external-secrets.io/provider-kubernetes referenced within the README.md under the list of the t supported backends (See kubernetes) do not exist and return a `HTTP -404`

**Comment by gusfcarvalho** [comment]
You should try https://external-secrets.io/v0.5.0/provider-kubernetes/ . I'll provide a fix to the README.
