### ISSUE TITLE
Questions about new vars crds.createClusterExternalSecret and crds.createClusterSecretStore and OLM

### ISSUE THREAD

**Issue by slopezz** [external-secrets/external-secrets#973]
**Describe the solution you'd like**

When installing ESO via OLM, it needs to set var `installCRDs` to `false`, because CRDs should be managed by OLM (not the operato itself).

https://github.com/external-secrets/external-secrets-helm-operator/blob/8c266828144d3b9fab62b3a98b8f762f127d3e51/hack/download-helm-chart.sh#L16

However, there are 2 new variables whose default value is `true` that seems to do exactly the same as previous var `installCRDs`:
```
crds:
    createClusterExternalSecret: true
    createClusterSecretStore: true
```

**First question**: Is it not misleading having 2 separate ways (`installCRDs` and new `crds.createClusterExternalSecret`/`crds.createClusterSecretStore`) doing the same function, creating CRDs?

**Second question**: in case of needing those 2 new vars, its default value should't be set to `false` in the OLM installation, like done with  `installCRDs` using sed at https://github.com/external-secrets/external-secrets-helm-operator/blob/8c266828144d3b9fab62b3a98b8f762f127d3e51/hack/download-helm-chart.sh#L16?

**What is the added value?**

Clarification about the usage of 2 vew vars to manage CRDs.

**Comment by gusfcarvalho** [comment]
Hi @slopezz! I'm afraid not! The use of these values is to control cluster scoped resources to be installed or not (this is for a namespaced ESO installation be fully supported). These flags relate to install CRDs and are an `and-ed` operation with installCRDs. (If you look closely, You'll see namespaced resources are always installed, but cluster-scoped resources now can be opted-out)

Its default should actually be set to true as only few customers actually need ESO deployments on a namespaced basis. Maybe this can be an option in OLM as well, although I'm particularly not familiar how could we do it ( from a compatibility perspective just setting installCRDs=false in OLM should already be enough as it will not install *any* of the mentioned resources even if `createClusterSecretStore=true` or `createClusterExternalSecret=true`).

**Comment by gusfcarvalho** [comment]
Nice! I'll close this issue then, but feel free to reopen it!
