### ISSUE TITLE
Publish Kubernetes manifests as release assets

### ISSUE THREAD

**Issue by kaiju** [external-secrets/external-secrets#974]
**Describe the solution you'd like**

https://github.com/external-secrets/external-secrets/blob/main/deploy/manifests/README.md states:

"When a new release of external-secrets is cut, these manifests will be automatically generated and published as an asset attached to the GitHub release."

However the only assets I can see that are attached to releases are a tarball and zip of the source, neither of which I can reference from a tool like Kustomize.

I would ideally like to be able to install external-secrets via Kustomize instead of Helm. While I can pull and render the Helm chart via Kustomize, it's a little confusing to have documentation that states manifests can be referenced as release assets if that's not the case.

**Comment by knelasevero** [comment]
@gusfcarvalho @moolen maybe we can remove these manifests from gitignore and push them every new release?

**Comment by ron1** [comment]
In order to provide first-class kustomization support, consider allowing kustomize-based installs from the /config directory on the main branch and release branches. For example, refer to how Kyverno supports YAML/Kustomize-based installs [here](https://kyverno.io/docs/installation/#install-kyverno-using-yamls).

**Comment by andersro93** [comment]
+1 
When you have clusters that are private and want tight control on the resources you deploy, a helm chart is not the way to go. A simple manifest that could contain the default configuration would be great. The rest could then be "kustomized" however one sees fit.
