### ISSUE TITLE
dataFrom key rewrite

### ISSUE THREAD

**Issue by moolen** [external-secrets/external-secrets#975]
relates to: #915

when using `dataFrom` users may want to rewrite the `key` so that it is easier for them to consume the secrets.
We have three cases to consider:
1. dataFrom.extract
2. dataFrom.find with name/regexp
3. dataFrom.find with tags

As outlined in the above mentioned issue: it would be quite convenient to have regexp capture groups. However, we still need to address the other two use cases.

Out of scope:
* we also need a way to template keys in `target.template.data[$key]`

**Comment by gusfcarvalho** [comment]
Throwing ideas here:

One possible way is to have a map in the form of:

```
spec:
  dataFrom:
    convert:
      -  origin: my-known-data-from-key
         target: my-new-data-from-key
      ...
```
Examples:
```
spec:
  dataFrom:
    convert:
      -  origin: ^dev-(.*)-(.*)$
         target: $1-new-rewrite-$2
      ...
```
behavior would be: before applying conversionStrategy, apply conversion marked in convert (this could be used as inputs for the `template` operation if we apply it before [here](https://github.com/external-secrets/external-secrets/blob/6d2614e3fae8b18e19fec2658a8424339ca89cb1/pkg/controllers/externalsecret/externalsecret_controller.go#L512-L515)

**Comment by mmerickel** [comment]
Just FYI I put some more details on workarounds and a suggested solution in #1067.

**Comment by bhargavamin** [comment]
I would really appreciate it if this feature is worked upon soonish. 

It will help in seamless migration from deprecated external-kubernetes-secrets to the new one.

**Comment by jzbruno** [comment]
I came here from issue #915. I would also like to see this. It is currently stopping migration from the old external-kubernetes-secrets.
