### ISSUE TITLE
Implement PushSecret

### ISSUE THREAD

**Issue by moolen** [external-secrets/external-secrets#976]
discussed in #641

We want to implement the SecretSink proposal https://github.com/external-secrets/external-secrets/blob/main/design/001-secretsink.md.

**Comment by dweber019** [comment]
We are really looking forward for this feature, awesome work!! 🚀 

Could you provide estimates when this feature (Hashicorp Vault) will be available.
Maybe like: yes we start next week, in 2-3 month, will take at least half a year.

**Comment by gusfcarvalho** [comment]
Hey @dweber019! We are currently working on it (as you can see with the related issues) as a way to upskill internally some teams here. Our work order can be followed [here](https://github.com/orgs/external-secrets/projects/2/views/11). Our first focus will be GCP, but then we can go for Hashicorp Vault as well.

I'd estimate 3 months to have basic functionality for one, maybe two providers.

Also, this is an initiative open to the community. So, if you want to join in (and maybe help us deliver it faster), we are happy to welcome you! :smile:

**Comment by gusfcarvalho** [comment]
Hi @robert-heinzmann-logmein ! A PR is open - basically following standard review process in our end :)

**Comment by agaudreault-jive** [comment]
Do you think there could be a way to use [TokenRequest](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/) to periodically generate a token for a service account and uploads the information to the secretStore? 

Currently, it would be impossible to use because the selector only has a secret as input, but it could have a serviceAccount selector.

Otherwise it is possible to [manually create a token](https://www.programmingwithwolfgang.com/use-the-tokenrequest-api-to-create-tokens-in-kubernetes/) with a fixed name for a ServiceAccount since 1.24, but it would be a long-lived token without rotation.

**Comment by gusfcarvalho** [comment]
Hi @agaudreault-jive ! This is already supported by ESO :)

**Comment by agaudreault-jive** [comment]
> Hi @agaudreault-jive ! This is already supported by ESO :)

@gusfcarvalho can you point me to documentation on how to achieve that? 👀

**Comment by gusfcarvalho** [comment]
I’m your SecretStore, when you define a ServiceAccountRef. We will automatically request a new token if permissions are there. If not, we fall back to searching for a secret.

**Comment by agaudreault-jive** [comment]
> In your SecretStore, when you define a ServiceAccountRef. We will automatically request a new token if permissions are there. If not, we fall back to searching for a secret.

I think you misunderstood the question or perhaps it was confusing. The goal would be to upload/push specific service account token to the target secretStore, in our case hashicorp vault.

Not authenticate to the secretStore with a service account :)

**Comment by moolen** [comment]
I'd add a generator [1] that produces a service account using the token-request API. This service account token is then stored in a secret (alongside ca cert). This secret can be referenced from the `PushSecret` and pushed to a remote store.

I think that would solve your use-case and i'd be super happy about that addition. This is kind of close to what [Vault Kubernetes secrets engine](https://developer.hashicorp.com/vault/docs/secrets/kubernetes) provides, but vault-agnostic :smile:.

[1] https://external-secrets.io/v0.7.0/guides/generator/

**Comment by dweber019** [comment]
Is PushSecret released and ready to use?

According to https://github.com/external-secrets/external-secrets/issues/1101 it has been implemented for HashiCorp Vault and I can find some documentation about it https://external-secrets.io/v0.7.0/api/pushsecret/ and https://external-secrets.io/v0.7.0/provider/aws-parameter-store/#creating-a-push-secret but not for https://external-secrets.io/v0.7.0/provider/hashicorp-vault/.

**Comment by moolen** [comment]
> Is PushSecret released and ready to use?

It has been released with 0.7.0, however expect some rough edges :)
We'd be glad if users report bugs for it so we can improve upon it.
