### ISSUE TITLE
After upgrade to 0.5.0, we see a lot more logins to Hashicorp Vault

### ISSUE THREAD

**Issue by lukasertl** [external-secrets/external-secrets#984]
We're using OpenShift 4.8 and the External Secrets Operator from Operator Hub.

We're using namespaced ExternalSecrets and SecretStores that link to a HashiCorp Vault, where we identify via Kubernetes auth.

Before upgrading to 0.5.0 we saw just a few logins to Vault every 5 minutes or so, but since upgrading to 0.5.0 (and also 0.5.1) we see multiple logins every second.

If we delete the ExternalSecret object (or the SecretStore) the logins stop.

Secrets are fetched correctly and we don't see any error messages or other problems with the setup, but this avalanche of logins fills up our Vault audit logs and puts constant stress on the Vault VMs.

**Comment by gusfcarvalho** [comment]
Hi @lukasertl ! Can you share a little bit more context? How is the controller configured? Are you using concurrency? Are you using multiple replicas with leader election?

**Comment by gusfcarvalho** [comment]
Which version were you using before upgrading to 0.5.0? Also, what is the authentication method you are currently using?

**Comment by gusfcarvalho** [comment]
can you get the `external-secrets` logs, please?

**Comment by lukasertl** [comment]
Your request has led me to discover that the `external-secrets` pod in this namespace was still running with a 0.4.4 container image, and further I noticed that the ReplicationSet and the DeploymentConfig were not upgraded with the operator.

So I tried to delete the old resources and recreate them but the OperatorConfig now errors out when I try to create it:

```
failed to install release: rendered manifests contain a resource that already exists.
Unable to continue with install: ValidatingWebhookConfiguration "secretstore-validate" in namespace "" exists
and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key
"app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key
"meta.helm.sh/release-name": must be set to "test"; annotation validation error: missing key "meta.helm.sh/release-namespace":
must be set to "myapp-test"
```

Apparently the ValidatingWebhookConfiguration isn't namespaced but has details of a different ESO controller that runs in another namespace.

I now noticed that in that other namespace we have multiple pods running:

```
eso-external-secrets-7877b598b6-cpx2b
eso-external-secrets-cert-controller-595466945c-lzqwq
eso-external-secrets-webhook-7689fc969b-2vkph
```

And these pods seem to run with upgraded 0.5.1 images.  It appears that the upgrade of the Operator has correctly upgraded the deployed resources of one namespace, but failed to upgrade the resources in the other namespaces, probably because that ValidatingWebhook would fail.

Anyway, these are the logs of the original `external-secrets` pod I was analyzing:
```
I0411 10:44:57.609253       1 request.go:665] Waited for 1.037464785s due to client-side throttling, not priority and fairness, request: GET:https://10.53.0.1:443/apis/node.k8s.io/v1?timeout=32s
{"level":"info","ts":1649673900.8662562,"logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":1649673900.867688,"logger":"setup","msg":"starting manager"}
{"level":"info","ts":1649673900.8682024,"msg":"Starting server","path":"/metrics","kind":"metrics","addr":"[::]:8080"}
{"level":"info","ts":1649673900.8684394,"logger":"controller.secretstore","msg":"Starting EventSource","reconciler group":"external-secrets.io","reconciler kind":"SecretStore","source":"kind source: *v1alpha1.SecretStore"}
{"level":"info","ts":1649673900.8684804,"logger":"controller.secretstore","msg":"Starting Controller","reconciler group":"external-secrets.io","reconciler kind":"SecretStore"}
{"level":"info","ts":1649673900.8686564,"logger":"controller.clustersecretstore","msg":"Starting EventSource","reconciler group":"external-secrets.io","reconciler kind":"ClusterSecretStore","source":"kind source: *v1alpha1.ClusterSecretStore"}
{"level":"info","ts":1649673900.8686914,"logger":"controller.clustersecretstore","msg":"Starting Controller","reconciler group":"external-secrets.io","reconciler kind":"ClusterSecretStore"}
{"level":"info","ts":1649673900.8686464,"logger":"controller.externalsecret","msg":"Starting EventSource","reconciler group":"external-secrets.io","reconciler kind":"ExternalSecret","source":"kind source: *v1alpha1.ExternalSecret"}
{"level":"info","ts":1649673900.8687344,"logger":"controller.externalsecret","msg":"Starting EventSource","reconciler group":"external-secrets.io","reconciler kind":"ExternalSecret","source":"kind source: *v1.PartialObjectMetadata"}
{"level":"info","ts":1649673900.868741,"logger":"controller.externalsecret","msg":"Starting Controller","reconciler group":"external-secrets.io","reconciler kind":"ExternalSecret"}
{"level":"info","ts":1649673900.8726144,"logger":"KubeAPIWarningLogger","msg":"external-secrets.io/v1alpha1 ClusterSecretStore is deprecated; use external-secrets.io/v1beta1 ClusterSecretStore"}
{"level":"info","ts":1649673900.8738506,"logger":"KubeAPIWarningLogger","msg":"external-secrets.io/v1alpha1 SecretStore is deprecated; use external-secrets.io/v1beta1 SecretStore"}
{"level":"info","ts":1649673900.8749907,"logger":"KubeAPIWarningLogger","msg":"external-secrets.io/v1alpha1 ExternalSecret is deprecated; use external-secrets.io/v1beta1 ExternalSecret"}
{"level":"info","ts":1649673901.1723,"logger":"controller.externalsecret","msg":"Starting workers","reconciler group":"external-secrets.io","reconciler kind":"ExternalSecret","worker count":1}
{"level":"info","ts":1649673901.1724164,"logger":"controller.secretstore","msg":"Starting workers","reconciler group":"external-secrets.io","reconciler kind":"SecretStore","worker count":1}
{"level":"info","ts":1649673901.1724396,"logger":"controller.clustersecretstore","msg":"Starting workers","reconciler group":"external-secrets.io","reconciler kind":"ClusterSecretStore","worker count":1}
```

**Comment by gusfcarvalho** [comment]
In 0.5.0 we did introduce these new elements (`webhook` and `certController`).

You do have multiple external-secrets running in several namespaces? Can you share more of your setup configuration? If you install multiple external-secrets operator using default values, I believe the expected behavior would be the one you are describing.

**Comment by lukasertl** [comment]
Yes, we use multiple external-secrets, configured in different namespaces.

Basically, we install ESO globally using OpenShift Operator Hub (which then would also take care of upgrades etc).

Then in each relevant namespace we would instantiate OperatorConfigs, SecretStores etc. with configurations as the ones above.

I'm gonna try to create OperatorConfigs with webhook and certController set to false and let you know of the results.

Thanks so far!

**Comment by lukasertl** [comment]
So, after reconfiguring all OperatorConfig instances with:
```
  certController:
    create: false
  webhook:
    create: false
```
I can report that the login flood to Vault has stopped and everything seems to work as before - thanks!

Is there any harm to have no Webhook and certController at all?

**Comment by gusfcarvalho** [comment]
Yes, there can be a harm to some extent. If you use `v1alpha1` CRDs, not using the `webhook` will make any `dataFrom` definition not to work anymore.

Do try to have at least one `webhook` and one `certController` installed. It needs to be only one for all the external-secrets deployments you have. You can check if one is already running with the command `kubectl get svc -A -l external-secrets.io/component=webhook`

**Comment by gusfcarvalho** [comment]
hi @lukasertl ! I'm closing this issue. Feel free to reopen it, though!
