### ISSUE TITLE
Certificate signed by unknown authority

### ISSUE THREAD

**Issue by precompiler** [external-secrets/external-secrets#985]
Hi,

I got below cert verification error when I tried to deploy an externalsecret custom resource, because our gateway uses self-signed certificate. Is there any way we can configure the operator to trust self-signed cert?

Events:
  Type     Reason        Age                From              Message

  Warning  UpdateFailed  13s (x3 over 43s)  external-secrets  authentication failed: Post "https://gatewayURL:8080/v2/auth": x509: certificate signed by unknown authority

**Comment by moolen** [comment]
Hey @precompiler Can you give me a little more context, please? which store provider do you use?

**Comment by precompiler** [comment]
Hi @moolen,

I use the akeyless provider. I've created k8s auth method and deployed the external secret operator to a k8s cluster following this doc => https://docs.akeyless.io/docs/external-secret-operator


---
apiVersion: v1
kind: Secret
metadata:
  name: akeylss-secret-creds
type: Opaque
stringData:
  accessId: "access-id"
  accessType: k8s
  accessTypeParam: "auth-method-name"
---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: akeyless-secret-store
spec:
  provider:
    akeyless:
      # URL of your akeyless API
      akeylessGWApiURL: "https://gatewaylURL:8080/v2"
      authSecretRef:
        secretRef:
          accessID:
            name: akeylss-secret-creds
            key: accessId
          accessType:
            name: akeylss-secret-creds
            key: accessType
          accessTypeParam:
            name: akeylss-secret-creds
            key: accessTypeParam
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: akeyless-external-secret-example
spec:
  refreshInterval: 5h
  secretStoreRef:
    kind: SecretStore
    name: akeyless-secret-store
  target:
    name: akeyless-secret-to-create
    creationPolicy: Owner
  data:
    - secretKey: username 
      remoteRef:
        key: /k8s/demoapp

**Comment by moolen** [comment]
Ah, ok i see and the connection towards `https://gatewayURL:8080/v2/auth` can not be established due to an invalid cert.The Provider doesn't support providing a `caBundle` as of now. 
There seems to be a way to provide a custom `http.Client` [here](https://github.com/akeylesslabs/akeyless-go/blob/master/configuration.go#L98). Tho i don't have credentials available to test it properly.

**Comment by gusfcarvalho** [comment]
@renanaAkeyless do you think you can help us out in this one? :smile:

**Comment by precompiler** [comment]
One workaround for this issue is to mount your caBundle to `/etc/ssl/certs/` of the operator pod.
