### ISSUE TITLE
kubectl get es (doesn't work) 

### ISSUE THREAD

**Issue by karr1gan** [external-secrets/external-secrets#988]
Hello gentelmen,

After switching to External-Secret-Operator the shortcut 
`kubectl get es `
doesn't work and we need to each time write
`kubectl get externalsecrets.external-secrets.io `
which is very annoying and we want to come back to the previous solution `k get es`. 

Do you know any solution to this case. I've seen that "`shortcut: - es`" is set in the ESO CRD yaml so it should work but unfortunately does not.

Best regards,
karr1gan

**Comment by moolen** [comment]
Hey @karr1gan that's probably due to having multiple resources installed that have `es` shortname.

Can you quickly run the following command? That should just print the following:

```
$ kubectl api-resources | grep " es "

externalsecrets                   es           external-secrets.io/v1beta1             true         ExternalSecret
```

**Comment by karr1gan** [comment]
Hej, the output of this command might be found below:

**Comment by moolen** [comment]
You have two crds installed that both claim the `es` short name (i guess youre migrating from KES?), thats why you have to specify the full name.

**Comment by karr1gan** [comment]
We have already migrated and deleted all the staff associated with KES so it should be only one entry ESO. How may I delete this resource?

**Comment by karr1gan** [comment]
We have already migrated and deleted all the staff associated with KES so it should be only one entry ESO. How may I delete this resource?

**Comment by gusfcarvalho** [comment]
you can do this with `kubectl delete crd externalsecrets.kubernetes-client.io`

**Comment by karr1gan** [comment]
thanx mate! 🍺

**Comment by gusfcarvalho** [comment]
I'm closing this issue now! Feel free to reopen it, though!
