### ISSUE TITLE
Revamp Readme

### ISSUE THREAD

**Issue by moolen** [external-secrets/external-secrets#992]
I think we should revamp the `readme.md`. We can take some inspiration from kyverno or other projects.

specifically i'd like to add:
* badge: bestpractices.coreinfrastructure.org 
* badge: license
* badge: slack channel
* badge: goreport

Maybe tackle #857 as well.

**Comment by moolen** [comment]
@knelasevero do we have a SVG of the logo somewhere? The `.png` in the `assets/` dir has a light border which i'd like to get rid of.
While we're at it: do you know who the original creator of the logo is and how we can possibily transfer IP ownership? this is definitely needed for cncf.

**Comment by knelasevero** [comment]
I think we had SVG somewhere in CS drive. @gusfcarvalho can you check?

A CS designer created the logo, his name is Mickey. @gusfcarvalho I think you would get easier contact with him as well. But actually CS has the IP. We have to formalize the transfer.

I only have contact in CS slack with people that enter that external channel :D

**Comment by gusfcarvalho** [comment]
I sent a message to Carla as she is the one from the Marketing helping me out with all these non-techie stuff. I'll let you know here what comes after in the end.

From what I understood it would be fine if CS donated the IP to Linux Foundation directly as well when the time comes, right? This is just because I think we do not have an 'ESO org' to actually receive it (or do we?)

**Comment by moolen** [comment]
> I think we do not have an 'ESO org' to actually receive it (or do we?)

We don't have on firm that could possibly accept that. I don't really know how IP rights transfer works across jurisdictions. As far as i'm aware of in germany there's a way to provide `a right of use` to a third party through a publishing law. I guess that would be one thing to clarify with carla what kind of right is transferred and to whom.

Yeah, that's fine to do that once needed. I think it would be just good to make people aware of what may be coming so they can raise issues early on in the process.

**Comment by moolen** [comment]
@gusfcarvalho did you find the svg?

**Comment by gusfcarvalho** [comment]
I'm waiting for Mickey (the designer who created the logo) to render the SVG version for me. It was never generated :smiling_face_with_tear:  It should be anytime between today and tomorrow (I hope :eyes: )

**Comment by gusfcarvalho** [comment]
Speaking of which... here they are
![External Secrets Icon](https://user-images.githubusercontent.com/17139678/164265865-042be352-94f8-4d84-8184-7bb20d4da3ce.svg)
![External Secrets Logo](https://user-images.githubusercontent.com/17139678/164265873-e1513759-2000-4abf-ac43-ed663d3c154c.svg)

**Comment by moolen** [comment]
Can you ask for the round logo as well, please?

**Comment by gusfcarvalho** [comment]
Asked. I think we should have it by tomorrow =)

**Comment by gusfcarvalho** [comment]
[ESO Roundel](https://user-images.githubusercontent.com/17139678/164454123-458b94b0-2af1-4ac2-89ce-914b43aba94c.svg)

Here you go!
