### ISSUE TITLE
Webhook result as a text

### ISSUE THREAD

**Issue by ehsan310** [external-secrets/external-secrets#998]
I'd like to get a result of API call which is not json object and is a pure text and pass it on as a secret

Some endpoint return value which is not json object

I either want to skip result setting or be able to fetch text.

**Comment by gusfcarvalho** [comment]
Hi @ehsan310 ! can you provide a little bit more context please?

**Comment by ehsan310** [comment]
imagine you call to an endpoint and the results is access key but the result from that endpoint is not json object and it’s a text in response.

I have the case that i call an endpoint to generate authorization token , it works but I can’t collect the value since it’s not written correctly on their end and return text with invalid json structure .

for example instead of something like 

{
	"access_key": "12346"
}

the response is just 12346

**Comment by gusfcarvalho** [comment]
yes, but I think the Webhook Provider this functionality. If you provide `result.jsonpath=""` it will render you the response.

**Comment by ehsan310** [comment]
Thank @gusfcarvalho ,it works , i have never tried an empty value to jsonpath.
