### ISSUE TITLE
v1alpha1 CRDs incompatible with Kubernetes version < v1.19.0

### ISSUE THREAD

**Issue by slaminad** [external-secrets/external-secrets#999]
**Context**

When deploying the ESO Helm chart (version `0.5.1`) on a Kubernetes cluster running `v1.18.13`, the installation fails with the following error:

```
$ helm -n $ESO_NAMESPACE install external-secrets external-secrets/external-secrets --version 0.5.1
Installing external-secret Helm chart...
Release "external-secrets" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(CustomResourceDefinition.spec.versions[0]): unknown field "deprecated" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionVersion
```

This is because of the `spec.version.deprecated` field added to the `v1alpha1` CRDs for [`ClusterSecretStores`](https://github.com/external-secrets/external-secrets/blob/main/config/crds/bases/external-secrets.io_clustersecretstores.yaml#L28), [`ExternalSecrets`](https://github.com/external-secrets/external-secrets/blob/main/config/crds/bases/external-secrets.io_externalsecrets.yaml#L31), and [`SecretStores`](https://github.com/external-secrets/external-secrets/blob/main/config/crds/bases/external-secrets.io_secretstores.yaml#L28). It does not seem to be present in the `ClusterExternalSecrets` CRD.

The `deprecated` field for CRDs is only available starting in Kubernetes version >= `v1.19.0`.

Ref: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.19.md#api-change-4
Ref: https://github.com/kubernetes/kubernetes/pull/92329

**Describe the solution you'd like**

Some way to skip installing the `v1alpha1` CRDs on Helm so installation can succeed on Kubernetes versions < `v1.19.0`.

**What is the added value?**

Maintain backwards-compatibility with Kubernetes versions < `v1.19.0`.

**Give us examples of the outcome**

Perhaps a change in the Helm chart to specify which version of the CRDs to install, i.e.:

```
installCRDs: true
crds:
    createClusterExternalSecret: true
    createClusterSecretStore: true
    installV1Alpha1: false        # if true, install v1alpha1 CRDs
    installV1Beta1: true          # if true, install v1beta1 CRDs
```

Or something to that effect.

**Observations (Constraints, Context, etc):**

ESO version: `0.5.1`
Kubernetes version: `v1.18.13`

Somewhat related to https://github.com/external-secrets/external-secrets/issues/857

**Comment by gusfcarvalho** [comment]
@moolen @knelasevero I'm particularly keen to drop the dreprecated notice in favour of allowing versions >1.16 to be running.

If not, we should really create a compatibility matrix.

WDYT?

**Comment by moolen** [comment]
I'm fine with this for the next couple of releases. But 1.19 is EOL already and i would like to move forward to provide the deprecation warnings to users who are already on 1.19+.

**Comment by knelasevero** [comment]
> I'm fine with this for the next couple of releases. But 1.19 is EOL already and i would like to move forward to provide the deprecation warnings to users who are already on 1.19+.

+1

@gusfcarvalho is there a way to put another notice on the top, specific about the crds, on old versions for the docs?

**Comment by gusfcarvalho** [comment]
> @gusfcarvalho is there a way to put another notice on the top, specific about the crds, on old versions for the docs?

I did not understand what you mean by that.

Maybe we should just support from 1.19 and onwards then. And probably address #857

**Comment by gusfcarvalho** [comment]
hi @slaminad ! We have come to the decision to stablish eso v0.5.0 and forward will only be compatible with kubernetes version `1.19` and forward. I will close this issue now, and thank you for opening it.

The compatibility version is going to be addressed for the next release.
